### ISSUE TITLE
Deep comparisons like .equals for Property values?

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#10]
Currently, property values send notifications if newValue!==oldValue.  But this could send a false positive when the value didn't truly change.  For example if setting

```javascript
p.position = new Vector2(10,10);
p.position = new Vector2(10,10);
```

that will send two notifications, because the 2nd Vector2 !== the 1st Vector2.  We may wish to implement .equals() functions for comparing instances.  However, this would increase the complexity of implementation for values used by Property, and equality checks can take longer at runtime.

**Comment by pixelzoom** [comment]
If a client needs deep equality, they can extend Property and override equalsValue. @samreid is that sufficient? If so, please close this issue.

**Comment by samreid** [comment]
I added docs to equalsValue and will close this issue.  However, I discovered a related issue which I will open shortly.
