### ISSUE TITLE
add value validation option(s) to Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#101]
It would be nice to have the option to specify valid values to `Property`, especially for `{Property.<string>}`.   I'm finding that this pattern appears repeatedly in my code:

```js
var CLOCK_SPEEDS = [ 'fast', 'normal', 'slow' ];

function MyModel(...) {
  var clockSpeedProperty = new Property( 'normal' );
  clockSpeedProperty.link( function( clockSpeed ) {
    assert && assert( _.contains( CLOCK_SPEEDS, clockSpeed ), 'invalid clockSpeed: ' + clockSpeed );
  ...
  } );
}
```

Besides that fact this is boilerplate, we're relying on the order that observers are called (first linked) to validate the value before other observers are called.  Even if Property guarantees that, it doesn't seem like a good way to handle validation.

Much cleaner would be this:

```js
function MyModel(... ) {
  var clockSpeedProperty = new Property( 'normal', {
    validValues: [ 'fast', 'normal', 'slow' ]
  } );
  ...
}
```

... and have `Property` handle value validation (for initial value and when the value changes) before any observers are notified.

This feature is also desirable in `PropertySet`, but may be a little trickier to add.

**Comment by samreid** [comment]
QueryStringMachine used: `allowedValues` and `validate`, it may be good to be consistent.

**Comment by pixelzoom** [comment]
9/22/16 dev meeting consensus:
Use `allowedValues` and `validate` (optional, mutually exclusive). I'll do this.

**Comment by pixelzoom** [comment]
We'll also need to work out how to do this for PropertySet.

**Comment by pixelzoom** [comment]
Before I start working on this... We need to define the API for PropertySet.

**Comment by pixelzoom** [comment]
I discussed `PropertySet` API wil @samreid.  There are many other issues with that API (including whether it should be deprecated) that need to be addressed before figuring out how to add that feature.  So I'm not sure how to proceed.

**Comment by samreid** [comment]
Based on #71 we are going to deprecate PropertySet, so this issue can restrict its focus to Property.

**Comment by pixelzoom** [comment]
Value validation options were added to Property in the above commit. 

`allowedValues` tests in console:

```
// invalid initial value
> var p = new phet.axon.Property(0, { allowedValues:[1,2,3] } )
assert.js:22 Assertion failed: invalid initial value: 0

// attempt to set an invalid value
> var p = new phet.axon.Property(1, { allowedValues:[1,2,3] } )
> p.set(3)
Property {elementType: null, events: Events, _value: 3, _initialValue: 1, changedEmitter: Emitter}
> p.set(4)
assert.js:22 Assertion failed: invalid value: 4
```

`validate` tests in console:

```
// invalid initial value
> var p = new phet.axon.Property( 0, { validate: function(value) { return ( value > 0 && value < 4 ); } } )

// attempt to set an invalid value
> var p = new phet.axon.Property(1, { validate: function(value) { return ( value > 0 && value < 4 ); } } )
> p.set( 3 )
Property {elementType: null, events: Events, _value: 3, _initialValue: 1, changedEmitter: Emitter}
> p.set( 4 )
assert.js:22 Assertion failed: invalid value: 4
```

Property with no constraints:

```
> var p = new phet.axon.Property(1)
> p.set(4)
Property {elementType: null, events: Events, _value: 4, _initialValue: 1, changedEmitter: Emitter}
> p.set('foo')
Property {elementType: null, events: Events, _value: "foo", _initialValue: 1, changedEmitter: Emitter}
```

@samreid Could you please review this, since you are most familiar with the issue?

Note that I did not add this feature to static `Property.addProperty`.  Besides looking generally questionable, that function does not provide a way to pass options, and I'm wondering how that's going to work with phet-io instrumentation. Perhaps a separate issue is warranted for this function?

**Comment by pixelzoom** [comment]
Test driving these new options in models-of-the-hydrogen-atom, see above commit.  

One thing I noticed immediately is that I'd like to have a boolean Property, to avoid repeating `allowedValues: [ true, false ]`, like in models-of-the-hydrogen-atom.Light, line 23:

```js
    // @public {boolean} is the light on?
    this.onProperty = new Property( false, {
      allowedValues: [ true, false ]
    } );
```

I'd prefer to see:

```js
    // @public {boolean} is the light on?
    this.onProperty = new BooleanProperty( false );
```

Or if you don't like inheritance:

```js
    // @public {boolean} is the light on?
    this.onProperty = Property.withBoolean( false );
```

**Comment by samreid** [comment]
BooleanProperty will be tracked in a separate issue, this issue will focus on `allowedValues` and `validate` for Property.js, the next step is for me to review it.

**Comment by samreid** [comment]
> QueryStringMachine used: `allowedValues` and `validate`, it may be good to be consistent.

Let's consider giving these similar terminology.  Currently `allowed` and `valid` are different words that mean the same thing.  Here are some pairs that may be superior (and whatever we decide we should backpropagate to QSM).

(1) validValues/validate
(2) validValues/validateValue
(2) validValues/isValidValue
(3) allowedValues/isValueAllowed

Adding @pixelzoom to thread to get feedback on these options.

**Comment by samreid** [comment]
Other review comments:

* Let's change the error message for `onValue` so that it is clear the listener was trying to *listen* to a value the property cannot take.
* It seems confusing for this.validate to take a non-null value even if options.validate was null.  See also next point:

* Many of our simulations have hundreds of Property value changes every second.  Now every property change requires a function invocation to check the value.  Will this hamper performance in sims?  Or perhaps because it is embedded in asserts it is OK because it will be stripped out?  But I wouldn't want our dev performance to deviate too much from our production performance.

Perhaps something like this:
```js
      set: function( value ) {
        assert && this.validate && assert( this.validate( value ), 'invalid value: ' + value );
        assert && this.validValues && assert( this.validValues.indexOf( value ) >= 0, 'invalid value: ' + value );
        if ( !this.equalsValue( value ) ) {
          this._setAndNotifyObservers( value );
        }
        return this;
      },
```

**Comment by pixelzoom** [comment]
Re https://github.com/phetsims/axon/issues/101#issuecomment-249943908...  My preference is 

> (3) validValues/isValidValue

**Comment by pixelzoom** [comment]
> Let's change the error message for onValue so that it is clear the listener was trying to listen to a value the property cannot take.

Addressed in above commit.

> It seems confusing for this.validate to take a non-null value even if options.validate was null

For the performance reason that you mentioned, agreed that we should not default to a no-op for `this.validate`.  But if `allowedValues` is provided, I think it still makes sense to define `this.validate` rather than have to deal with `allowedValues` as a separate test everywhere validation is required. Addressed in above commit.

**Comment by pixelzoom** [comment]
> Let's change the error message for onValue so that it is clear the listener was trying to listen to a value the property cannot take.

Addressed in above commit.

> It seems confusing for this.validate to take a non-null value even if options.validate was null

For the performance reason that you mentioned, agreed that we should not default to a no-op for `this.validate`.  But if `allowedValues` is provided, I think it still makes sense to define `this.validate` rather than have to deal with `allowedValues` as a separate test everywhere validation is required. Addressed in above commit.

**Comment by pixelzoom** [comment]
> The tests you ran above could be formalized in the axon qunit tests http://localhost/axon/tests/qunit/unit-tests.html

Considering that these tests don't appear to be maintained or run automatically (they currently fail with 'phet is not defined'), I'm not enthusiastic about having to fix them before adding my tests.

**Comment by samreid** [comment]
> (they currently fail with 'phet is not defined')

In my browser, it looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/18923825/0b5a1a34-856b-11e6-938c-de45b10c41dc.png)

Let's try to figure out what is wrong here.

**Comment by pixelzoom** [comment]
Ah... I was opening http://localhost/~cmalley/GitHub/axon/tests/example.html, which fails.  Is that something that should be fixed or deleted?

I'll proceed with adding unit tests.

**Comment by pixelzoom** [comment]
Review comments addressed, @samreid please review https://github.com/phetsims/axon/issues/101#issuecomment-250226503.

Regarding the option names... I'd really like to resolve that quickly, since I'm using these options in models-of-the-hydrogen-atom, the options appear in unit tests, QueryMachineStrings and FBQueryParameters may need to change, etc.   Setting priority to high.

**Comment by samreid** [comment]
> My preference is (3) validValues/isValidValue

That sounds good, proceed if you wish.

**Comment by pixelzoom** [comment]
Property options have been renamed, unit tests pass.

Corresponding QueryStringParameter options are renamed in https://github.com/phetsims/query-string-machine/issues/13.

@samreid please review.

**Comment by samreid** [comment]
> Ah... I was opening http://localhost/~cmalley/GitHub/axon/tests/example.html, which fails. Is that something that should be fixed or deleted?

I deleted it above.

**Comment by samreid** [comment]
Review looks good, my only recommendation is to use Qunit.throws for the unit tests, which is being tracked in https://github.com/phetsims/axon/issues/107

Closing.
