### ISSUE TITLE
Clear shouldn't copy

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#103]
```js
    /**
     * Removes all items from the array.
     * @public
     */
    clear: function() {
      var copy = this._array.slice( 0 );
      for ( var i = 0; i < copy.length; i++ ) {
        this.remove( copy[ i ] );
      }
    },
```

Can we clear without a slice?

**Comment by jonathanolson** [comment]
We could presumably handle this similarly to other cases with re-entrant behavior, and only slice our internal array when ```this.remove()``` calls a callback that modifies our array.

That opens us up a bit easier for infinite loops, e.g.:
```
array.addItemRemovedListener( function( item ) { array.push( something ); } );
```

**Comment by samreid** [comment]
What about:

```js
while (this.length>0){
this.remove(this.get(0));
}
```

Would that work?

**Comment by jonathanolson** [comment]
To me it is unclear how to handle clear() with an observer that will add additional content (maybe assertion failure).

Besides detecting that, looping with pop() would be more efficient.

**Comment by samreid** [comment]
> Besides detecting that, looping with pop() would be more efficient.

I was hesitant to change the removal order (currently FIFO), but FILO makes more sense to me, should we go for it?  What level of testing would be necessary?

**Comment by jonathanolson** [comment]
> What level of testing would be necessary?

Sounds like something that IF there is a bug, it will be hard for us to find it initially without having pre-recorded user input and verifying instrumented output. We could run fuzz tests potentially?

**Comment by samreid** [comment]
Let's try this:

```js
    /**
     * Removes all items from the array.
     * @public
     */
    clear: function() {
      while ( this.length > 0 ) {
        this.pop();
      }
    },
```

Committing shortly.

**Comment by samreid** [comment]
I should run through the automated tests after this order change.

**Comment by samreid** [comment]
So far so good:
![image](https://cloud.githubusercontent.com/assets/679486/18938839/d5a94c68-85b8-11e6-85fb-00af3dc30390.png)

**Comment by samreid** [comment]
> To me it is unclear how to handle clear() with an observer that will add additional content (maybe assertion failure).

> Besides detecting that, looping with pop() would be more efficient.

How might we detect that?  Also, is that something that should be left for QA or caught in code?

Anything else to do for this issue?

**Comment by jonathanolson** [comment]
> How might we detect that?

It would likely cause an infinite loop and stall out the sim tests. If the sim tests completed, I don't think we have to worry.

> Anything else to do for this issue?

Don't think so, closing.
