### ISSUE TITLE
Add BooleanProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#104]
See https://github.com/phetsims/axon/issues/101#issuecomment-249695611

@pixelzoom said:

Test driving these new options in models-of-the-hydrogen-atom, see above commit.  

One thing I noticed immediately is that I'd like to have a boolean Property, to avoid repeating `allowedValues: [ true, false ]`, like in models-of-the-hydrogen-atom.Light, line 23:

```js
    // @public {boolean} is the light on?
    this.onProperty = new Property( false, {
      allowedValues: [ true, false ],
      ...
    } );
```

I'd prefer to see:

```js
    // @public {boolean} is the light on?
    this.onProperty = new BooleanProperty( false, {...} );
```

Or if you don't like inheritance:

```js
    // @public {boolean} is the light on?
    this.onProperty = Property.withBoolean( false, {...} );
```

**Comment by samreid** [comment]
I created BooleanProperty above, @pixelzoom would you like to take a look?

**Comment by pixelzoom** [comment]
BooleanProperty looks good.  

But there's a more general issue here that we should discuss: What are the common types of validation and what can we provide to make make that validation easier?

For example, here's another boilerplate validation:

```js
var volumeProperty = new Property( 0, {
  validate: function( value ) { 
    ( typeof value === 'number' ) && MyConstants.VOLUME_RANGE.contains( value ); 
  }
} );
```

Something like this would be better:

```js
var volumeProperty = new NumberProperty( 0, {
  range: MyConstants.VOLUME_RANGE
} );
```

So should we discuss this? Or do you think that inheritance (ala BooleanProperty) is an appropriate general way to handle this?

**Comment by pixelzoom** [comment]
Really don't like this pattern that I see in the BooleanProperty unit tests:

```js
   try {
      new BooleanProperty( 'hello' );
      equal( true, false, 'Should have errored out when giving boolean property a bad value' );
    }
    catch( err ) {
      equal( true, true, 'Should have errored out when giving boolean property a bad value' );
    }
```

Problems:
(1) message is duplicated
(2) message should describe the test, not what should have happened
(3) There must be a better way than this try/catch pattern.

**Comment by samreid** [comment]
@pixelzoom said:

> BooleanProperty looks good.

So I'm going to close this issue.  I've moved the side issues to #106 and #107.
