### ISSUE TITLE
Expand/Improve Property validation

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#106]
From #104 and #101 @pixelzoom said:

BooleanProperty looks good.  

But there's a more general issue here that we should discuss: What are the common types of validation and what can we provide to make make that validation easier?

For example, here's another boilerplate validation:

```js
var volumeProperty = new Property( 0, {
  validate: function( value ) { 
    ( typeof value === 'number' ) && MyConstants.VOLUME_RANGE.contains( value ); 
  }
} );
```

Something like this would be better:

```js
var volumeProperty = new NumberProperty( 0, {
  range: MyConstants.VOLUME_RANGE
} );
```

So should we discuss this? Or do you think that inheritance (ala BooleanProperty) is an appropriate general way to handle this?

**Comment by pixelzoom** [comment]
I'm test driving BooleanProperty in models-of-the-hydrogen-atom, see above commit.  If our approach to boolean Properties changes, this client will need to be changed too.

**Comment by samreid** [comment]
> Or do you think that inheritance (ala BooleanProperty) is an appropriate general way to handle this?

Yes, inheritance seems like a good solution here.  

> So should we discuss this?

Let's proceed with adding Property subclasses and validation as we go and see where it leads us.  Assigning back to @pixelzoom for work on https://github.com/phetsims/axon/issues/106#issuecomment-250270474 or further discussion.

**Comment by pixelzoom** [comment]
To vet the use of inheritance, I created `NumberProperty` and used it in MOTHA.  Seems to be working nicely.  @samreid If this looks good to you, feel free to close this issue, and we'll do as you suggested ("proceed with adding Property subclasses and validation as we go").

**Comment by samreid** [comment]
NumberProperty looks great, let's continue with this pattern.
