### ISSUE TITLE
Better unit test for testing errors

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#107]
In https://github.com/phetsims/axon/issues/104#issuecomment-250245634

@pixelzoom said:

Really don't like this pattern that I see in the BooleanProperty unit tests:

```js
   try {
      new BooleanProperty( 'hello' );
      equal( true, false, 'Should have errored out when giving boolean property a bad value' );
    }
    catch( err ) {
      equal( true, true, 'Should have errored out when giving boolean property a bad value' );
    }
```

Problems:
(1) message is duplicated
(2) message should describe the test, not what should have happened
(3) There must be a better way than this try/catch pattern.

Addressed (1) and (2) in https://github.com/phetsims/axon/commit/df792a9844efc308d7657b152bd5ec384e063cef.

So we still need to address (3).

**Comment by jonathanolson** [comment]
Scenery uses a pattern to conditionally enable unit test assertion checks if assertions are enabled:
```js
window.assert && throws( function() { d.getUniqueTrail(); }, 'D has no unique trail, since there are two' );
```
(example from where d.getUniqueTrail() should fail an assertion).

The assert guard is not needed if it's a throw that you expect.

See QUnit documentation on throws for more you can do with it.

**Comment by samreid** [comment]
Works great @jonathanolson, thanks!  @pixelzoom please take a look.

**Comment by pixelzoom** [comment]
Much nicer!

@samreid, I wondering why the test description is the empty string for this test:

```js
    var testDescription = '';
    throws( function() {new BooleanProperty( 'hello' );}, testDescription );
```

**Comment by samreid** [comment]
I inlined the test descriptions and added the missing description above.  @pixelzoom would you like to spot check?

**Comment by pixelzoom** [comment]
👍 Closing.
