### ISSUE TITLE
Unit test fixes for compiled unit tests

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/axon#108]
Since window.assert is falsy, assertions are NOT thrown in compiled unit tests, so the throws() statements don't actually throw any errors, resulting in test failures.

Adding conditionals so that those checks only apply when assert is enabled.

**Comment by jonathanolson** [comment]
@samreid, can you verify changes to the unit tests look OK?

**Comment by samreid** [comment]
Yes, adding a check for assert before throws seems appropriate.  Closing.
