### ISSUE TITLE
Helper methods for Property

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/axon#109]
I'm doing some sim work, and moving it away from ES5 getters/setters, but turning

``` js
this.value++;
```

into

``` js
this.valueProperty.set( this.valueProperty.get() + 1 );
```

just makes it difficult to read.

Could we have:

``` js
this.valueProperty.increment(); // like above
this.valueProperty.decrement();
```

The general pattern:

``` js
this.value += otherValue;
// e.g.
this.valueProperty.set( this.valueProperty.get() + otherValue );
```

could also benefit with readability:

``` js
this.valueProperty.add( otherValue ); // works for numbers or strings
this.valueProperty.subtract( otherValue );
```

From a code readability perspective, I feel like those would help a lot, even though it feels somewhat wrong to put typed (numeric/string) methods on something generic that can hold other types.

Thoughts?

**Comment by jonathanolson** [comment]
Actual example here (https://github.com/phetsims/making-tens/issues/99), recommended old ES5 getter/setter method in February.

**Comment by samreid** [comment]
Since @pixelzoom and I started creating Property subclasses, it seems like it would be straightforward to add a method like this to NumberProperty.  Do we need increment/decrement/subtract in the API, or is `add` sufficient?  For instance, `add(1)`.  But still good to leave assigned to developer meeting to see if this would be clear for other developers or suffer from "too many ways to do the same thing".

**Comment by jonathanolson** [comment]
```add(1)``` seems sufficiently readable.

**Comment by andrewadare** [comment]
> From a code readability perspective, I feel like those would help a lot, even though it feels somewhat wrong to put typed (numeric/string) methods on something generic that can hold other types.

This puts the main pro and con nicely. I'd rather live with a little extra verbosity for the sake of safety and transparency. But, if I'm outvoted (which is fine), I'd at least advocate for type-checking with assertions in any new methods that are intended for specific types.

**Comment by samreid** [comment]
@jonathanolson said:

>  it feels somewhat wrong to put typed (numeric/string) methods on something generic that can hold other types.

@samreid replied:

> it seems like it would be straightforward to add a method like this to NumberProperty.

This means we do not need to put typed methods on something generic.  We would put the number functions on NumberProperty.

@andrewadare said:

> I'd at least advocate for type-checking with assertions in any new methods that are intended for specific types.

This will not be necessary because `add` would be defined on `NumberProperty`, not `Property`.

**Comment by samreid** [comment]
# VOTING COMMENT

"add your reaction" as 👍  : This is a vote for creating axon/NumberProperty and adding a method `add` as described above.  Main reason to vote for this: to simplify readability when working with numeric Property instances, like `myProperty.add(7);`

"add your reaction" as 👎  : This is a vote to continue using Property as it is and change its value using the existing `get/set` methods, like `myProperty.set( myProperty.get() + 7 )`

For discussion/to propose other options/identify other pros or cons, please add comments below.  Voting will commence immediately and conclude when we have enough votes.

**Comment by samreid** [comment]
# Voting comment

Vote for adding `subtract` here.

**Comment by samreid** [comment]
Assigned to @samreid to implement as prescribed.

**Comment by samreid** [comment]
I added the methods and tested them in the console:

![image](https://cloud.githubusercontent.com/assets/679486/19375315/0e7d04b6-9190-11e6-8489-524802411bf2.png)

Committing shortly.

**Comment by samreid** [comment]
Added above, @jonathanolson can you please review and exercise the new methods in your context?

**Comment by pixelzoom** [comment]
In case anyone is confusing "don't like ES5 setter/getter for PropertySet" with "don't like ES5 setter/getter in general"...  I don't have any problem with the ES5 setters/getters on Property.  E.g.

```
this.value++;
```

... is perfectly acceptable. 

So not a fan of adding `add` and `subtract` to NumberProperty. Because next will be `multiply`, `divide`, ...

**Comment by samreid** [comment]
Comparing options:

```js
// method 1
ageProperty.set(ageProperty.get()+1);

// method 2
ageProperty.add(1);

// method 3
ageProperty.value++;
```

For times:
```js
// method 1
ageProperty.set(ageProperty.get()*2);

// method 2
ageProperty.times(2);

// method 3
ageProperty.value*=2;
//or
ageProperty.value = ageProperty.value*2;
```

I'm trying to apply @pixelzoom's argument to another value type that has a lot of convenience methods: Vector2.  In that case, it seems sensible to have methods like `Vector2.add`, `Vector2.times`, etc instead of just having to operate on each of the x,y values, or a more general `Vector2.mutate` function.  I wonder if Vector2 sets a precedent that means it is reasonable/good to have convenience methods, even if there are many of them?

**Comment by jonathanolson** [comment]
To me, code becomes more readable with:
```js
ageProperty.value = 5;
someCall( ageProperty.value );
```
instead of the ```get()``` and ```set()```, and also do prefer method 3 above.

Since that's duplication of functionality, should we consider preferring using property.value instead of get() and set()?

One disadvantage of using property.value is the inability to easily bind the getter/setter:
```js
ageProperty.set.bind( ageProperty );
```
but I don't think that's a common pattern.

**Comment by pixelzoom** [comment]
@jonathanolson said:
> should we consider preferring using property.value instead of get() and set()?

I don't think we necessarily need to prefer one over the other.  Both make it clear that a Property's value is being accessed or modified.   Promoting consistency might be a good thing.  E.g., I would avoid examples like this that mix approaches:

```js
voltageProperty.value = currentProperty.get() * resistanceProperty.value;
```

**Comment by samreid** [comment]
I'm interested in pursuing usage of `Property.value` instead of `NumberProperty.add` and `NumberProperty.subtract`.  I'll remove them from NumberProperty.  @jonathanolson if you are using them already, you'll need to port away from them.

**Comment by pixelzoom** [comment]
@samreid said:
> I'm interested in pursuing usage of Property.value instead of NumberProperty.add and NumberProperty.subtract.

I'm going to try using Property.value instead of Property.set and Property.get in unit-rates.  That sim (which I inherited) didn't use one approach consistently, but was mostly Property.value. It's now using Property.value exclusively.

**Comment by samreid** [comment]
> I'm going to try using `Property.value` instead of `Property.set` and `Property.get` in unit-rates. 

In loops that do many computations (more than 100x/frame), Property.get() and Property.set() may be preferable due to better performance (may be in the noise on a standard profiler though.)

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/axon/issues/109#issuecomment-254694313, I said:
> I'm going to try using Property.value instead of Property.set and Property.get in unit-rates.

I used `value` throughout unit-rates, and have a slight preference for the resulting syntax.  As @samreid said above, `set/get` are more appropriate for performance-critical code.

**Comment by samreid** [comment]
Likewise, I think Property.value has proven to be a good level of abstraction, with the option to use get/set for performance-critical code.  Can we close this issue?

**Comment by pixelzoom** [comment]
There are 2 issues combined herein:

(1) Whether to add helper functions (`add`, `subtract`, ...) and their ES5 setters/getters to subtypes of Property (e.g. NumberProperty, BooleanProperty,...)

(2) Whether to prefer `value` or `set/get` API for Property.

Looks like the majority (me excluded) is a "yes" to (1).

And I'm fine with a "no" on (2).

So closing.

**Comment by samreid** [comment]
To clarify, NumberProperty doesn't have helper functions and using `.value` seems to alleviate the need for them.  It seems the same argument applies to many property subclasses.

**Comment by pixelzoom** [comment]
Got it. Anything else to do here?

**Comment by samreid** [comment]
All set, thanks!
