### ISSUE TITLE
Rename elementType to phetioValueType

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#110]

**Comment by samreid** [comment]
Done above, and I tested a few sims and wrappers.  Lint is passing.  No problems noted.  @zepumph please be aware of this change in case it impacts Forces and Motion: Basics, and please review at your convenience (to make sure my changes are good and that I didn't miss anything).

**Comment by zepumph** [comment]
This looks good to me, and the FAMB ca wrapper hasn't run into any problems. Closing.
