### ISSUE TITLE
delete Property.addProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#111]
Related to https://github.com/phetsims/chipper/issues/515.

`Property.addProperty` (not to be confused with `PropertySet.addProperty`) is deprecated.  It's used in a handful of places:

- [x] bending-light (1)
- [x] charges-and-fields (1)
- [x] masses-and-springs (5)
- [ ] scenery (1)

Seems like we should be able to clean these up relatively quickly.

**Comment by pixelzoom** [comment]
@jonathanolson There is 1 remaining usage of Property.addProperty, in scenery.Display:

```js
1659  Property.addProperty( Display, 'focus', null ); // { display: {Display}, trail: {Trail} }
```

Can you please take care of this one?  Then either delete Property.addProperty, or assign this issue back to me to do so.

**Comment by jonathanolson** [comment]
> Can you please take care of this one?

Will do.

**Comment by jonathanolson** [comment]
> Can you please take care of this one? Then either delete Property.addProperty, or assign this issue back to me to do so.

Done.

**Comment by pixelzoom** [comment]
Property.addProperty deleted. Closing.
