### ISSUE TITLE
incorrect doc for Property.multilink and unmultilink ?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#112]
Added by @samreid in @aa5bfb9e96d9e3ded8308d3dfc036ae99d49e540, here's what `Property.unmultilink` currently looks like in master:

```js
  /**
   * Removes the multilinked listener from this Property.
   * Same as calling detach() on the handle (which happens to be a DerivedProperty instance)
   * @param derivedProperty
   * @static
   */
  axon.Property.unmultilink = function( derivedProperty ) {
    derivedProperty.dispose();
  };
```

This documentation looks suspicious to me.

First, the "from this Property" bit can't be the case, since this is a static function, not an instance function.

Second, `multilink` and `lazyMultilink` both return a `Multilink`, not a `DerivedProperty`.   And the sole usage that I see (in expression-exchange) passes in a `Multilink`, not a `DerivedProperty`.  So I suspect that the sole parameter should be `{Multilink} multilink`.

**Comment by pixelzoom** [comment]
`multilink` and `lazyMultilink` are convenience functions, and (more importantly, I suspect) a way to instantiate a Multilink without assignment - something that lint would complain about.

So why do we even need `Property.unmultilink`?  Can't the client simply call `dispose` directly on the Multilink instance?  (Worth mentioning again - `unmultilink` is used on in 1 place.)

**Comment by pixelzoom** [comment]
`multilink` and `lazyMultilink` are convenience functions, and (more importantly, I suspect) a way to instantiate a Multilink without assignment - something that lint would complain about.

I.e.:

```js
// lint complains
new Multilink( [ distanceProperty, speedProperty ], function( distance, speed ) { .... } );

// lint complains unless myMultilink is used somewhere
var myMultilink = new Multilink( [ distanceProperty, speedProperty ], function( distance, speed ) { .... } );

// OK with lint
Property.multilink(  [ distanceProperty, speedProperty ], function( distance, speed ) { .... } );
```

So why do we even need `Property.unmultilink`?  Can't the client simply call `dispose` directly on the Multilink instance?  (Worth mentioning again - `unmultilink` is used on in 1 place.)

**Comment by pixelzoom** [comment]
More incorrect doc?   Property.multilink:

```js
     /**
       * Registers an observer with multiple properties, then notifies the observer immediately.
       * @param {Property[]} properties
       * @param {function} observer no params, returns nothing
       * @static
       */
      multilink: function( properties, observer ) {
        return new Multilink( properties, observer, false );
      },
```

But `Multilink` constructor indicates that the `observer` (aka `callback`) parameters **does** take parameters:

```js
20 @param {function} callback function that expects args in the same order as dependencies
```

**Comment by samreid** [comment]
Fixed docs above:

> So why do we even need `Property.unmultilink`?  Can't the client simply call `dispose` directly on the Multilink instance? 

I recommend using multilink/unmultilink for symmetry with link/unlink.

@pixelzoom anything else to do here?
