### ISSUE TITLE
add "deep equality" option to Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#115]
This issue started in https://github.com/phetsims/balloons-and-static-electricity/issues/235#issuecomment-270707026:

@samreid said:
> @pixelzoom I'd love to get your recommendation on this.  I would like to have Property instances that use `equals` instead of `===`.  The current way to do this is by subclassing or overriding the `Property.equalsValue` method.  Should we make it a Property option `useEqualsMethod` or `useReferenceEquality` or create a Property subclass like `ValueProperty` that does that?
>
> I guess I'm leaning toward a Property option (whatever it is called).  What do you think of that?

**Comment by pixelzoom** [comment]
I would proceed with great caution on this.  There are pitfalls to using deep equality. Let's discuss via voice, but the 2 big ones are:
 
(1) If the client isn't also using deep equality, then weird/subtle problems may occur. Example:

```js
1 var homeLocation = new Vector2(100,100);
2 var locationProperty = new Property( ..., {  useReferenceEquality: false } );
3 locationProperty.link( function( location ) {
4   if ( location === homeLocation ) {
5    // do something special when the Node is at it's "home" location
6   }
7 } );
```

The `if` statement on line 4 is unlikely to ever evaluate to `true`, because the expression should be `location.equals( homeLocation )`.  And that assumes that using `equals` is equivalent to how `Property` does its "deep equals" comparison.

(2) Polymorphism problems. Consider this sequence, where `MyVector2 extends Vector2`:

```js
1 var myVector = new Property( new Vector( 0, 1 ), {  useReferenceEquality: false } );
2 var myVector.value = new Vector2(2,3);
3 var myVector.value = new MyVector2(2,3);
4 var myVector.value = new MyVector(3,4);
5 var myVector.value = new Vector2(1, 2);
```

Line 1: How do we determine the type of the Property value? By its current value? By its initial value? What if the initial value is null?  
Line 3: Assignment may (silently) not occur because, according to the Vector2 interface, MyVector2(2,3) is equal to Vector(2,3).
Line 4: The current value is of type MyVector, and the new value is of type Vector2. Will this assignment fail?

That said... If you are going to add this feature, a Property option seems like a reasonable way to do it (better than inheritance). And `useReferenceEquality:true` seems like a fine name and default.

I also noticed... `areValuesEqual` should be `static`, because it requires no access to instance properties.  And presumably once options `useReferenceEquality` is added, `areValuesEqual` should also become `private`.

**Comment by pixelzoom** [comment]
Looking at the examples above, I don't like:

```js
var locationProperty = new Property( ..., {  
  useReferenceEquality: false 
} );
```

It's not communicating the feature that's being enabled for the Property.  This is clearer:

```js
var locationProperty = new Property( ..., {  
  useDeepEquality: true 
} );
```

**Comment by pixelzoom** [comment]
Pitfall (3):

In https://github.com/phetsims/balloons-and-static-electricity/issues/235, a Property's equals comparison was changed from `===` to `equals` in order to address a PhET-iO issue.  And I'm guessing that this will be a common scenario.  And unless you closely examine how the Property is being used by the client, you may introduce a non-obvious bug (see pitfall 1 above).

**Comment by pixelzoom** [comment]
Answers to the questions in https://github.com/phetsims/balloons-and-static-electricity/issues/235#issuecomment-270722145 (duplicate PhET-iO messages) may also determine whether this feature is really necessary.

**Comment by pixelzoom** [comment]
Unassigning myself. @samreid let me know if/when you want to discuss.

**Comment by samreid** [comment]
Perhaps it would be sufficient to implement Vector2Property with value-based equality semantics.  Users that would need instance-based equality could use Property.  I don't know of any other types in practice that currently would require value-based equals semantics.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/axon/issues/115#issuecomment-270723269 said:
> Answers to the questions in phetsims/balloons-and-static-electricity#235 (comment) (duplicate PhET-iO messages) may also determine whether this feature is really necessary.

The questions are:
• How often was this happening, and why was it happening?
• Is there another way that this could be solved, perhaps on the client side?
• Would it be acceptable to make the analysis code responsible for ignoring these notifications?

**Comment by jbphet** [comment]
@samreid came across issues with notifications for changes to Vector2 values when they were being set to the same value, and @samreid asked me to show the example in this issue.  The case is in Build an Atom, and it occurs on a reset when the particles are all positioned back into the buckets.  Some of the particles where already there.  The output is shown below, and you can see that the positions are actually the same.

```219 buildAnAtom.symbolScreen.view.resetAllButton fired
phetioEvents.js?bust=1488386467122:60 	220 buildAnAtom.symbolScreen.model.protons_0.destinationProperty changed {"oldValue":{"x":-172,"y":-209},"newValue":{"x":-172,"y":-209}}
phetioEvents.js?bust=1488386467122:60 	221 buildAnAtom.symbolScreen.model.protons_0.positionProperty changed {"oldValue":{"x":-172,"y":-209},"newValue":{"x":-172,"y":-209}}
phetioEvents.js?bust=1488386467122:60 	222 buildAnAtom.symbolScreen.model.protons_1.destinationProperty changed {"oldValue":{"x":-152,"y":-209},"newValue":{"x":-152,"y":-209}}
phetioEvents.js?bust=1488386467122:60 	223 buildAnAtom.symbolScreen.model.protons_1.positionProperty changed {"oldValue":{"x":-152,"y":-209},"newValue":{"x":-152,"y":-209}}
phetioEvents.js?bust=1488386467122:60 	224 buildAnAtom.symbolScreen.model.protons_2.destinationProperty changed {"oldValue":{"x":-132,"y":-209},"newValue":{"x":-132,"y":-209}}
phetioEvents.js?bust=1488386467122:60 	225 buildAnAtom.symbolScreen.model.protons_2.positionProperty changed {"oldValue":{"x":-132,"y":-209},"newValue":{"x":-132,"y":-209}}
phetioEvents.js?bust=1488386467122:60 	226 buildAnAtom.symbolScreen.model.protons_3.destinationProperty 
```

**Comment by samreid** [comment]
Based on discussion with @jbphet, we added useDeepEquality to Property.js and will test it out in Build an Atom.

**Comment by samreid** [comment]
@jbphet reviewed the changes and said everything seems OK.  It would be great if/when @pixelzoom has time to double check the changes.

**Comment by pixelzoom** [comment]
(1) As stated in https://github.com/phetsims/axon/issues/115#issuecomment-270719556 and https://github.com/phetsims/axon/issues/115#issuecomment-270721351, I think adding this functionality is (in general) a bad idea. That said...

(2) You didn't address the "polymorphism pitfall" identified in https://github.com/phetsims/axon/issues/115#issuecomment-270719556. This looks like an attempt to do so in `areValuesEqual`:

```js
174 assert && assert( a.equals( b ) === b.equals( a ), 'incompatible equality checks' );
```
But it doesn't address the case when `b` is a subtype of `a` that doesn't override `equals`. Consider replacing the `assert` with:

```js
174 assert && assert( a.constructor === b.constructor, 'a and b are different types' );
```

And should this be an assert? Or should it return false? 

(3) The implementation of `areValuesEqual` has 2 cases of `return a ===b`, the first of which would be unnecessary if the `if` expression where `( this.useDeepEquality && a && a )`. 

(4) Why is `areValuesEqual` and `equalsValue` public?

**Comment by jonathanolson** [comment]
> I think adding this functionality is (in general) a bad idea.

What if we resolve the potential pitfalls by implementing the recommended equals behavior specified in Effective Java (so it can handle subtypes and polymorphism)? It seems to be a solvable problem, and being able to use equals() sounds like both a performance and phet-io gain.

**Comment by samreid** [comment]
> being able to use equals() sounds like both a performance and phet-io gain.

Checking reference equality will always be faster than calling `equals()` implementations.

**Comment by samreid** [comment]
I saw several cases like this:

```js
this.locationProperty.areValuesEqual = function( a, b ) { return a.equals( b ); };
```

that we will be able to convert.

**Comment by samreid** [comment]
> (1) As stated in https://github.com/phetsims/axon/issues/115#issuecomment-270719556 and https://github.com/phetsims/axon/issues/115#issuecomment-270721351, I think adding this functionality is (in general) a bad idea. 

We couldn't find a superior solution--it seems like axon is the right place to address this.

> (2) You didn't address the "polymorphism pitfall" identified in 

I added a check that constructors are equal

> (3) The implementation of `areValuesEqual` has 2 cases of `return a ===b`, the first of which would be unnecessary if the `if` expression where `( this.useDeepEquality && a && a )`. 

I consolidated the logic

> (4) Why is `areValuesEqual` and `equalsValue` public?

I made them private and eliminated usages of them.

@pixelzoom would you like to discuss this further

**Comment by samreid** [comment]
I ran into this problem in Balloons and Static Electricity:
![image](https://user-images.githubusercontent.com/679486/29032048-58958030-7b4d-11e7-88da-86e8d79d8331.png)

These vectors should be treated as equal in this context.  I'll look into it.

**Comment by samreid** [comment]
I'm unfamiliar with ImmutableVector2, but it looks like it is intended to be used for assertion checking.

**Comment by pixelzoom** [comment]
> I added a check that constructors are equal

This will cause problems, as you've discovered in https://github.com/phetsims/axon/issues/115#issuecomment-320685286.  

> @pixelzoom would you like to discuss this further?

Not really.  I'm going to avoid this using this feature in my code

**Comment by samreid** [comment]
Sounds good, if you think of a better solution, let me know!

**Comment by pixelzoom** [comment]
Reopening. 

@samreid Why is `this.useDeepEquality` public?  I see no reason for it to be public, and it's not currently used outside of Property.

**Comment by samreid** [comment]
Confirmed and converted to private, anything else for this issue @pixelzoom?
