### ISSUE TITLE
BooleanProperty should specify its own phetioValueType

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#116]
Currently phetioValueType: TBoolean is scattered everywhere instrumented BooleanProperties are used.  Instead, we should factor this out into axon.

**Comment by samreid** [comment]
Fixed in the above commits and tested in CLB (with and without phet-io).  Leaving open until further testing is complete.

**Comment by jonathanolson** [comment]
Fixed BooleanProperty usage where options is not specified in the commit above (proportion-playground wasn't loading).

**Comment by samreid** [comment]
Thanks @jonathanolson!

**Comment by samreid** [comment]
This seems like it is working well, closing.

**Comment by pixelzoom** [comment]
Reopening.  Noted during https://github.com/phetsims/graphing-quadratics/issues/43.  As currently implemented, the client can change `phetioType`.  Is that really desired, or should `phetioType` be set by BooleanProperty? 

Same issue in StringProperty and NumberProperty.

**Comment by samreid** [comment]
The current code is 
```js
    options = _.extend( {
      phetioType: PropertyIO( BooleanIO )
    }, options );
```

@pixelzoom is asking if we should go to a pattern more like:

```js
options.phetioType = PropertyIO( BooleanIO );
```

In my opinion, the former pattern is superior because it allows extensibility--if we later have a subclass of BooleanProperty that needs to provide its own phetioType, it would be able to do.  Hard-coding the `phetioType` makes this impossible.

**Comment by pixelzoom** [comment]
How is it possible to use a different value for `phetioType` when it's impossible to use a different value for `valueType`?  See BooleanProperty constructor below.   

And isn't the point to have consistency for these type-specific Property subclasses? 

```js
  function BooleanProperty( value, options ) {

    options = _.extend( {
      phetioType: PropertyIO( BooleanIO )
    }, options );

    assert && assert( !options.isValidValue, 'isValidValue is not supported by BooleanProperty' );
    assert && assert( !options.validValues, 'validValues is not supported by BooleanProperty' );
    assert && assert( !options.valueType, 'valueType is set by BooleanProperty' );
    options.valueType = 'boolean';  // BooleanProperty requires values to be primitive booleans

    Property.call( this, value, options );
  }
```

**Comment by samreid** [comment]
I also prefer the `options.valueType = 'boolean';` to be in the options, for the same reason.

**Comment by pixelzoom** [comment]
So you're saying that we might need to set BooleanType to something other than `valueType: 'boolean'`?   I'm having a difficult time coming up for a reason why that would be necessary or desirable.  Do you have a plausible scenario?

**Comment by pixelzoom** [comment]
So if we move `valueType` and `phetioType` to options as you've suggested, then I can write this and nothing will complain:

```js
var visibleProperty = new BooleanProperty( 'foo', {
  valueType: 'string',
  phetioType: PropertyIO( StringIO )
} );
```

Trying to understand why that's OK or even desirable.

**Comment by samreid** [comment]
My objection is to the pattern in general. If I came up with an example for this particular case it would be very contrived.

**Comment by pixelzoom** [comment]
You object to giving subclasses control over specific superclass options by preventing clients from from setting those options?   Nothing wrong with this example?

```js
class RedLine extends Line {
  constructor( options ) {
    options = _.extend( {
      stroke: 'red'
    } );
  }
}

var line = new RedLine( { stroke: 'blue' } );
```

**Comment by samreid** [comment]
Perhaps the general case would be to provide something like this:

```js
    options = _.extend( {
      a: A
    }, options );
    assert && assert( options.a instanceof A );
```

This would allow subtypes to provide instances of type B extends A.  But I think you are right about constants/primitives.

**Comment by pixelzoom** [comment]
That general case is nothing but type checking.  That's different from taking full responsibility for an option value.  Which I thought was the point of BooleanProperty -- to be responsible for ensuring that values were of type `boolean`.

**Comment by samreid** [comment]
So is the recommended solution something like this?

```js
    options = options || {};

    assert && assert( !options.hasOwnProperty( 'phetioType' ), 'phetioType is provided by BooleanProperty' );
    options.phetioType = PropertyIO( BooleanIO );
```

That seems great for this case.

**Comment by pixelzoom** [comment]
Yep, BooleanProperty constructor would be:

```js
  function BooleanProperty( value, options ) {

    options = options || {};

    assert && assert( !options.isValidValue, 'isValidValue is not supported by BooleanProperty' );
    assert && assert( !options.validValues, 'validValues is not supported by BooleanProperty' );
    assert && assert( !options.valueType, 'valueType is set by BooleanProperty' );
    options.valueType = 'boolean';  // BooleanProperty requires values to be primitive booleans

    assert && assert( !options.hasOwnProperty( 'phetioType' ), 'phetioType is set by BooleanProperty' );
    options.phetioType = PropertyIO( BooleanIO );

    Property.call( this, value, options );
  }
```

What I understood you to mean in https://github.com/phetsims/axon/issues/116#issuecomment-435258731 was:

```js
  function BooleanProperty( value, options ) {

    options = _.extend( {
     options.valueType = 'boolean',
      phetioType: PropertyIO( BooleanIO )
    }, options );

    Property.call( this, value, options );
  }
```

... but that allows the client to bypass  BooleanProperty's sole responsibility.

**Comment by samreid** [comment]
I'm on board, thanks for talking me through it!  Committed above, anything else for this issue?

**Comment by pixelzoom** [comment]
Should we do the same for StringProperty and NumberProperty?

**Comment by pixelzoom** [comment]
NumberProperty is currently `phetioType: NumberIO`.  Shouldn't that be `phetioType: PropertyIO( NumberIO )`?

**Comment by samreid** [comment]
NumberProperty currently has this code:

```js
    options = _.extend( {
      numberType: 'FloatingPoint', // {string} see VALID_VALUE_TYPES

      // {Range|null} range
      range: null,
      phetioType: NumberPropertyIO
    }, options );
```

Note `phetioType: NumberPropertyIO` as opposed to `phetioType: NumberIO`.  Please see `NumberPropertyIO` for more details.

> Should we do the same for StringProperty and NumberProperty?

Yes, I suspect so.  I'll commit shortly.

**Comment by pixelzoom** [comment]
Ah, I see... NumberProperty is currently `phetioType: NumberPropertyIO`.  

```js
BooleanProperty - `phetioType: PropertyIO( BooleanIO )`
StringProperty - `phetioType: PropertyIO( StringIO )`
NumberProperty - `phetioType: NumberPropertyIO`
```

Is NumberProperty different from the others because it saved state?

**Comment by samreid** [comment]
It looks like NumberPropertyIO adds the numeric range and number type, which are not part of NumberIO.

**Comment by samreid** [comment]
Proposed fixes committed, ready for review.

**Comment by pixelzoom** [comment]
Looks good, closing.
