### ISSUE TITLE
ObservableArray: are anyElementMatchesPredicate and count  necessary?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#117]
@samreid added `anyElementMatchesPredicate` and `count` to `ObservableArray` in @8ed4fc2202620d5cbd28857f79a43361434d8594.  Looks like circuit-construction-kit-common (the only client) was the motivation for adding these.

Imo, these are unnecessary.  ObservableArray doesn't need the extra baggage, and this type of "predicate test" is handled very nicely by lodash.

`anyElementMatchesPredicate` duplicates `_.find`.
`count` duplicates `_.filter`.

Examples of how lodash accomplished the same thing:

```
> var myArray = new phet.axon.ObservableArray( [ -2, -1, 0, 1, 2 ] );
> !!_.find( o.getArray(), function( item ) { return item === 1; } )
true
> !!_.find( o.getArray(), function( item ) { return item === 4; } )
false
> _.filter( o.getArray(), function( item ) { return item > 0; } ).length
2
```

**Comment by pixelzoom** [comment]
This issue was noted while using ObservableArray in Unit Rates, and discovering that some documentation needed fixing (including for these functions, which were both missing visibility annotations).

**Comment by pixelzoom** [comment]
How the usages in circuit-construction-kit-common would be replaced:

Circuit line 581 before:

```js
  return this.circuitElements.anyElementMatchesPredicate( function( circuitElement ) {
        return circuitElement.containsBothVertices( a, b );
      } );
```

after:

```js
  return !!_.find( this.circuitElements.getArray(), function( circuitElement ) {
        return circuitElement.containsBothVertices( a, b );
      } ) );
```

Circuit line 437 before:

```js
      return this.circuitElements.count( function( circuitElement ) {
        return circuitElement.containsVertex( vertex );
      } );
```

after:

```js
      return _.filter( this.circuitElements.getArray(), function( circuitElement ) {
        return circuitElement.containsVertex( vertex );
      } ) ).length;
```

**Comment by jonathanolson** [comment]
I feel like we should have a general count() function that does what ObservableArray does (I run into this with regular arrays a lot, and it feels unclean).

Also instead of `!!_.find( ... )`, use `_.some( ... )`, and if we keep functions on ObservableArray, I'd recommend a name change to observableArray.some( ... ).

In general, I have a slight preference towards including helper functions, as it makes code more readable, e.g.:

```js
array.count( predicate );
```
vs
```js
_.filter( array.getArray(), predicate ).length;
```

particularly because the verbose pattern is very easy to mess up silently:
```js
var array = new phet.axon.ObservableArray( [ 1, 2, 3 ] );

// Whoops, forgot getArray(). Returns 0 with no error
_.filter( array, function( x ) { return x < 2; } ).length;

// Correct now
_.filter( array.getArray(), function( x ) { return x < 2; } ).length;

var hasElement = _.filter( array.getArray, predicate );
if ( hasElement ) {
  // Forgot length, so this will always execute
}
```

**Comment by pixelzoom** [comment]
> In general, I have a slight preference towards including helper functions

Why should ObservableArray be different than plain old JS arrays?  If you can use the same API that one would use for JS arrays, that is (to me) a bonus.  Even if it's slightly less "clean".

The  helper functions that we added have this identical structure:

```js
     for ( var i = 0; i < this._array.length; i++ ) {
        if ( predicate( this._array[ i ] ) ) {
          do something
        }
      }
      return something;
```

When someone wants to return all elements that matches a predicate, are we going to add yet-another function to do that?  Where do we stop replicating the "predicate" functionality that's already present in lodash?

**Comment by jonathanolson** [comment]
> The helper functions that @samreid added have this identical structure

I didn't check the implementation. Presumably it could use the lodash replacements you recommended.

> Where do we stop replicating the "predicate" functionality that's already present in lodash?

Seems like a slippery slope (note ObservableArray.filter/map already exist, so we have array.filter(), observableArray.filter and _.filter).

One one hand, I'd like to simplify client code and help prevent easy silent bugs from happening. On the other hand, I don't want to have multiple implementations, particularly if they differ (like the filter functions currently).

My current best thought is to forward functions to lodash, e.g.:

```js
ObservableArray.map = function() {
  _.map.apply( null, this.getArray(), Array.prototype.slice.call( arguments ) );
};
```

which would allow all of the advanced functionality that Lodash supports for things like map (e.g. `array.map( 'x' )` would grab the item.x out of each item).

Thus we wouldn't be duplicating implementations (just forwarding to Lodash's advanced handling), but it would help prevent easy mistakes (can't forget the `getArray()`).

**Comment by samreid** [comment]
I'm a big fan of @jonathanolson's recommendation above, with the additional thought that we should  forward to native js array functions where possible and forward to lodash methods where native array methods are not possible.

**Comment by jonathanolson** [comment]
> we should forward to native js array functions where possible and forward to lodash methods where native array methods are not possible.

Map exists on Array, but I prefer the Lodash version because it allows for the example in my previous comment, so would prefer lodash even when native is available.

**Comment by samreid** [comment]
Today @jonathanolson and I noted that _.forEach, Array.forEach and ObservableArray.forEach all exhibit different behavior under concurrent modification.  Fun!

**Comment by pixelzoom** [comment]
Specifics or (better) example?

**Comment by samreid** [comment]
```js
var myArray = [0,1,2,3];
_.forEach(myArray,function(x){console.log(x);myArray.length=0;});
```

0
undefined
undefined
undefined

```js
var myArray = [0,1,2,3];
myArray.forEach(function(x){console.log(x);myArray.length=0;});
```

0
undefined

```js
var o = new phet.axon.ObservableArray([0,1,2,3])
o.forEach(function(x){console.log(x);myArray.length=0;});
```

0 
1
2
3

**Comment by samreid** [comment]
In the preceding commit, I added ObservableArray.find which forwards to lodash.find and it seems to be working nicely.  I think it is good to keep `count` since filter().length creates unnecessary garbage.  I'm not ready to change other implementations over to lodash implementation--not certain that's best.

**Comment by pixelzoom** [comment]
@samreid what's left to do here?

**Comment by samreid** [comment]
> I think it is good to keep count since filter().length creates unnecessary garbage. I'm not ready to change other implementations over to lodash implementation--not certain that's best.

This question was asked in https://stackoverflow.com/questions/35562307/count-where-in-a-collection and garbage is noted as an issue.  The `sumBy` approach doesn't seem superior to `ObservableArray.count`

I'm also seeing ObservableArray.reduce which could be switched to lodash, leaving self assigned to investigate.
