### ISSUE TITLE
Allow ObservableArray access by bracket operator

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#118]
Currently when using ObservableArray, the client must use observableArray.get(i) instead of observableArray[i], which has led to some bugs in refactoring.  I realized it is possible to use bracket operator for observable array (though not without some drawbacks).  Some ideas for implementing this are described here:
http://stackoverflow.com/questions/1711357/how-would-you-overload-the-operator-in-javascript

This seems like it might be a crazy idea, but maybe worth thinking through to have a clear grasp of the disadvantages before we decide against it.

**Comment by jonathanolson** [comment]
Notable: http://caniuse.com/#feat=proxy (and we'll want to check to make sure it doesn't crater performance). I recall browser support was insufficient beforehand, but there are a lot of things that proxy can help.

**Comment by samreid** [comment]
Proxy seems like the right solution to this problem (if we decide to investigate it), but a read-only "hack" is possible where we assign values like this:
```js
set: function(index, element){
  this.[index] = element;
}
```

This could also tank performance.  And Proxy sounds interesting for investigation.

**Comment by jonathanolson** [comment]
> This could also tank performance.

Probably would happen when you remove the first element (needs to reassign all indices). Would recommend waiting for Proxy to handle this.

**Comment by samreid** [comment]
@jonathanolson or @oliver-phet, can you please report on current IE11 usage from our analytics?

**Comment by samreid** [comment]
Unassigning until all our platforms support Proxy.

**Comment by pixelzoom** [comment]
For the record... I'm not a fan of add support for observableArray[i], for the same reason that I was not a fan of PropertySet.  It obscured the fact that we're dealing with an ObservableArray.

**Comment by pixelzoom** [comment]
This enhancement was first menqioned by @samreid in https://github.com/phetsims/axon/issues/5#issuecomment-224752263.

**Comment by samreid** [comment]
Agreed, let's use the existing ObservableArray API, closing.
