### ISSUE TITLE
Remove DerivedProperty convenience functions

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#120]
Extending from https://github.com/phetsims/axon/issues/88.

@samreid and I stumbled across this during a phet-io meeting. It seems like few if any of these are actually being used in our code. If they are being used, they should be moved to their parent (Property). 

Are they worth removing?

**Comment by samreid** [comment]
@zepumph can you please look through these and remove any DerivedProperty methods like this that are unused in sims?  (Methods used only in unit tests can be deleted).

**Comment by zepumph** [comment]
I removed multiple functions from DerivedProperty and the test suite. The other ones that we kept have just a few uses scattered around the project. @samreid could you close if all looks good.

**Comment by samreid** [comment]
@jonathanolson said:

> Continuous testing is very orange/red. Anyone actively working on DerivedProperty, or can I apply fixes?
> Applied fixes

**Comment by zepumph** [comment]
Thanks @jonathanolson for helping out with lint, c25a9a221f8d182d0360fedda11b76549f497c88

**Comment by samreid** [comment]
Thanks, looks great @zepumph, closing.
