### ISSUE TITLE
in JSDoc for ObservableArray, should array be optional?

### ISSUE THREAD

**Issue by jbphet** [phetsims/axon#121]
My IDE is in some cases flagging usages of `new ObservableArrary()` with a warning that says "Invalid number of arguments" based on the JSDoc header.  I think `array` should probably be `[array]' in the JSDoc, but I thought I've have @samreid verify and make the change if I'm correct on this.

**Comment by samreid** [comment]
Fixed, thanks @jbphet!

**Comment by pixelzoom** [comment]
Having 2 optional parameters makes for some odd code in the constructor... But I verified that this was fixed.   Closing.
