### ISSUE TITLE
change Property.dispose() to unlink listeners instead of asserting

### ISSUE THREAD

**Issue by jbphet** [phetsims/axon#124]
As of this writing, the `dispose()` function in `Property.js` asserts if a `Property` instance is disposed that still has listeners attached.  In a recent developer meeting, we decided that because disposing of a property that had listeners attached is not likely to create a memory leak, this is probably not the best approach.  Instead, we should just clear out all references to listeners.

The discussion was originally logged in https://github.com/phetsims/sun/issues/274 starting at comment https://github.com/phetsims/sun/issues/274#issuecomment-299219698 and proceeding for the next 4 comments.

**Comment by jbphet** [comment]
Implemented, assigning to @samreid for review.

**Comment by jbphet** [comment]
For reference, I tested several simulations that call Property.dispose(), making sure to do the things with the simulation that caused `Property,dispose()` to be called.  I saw no problems.  The sims were:
+ Charges and Fields
+ CCK Black Box Study
+ Expression Exchange
+ John Travoltage

**Comment by samreid** [comment]
The change set looks great.  @zepumph can you please track down the axon issue where PHET_IO_FUNCTION was introduced and make sure everything still works properly after this change?

**Comment by zepumph** [comment]
https://github.com/phetsims/sun/issues/274#issuecomment-307138289 

It looks like @jbphet took care of this. I will look over this soon, and close if all seems good.

**Comment by jbphet** [comment]
I did take care of it, and I think it is safe to close this.

**Comment by zepumph** [comment]
Great thanks!
