### ISSUE TITLE
Emitter.dispose() - change to remove all listeners instead of asserting

### ISSUE THREAD

**Issue by jbphet** [phetsims/axon#126]
In #124, `Property.dispose()` was changed to remove all listeners instead of asserting.  I just used `Emitter` for something, and noticed that its dispose function asserts.  I'm thinking that this should also be changed to remove all listeners.

Assigning to @samreid to make sure that he concurs, then he can either do it or assign it to me for implementation.

**Comment by samreid** [comment]
I can't think of any reason the same decision wouldn't apply to Emitter.  Can you take a look?

**Comment by pixelzoom** [comment]
Way back when this issue was created, Emitter.dispose was:

```js

    /**
     * Dispose an Emitter that is no longer used.  Like Property.dispose, this method checks that there are no leaked
     * listeners.
     */
    dispose: function() {
      assert && assert( !this.hasListeners(), 'Listeners should have been removed before disposal' );
    },
```

It is currently:

```js
    dispose() {

      // See https://github.com/phetsims/axon/issues/124
      this.listeners.length = 0;

      PhetioObject.prototype.dispose.call( this );
    }
```

So this problem no longer exists, and I'm closing this issue.  @jbphet if you disagree, please reopen.
