### ISSUE TITLE
Remove Property.once

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#130]
Discovered in https://github.com/phetsims/axon/issues/129 it looks like `property.once` only appears in 3 sites (all in Area Builder).  Perhaps we should eliminate this feature of Property.

**Comment by samreid** [comment]
Is this as simple as adding a line like:

```js
movableShape.userControlledProperty.unlink( thisFunction );
```

to each of the invocations?  In that case it may make sense to take Property.once out of its API to keep it mean and lean.

@jbphet can you please take a look?

**Comment by jbphet** [comment]
These usages can be refactored if necessary.  However, I found the `once` method to be convenient and clear in these locations.  I just took a look at #129, and all it said about this method was:

> `once` has the same problems as `lazyLink`.

If that's truly the case, why not apply the same fix to both and keep them?

**Comment by samreid** [comment]
I'm not sure what's best.  Let's ping @jonathanolson and @jessegreenberg

**Comment by jonathanolson** [comment]
`once` seems convenient potentially, I'd like to know more about the reason for removal.

Is it that the change may never happen, so we need to keep a reference to the listener (and thus on our disposal, conditionally remove the listener)?

**Comment by samreid** [comment]
Here are my main reasons for wanting to remove `Property.once`:

(1) It doesn't provide much value.  It currently adds 22 lines of code to Property.js to cut down on 3 lines of code elsewhere.  Yes, this could change if we start using Property.once more, but I'm reporting on the current state.  It also increases the Property.js API, which is not clearly warranted.

(2) It has unusual semantics.  For instance
```js
// This works great
nameProperty.link(x);
nameProperty.unlink(x);

// This is incorrect
nameProperty.once(x);
nameProperty.unlink(x);

// Given the current implementation here is how you would have to do that:
var onceWrapper = nameProperty.once(x);
nameProperty.unlink(onceWrapper);
```

(3) In code review, the user can search for link() to find links and lazy links and link attributes.  But this may be missed.  However, this is not a serious problem and we could change the search to be `Property.` or rename this method.

**Comment by samreid** [comment]
@jbphet says it is nice and readable at the usage site, and lots of JS emitter libraries provide "once"

**Comment by samreid** [comment]
@jonathanolson says even though it is not in the primary `link` and `unlink` api, it is still a valuable 2ndary API, like `linkAttribute`.

Perhaps @jessegreenberg and I can find a way to overcome the unusual semantics in #129
