### ISSUE TITLE
Delete TEvents?

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#133]
I see no usages of this outside of the file itself. I think it should be deleted. @samreid please confirm.

**Comment by samreid** [comment]
I was surprised to see no usage of this in Events.js, perhaps it was used once.  I found a paper trail here https://github.com/phetsims/axon/issues/100 that said TEvents was only used in Beaker.  So I think it's safe to delete.  I'll do so now.

**Comment by samreid** [comment]
> @samreid please confirm.

Please add me as an assignee to issues where my feedback is requested.

**Comment by samreid** [comment]
Removed in the preceding commit.  Reassigned to @zepumph to see if there's anything else and to confirm to add me as assignee in future issues that need my feedback.

**Comment by zepumph** [comment]
I'll assign for here on, sorry about that! All looks good for this. I remember a while ago that we changed all toEventOnStatic to use toEventOnEmit. I bet that got rid of a few usages of this?

Closing.
