### ISSUE TITLE
link doesn't provide old value in callback

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#138]
Copied from https://github.com/phetsims/phet-io/issues/1125

In the axon library, the callback for 'Property.link` provides the old value of the property as a second parameter in the callback function call.  I'm doing some work on wrappers, and have a situation where that would be useful, but the old value doesn't appear to be provided.

Below is a code example.  In this case, `oldUserControlled` is always undefined.

```
    simIFrameClient.invoke(
      'buildAnAtom.' + screen + '.model.protons_0.userControlledProperty',
      'link',
      [ function( userControlled, oldUserControlled ) {
        console.log( 'oldUserControlled = ' + oldUserControlled );
        if ( userControlled ){
          window.soundAssociations.proton.dragStarted.play();
        }
        else{
          window.soundAssociations.proton.dragEnded.play();
        }
      } ]
    );
```

**Comment by zepumph** [comment]
@zepumph said 

I worked on this today, and it actually ended up being a real pain in the butt. I thought it would be as simple as just adding that extra argument to pass through, and then using it, but it revealed a flaw in TTypes where most of the complex `toStateObject` functions don't support nulls being passed through. This was revealed because the link function is first called with the second value (oldValue) null. I have two ways to go about solving this. The first is to add this line into `SimIFrameClient.wrapFunction.f` 

```js
        // Workaround so that toStateObject doesn't have to support null;        
        if ( parameterValue === null ) {
          coercedArguments.push( null );
        }
        else {
          coercedArguments.push( parameterType.toStateObject( parameterValue ) );
        }
```

instead of just the last line like it is now.

The other is for TTypes to support null values. It seems like this is the best solution for some reasons. It feels for robust to me. The problem is that it adds even more boilerplate to ttypes when most of the time we don't care. I am going to implement to the first option right now to see how it goes, and then we can always improve on this later.

@jbphet for future reference I didn't find this issue until poking around in the repo's unassigned issues, which I do pretty rarely (maybe I should more). Anywho, feel free to assign any phet-io issues directly to me and they will probably be solved sooner.

**Comment by zepumph** [comment]
Then I said:
A list of TTypes that would need the addition of null checks if we go with option 2 above:

* TBounds2.js
* TBounds3.js
* TVector2.js
* TVector3.js
* TBeersLawSolution.js
* BLL/TSolute.js
* Molarity/TSolute.js
* TColor.js

**Comment by zepumph** [comment]
Then @jbphet said: 
@zepumph said:

> @jbphet for future reference I didn't find this issue until poking around in the repo's unassigned issues...

Thanks for letting me know, and I'll make sure to assign them to you in the future.  Glad you found it.

**Comment by zepumph** [comment]
I said:
The extra check in SimIFrameAPI also needs to protect against undefineds as well. The reason I don't just protect against falsey is because I want empty strings to pass through alright.

**Comment by zepumph** [comment]
This issue is ready to close. @jbphet you should be able to get oldValue from a link call over the frame on master. Let me know if there are any problems. Closing

**Comment by jbphet** [comment]
Thanks @zepumph.  I probably won't test it right away, but will do so when needed for the sonification work.
