### ISSUE TITLE
Save & Load Arrays and ObservableArrays by saving references to elements

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#139]
carried from https://github.com/phetsims/phet-io/issues/855

@samreid said:  

From https://github.com/phetsims/phet-io/issues/319#issuecomment-260048103

For ObservableArray, we could save/load the list of tandems, and use that for object identity (so objects don't get deserialized twice).

This may just be necessary for redundant arrays, primary arrays should already be handled by the default save/load.

**Comment by samreid** [comment]
`createObservableArray` and `ArrayIO` both support state, and we can also use `PhetioGroup` when necessary.  @zepumph can this issue be closed?
