### ISSUE TITLE
Phase 2: remove the guard from Property.link

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#140]
Phase 2 of https://github.com/phetsims/axon/issues/129#issuecomment-321997713.

Here's the change that will be made:

```js
      link: function( listener ) {
-         if ( !this.changedEmitter.hasListener( listener ) ) {
          this.changedEmitter.addListener( listener );
          listener( this.get(), null ); // null should be used when an object is expected but unavailable
-         }
      },
```

Since we're not done with Phase 1 (https://github.com/phetsims/axon/issues/132), I won't modify the "listeners" branch yet.

**Comment by pixelzoom** [comment]
Testing with `?ea&fuzzMouse`, I discovered and fixed 1 issue in joist (phetsims/joist#441) and beers-law-lab.   All of the sims that I'm responsible for are error-free for Phase 2.

**Comment by jessegreenberg** [comment]
Running test-server without the guard in ```link```, I am not seeing any issues related to this phase. All I see is:
```
circuit-construction-kit-black-box-study
Uncaught TypeError: startVertex.positionProperty.get(...).distance is not a function
TypeError: startVertex.positionProperty.get(...).distance is not a function
   ...
optics-lab
Uncaught TypeError: Cannot read property 'getStart' of undefined
TypeError: Cannot read property 'getStart' of undefined
  ...
```

**Comment by jessegreenberg** [comment]
Sorry, https://github.com/phetsims/axon/issues/140#issuecomment-327953320 was likely applied to master and doesn't apply.

**Comment by pixelzoom** [comment]
9/14/17 dev meeting:

Let's add change in https://github.com/phetsims/axon/issues/140#issue-256008718 to the 'listeners' branch.  Remaining Phase 1 (#132) issues are for @jonathanolson, so he'll address Phase 1 (#132) and Phase 2 at the same time.   Someone needs to run test-sever with the 'listeners' branch to identify which sims have the Phase 2 problem.

**Comment by pixelzoom** [comment]
I removed the guard in `link`, see above commit.

Does someone want to volunteer to identify which sims fail with the `link` guard removed?

**Comment by jessegreenberg** [comment]
> Does someone want to volunteer to identify which sims fail with the link guard removed?

Ill take a look.

**Comment by jessegreenberg** [comment]
Running through test-server on the ```listeners``` branch, here is  a checklist with sims where I am seeing errors:

- [ ] area-builder (@jbphet)
- [ ] build-a-molecule (@jonathanolson) 
- [ ] charges-and-fields (@jonathanolson)
- [ ] circuit-construction-kit-black-box-study (@samreid) 
- [ ] circuit-construction-kit-dc (@samreid)
- [ ] circuit-construction-kit-dc-virtual-lab (@samreid)
- [ ] expression-exchange (@jbphet)
- [ ] fractions-intro (@jonathanolson)

The CCK issues could be unrelated, but adding to list in case they are masking listener issues. Assigning issue to the devs in this checklist.

**Comment by samreid** [comment]
The `listenters` branch in axon is out of date and causing CCK to fail.  I'll merge master to `listeners`.

**Comment by samreid** [comment]
Merge complete

**Comment by samreid** [comment]
Thanks @jessegreenberg, this revealed an issue in a CCK dispose function.  Fixed in the preceding commit.

**Comment by samreid** [comment]
I'm tracking CCK in the aforementioned issue, so unassigning myself from this one.

**Comment by pixelzoom** [comment]
Since @jbphet is on vacation, I took at look at area-builder and expression-exchanged.

area-builder is failing in Property.once, not obvious (to me) why, so I punted.

expression-exchange was fixed in https://github.com/phetsims/expression-exchange/issues/130.

**Comment by jbphet** [comment]
I have fixed the issue in Area Builder.  The problem was due to a race condition where a composite shape that was animating to a destination on the shape placement board.  If, when the shape arrived, other shapes had been removed and the animating shape had to return to its origin, the animation would first finish, then be started again (to go back to the creator box), which would result in the `once` listener being called twice.  I fixed this by explicitly adding and removing the listener rather than relying on `once`.  The `once` method is still used in other places in the sim.

**Comment by jbphet** [comment]
I've reviewed the expression-exchange commits and the look good (see https://github.com/phetsims/expression-exchange/issues/130#issuecomment-333206019).  Unassigning myself.

**Comment by samreid** [comment]
The last unchecked box is CCK black box study which exhibits the problem in https://github.com/phetsims/sun/issues/322, I could use help deciding how to address it.

**Comment by samreid** [comment]
@jonathanolson and I worked on https://github.com/phetsims/sun/issues/322 and got CCK Black Box checked off.  Hence we are at a good point where we can merge the axon listener branch to master.  Note: CCK DC is close to getting RC shas.  If we merge before SHAs then we will have the opportunity to reveal latent bugs during testing, but it may require another QA cycle (if problems come up).

**Comment by samreid** [comment]
We decided to merge axon listeners branch to master.

**Comment by samreid** [comment]
OK merge complete!

**Comment by samreid** [comment]
Let's close and reopen if Bayes finds problems.
