### ISSUE TITLE
Replace usages of Events with Emitter

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#142]
Events.js is deprecated and Emitter should be used instead, we should chip away at this.  This is somewhat related to https://github.com/phetsims/axon/issues/102 because PropertySet extended Events.

**Comment by samreid** [comment]
Scheduled for developer meeting to do the following:
1. Make sure this is a desirable task to complete
2. Determine what to do with usages in Node.js.  Should this file become Node-specific, or integrated into Node?  Should Node use emitters?  How many emitters would each Node need to evade Events?
3. Schedule/plan for working on this

**Comment by pixelzoom** [comment]
Searching for "var Events", I see the following number of usages by repository:

> 1 axon (Property)
2 dot (Transform3, Transform4)
3 fluid-pressure-and-flow
3 kite (Shape, Segments, Subpath)
1 molecule-shapes
6 scenery (Node, Display, Drawable, Instance, AccessibleInstance, AccessiblePeer)

Thoughts:

(1) Replace usages of "var Events" with "var Emitter" in sim repos first.

(2) Property and Node both extend Events. Use of the Events API for those subtypes will be probably be the bulk of the changes to client code. This will be time-consuming and (potentially) destabilizing to locate and change.

(3) Node extends Events has always felt a bit wrong. I don't think that Node should extend Emitter. Changing from inheritance to (e.g.) composition will complicate changes to client code.

**Comment by samreid** [comment]
> 1 axon (Property)

> Property and Node both extend Events. 

Did you mean PropertySet?  That currently extends Events and will be deleted once it is no longer used.

**Comment by pixelzoom** [comment]
Yes, I meant PropertySet.  Looks like you didn't see the EDIT to my comment above.

**Comment by pixelzoom** [comment]
9/14/17 dev meeting:

Start by removing `var Events` from sims.
Then remove from dot and kite.
Then address scenery (where some of the usage is internal).

All of the above except FAPF is in @jonathanolson's wheelhouse, so he self assigned.

**Comment by samreid** [comment]
Co-assigning to @zepumph to work on the FPAF occurrences.  It looks like all of the occurrences trigger `update` or `updated`, so these should all change to `updatedEmitter.emit`.

**Comment by zepumph** [comment]
FPAF was completed in https://github.com/phetsims/fluid-pressure-and-flow/issues/297. Unassigning.

**Comment by samreid** [comment]
Events has been deleted, closing.
