### ISSUE TITLE
preventGetSet in sims that no longer use PropertySet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#143]
Related to https://github.com/phetsims/axon/issues/102 (Deprecate PropertySet), this function was added to `Property`:

```js
      /**
       * When porting simulations away from PropertySet, it is useful to have a way to guarantee that all ES5
       * getters and setters have been refactored.  This method can help you identify ES5 get/set calls that still exist
       * if they are triggered in the code at runtime.
       * @param {Object} object
       * @param {string} prop
       * @deprecated this is for debugging only - do not leave calls to this function in production code
       */
      preventGetSet: function( object, prop ) {
```

Note the `@deprecated` annotation:  "this is for debugging only - do not leave calls to this function in production code".

The following sims (some production code) contain calls to `preventGetSet`:

- [x] bending-light
- [x] energy-skate-park-basics
- [x] fraction-matcher
- [x] protein-synthesis
- [x] sugar-and-salt-solutions

PropertySet has been removed from all of these sims.  And @samreid is the responsible developer for all of them.

@samreid did you forget to remove `preventGetSet` after completing https://github.com/phetsims/axon/issues/102?

**Comment by samreid** [comment]
Planning to remove these occurrences after PropertySet is gone.

**Comment by samreid** [comment]
Also, when PropertySet is gone, we'll also delete `Property.preventGetSet`.

**Comment by pixelzoom** [comment]
Deletion of `preventGetSet` is tracked in https://github.com/phetsims/axon/issues/144.

**Comment by pixelzoom** [comment]
@samreid said:
> Planning to remove these occurrences after PropertySet is gone.

Your call, but not advised to wait.  This function was intended to be used during the conversion process, then removed immediately -- i.e. "do not leave calls to this function in production code".

**Comment by zepumph** [comment]
Just so we know, fluid-pressure-and-flow has not yet been converted from `PropertySet`, so please don't delete usages of `preventGetSet` there quite yet.

**Comment by pixelzoom** [comment]
@zepumph said:
> Just so we know, fluid-pressure-and-flow has not yet been converted

My bad. Removed from the checklist in https://github.com/phetsims/axon/issues/143#issue-257137181.

**Comment by samreid** [comment]
I removed usages in completed sims, reassigned to @pixelzoom for feedback/review.

**Comment by pixelzoom** [comment]
Verified that the only remaining usages are in sims that haven't still use PropertySet (i.e., fluid-pressure-and-flow).  Closing.
