### ISSUE TITLE
delete Property.preventGetSet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#144]
Related to #102 and #143...  Let's not forget to delete Property.preventGetSet when PropertySet is gone.

**Comment by samreid** [comment]
I'd like Bayes to test preventGetSet in Fluid Pressure and Flow for a couple of days before removing it.

**Comment by samreid** [comment]
Bayes says we are good to go:
![image](https://user-images.githubusercontent.com/679486/30429531-1b099ebe-9915-11e7-95f9-1f4aef9f3f44.png)

I'll delete Property.preventGetSet now.

**Comment by samreid** [comment]
I removed it, closing.
