### ISSUE TITLE
Should Property have a `phetioReadonly` property?

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#145]
From https://github.com/phetsims/scenery-phet/issues/327.

Sometimes in phet-io we want to instrument a Property without giving clients the ability to set it and get themselves in trouble. 

As discussed in the aforementioned issue, I think it would be better to put it directly on the Property, rather than on the TType, even though it would be used just for PhET-iO. Maybe we should discuss with a broader scope of developers to see if this would be useful for PhET development.

**Comment by samreid** [comment]
`phetioReadOnly` is working well, we may move it from all types just to Property as part of https://github.com/phetsims/scenery/issues/711, closing.
