### ISSUE TITLE
Property.js creates needless closures

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#147]
During the code review of Circuit Construction Kit: DC, @jonathanolson pointed out that it can be better for memory and performance to eliminate closures and we moved to a closure-less dispose pattern for several object types.  I noticed Property.js is creating disposal closures and I added 

```js
var count = 1;

///...

console.log('closure',count++);
```
to count how many Property.dispose closures are created on startup, I saw:

CCK-DC: 1008
Function Builder: 1458

We will likely need to assign `this.tandem=options.tandem` for use in the disposal.

Tagging @jonathanolson and @pixelzoom and @jbphet so they are aware of this pending change.

**Comment by samreid** [comment]
Fixed in the preceding commit, @jonathanolson @pixelzoom or @jbphet can you please review?

**Comment by pixelzoom** [comment]
👍 Commit looks good to me.

**Comment by pixelzoom** [comment]
Back to @samreid. If there's nothing else to do here, or you don't need an additional review, feel free to close.
