### ISSUE TITLE
Issues in DerivedProperty.dispose

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#148]
DerivedProperty.dispose seems to call tandem.removeInstance a 2nd time, and doesn't have super.dispose last.  We should remedy this.  Discovered in https://github.com/phetsims/build-an-atom/issues/176

**Comment by samreid** [comment]
Proposed fix is above, @pixelzoom can you please take a look?

**Comment by pixelzoom** [comment]
Property calls `addInstance` like this:

```js
99 options.tandem.addInstance( this, this.ttype, options );
```

DerivedPropery calls `addInstance` like this:

```js
options.tandem.supplied && options.tandem.addInstance( this, TDerivedProperty( options.phetioValueType ), options );
```

Why are they both calling `addInstance`?
Why are the calls different?

**Comment by samreid** [comment]
We discussed this Thursday and I jotted down notes here https://github.com/phetsims/tandem/issues/31.  To summarize answers to the above questions:

> Why are they both calling addInstance?

Child class and parent class call tandem.addInstance so that the instance is only registered once with the correct type and after it is fully initialized.  The parent class gets a `tandem.createSupertypeTandem` which turns `tandem.addInstance` into a no-op.

> Why are the calls different?

The TDerivedProperty invocation would fail if not provided a valid options.phetioValueType, hence we make sure the tandem is supplied (i.e. that the instance is instrumented) before trying to create the TType.  Note that in Property a different pattern is used:

```js
    this.ttype = TProperty( options.phetioValueType || TVoid, {
      phetioInstanceDocumentation: options.phetioInstanceDocumentation,
      phetioState: options.phetioState
    } );
```

This looks problematic, I think these options are getting moved out of TProperty as part of https://github.com/phetsims/phet-io/issues/1225

**Comment by pixelzoom** [comment]
I don't understand much of the response in https://github.com/phetsims/axon/issues/148#issuecomment-338442668. But...

@samreid said:
> Child class and parent class call tandem.addInstance so that the instance is only registered once

Why is this the case for DerivedProperty but not for other subtypes of Property?   
What happens if I want to create a subtype of DerivedProperty that necessitates a different TType?

Other issues:

(1) The comment after this (modified) line in DerivedProperty is now stale, you're not overriding anything:
```
54 this.derivedPropertyTandem = options.tandem; // @private - set after parent to override this.tandem from Property.js
```

(2) We decided that, to prevent shadowing/overwriting, there should never be an assignment to `this.tandem`.   I see 24 occurrences of "this.tandem =", including in `Property`.

**Comment by samreid** [comment]
> Why is this the case for DerivedProperty but not for other subtypes of Property?

e.g., StringProperty doesn't define any new methods, nor does it need a different implementation of `toStateObject` for serialization, hence it does not require its own TType.

> What happens if I want to create a subtype of DerivedProperty that necessitates a different TType?

Then you subclass DerivedProperty as MyDerivedPropertySubclass, create a TType TMyDerivedPropertySubclass then in the MyDerivedPropertySubclass constructor, pass tandem.createSuperTypeTandem() to the parent then use tandem.addInstance(this,TMyDerivedPropertySubclass) at the end of the constructor.

**Comment by pixelzoom** [comment]
Thanks for clarifying.  This all seems quite complicated, and I'm not confident that I could correctly instrument a type hierarchy.  But that's not what we're trying to resolve in this issue, so closing.
