### ISSUE TITLE
lengthProperty can be improved in ObservableArray

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#149]
As part of https://github.com/phetsims/build-an-atom/issues/156 @jbphet and @samreid and I found that the lengthProperty in ObservableArray isn't implemented in the best way. It is basically a DerivedProperty, but implemented as a NumberProperty. It also isn't instrumented for phet-io, which led to a proliferation of DerivedProperties in shred/ParticleAtom to keep track of the lengths in an instrumented manner. A question is whether or not we want this to always be instrumented, or even always be created. Is that increase in complexity worth the savings?

**Comment by pixelzoom** [comment]
My 2 cents...

According to its doc, "A DerivedProperty is computed based on other Properties".  So while `lengthProperty` is indeed derived from the length of the internal array (`this._array`), I would not expect it to be a `DerivedProperty`, because it has no dependencies on other `Property` instances.

Since `lengthProperty` is `@public (read-only)`, yes, it should be instrumented for PhET-iO. 

Given the number of sims that likely depend on `lengthProperty`, yes, it should always be instantiated.

**Comment by samreid** [comment]
> Since lengthProperty is @public (read-only), yes, it should be instrumented for PhET-iO.

Just because something is public in our code no longer implies that it should be instrumented for PhET-iO (as opposed to when we subscribed to the instrument-everything philosophy), but in this case it seems suitable that instrumented ObservableArrays should always have instrumented lengthProperty values.

@zepumph do we just use tandem.createTandem() and the optional part will pass through properly?

**Comment by zepumph** [comment]
That's right! Children will also be `tandem.optional && !tandem.supplied`

**Comment by samreid** [comment]
I instrumented `lengthProperty` and added `phetioSettable=false` so there won't be controls for it in instance proxies.  I tested in Forces and Motion Basics + instance proxies and 3 occurrences of lengthProperty seemed good.  I tested Faraday's Law which only has an ObservableArray with optional tandem and I confirmed that lengthProperty does not appear in instance proxies.

@zepumph can you please review?

**Comment by samreid** [comment]
Bayes reported

```
build-an-atom : phet-io-fuzz : require.js : run
Uncaught Error: Assertion failed: Cannot register two different instances to the same id: buildAnAtom.gameScreen.view.challenges_0View.schematicToElementChallengeView.noninteractiveSchematicAtomNode.particleAtom.protons.lengthProperty
Error: Assertion failed: Cannot register two different instances to the same id: buildAnAtom.gameScreen.view.challenges_0View.schematicToElementChallengeView.noninteractiveSchematicAtomNode.particleAtom.protons.lengthProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1509802686547/assert/js/assert.js:22:13)
    at Object.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1509802686547/phet-io/js/phetio.js?bust=1509804235829:533:19)
    at Object.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1509802686547/phet-io/js/phetio.js?bust=1509804235829:657:14)
    at Tandem.addInstance (https://bayes.colorado.edu/continuous-testing/snapshot-1509802686547/tandem/js/Tandem.js?bust=1509804235829:127:36)
    at new NumberProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1509802686547/axon/js/NumberProperty.js?bust=1509804235829:135:31)
    at new ObservableArray (https://bayes.colorado.edu/continuous-testing/snapshot-1509802686547/axon/js/ObservableArray.js?bust=1509804235829:54:27)
    at new ParticleAtom (https://bayes.colorado.edu/continuous-testing/snapshot-1509802686547/shred/js/model/ParticleAtom.js?bust=1509804235829:69:20)
    at new NonInteractiveSchematicAtomNode (https://bayes.colorado.edu/continuous-testing/snapshot-1509802686547/build-an-atom/js/game/view/NonInteractiveSchematicAtomNode.js?bust=1509804235829:32:24)
    at new SchematicToElementChallengeView (https://bayes.colorado.edu/continuous-testing/snapshot-1509802686547/build-an-atom/js/game/view/SchematicToElementChallengeView.js?bust=1509804235829:38:39)
    at SchematicToElementChallenge.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1509802686547/build-an-atom/js/game/model/SchematicToElementChallenge.js?bust=1509804235829:37:14)
Approximately 11/4/2017, 7:38:06 AM
```

This suggests we need to dispose the `lengthProperty`

**Comment by samreid** [comment]
The two commits should resolve the problem, leaving assigned to @zepumph for review.

**Comment by zepumph** [comment]
That looks good. Thanks for going through with this. Also congrats to all on emit4!! Is it possible that we could combine the "options" with the stateobject? Both are keys that are dependent on the instance, and I don't think that any keys from the state object should conflict with the addInstance options. (we could check with assertions too)

**Comment by pixelzoom** [comment]
@zepumph asked:
> Is it possible that we could combine the "options" with the stateobject? Both are keys that are dependent on the instance, and I don't think that any keys from the state object should conflict with the addInstance options. (we could check with assertions too)

Could you clarify this, I don't understand what you're asking.

**Comment by zepumph** [comment]
Indeed!

On phetio.js:563 we have this line:
`      options.phetioMethods && instanceAddedEmitter.emit4( phetioID, typeAPI, WrapperType.toStateObject ? WrapperType.toStateObject( instance ) : {}, options );`

Which in the above commits was adapted to emit a 4th arg. I posit if we can't combine these options (4th arg) with the third arg, which is a version of the toStateObject. Although they hold different types of data, they both are unique based on the instance and it may decrease complexity slightly if they were treated as one. FYI the toStateObject data is more like important properties for the instance, where as the options are more like properties for the phetio interface (what features to opt in to, documentation for the client. . .)

**Comment by samreid** [comment]
I think it will be simpler to keep them separate, since they will be used very differently.

**Comment by zepumph** [comment]
Sounds good. Thanks for tackling this @samreid.

**Comment by samreid** [comment]
@zepumph anything else before closing?

**Comment by zepumph** [comment]
Looks good.
