### ISSUE TITLE
Remove Property.onValue

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#150]
In https://github.com/phetsims/axon/issues/129 we decided we want to remove Property.onValue and just use Property.link instead for simplicity.  I'll take a look through cases and determine whether I can tackle it or should promote it to a chip-away issue for the team.

**Comment by samreid** [comment]
5 down 7 to go, it's been straightforward so far

**Comment by samreid** [comment]
I converted all usages and removed Property.onValue.  While it would be possible to reassign each commit to the responsible developer, I think it would be more efficient to just assign one developer to review all of the 12 conversions.  @jonathanolson @jbphet @pixelzoom can one of you volunteer to review and verify the changes.

**Comment by pixelzoom** [comment]
I've never used `onValue`, and I don't have time, so unassigning.

**Comment by jonathanolson** [comment]
Review looks good, with the exception of https://github.com/phetsims/seasons/commit/2f68b8dbba675eb34588f12b33707e0df170f20b introducing a formatting issue by removing spaces in parenthesis.

**Comment by samreid** [comment]
Thanks, closing.
