### ISSUE TITLE
DerivedProperty.tandem overwrites Property.tandem with wrong tandem

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#151]
We discovered this on Thursday.

**Comment by samreid** [comment]
We also discussed another Node-like strategy for setting tandems with phetioType, but I'm not sure where that issue is, and it will be good to have this fixed until we switch to another pattern (if we do).  @zepumph can you double check my commit and make sure I didn't miss anything?  Also do you know where we tracked discussion of the Node-like strategy for model tandems?

**Comment by zepumph** [comment]
That looks good. I went ahead and did the same thing to property just to be safe. Is https://github.com/phetsims/tandem/issues/31 the tracked discussion you were looking for? Closing.
