### ISSUE TITLE
visibility of phetioValueType

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#154]
Property:

```js
    // @public - export the phet-io element type
    this.phetioValueType = options.phetioValueType;
```

Shouldn't this be `@public (read-only, phet-io)` ?

**Comment by samreid** [comment]
It is for phet-io, but read by non-phet-io types such as `RectangularToggleButton`, `ComboBox`, etc.  So should we mark it as `@public (read-only) - used to indicate the TType of the element` ?

**Comment by pixelzoom** [comment]
Changed to:

```js
    // public (phet-io) (read-only)
    this.phetioState = options.phetioState;
```

 I didn't see a need to be more verbose, since `options.phetioState` is already documented, and its documentation is different than "used to indicate the TType of the element".  If you disagree, feel free to change, but make doc identical for `this.phetioState` and `options.phetioState`.
