### ISSUE TITLE
StringProperty: add support for validValues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#156]
Similar to https://github.com/phetsims/axon/issues/153 for NumberProperty...

StringProperty currently does not support validValues:

```js
41 assert && assert( !options.validValues, 'StringProperty cannot use validValues' );
```

This is needed in equality-explorer.  And I suspect that it's generally useful, since sets of string values are often used as a sort of enumeration.

**Comment by pixelzoom** [comment]
I'm also going to do some cleanup similar to https://github.com/phetsims/axon/issues/157.

**Comment by pixelzoom** [comment]
Cleanup and support for `validValues` in the above commit.

Console tests:

```
// default validation
> var p = new phet.axon.StringProperty( 'foo' )
undefined
> p.value = 'bar'
"bar"
> p.value = 0
Assertion failed: invalid value: 0

// validValues
> var p = new phet.axon.StringProperty( 'foo', { 
  validValues: [ 'foo', 'bar' ] 
} )
undefined
> p.value = 'bar'
"bar"
> p.value = 'bad'
Assertion failed: invalid value: bad

// isValidValue
> var p = new phet.axon.StringProperty( 'foo', { 
  isValidValue: function( value ) { return value[0] === 'f'; } // beings with 'f'
} )
undefined
> p.value = 'five'
"five"
> p.value = 'bad'
Assertion failed: invalid value: bad

// mutually exclusive options
> var p = new phet.axon.StringProperty( 'foo', { 
  validValues: [ 'foo', 'bar' ], 
  isValidValue: function( value ) { return value[0] === 'f'; } 
} )
Assertion failed: validValues and isValidValue are mutually exclusive
```

I was going to add the above to unit tests, but (a) wasn't confident that axon unit tests are using the correct pattern for failing cases, the `window.assert && throws` stuff looks odd to me; and (b)  didn't get a timely reply on Slack developer channel.

@samreid please review.

**Comment by pixelzoom** [comment]
Reviewed, change looks good.  It was also instructional for me to look at how unit tests were added.

**Comment by samreid** [comment]
Thanks, I should point out that axon is using a bit older version of qunit.  We opted for the new one in query-string-machine and the test apis are a bit different (newer one is preferable).

**Comment by pixelzoom** [comment]
Thanks - I think that's what concerned me when I started looking at axon unit tests.  I did add tests to query-string-machine, and axon didn't match what I was expecting.
