### ISSUE TITLE
"TODO: fix" in DerivedProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#160]
DerivedProperty:

```js
    and: function( properties, options ) {
      return new DerivedProperty( properties, _.reduce.bind( null, properties, conjunctionWithProperty, true ), options ); // TODO: fix
    },
```

This effectively makes `and` unusable - no idea what's broken or what needs to be fixed.  Looks like this was added by @jonathanolson and noted by @samreid in https://github.com/phetsims/axon/issues/88#issuecomment-176996165.

**Comment by jonathanolson** [comment]
I don't recall why this was there, and things seem fine. Any objections to removing the TODO?

**Comment by pixelzoom** [comment]
I revised the unit tests for DerivedProperty.and/or in https://github.com/phetsims/axon/commit/7fc7862cfda97eac7a7ac0ddbe264be912777a73, and I see no problems.  This was probably vestigial, so I've deleted the TODO.
