### ISSUE TITLE
problems with DerivedProperty 'and', 'or'

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#163]
Ran into this in equality-explorer. Static functions `and` and `or` have problems.

(1) They don't verify that their arguments are actually `{Array.<Property.<boolean>>}`. E.g. this succeeds without error:

```
phet.axon.DerivedProperty.and( [ new phet.axon.Property('foo') ] )
```

(2) If their arguments aren't `{Array.<Property.<boolean>>}`, they don't return `{boolean}`, they return truthy or falsy.  E.g.:

```
> var a = new phet.axon.Property( 0 )
> var b = new phet.axon.Property( 1 )
> var p = phet.axon.DerivedProperty.and([ a, b ] )
> p.value
0
> a.value = 1
> p.value
1
```

I'd be OK with updating the documentation to indicate that the inputs may be Properties of any type, and the returned value is truthy/falsy.

**Comment by pixelzoom** [comment]
Looks like these were added by @jonathanolson in https://github.com/phetsims/axon/issues/88.

**Comment by pixelzoom** [comment]
Revising what I said above...  I'd be OK with updating the documentation to indicate that the inputs may be Properties of any type.  But I'd like to make the return values `{boolean}` by putting a `!!` in front of the return values in private functions `andFunction` and `orFunction`.

**Comment by pixelzoom** [comment]
Also related to https://github.com/phetsims/axon/issues/160.  There's a TODO that indicates that `or` needs to be fixed, but no info about what's wrong.

**Comment by pixelzoom** [comment]
In Slack discussion, @jonathanolson suggested adding this assertion to `andFunction` and `orFunction`:

```js
    assert && assert( typeof property.value === 'boolean', 'boolean value required' );
```

... which I will do. 

This is likely to break something, but we'll deal with it when it pops up in automated testing. @phet-steele, heads up.

**Comment by jonathanolson** [comment]
I'm running aqua tests on my side to see if I can proactively fix anything.

**Comment by pixelzoom** [comment]
I revised the unit tests for DerivedProperty.and/or, all tests passing.

**Comment by pixelzoom** [comment]
@jonathanolson please review.  Unit tests have been updated.

**Comment by pixelzoom** [comment]
@jonathanolson please review. Unit tests have been updated. (Note that axon is using old-style unit testing. I've proposed updating in https://github.com/phetsims/tasks/issues/900.)

**Comment by jonathanolson** [comment]
Unit tests look great. Not sure if it's ready to close (but seems ready to me), assigning back.
