### ISSUE TITLE
Should we require tandems for all ObservableArrays?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#164]
ObservableArray:

```js
    // TODO: Should we require tandems for all ObservableArrays? 
```

All TODOs in common code should refer to associated GitHub issues.

**Comment by pixelzoom** [comment]
I see this in `options`:

```js
tandem: Tandem.tandemOptional(),
```

... and that's similar to what I see in Property, DerivedProperty, etc. So I'm wondering... Is this TODO vestigial?

**Comment by zepumph** [comment]
Marking for phet-io meeting.

**Comment by samreid** [comment]
Not all ObservableArrays should be instrumented.  We are moving toward a more sparse/stable instrumentation strategy.  They will remain optional to avoid leaking implementation details.

**Comment by samreid** [comment]
TODO removed, closing.
