### ISSUE TITLE
DerivedProperties must be disposed before their dependencies

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#167]
From https://github.com/phetsims/build-an-atom/issues/176#issuecomment-337687271 and https://github.com/phetsims/build-an-atom/issues/156 @zepumph and @jbphet and @samreid determined that DerivedProperties must be disposed before the dependencies.  Consider this example:

```js
var x = new Property();
var y = new DerivedProperty([x],function(){return x/2;});

x.dispose();
y.dispose();
```

This will throw an assertion error when `y` tries to remove its listener--it will not be able to remove the listener because it was previously removed in `x.dispose()`.  Hence it is a new constraint for our simulations (introduced in https://github.com/phetsims/axon/issues/129 ) that DerivedProperties must be disposed before their dependencies.

Scheduled for developer meeting to make sure everyone is aware of this new constraint.

**Comment by samreid** [comment]
Also I have some deja-vu about this, so please let me know if we already discussed it.

**Comment by pixelzoom** [comment]
I believe that we discussed this in 10/19/2017 developer meeting as a tangent to this agenda item:

> ✓JB, MK, and SR: In the process of instrumenting the game in Build an Atom for PhET-iO, we are needing to implement quite a few new dispose functions.  We’d like to discuss this with the group to see if anyone has any alternative ideas and to create awareness around this situation, since it will affect all common code and instrumented sims.

... and concluded that (a) adding dispose methods is an unavoidable cost of PhET-iO, and (b) this behavior in DerivedProperty is expected.

**Comment by samreid** [comment]
Sounds good, thanks @pixelzoom.  Closing.
