### ISSUE TITLE
NumberProperty has no default for options.units

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#169]
Noted while looking at https://github.com/phetsims/phet-io/issues/1292.

NumberProperty apparently takes `options.units`.  But there's no default (and hence no documentation) present in the constructor:

```js
    options = _.extend( {
      range: null, // {null|Range|{min:number, max:number}} range of the value
      valueType: 'FloatingPoint', // {string} see VALID_VALUE_TYPES
      phetioType: NumberPropertyIO
    }, options );
```

Need to add:

```js
    units: null, // {string|null} units for the number, see VALID_UNITS
```

**Comment by samreid** [comment]
Fixed as proposed, thanks for the fix, back to you for review.
