### ISSUE TITLE
DerivedProperty duplicates logic used to derive value

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#170]
Noted while working on https://github.com/phetsims/phet-io/issues/1292.

This logic is duplicated in DerivedProperty:

`derivation.apply( null, dependencies.map( function( property ) {return property.get();} ) )`

Since this is how the value is derived, it should definitely not be duplicated.

**Comment by samreid** [comment]
Proposed fix has been pushed, @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
Looks good to me, I don't see any problems. Closing.
