### ISSUE TITLE
DerivedProperty override of 'get value' should be removed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#171]
Noted while working on phetsims/phet-io#1292.

This function override in DerivedProperty:

```js
    /**
     * Override get value as well to satisfy the linter which wants get/set pairs (even though it just uses the same code as the superclass).
     * @returns {*}
     * @override
     * @public
     */
    get value() {return Property.prototype.get.call( this );},
```

... is confusing and unnecessary.  If I remove it, there is no complaint from the linter.

**Comment by samreid** [comment]
Removed, ready for review.

**Comment by samreid** [comment]
I've noticed that with the `DerivedProperty.get` removed, the sims are crashing with this error:

> Assertion failed: Invalid fill type

I'm not sure what this has to do with `get` being overriden in DerivedProperty though.  I'll revert for now and we can investigate.

**Comment by samreid** [comment]
Without the override, DerivedProperty.value is coming up as undefined.  Perhaps ES5 get/set don't attach to the prototype in the same way ordinary methods do?

**Comment by samreid** [comment]
@jonathanolson can you look into this?  You can replicate the problem by commenting out DerivedProperty.get (which is a trivial override that just calls Property.get) and running any sim.

**Comment by jonathanolson** [comment]
This looks like an issue with how inherit/extend works with ES5 getters/setters. Basically the get/set pair (or just a single get or set) defines a property, and the properties get overridden as a whole unit.

So if a complete pair (get/set) gets overridden by just a setter (with no getter), it "removes" the getter (the setter+nothing is put in its place).

It seems like they behavior I'd want is for inheritance/extension to be smart enough to mix/match the getters/setters, so that a subtype "setter with no getter" will only override the setter, like would be expected in this case.

Tagging for developer meeting to see if there are objections to this proposed change of behavior. (I haven't run into it, as I typically have `get something() { return this.getSomething(); }` and I'd just override `getSomething()`, or equivalently for a setter.

**Comment by jonathanolson** [comment]
> Agreed, but if the implementation is nontrivial it may be better to live with the existing workaround in DerivedProperty and other potential cases.

Implementation should be fine.

The larger question should be what happens here:
```js
var parent = { value: 5 };
var child = { get value() { return 6; } };
var combined = extend( {}, parent, child );
combined.value; // presumably should be 6
combined.value = 4; // this... currently does nothing because there is no setter
combined.value; // ... currently 6
```
Additionally, similar things happen if you override a normal value with a setter (with no getter).

**Comment by jonathanolson** [comment]
For reference (I'll be afk for a bit), the implementation fix would presumably to check the result of `Object.getOwnPropertyDescriptor( source, prop )` (in extend.js), see if it is a getter/setter with one or the other undefined. If so, it will try to fill it in with the corresponding function in `Object.getOwnPropertyDescriptor( obj, prop )` if available.

**Comment by pixelzoom** [comment]
@samreid @jonathanolson and I discussed this issue briefly after 1/18/18 dev meeting.  I think the consensus was that we should restore the override of `get value()` in DerivedProperty, but change the documentation to indicate the reason why it's necessary.  That is, not related to linting, but that `set value` and `get value` must be overridden in pairs.

**Comment by jonathanolson** [comment]
Looked into patching so this would be possible. With inheritance, it actually gets really complicated finding the correct property descriptor of what is being changed (since it is on the prototype).

Recommend deferring or closing, and leaving in the "do-nothing" getter.

**Comment by pixelzoom** [comment]
I'm fine with closing as "do nothing".  But this documentation should be changed, since it's what started this issue:

```js
    /**
     * Override get value as well to satisfy the linter which wants get/set pairs (even though it just uses the same code as the superclass).
     * @returns {*}
     * @override
     * @public
     */
    get value() {return Property.prototype.get.call( this );}
```

What's a more accurate description of why this override is needed?

**Comment by samreid** [comment]
Unassigning myself; @jonathanolson is best equipped to answer this question.

**Comment by jonathanolson** [comment]
Updated documentation to:

```
     * Override the getter for value as well, since we need the getter/setter pair to override the getter/setter pair in Property
     * (instead of a setter with no getter overriding). See https://github.com/phetsims/axon/issues/171 for more details
```

Is that sufficient? If so, let's close the issue.
