### ISSUE TITLE
NumberProperty: rename options.valueType to numberType

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#173]
While adding `valueType` option to `Property` (see https://github.com/phetsims/axon/issues/172), I discovered that `NumberProperty` already has a `valueType` option, which is propagated to (by not used by) Property.

In `NumberProperty`:

```js
67 // valid values for options.valueType
68 var VALID_VALUE_TYPES = [ 'FloatingPoint', 'Integer' ];
...
79 valueType: 'FloatingPoint', // {string} see VALID_VALUE_TYPES
```

After Slack discussion, we decided that it would be more appropriate to name this `numberType`.  There are many (75?) client usages, instance-proxies, PhET-iO doc,...   @samreid volunteered to rename.

**Comment by pixelzoom** [comment]
Also consider renaming the valid values.  Skype discussion:

Chris Malley [5:31 PM]
While you’re at it… Consider `[ 'float', 'integer' ]` as the values. `[ 'FloatingPoint', 'Integer' ]` look like type names to me, and just kinda weird.

Sam Reid [5:32 PM]
Sounds good, thanks!

Jonathan Olson [5:32 PM]
wouldn't 'float' usually indicate 32bit, while JS uses "double" (64bit) floating point numbers?

Chris Malley [5:33 PM]
They are currently `[ 'FloatingPoint', 'Integer' ]`, so either way the name may be incorrect.
Would `[ 'double', 'integer' ]` be more accurate?

Jonathan Olson [5:34 PM]
I don't see a problem with `'floatingPoint`, if we're lower-casing things

Chris Malley [5:34 PM]
Or are you saying that we don’t know whether it’s double or float?
If JS uses 64-bit on all platforms, then I’d vote for `[ 'double', 'integer' ]`

Sam Reid [5:36 PM]
It’s more that we want to convey whether it is countinuous or discrete with step size 1.
Not exactly how many bits.

Chris Malley [5:36 PM]
`[ 'decimal', 'integer' ]`
just brainstorming there…
floating point is a decimal number where the decimal point floats.
I’m also fine with `[ 'floatingPoint', 'integer' ]`.

**Comment by samreid** [comment]
I renamed valueType=>numberType and aqua is coming up green for PhET brand.

**Comment by samreid** [comment]
PhET-iO aqua came up green too.

**Comment by samreid** [comment]
I tested BAA instance proxies and saw several `numberType: 'Integer'` and it seemed OK.  I'll move the renaming of floating point/integer to a new issue and reassign this one to @pixelzoom to review as it pertains to https://github.com/phetsims/axon/issues/172

**Comment by pixelzoom** [comment]
@samreid FYI this commit looks unrelated: https://github.com/phetsims/phet-io-wrapper-visualizing-engagement/commit/ebf46abe7b9ef322accc614d8c829644d23402f9.

**Comment by samreid** [comment]
Sorry, wrong issue reference.  All else seems ok, closing.
