### ISSUE TITLE
issues with valueType and phetioType options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#175]
PhetioObject has `phetioType` option for specifying the IO type.  We recently added a `valueType` option to Property (a subtype of PhetioObject), to support type validation for Properties with homogeneous value.

--- 
In 2/20/18 2:30 PM Slack developer channel, I said (edited):

Specifying both `valueType` and `phetioType` also has a bit of a smell. E.g. in the example below, `Vector2` and `Vector2IO` are tied together, but we have to specify both. 

```js
var locationProperty = new Property( initialLocation, {
 valueType: Vector2,
 phetioType: Vector2IO,
 isValidValue: function( value ) { return value.x > 0; } 
} );
```

---
In https://github.com/phetsims/axon/issues/172#issuecomment-367517012, @samreid said:

Also did you want to discuss the code smell associated with specifying the phetioType and the valueType like this example:

```js
new Property(value,{
  valueType: Vector2
  phetioType: Vector2IO
});
```

I agree it has code smell but not sure what to do about it, if anything.

**Comment by pixelzoom** [comment]
I have no suggestions for how (or whether) to address this.  Labeling for developer meeting.

**Comment by zepumph** [comment]
Wouldn't the usage of `Property`'s  `phetioType` be more like:


```js
var locationProperty = new Property( initialLocation, {
 valueType: Vector2,
 phetioType: PropertyIO( Vector2IO),
 isValidValue: function( value ) { return value.x > 0; } 
} );
```

In which case, it may be harder to combine those two lines.

**Comment by jonathanolson** [comment]
If every type had its associated phet-io type tagged (e.g. `Vector2.phetioType` was `Vector2IO`), then we could get the `phetioType` from the `valueType` for most cases, correct? Is that something we'd want to do?

**Comment by zepumph** [comment]
It may be a bit more complicated because there isn't always a 1 to 1 correspondence. `RichText`, `Text`, `MultilineText` and others all use `TextIO`. Would that be a hindrance?

**Comment by jonathanolson** [comment]
> It may be a bit more complicated because there isn't always a 1 to 1 correspondence. RichText, Text, MultilineText and others all use TextIO. Would that be a hindrance?

That case may work, since they could all use `TextIO`. Is there ever a case where one type (not including subtypes) can have multiple acceptable IO types? (e.g. if RichText used like `TextIO` or `SomethingElseIO` based on how it was used in a sim).

**Comment by samreid** [comment]
Yes, you are correct @zepumph about it being `Property(Vector2IO)`

**Comment by samreid** [comment]
I'm inclined to advocate the strategy in https://github.com/phetsims/axon/issues/175#issuecomment-367752500 because it will be most consistent with usage of `phetioType` elsewhere, and most flexible (even though a bit redundant).

**Comment by pixelzoom** [comment]
2/22/18 dev meeting: Consensus is that it's OK to have to specify both `valueType` and `phetioType`. @zepumph pointed out that we could attempt to do something clever to get (e.g.) Vector2 from Vector2IO, but that would likely get us into trouble.
