### ISSUE TITLE
incorrect/confusing phetioType in Property subtypes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#176]
```js
phetioType: NumberPropertyIO // NumberProperty.js
phetioType: StringIO // StringProperty.js
phetioType: PropertyIO( BooleanIO ) // BooleanProperty.js
```

Why are there 3 variations here? Is StringProperty buggy?

**Comment by pixelzoom** [comment]
Sam Reid [11:41 AM]
StringProperty should have `phetioType: PropertyIO( StringIO )`

Chris Malley [11:41 AM]
Why not StringPropertyIO and BooleanPropertyIO ?

**Comment by samreid** [comment]
`StringPropertyIO` and `BooleanPropertyIO` would not add any methods or attributes, so do not need to be created.

**Comment by pixelzoom** [comment]
I fixed phetioType in StringProperty.  It's been broken since 11/15/18, probably wasn't noticed sooner since devs don't appear to be using StringProperty (only 6 usages, which is a different problem).  No idea how to verify this, so assigning to @samreid to follow up.

**Comment by samreid** [comment]
I tested by adding this code to faradays-law-main.js

```js
  var p = new StringProperty( 'hello', { tandem: Tandem.rootTandem.createTandem( 'helloStringProperty' ) } );
  console.log( p );
```

With the old code this crashes, with the new code it runs nicely.  Closing.
