### ISSUE TITLE
Property.valueType should work for Enums

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#177]
I tried our enum pattern with Property.valueType and was met with:

```
Assertion failed: valueType must be {function|string|null}, valueType=[object Object]
```

@ariel-phet do you want @pixelzoom to take a look at that?  Ideally it would just be a few minutes to find out if valueType should support that or not, and how to implement it.  I can implement it after getting @pixelzoom input (if he has time).

**Comment by pixelzoom** [comment]
Example?

**Comment by samreid** [comment]
I pushed a failing test in the preceding commit.

**Comment by pixelzoom** [comment]
Step 1: Decide what PhET enum pattern will use.  The example in the failing test is not an idiomatic enum.   Typical JS enum pattern is to assign integer values to each enum value, example below. I've used strings in the past because they're more useful in debugging.

```js
var ViewTypeEnum = {
 TOP: 0
 SIDE: 1
};
```

Step 2: Determine how to identify an enum, which is essentially a singleton.

Step 3: Decide how to verify that a value is a field in the enum singleton.  You can't use `hasOwnProperty` and you can't compare the value of the property.

**Comment by pixelzoom** [comment]
We should also discuss the value of enum vs {string[]}.  Is enum pattern widespread in PhET code? Is using string literals more idiomatic?  Is it worth adding support for enum to Property `valueType`?

**Comment by samreid** [comment]
Maybe enums should use `validValues` instead of `valueType` for now?

**Comment by pixelzoom** [comment]
For PhET-iO, do enums vs string literals have any advantages?  If a Property takes an enum value, how do support value selection in instance-proxies?

**Comment by samreid** [comment]
True enum types (like in Java) would need IO types to serialize/deserialize.  String literals are extremely easy for PhET-iO.  Enum types that use descriptive `string` values are also easy for PhET-iO (no need for IO type adapter).

**Comment by pixelzoom** [comment]
How do you use `validValues` to valid an enum?   The first 2 assignments below should fail, but they succeed because where's not comparing references, we're comparing values.

```js
> var MyEnum = { TOP: 0, BOTTOM: 1 }
> var myProperty = new phet.axon.Property( MyEnum.TOP, { validValues: [ MyEnum.TOP, MyEnum.BOTTOM ] } );
> myProperty.value = 0
0
> myProperty.value = 1
1
> myProperty.value = 2
Assertion failed: value is not a member of validValues: 2
```

**Comment by pixelzoom** [comment]
Agreed. It's a major flaw in the JS enum pattern, hazard of not having proper language support.

**Comment by samreid** [comment]
This pattern would give us enum type correctness and permit Property.valueType at the expense of not having good debugging info and requiring PhET-iO adapters:

```js
  function ViewTypeEnum() {}

  ViewTypeEnum.TOP = new ViewTypeEnum();
  ViewTypeEnum.SIDE = new ViewTypeEnum();
```

**Comment by ariel-phet** [comment]
@samreid - apparently @pixelzoom already took some time....we would prefer right now to only ping him for essential work/questions as he attempts to clear out time to focus on EqEx

**Comment by samreid** [comment]
@jonathanolson @jbphet @jessegreenberg any interest in pursuing an enum pattern like the one described in https://github.com/phetsims/axon/issues/177#issuecomment-369811381 ?

**Comment by jonathanolson** [comment]
> @jonathanolson @jbphet @jessegreenberg any interest in pursuing an enum pattern like the one described in #177 (comment) ?

So I've used that for when I need "richer" enumerations (that have methods/etc.), and it works. The "downside" is that you'd need a toString() to convert them nicely to a string. The upside is that it could possibly be higher-performance than using string literals (in addition to better type checking).

Orientation.js is an example of a "richer" enumeration that follows this pattern.

**Comment by jessegreenberg** [comment]
Proposal is we can use any type. It is not worthwhile for us to create a strict enum type. @jonathanolson or @pixelzoom can you please update this comment with additional consensus notes?

**Comment by pixelzoom** [comment]
If you have an enum like area-model-common's `Orientation`, where the enum has a constructor and each enum value is an object instance, use this pattern:

```js
var orientationProperty = new Property( { 
  valueType: Orientation 
} );
```

If you have an enum where the values are strings (e.g. acid-base-solutions `SolutionType`) or numbers (the more idiomatic JS approach), use this pattern:

```js
var solutionTypeProperty = new Property( {
  validValues: _.map( SolutionType )
} );

**Comment by pixelzoom** [comment]
If you have an enum like area-model-common's `Orientation`, where the enum has a constructor and each enum value is an object instance, use this pattern:

```js
var orientationProperty = new Property( { 
  valueType: Orientation 
} );
```

If you have an enum where the values are strings (e.g. acid-base-solutions `SolutionType`) or numbers (the more idiomatic JS approach), use this pattern:

```js
var solutionTypeProperty = new Property( {
  validValues: _.map( SolutionType )
} );
```

... and beware that in this pattern, `solutionTypeProperty.value = SolutionType.WATER` and `solutionTypeProperty.value = 'water'` will both succeed, because we're using value comparison, not reference comparison.

**Comment by jbphet** [comment]
It looks like this was assigned to me to comment on https://github.com/phetsims/axon/issues/177#issuecomment-370182382, but @pixelzoom (later) said:

> We will not implement specific support for enums in Property value validation.

So, it sounds like a decision was made, and I'm okay with it.  Back to @samreid to see if anything else needs to be done.

**Comment by samreid** [comment]
Sounds good to me, closing.
