### ISSUE TITLE
Should each Emitter instance be allowed to emit with any number of args?

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#182]
Right now there is complete flexibility on how many arguments you emit with for an emitter instance. So far there haven't seen to be any complaints about this loose system, but @samreid, @chrisklus, and @zepumph ran into difficulties with this for PhET-iO today. 

Would this be safer and more maintainable if an Emitter instance was defined with a set number of args that it expected to emit with? Perhaps this would be too rigid of a system? Are there many places where a single emitter will use more than one emitting function in different use cases?

For example, here is something you can currently do with Emitter:

```js

var e = new Emitter();

e.emit();

e.emit1( new Property());

e.emit3( 'hi', 'you', 'rock')

e.emit1( new Vector2( 3, 4) );
```

For obvious reasons, this seems brittle and difficult when it comes to adding listeners to this `Emitter`.

The reason this came up, was because we were trying to decide how `EmitterIO` should properly serialize Emitter's arg types. For example we have an `EmitterIO.<BooleanIO>` that is still technically allowed to `emit3()`, although that breaks across the phet-io api. 

A "strong typing" solution (that we aren't necessarily pushing for) would be to have a different type for each number of args you plan to emit for, like `Emitter extends BaseEmitter`, `Emitter1 extends BaseEmitter`, `Emitter2 extends BaseEmitter`. Each type would only have the emitting method that corresponds to the number of args it is made for.

**Comment by zepumph** [comment]
Adding to developer meeting, although likely it would be nice to have a week of async discussion and thought gathering before bringing this to the team.

**Comment by samreid** [comment]
I appreciate the simplicity of a single `Emitter` type and I'm not aware of any misusages of it so far.  Another option alluded to in https://github.com/phetsims/axon/issues/182#issue-357394462 would be to pass an option to Emitter indicating the number and/or type of emit arguments.  We kind of have something like that for PhET-iO in `Emitter.options.phetioType`.

**Comment by samreid** [comment]
Another possibility would be to convert everything to be `emit1` and named as `emit`.  When called with no arguments, then the argument is undefined.  When called with 1 argument, it works as expected. To call with 2+ arguments, you would need to use an array or object.

**Comment by zepumph** [comment]
>Another possibility would be to convert everything to be emit1 and named as emit. When called with no arguments, then the argument is undefined. When called with 1 argument, it works as expected. To call with 2+ arguments, you would need to use an array or object.

For PhET-iO would we then need a `Nullable( phetioArgumentType || ArrayIO( phetioArgumentTypes ) )` typeIO to handle this flexibility across the frame?

**Comment by zepumph** [comment]
Also note that there are only 35 or so usages of `emit2` and `emit3`. Much less than I would have thought.

**Comment by samreid** [comment]
> For PhET-iO would we then need a `Nullable( phetioArgumentType || ArrayIO( phetioArgumentTypes ) )` typeIO to handle this flexibility across the frame?

Well, each EmitterIO would be created with the appropriate type on a case-by-case basis (instead of thinking of one type that works for everything).  For instance:

```js
new Emitter({phetioType: EmitterIO(StringIO)});
new Emitter({phetioType: EmitterIO(VoidIO)}); // for no-args?
new Emitter({phetioType: EmitterIO(ArrayIO(Vector2IO))});
```

**Comment by pixelzoom** [comment]
Do Emitter instances typically use one of the `emit*` methods, or are there some case where more than one is used?

**Comment by zepumph** [comment]
>Do Emitter instances typically use one of the emit* methods, or are there some cases where more than one is used?

Seems like a hard question to answer definitively. I can say with relatively strong confidence that I have not emitted using multiple methods for the same emitter instance.

**Comment by pixelzoom** [comment]
Since all listeners are called when any emit method is called, I don't see how using more than 1 of the emit methods would not be buggy.  And if it did work, it seems like a bad practice to use an emitter for more than one purpose.

**Comment by zepumph** [comment]
Springboarding from that, perhaps the easiest solution to validate is to have an option of type `{number}` called something like `numberOfArgs`. Them `emit3` can assert that `numberOfArgs === 3`.

**Comment by pixelzoom** [comment]
I'm now recalling the 2 things that I don't like about the current Emitter implementation. 
(1) If you need to call a listener with N args, and emitN doesn't exist, you have to add it to Emitter. 
(2) Nothing prevents you from using more than one of the emit methods.

What @zepumph proposed in https://github.com/phetsims/axon/issues/182#issuecomment-418930001 sounds like a reasonable way to prevent you from using more than one emit method.

**Comment by jonathanolson** [comment]
If the concern is serialization, couldn't emitters be given an array of phet-io types for the arguments?

**Comment by jbphet** [comment]
For the record, I've never had a case where I used different numbers of params from the same emitter.

**Comment by zepumph** [comment]
Decided in the developer meeting, we will update `Emitter` to only have one method, `emit`. When instantiating this Emitter, we will pass in a `valueTypes` array that holds the types expected in the emit call.

Then in the `emit` method we will assert that all arguments are of the correct length and types. This is hidden behind assert, so performance isn't a concern. 

This code will  mimic that of `Property.js` and the way it asserts the correct `valueType`. 

For PhET-iO we will have a parallel array option `phetioValueTypes` that already exists. 


I'll give this one a go.

**Comment by zepumph** [comment]
(phet-io thanks you)

**Comment by zepumph** [comment]
I think this is safest to try to accomplish in steps, rather than just one super commit. I think I will do the following steps:

1. update the Emitter constructor to support the way of the future, but don't assert out if it isn't doing it (to support backwards compatability).
2. update the emit() function to support emit1, and transfer emit1 usages.
3. Do the same for emit2
4. Do the same for emit3.
5. Update Emitter so that it fails if you don't specify the appropriate valueTypes

**Comment by zepumph** [comment]
* I'm unsure about how to set the `validValues` for Property's `changedEmitter`.

**Comment by samreid** [comment]
Can they come from the Property's validValues?  Or maybe we don't need to supply them because the Property.changeEmitter is not instrumented?

**Comment by zepumph** [comment]
I think I would like a mid-point review before proceeding, so far I have:

* added validValues
* converted `emit()` so support any number (up to 3) arguments for phet and phet-io brands
* Converted one usage in Arithmetic, and one in Build A Molecule from emit1 to emit.

Before continuing through usages, it would be nice to know how "on track" these changes are. @samreid do any of you have time for a quick in-progress review?

**Comment by zepumph** [comment]
As a note, I just found https://stackoverflow.com/questions/203739/why-does-instanceof-return-false-for-some-literals while working on https://github.com/phetsims/friction/issues/116 which points to a more verbose type check for literals than just `typeof`:


>I use:
```
function isString(s) {
    return typeof(s) === 'string' || s instanceof String;
}
```
>Because in JavaScript strings can be literals or objects.

Just a thought

**Comment by samreid** [comment]
I don't know much about wrapper types, but it seems unlikely that we would use them interchangeably in our simulations.

![image](https://user-images.githubusercontent.com/679486/46566704-25ab9a00-c8e1-11e8-9bce-6421e4da5dc2.png)

**Comment by zepumph** [comment]
@samreid found an article about optimizing with arguments, https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments, and it makes me feel good about using `arguments.length` in the `emit` function. I'm going to try it out and see how it goes.

**Comment by samreid** [comment]
I'm also noticing Emitter.emit is allocating array each time--this should be avoided by passing arguments using apply, see https://stackoverflow.com/questions/3914557/passing-arguments-forward-to-another-javascript-function

@zepumph can you look into that part?

**Comment by samreid** [comment]
> added support for optional arguments with optionsal.areTypesOptions. I'm not stoked on this, but I couldn't think of how else to handle this, see PressListener's emitters for more context.

Property.js solves this by providing a function `isValidValue` that checks the value.  Would this be a good move for Emitter? Providing either `valueTypes` or `valuePredicates` but not both?

**Comment by zepumph** [comment]
>That sounds reasonable, having the IO type be able to check for compatible instances seems ok, even if we have to revisit our decision about allowing the types to diverge.

I experemented with this in #190, and gave up because the ifphetio! plugin makes this hard.

I removed areTypesOptional array and simplified the emitter logic. I think we are ready to begin to convert usages.

**Comment by samreid** [comment]
Please note a fix @chrisklus and I committed for the unit tests.

**Comment by chrisklus** [comment]
@zepumph made progress on this in https://github.com/phetsims/axon/issues/190, @zepumph is this current issue still block-publication?

**Comment by zepumph** [comment]
Yes I think so. There are many usages of emit1,2, and 3 that need to be moved over. Because it is in the half finished state that it is right now, I want to keep that label on.

**Comment by zepumph** [comment]
Removing block-publication because CL is in rc with these changes, and bayes doesn't seem to mind the intermediate state we are in.

I will read it if master becomes unstable while continuing work on this issue.

**Comment by zepumph** [comment]
In https://github.com/phetsims/axon/issues/189 we have come up with a nice strategy for Property, and now need to apply this to Emitter. Afterwards we will will add phetioType to Validator.js in https://github.com/phetsims/axon/issues/194.

Marking off hold to try to convert usages currently using `TypeDef` and `Emitter.argumentTypes` over to use `Validator`.

**Comment by zepumph** [comment]
Thoughts while working on this:

* Should we rename "argumentTypes" to something like "listOfValidatorOptionsForArguments"
* Emitter didn't seem to have a need for `pickOptions`, but I'm wondering if Validator.validateOptions should error out if there are other, unexpected keys in the object passed in. To me that feel very strict, and we may run into problems with it, but it also could be a nice way to assert that things are happening as we expect. As discussed in last dev meeting, it is less idiomatic to pick options out of an object, and more appropriate to pass the whole thing to a parent and have the parent only use the options it is expecting, and to ignore the rest. The Property/Validator relationship is a bit different than the parent/child type one though.



Summary of work:
In the above commits I updated Emitter to use Validator. This involved
* removing any `argumentTypes` validation from `EmitterIO`
* Changing code in Emitter.js from TypeDef to `Validator`
* Deleting TypeDef
* Converting the 41 usages of emitters calling `emit` with an arg from depending on EmitterIO, to instead using `argumentTypes` with Validator-like options.

Overall I'm happy about this change, and I think, after a review, phet brand should be cleared to use this approach for creating emitters. 

The main drag about the above commit is that it doesn't yet support phetioType as part of argumentTypes, which I think is the way to go so we don't have to support parallel arrays. But since we don't support that yet, for phet-io instrumented Emitters we have an array for `argumentTypes`, and one passed into the EmitterIO for the `phetioType`. Each of these has the same todo on it:
`      // TODO: use of both of these is redundant, and should get fixed with https://github.com/phetsims/axon/issues/194`

I pointed to that issue instead of this one because that is above consolidating phetioType and the traditional "valueType" into a single place.


@samreid and I still need to support moving EmitterIO types into argumentTypes for Emitter specifically. I'll make a new issue for that.

**Comment by zepumph** [comment]
@samreid please review this, and note https://github.com/phetsims/axon/issues/204 as further work in combining phetioType into `argumentTypes`.

**Comment by zepumph** [comment]
I don't want un-reviewed code in master for too long. marking blocks publication.

**Comment by samreid** [comment]
Review is complete, this is working nicely and follow-up work is lower priority and noted in other issues.
