### ISSUE TITLE
Problems related to Property value type specification

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#185]
For https://github.com/phetsims/phet-io/issues/1359

@pixelzoom said:
> There are 3 problems related to Property type specification:  (1) current lack of support for heterogenous Properties, (2) the need to add redundant type specification when instrumenting, and (3) maintenance problems required to keep redundant type specification in sync.

From slack conversation, it is clear that we want to support heterogeneous Properties for simulation implementation.

Will instrumented Property instances be homogeneous or heterogeneous?  If heterogeneous, how do we make that work for PhET-iO?  In either case, how can we align the core and phet-io parts so they aren't duplicated?

**Comment by zepumph** [comment]
Number (2) may be solved with https://github.com/phetsims/phet-io/issues/1373.

**Comment by zepumph** [comment]
Discussed in phet-io team meeting today,

> current lack of support for heterogenous Properties,

Heterogenous Properties aren't used often. Most often it is a code smell that should be refactored (as was the case while instrumenting the gameStateProperty in BAA). If it is needed, then PhET-iO Does support it, via creation of an IOType like `StringOrNumberIO`. Though this isn't ideal, we have yet to run into this in 3 years, and can talk about it more in the future if it becomes more of a problem.


> the need to add redundant type specification when instrumenting

I am working this, as part of https://github.com/phetsims/axon/issues/189 and phetsims/phet-io#1373. Hopefully type and typeIO validation can be streamlined

>maintenance problems required to keep redundant type specification in sync.

There will always be a maintenance overhead when there is a TypeIO in addition to the Type. Hopefully by addressing the first two concerns well, we can limit this.

@pixelzoom how does this sound. Is there anything else to discuss for this issue?

**Comment by pixelzoom** [comment]
@zepumph said:
> ... Heterogenous Properties aren't used often ...

Two common examples of heterogenous Properties:

`{Property.<SomeType|null>}`
`{Property.<Color|string>}`

So while I agree that some uses of homogenous Properties have a code smell, there are appropriate uses, and we shouldn't do anything to prevent it. 

That said, I'm OK closing this issue, since the points raised are being addressed in other issues.
