### ISSUE TITLE
Emitter should accept an option that adds a listener

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#186]
Many types such as FireListener and PushButtonModel support adding a listener during construction, which is very convenient.  New usage of Emitter such as https://github.com/phetsims/scenery/issues/861 and https://github.com/phetsims/sun/issues/396 would benefit from a listener arg in Emitter as well.

**Comment by samreid** [comment]
@jonathanolson does this seem OK to you?  I added Emitter.listener and a sample usage.

**Comment by jonathanolson** [comment]
Sounds good to me, was useful.

**Comment by samreid** [comment]
Thanks @jonathanolson, closing.
