### ISSUE TITLE
Identifying the Property from a change callback

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/axon#187]
There's a case in Scenery where I currently need to identify the Property that changed from a callback. Basically the currently-existing (buggy) code looks like:
```js
this.someListener = this.someMethod.bind( this );
// ... and something that can be done for multiple properties:
property.lazyLink( this.someListener );
// ...
property.unlink( this.someListener );
```
but when `someMethod` is called, it doesn't know which Property changed (only the values). Instead I want to have the callback essentially be `someMethod( newValue, oldValue, property )` (or technically in this case, some way I can look up some information about the Property in a map).

To do this the standard way is not only pretty ugly, but also bad for memory (creating lots of closures and objects):
```js
this.listenerReferences = [];
// ...
const listener = ( newValue, oldValue ) => this.someMethod( newValue, oldValue, property );
property.lazyLink( listener );
this.listenerReferences.push( {
  listener,
  property
} );
// ... would need to add in error checks also
for ( let i = 0; i < this.listenerReferences.length; i++ ) {
  const reference = this.listenerReferences[ i ];
  if ( reference.property === property ) {
    property.unlink( reference.listener );
    break;
  }
}
```

but there are two potential ways around this:

1. Pass the Property itself (to value change events) as the 3rd parameter.
2. Put unique identifiers on Property.

For option 1, it would look exactly like the current (short) code, but since it would be `someMethod( newValue, oldValue, property )` it just works.

For option 2, a map lookup could be used, e.g.:
```js
this.someListener = this.someMethod.bind( this );
this.propertyMap = {};
// ...
property.lazyLink( this.someListener );
this.propertyMap[ property.id ] = property;
// ...
property.unlink( this.someListener );
delete this.propertyMap[ property.id ];
```

My exact use-case here needs to do a map anyways (like option 2), so I'm not sure what's best. Potentially both changes might be nice, and there is precedent for both in other types.

Thoughts? Are there complications for phet-io if we change the emitter? (It currently does emit1 AND emit2 on the changeEmitter, which adds some minor trickyness).

**Comment by pixelzoom** [comment]
Is there potentially a similar need with `MultiLink` and `DerivedProperty`, where there are multiple `Property` dependencies?

**Comment by samreid** [comment]
> Are there complications for phet-io if we change the emitter? (It currently does emit1 AND emit2 on the changeEmitter, which adds some minor trickyness).

Property.emitter is not phet-io instrumented, so this would not be a problem.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/axon/issues/187#issuecomment-429083341

@jonathanolson said that for things that may extend Property, we will need to check for collisions with the id.

**Comment by jessegreenberg** [comment]
Developer meeting: No objections, @jonathanolson is free to proceed with this.

**Comment by jonathanolson** [comment]
This is completed. In a quick review of my previous commit, I did fix a bug (so it's probably worth it to get a quick code review). @ariel-phet thoughts?

**Comment by samreid** [comment]
The change sets look good.  I also added `this` to the initial `link` callback.  I would also recommend adding at least one unit test that exercises this new functionality.

**Comment by pixelzoom** [comment]
Should `this.id` be added to Property `toString`?

**Comment by jonathanolson** [comment]
I'm fine with adding the id to toString. Ok with e.g. `'Property#3{...value...}`?

**Comment by jonathanolson** [comment]
Added unit tests and the toString(). Closing.
