### ISSUE TITLE
How to hide Emitter args from phet-io data stream

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#188]
The issue is that we don't necessarily want to expose all emitter arguments for every instrumented emitter. Some are not helpful, like a `Trail` or `Node`. Right now we are using the `VoidIO` type to encode those args, but I would like to investigate other potential ideas, of which I currently don't have any. . .

Off the top of my head, could we provide an option the EmitterIO arg schema that says "public: false", or just pass in null there to symbolize that we don't want it to be public. Then in the EmitterIO constructor we could fill that in with something consistent that all Emitters can use, and it is factored out in a single place. That seems better to me than spreading `VoidIO` around the project because "it works"

What do you two think @samreid @chrisklus?

**Comment by zepumph** [comment]
This seems like a subset of https://github.com/phetsims/phet-io-wrappers/issues/179

**Comment by erikjreid** [comment]
Also related to https://github.com/phetsims/scenery/issues/875

**Comment by samreid** [comment]
Also related to https://github.com/phetsims/scenery/issues/875

**Comment by samreid** [comment]
My comments are here: https://github.com/phetsims/scenery/issues/875#issuecomment-444293973

**Comment by zepumph** [comment]
>VoidIO is an appropriate description of the IO Type for these parameters, because as far as PhET-iO is concerned, there is no value there.

If we feel that way, then I would recommend creating an IOType specifically to be used a this placeholder for a private arg. That way we aren't overloading VoidIO. @samreid what do you think about something like `PrivateIO` or `HiddenIO`?

**Comment by samreid** [comment]
Would `PrivateIO` end up in the API files?  Also, I'm having trouble identifying the pros and cons between:
(a) using `PrivateIO` vs
(b) using `VoidIO` with a comment that says /*actually an integer, but only used in the sim side*/
especially since it is possible to forget the comment or accidentally use `VoidIO` where `PrivateIO` should have been used.

**Comment by zepumph** [comment]
Without these usages, `VoidIO` is only used in IO types to specify public function metadata. Perhaps this increase in functionality is acceptable, but it still feels like it is vague and not clear what that `VoidIO` is doing there, both publicly (in studio) and to devs (me). 

If we had a specific item that meant "hide this from public consumption," it would be much easier to cut that out of the public side. I'm not sure exactly how that would look, but we could omit it from typeNames, and value checking potentially if desired.

**Comment by samreid** [comment]
In https://github.com/phetsims/axon/issues/257 @zepumph added `phetioPrivate: true` which looks much better to me than `VoidIO` or `PrivateIO`. Can we proceed with that?

**Comment by zepumph** [comment]
Yes that is very good. Sorry I totally forgot about that. Currently there are no usages of `VoidIO` as a way to hide args. `phetioPrivate` is documented in Action.js. Ready to close?
