### ISSUE TITLE
Add PropertySet.get or equivalent

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#19]
PropertySet has a set function to set multiple values at once, and it would be good to have a get function to get all state in a JS object (e.g., for serialization).

**Comment by samreid** [comment]
PropertySet.set currenty looks like so:

```js
    /**
     * Set all of the values specified in the object hash
     * Allows you to use this form:
     * puller.set( {x: knot.x, y: knot.y, knot: knot} );
     *
     * instead of this:
     * puller.x.value = knot.x;
     * puller.y.value = knot.y;
     * puller.knot.value = knot;
     *
     * Throws an error if you try to set a value for which there is no property.
     */
    set: function( values ) {
      var propertySet = this;
      Object.getOwnPropertyNames( values ).forEach( function( val ) {
        if ( typeof(propertySet[ val + 'Property' ] === 'Property') ) {
          propertySet[ val + 'Property' ].set( values[ val ] );
        }
        else {
          throw new Error( 'property not found: ' + val );
        }
      } );
    }
```

Can some combination of @jonathanolson @jbphet @pixelzoom chime in on whether this should be called `set` or `setState` or `setValues` or something else?  Same for `get'.

**Comment by pixelzoom** [comment]
Is there a use case that we think is valuable for PropertySet.set and get? I've haven't yet needed it. 

I'd be fine with set and get, or setValues and getValues.

**Comment by samreid** [comment]
I have used PropertySet.get and PropertySet.set to implement save/load as well as record/playback.  I guess at the moment I'm leaning toward setValues/getValues because get/set conflict somewhat (conceptually though not programatically) with ES5 `get` and `set` getter/setter declarations.

**Comment by samreid** [comment]
Renamed above.  Usages of .get() and .set( are very hard to find in the source code since there are many false positives.  The one case I was certain about was in Sim.js and has been fixed above.  Hopefully we can discover any others as we go and address them when discovered.  Closing.
