### ISSUE TITLE
Can phetioType cover options.valueTypes in Emitter?

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#190]
I investigated this briefly when working on #182, but ran into issues because we don't have access to all typeIOs in phet brand because of the ifphetio! plugin, so I gave up on this for now.  Here is a snippet in the constructor of EmitterIO that seemed promising:

```

      var valueTypes = [];
      var elementTypes = elements.map( function( element ) {

        // validate the look of the content
        assert && assert( typeof element === 'object' );
        var keys = Object.keys( element );
        for ( let i = 0; i < keys.length; i++ ) {
          const key = keys[ i ];
          assert && assert( ELEMENT_KEYS.indexOf( key ) >= 0, 'unrecognized element key: ' + key );
        }
        assert && assert( element.predicate || element.type.valueType, 'no valueType specified' );
        valueTypes.push( element.predicate || element.type.valueType );
        return element.type;

      } );
```

**Comment by samreid** [comment]
Can you please clarify why the typeIOs are needed?  Would it be OK to specify a `predicate` for each entry in the `EmitterIO` args?

**Comment by zepumph** [comment]
If we could access the typeIOs always, then we could save a lot of spots of needing the `predicate`. It's annoying to have the 'number' boilderplate for every single 'NumberIO'.

What if we could move the types out of phet-io?

**Comment by samreid** [comment]
> What if we could move the types out of phet-io?

That sounds promising, perhaps moving them to tandem (which is the repo for simulation-side phet-io things)?  Do we need to get @kathy-phet to sign off because it involves moving previously proprietary code out to public?  Any other part of this need discussion at phet-io dev meeting?

Also, how do we specify that something has to be a number greater than zero?  Do we specify `NumberIO` in addition to a predicate?

**Comment by kathy-phet** [comment]
I will need to discuss this for reason Sam says.

Kathy

Sent from my iPhone

On Oct 18, 2018, at 8:38 AM, Sam Reid <notifications@github.com<mailto:notifications@github.com>> wrote:


What if we could move the types out of phet-io?

That sounds promising, perhaps moving them to tandem (which is the repo for simulation-side phet-io things)? Do we need to get @kathy-phet<https://github.com/kathy-phet> to sign off because it involves moving previously proprietary code out to public? Any other part of this need discussion at phet-io dev meeting?

Also, how do we specify that something has to be a number greater than zero? Do we specify NumberIO in addition to a predicate?

**Comment by samreid** [comment]
The types that would move from phet-io/js/types would be:
ArrayIO
BooleanIO
FunctionIO
NullableIO
NumberIO
ObjectiO
StringIO
VoidIO

The type that would remain is:
PhetIO.js (soon to be renamed to something like PhetioEngineIO.js

phet-io/js currently has 2673 lines of code.  Removing the types identified above reduces this to 2172 lines of code (so about 20% of the js).  The expected benefit is this would simplify simulation development by allowing us to combine axon type validation with PhET-iO types.

I labeled this issue for discussion at an upcoming phet-io dev meeting.

**Comment by zepumph** [comment]
Decided today in the PhET-iO meeting. @kathy-phet and devs are alright with us moving these types to tandem. We will not move the PhETIO.js IOType.

**Comment by zepumph** [comment]
Now that #1396 has been handled. I am going to put the core phet type on the `coreType` key of the static properties in the IOTypes, and then use that in EmitterIO to formulate the EmitterIO's valueTypes. Then Emitter.js can either use the `valueTypes` provided with it's options, or from the EmitterIO type.

**Comment by zepumph** [comment]
I discussed this further with @samreid. We decided that instead of having a `coreType` key, it made more sense for a general `isInstance` function that can check if anything is of said IOType's core type.

This is working really well in phet-io, but not in phet brand. This is because we are relying on `phetioInherit` to assign the `isInstance` call to the subtype. As a result, I can't commit anything, as much as I may want to. Instead here is a working copy patch that I can hopefully work with @samreid on to get this to a commitable point.

<details>
Index: tandem/js/types/StringIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/types/StringIO.js	(revision 58c8e57648bb338a61644f0e13d6303122c6138b)
+++ tandem/js/types/StringIO.js	(date 1539914802984)
@@ -24,6 +24,14 @@
   phetioInherit( ObjectIO, 'StringIO', StringIO, {}, {
     documentation: 'Wrapper for the built-in JS string type',
 
+    /**
+     * @override
+     * @public
+     * @param {*} instance
+     * @returns {boolean}
+     */
+    isInstance: function( instance ) { return typeof instance === 'string'; },
+
     /**
      * Encodes a string to a state (which also happens to be a string).
      * @param {Object} value
Index: tandem/js/types/ObjectIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/types/ObjectIO.js	(revision 58c8e57648bb338a61644f0e13d6303122c6138b)
+++ tandem/js/types/ObjectIO.js	(date 1539914654465)
@@ -42,6 +42,14 @@
      */
     documentation: 'The root of the wrapper object hierarchy.',
 
+    /**
+     * A predicate function that will return whether the argument is an instance of this IOType's coreType
+     * @public
+     * @param {*} instance
+     * @returns {boolean} - whether or not the passed in arg is of type Object
+     */
+    isInstance: function( instance ) { return instance instanceof Object;},
+
     /**
      * Return the json that ObjectIO is wrapping.  This can be overridden by subclasses, or types can use ObjectIO type
      * directly to use this implementation.
Index: tandem/js/types/NumberIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/types/NumberIO.js	(revision 58c8e57648bb338a61644f0e13d6303122c6138b)
+++ tandem/js/types/NumberIO.js	(date 1539914802988)
@@ -26,6 +26,14 @@
   return phetioInherit( ObjectIO, 'NumberIO', NumberIO, {}, {
     documentation: 'Wrapper for the built-in JS number type (floating point, but also represents integers)',
 
+    /**
+     * @override
+     * @public
+     * @param {*} instance
+     * @returns {boolean}
+     */
+    isInstance: function( instance ) { return typeof instance === 'number'; },
+
     /**
      * Encodes a number to a state (which also happens to be a number).
      * @param {Object} value
Index: tandem/js/types/NullableIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/types/NullableIO.js	(revision 58c8e57648bb338a61644f0e13d6303122c6138b)
+++ tandem/js/types/NullableIO.js	(date 1539914654454)
@@ -44,6 +44,14 @@
       // Signify documentation, used in documentation wrappers like PhET-iO Studio.
       documentation: 'A wrapper to wrap another IOType, adding support for null.',
 
+      /**
+       * @override
+       * @public
+       * @param {*} instance
+       * @returns {boolean}
+       */
+      isInstance: function( instance ) { return instance === null || ioType.isInstance( instance ); },
+
       /**
        * If the argument is null, returns null.
        * Otherwise converts the instance to a state object for serialization.
Index: tandem/js/types/FunctionIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/types/FunctionIO.js	(revision 58c8e57648bb338a61644f0e13d6303122c6138b)
+++ tandem/js/types/FunctionIO.js	(date 1539914654471)
@@ -48,6 +48,16 @@
       documentation: 'Wrapper for the built-in JS function type.<br>' +
                      '<strong>Arguments:</strong> ' + argsString + '<br>' +
                      '<strong>Return Type:</strong> ' + returnType.typeName,
+
+
+      /**
+       * @override
+       * @public
+       * @param {*} instance
+       * @returns {boolean}
+       */
+      isInstance: function( instance ) { return typeof instance === 'function';},
+
       returnType: returnType,
       parameterTypes: parameterTypes,
       wrapForPhetioCommandProcessor: true
Index: tandem/js/types/BooleanIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/types/BooleanIO.js	(revision 58c8e57648bb338a61644f0e13d6303122c6138b)
+++ tandem/js/types/BooleanIO.js	(date 1539914654474)
@@ -24,6 +24,14 @@
   phetioInherit( ObjectIO, 'BooleanIO', BooleanIO, {}, {
     documentation: 'Wrapper for the built-in JS boolean type (true/false)',
 
+    /**
+     * @override
+     * @public
+     * @param {*} instance
+     * @returns {boolean}
+     */
+    isInstance: function( instance ) { return typeof instance === 'boolean';},
+
     /**
      * Encodes a boolean to a state (which also happens to be a boolean).
      * @param {boolean} value
Index: tandem/js/types/ArrayIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/types/ArrayIO.js	(revision 58c8e57648bb338a61644f0e13d6303122c6138b)
+++ tandem/js/types/ArrayIO.js	(date 1539914775166)
@@ -37,6 +37,14 @@
       documentation: 'A wrapper for the built-in JS array type, with the element type specified.',
       elementType: elementType,
 
+      /**
+       * @override
+       * @public
+       * @param {*} instance
+       * @returns {boolean}
+       */
+      isInstance: function( instance ) { return Array.isArray( instance ); },
+
       /**
        * Serialize an array by serializing each element
        * @param {Object[]} array
Index: tandem/js/types/VoidIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- tandem/js/types/VoidIO.js	(revision 58c8e57648bb338a61644f0e13d6303122c6138b)
+++ tandem/js/types/VoidIO.js	(date 1539914802986)
@@ -30,6 +30,14 @@
     {
       documentation: 'Type for which there is no instance, usually to mark functions without a return value',
 
+      /**
+       * @override
+       * @public
+       * @param {*} instance
+       * @returns {boolean}
+       */
+      isInstance: function( instance ) { return instance === undefined; },
+
       toStateObject: function() {
         return undefined;
       }
Index: axon/js/Emitter.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- axon/js/Emitter.js	(revision 50d885660ed5d9bcd788e641465a9d6ed6c60fa8)
+++ axon/js/Emitter.js	(date 1539915182262)
@@ -25,7 +25,7 @@
 
         // {Array.<string|function|null>} used to validate that you are emitting with the appropriate number/types of args, matches
         // logic of assertValueType, see https://github.com/phetsims/axon/issues/182
-        valueTypes: [],
+        valueTypes: null,
 
         tandem: Tandem.optional,
         phetioState: false,
@@ -35,6 +35,16 @@
 
       super( options );
 
+      if ( !options.valueTypes ) {
+        if ( this.isPhetioInstrumented() ) {
+          options.valueTypes = options.phetioType.valueTypes;
+        }
+        else{
+          // TODO: phetioInherit makes it so we need this conditional check in phet brand!!!
+          options.valueTypes = [];
+        }
+      }
+
       // @private
       this.numberOfArgs = options.valueTypes.length;
 
@@ -48,11 +58,6 @@
         }
       };
 
-      // TODO: comment this back in once all emitter method consolidation work is complete, https://github.com/phetsims/axon/issues/182
-      // if ( this.isPhetioInstrumented() ) {
-      //   assert && assert( options.phetioType.parameterTypes.length === this.numberOfArgs,
-      //     'phet/phet-io argument types mismatch.' );
-      // }
 
       // @private {function[]} - the listeners that will be called on emit
       this.listeners = [];
Index: axon/js/EmitterIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- axon/js/EmitterIO.js	(revision 50d885660ed5d9bcd788e641465a9d6ed6c60fa8)
+++ axon/js/EmitterIO.js	(date 1539915734427)
@@ -35,6 +35,7 @@
 
     assert && assert( Array.isArray( elements ) );
 
+    var valueTypes = [];
     var elementTypes = elements.map( function( element ) {
 
       // validate the look of the content
@@ -44,6 +45,8 @@
         const key = keys[ i ];
         assert && assert( ELEMENT_KEYS.indexOf( key ) >= 0, 'unrecognized element key: ' + key );
       }
+      assert && assert( element.predicate || element.type.isInstance, 'no valueType specified' );
+      valueTypes.push( element.predicate || element.type.isInstance );
       return element.type;
 
     } );
@@ -93,6 +96,17 @@
        * {Array.<ObjectIO>} - typeIOs
        */
       parameterTypes: elementTypes,
+
+      /**
+       * @public
+       * {Array.<function>} - list of predicate functions that will validate an value against whether it is of the
+       * element IOType's core type.
+       */
+      valueTypes: valueTypes,
+
+      /**
+       * {Array.<Object>} - see constructor for details on object literal keys
+       */
       elements: elements
     } );
   }
Index: dot/js/Vector2IO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- dot/js/Vector2IO.js	(revision 8f34839c6bb6279b667d2c786586ede74da252e2)
+++ dot/js/Vector2IO.js	(date 1539914746887)
@@ -30,6 +30,15 @@
   phetioInherit( ObjectIO, 'Vector2IO', Vector2IO, {}, {
     documentation: 'A numerical object with x and y properties, like {x:3,y:4}',
 
+    /**
+     * @override
+     * @public
+     * @param {*} instance
+     * @returns {boolean}
+     */
+    isInstance: function( instance ) { return instance instanceof dot.Vector2; },
+
+
     /**
      * Encodes a Vector2 instance to a state.
      * @param {Vector2} vector2
Index: phet-io/js/phetioInherit.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- phet-io/js/phetioInherit.js	(revision 9a8b1631c03d5f7830e72d2f3428e4e25d1529ab)
+++ phet-io/js/phetioInherit.js	(date 1539915501527)
@@ -37,6 +37,10 @@
         .join( ', ' ) + '>';
     }
 
+    if ( staticProperties.isInstance ) {
+      staticProperties.isInstance.isPredicate = true;
+    }
+
     // The method order is used to determine the ordering of the documentation for a type's methods, see Studio for usage.
     subtype.methodOrder = staticProperties.methodOrder || [];
     subtype.methodOrder.forEach( function( methodName ) {
Index: sun/js/Checkbox.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- sun/js/Checkbox.js	(revision 3f9f713fada74b389f6cb61c19900f0577f321be)
+++ sun/js/Checkbox.js	(date 1539914654467)
@@ -100,7 +100,6 @@
 
     // @private - sends out notifications when the checkbox is toggled.
     var toggledEmitter = new Emitter( {
-      valueTypes: [ 'boolean' ],
       tandem: options.tandem.createTandem( 'toggledEmitter' ),
       phetioDocumentation: 'Emits when user input causes the checkbox to toggle, emitting a single arg: the new boolean value of the checkbox state.',
       phetioReadOnly: options.phetioReadOnly,
Index: joist/js/Sim.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- joist/js/Sim.js	(revision fce8c7cbcdc44fe8165dbdc78241504efe435fdf)
+++ joist/js/Sim.js	(date 1539914654445)
@@ -94,7 +94,6 @@
 
     // @public Emitter that indicates when the sim resized.  This Emitter is implemented so it can be automatically played back.
     this.resizedEmitter = new Emitter( {
-      valueTypes: [ 'number', 'number' ],
       tandem: ROOT_TANDEM.createTandem( 'resizedEmitter' ),
       phetioType: EmitterIO( [
         { name: 'width', type: NumberIO },
@@ -145,7 +144,6 @@
 
     // @public Emitter that indicates when a frame ends.
     this.frameEndedEmitter = new Emitter( {
-      valueTypes: [ 'number' ],
       tandem: ROOT_TANDEM.createTandem( 'frameEndedEmitter' ),
       phetioType: EmitterIO( [ { name: 'dt', type: NumberIO } ] ),
       phetioHighFrequency: true,
@@ -155,7 +153,6 @@
     // @private {Emitter} Emitter that steps the simulation, This Emitter is implemented so it can be automatically
     // played back.
     this.stepSimulationEmitter = new Emitter( {
-      valueTypes: [ 'number' ],
       tandem: ROOT_TANDEM.createTandem( 'stepSimulationEmitter' ),
       phetioType: EmitterIO( [ { name: 'dt', type: NumberIO } ] ),
       phetioHighFrequency: true,
Index: arithmetic/js/common/model/ArithmeticModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- arithmetic/js/common/model/ArithmeticModel.js	(revision fb11c15171e628cb5100f907d0ba587c9cf186ea)
+++ arithmetic/js/common/model/ArithmeticModel.js	(date 1539914654449)
@@ -39,7 +39,6 @@
 
     // @private - for PhET-iO
     this.checkAnswerEmitter = new Emitter( {
-      valueTypes: [ Object ],
       tandem: tandem.createTandem( 'checkAnswerEmitter' ),
       phetioType: EmitterIO( [ { name: 'results', type: ObjectIO, documentation: 'hello' } ] )
     } );
Index: scenery/js/listeners/DragListener.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/listeners/DragListener.js	(revision feb30c14b2d7de6349fb187afc0a60524684637e)
+++ scenery/js/listeners/DragListener.js	(date 1539914765262)
@@ -43,7 +43,6 @@
   var Bounds2 = require( 'DOT/Bounds2' );
   var Emitter = require( 'AXON/Emitter' );
   var EmitterIO = require( 'AXON/EmitterIO' );
-  var Event = require( 'SCENERY/input/Event' );
   var EventIO = require( 'SCENERY/input/EventIO' );
   var inherit = require( 'PHET_CORE/inherit' );
   var PhetioObject = require( 'TANDEM/PhetioObject' );
@@ -184,7 +183,6 @@
 
     // @private {Emitter} - emitted on drag. Used for triggering phet-io events to the data stream, see https://github.com/phetsims/scenery/issues/842
     this._draggedEmitter = new Emitter( {
-      valueTypes: [ Event ],
       tandem: options.tandem.createTandem( 'draggedEmitter' ),
       phetioHighFrequency: true,
       phetioDocumentation: 'Emits whenever a drag occurs with an EventIO argument.',
Index: scenery/js/input/Input.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/input/Input.js	(revision feb30c14b2d7de6349fb187afc0a60524684637e)
+++ scenery/js/input/Input.js	(date 1539914654461)
@@ -231,7 +231,6 @@
     // @private {Emitter} - Emits to the PhET-iO data stream.  
     this.mouseUpEmitter = new Emitter( {
       phetioPlayback: true,
-      valueTypes: [ Vector2, window.Event ], // Note this is a DOM event, not a scenery.Event
       tandem: options.tandem.createTandem( 'mouseUpEmitter' ),
       phetioType: EmitterIO( [
         { name: 'point', type: Vector2IO },
@@ -249,7 +248,6 @@
     // @private {Emitter} - Emits to the PhET-iO data stream.  
     this.mouseDownEmitter = new Emitter( {
       phetioPlayback: true,
-      valueTypes: [ Vector2, window.Event ], // Note this is a DOM event, not a scenery.Event
       tandem: options.tandem.createTandem( 'mouseDownEmitter' ),
       phetioType: EmitterIO( [
         { name: 'point', type: Vector2IO },
@@ -267,7 +265,6 @@
     // @private {Emitter} - Emits to the PhET-iO data stream.  
     this.mouseMovedEmitter = new Emitter( {
       phetioPlayback: true,
-      valueTypes: [ Vector2, window.Event ], // Note this is a DOM event, not a scenery.Event
       tandem: options.tandem.createTandem( 'mouseMovedEmitter' ),
       phetioType: EmitterIO( [
         { name: 'point', type: Vector2IO },
@@ -286,7 +283,6 @@
     // @private {Emitter} - Emits to the PhET-iO data stream.  
     this.mouseOverEmitter = new Emitter( {
       phetioPlayback: true,
-      valueTypes: [ Vector2, window.Event ], // Note this is a DOM event, not a scenery.Event
       tandem: options.tandem.createTandem( 'mouseOverEmitter' ),
       phetioType: EmitterIO( [
         { name: 'point', type: Vector2IO },
@@ -304,7 +300,6 @@
     // @private {Emitter} - Emits to the PhET-iO data stream.  
     this.mouseOutEmitter = new Emitter( {
       phetioPlayback: true,
-      valueTypes: [ Vector2, window.Event ], // Note this is a DOM event, not a scenery.Event
       tandem: options.tandem.createTandem( 'mouseOutEmitter' ),
       phetioType: EmitterIO( [
         { name: 'point', type: Vector2IO },
@@ -322,7 +317,6 @@
     // @private {Emitter} - Emits to the PhET-iO data stream.  
     this.wheelScrolledEmitter = new Emitter( {
       phetioPlayback: true,
-      valueTypes: [ window.Event ], // Note this is a DOM event, not a scenery.Event
       tandem: options.tandem.createTandem( 'wheelScrolledEmitter' ),
       phetioType: EmitterIO( [
         { name: 'event', type: DOMEventIO }
@@ -346,7 +340,6 @@
     // @private {Emitter} - Emits to the PhET-iO data stream.
     this.touchStartedEmitter = new Emitter( {
       phetioPlayback: true,
-      valueTypes: [ 'number', Vector2, window.Event ], // Note this is a DOM event, not a scenery.Event
       tandem: options.tandem.createTandem( 'touchStartedEmitter' ),
       phetioType: EmitterIO( [
         { name: 'id', type: NumberIO },
@@ -365,7 +358,6 @@
     // @private {Emitter} - Emits to the PhET-iO data stream.
     this.touchEndedEmitter = new Emitter( {
       phetioPlayback: true,
-      valueTypes: [ 'number', Vector2, window.Event ], // Note this is a DOM event, not a scenery.Event
       tandem: options.tandem.createTandem( 'touchEndedEmitter' ),
       phetioType: EmitterIO( [
         { name: 'id', type: NumberIO },
@@ -387,7 +379,6 @@
     // @private {Emitter} - Emits to the PhET-iO data stream.
     this.touchMovedEmitter = new Emitter( {
       phetioPlayback: true,
-      valueTypes: [ 'number', Vector2, window.Event ], // Note this is a DOM event, not a scenery.Event
       tandem: options.tandem.createTandem( 'touchMovedEmitter' ),
       phetioType: EmitterIO( [
         { name: 'id', type: NumberIO },
@@ -409,7 +400,6 @@
     // @private {Emitter} - Emits to the PhET-iO data stream.
     this.touchCanceledEmitter = new Emitter( {
       phetioPlayback: true,
-      valueTypes: [ 'number', Vector2, window.Event ], // Note this is a DOM event, not a scenery.Event
       tandem: options.tandem.createTandem( 'touchCanceledEmitter' ),
       phetioType: EmitterIO( [
         { name: 'id', type: NumberIO },
@@ -431,7 +421,6 @@
     // @private {Emitter} - Emits to the PhET-iO data stream.
     this.penStartedEmitter = new Emitter( {
       phetioPlayback: true,
-      valueTypes: [ 'number', Vector2, window.Event ], // Note this is a DOM event, not a scenery.Event
       tandem: options.tandem.createTandem( 'penStartedEmitter' ),
       phetioType: EmitterIO( [
         { name: 'id', type: NumberIO },
@@ -450,7 +439,6 @@
     // @private {Emitter} - Emits to the PhET-iO data stream.
     this.penEndedEmitter = new Emitter( {
       phetioPlayback: true,
-      valueTypes: [ 'number', Vector2, window.Event ], // Note this is a DOM event, not a scenery.Event
       tandem: options.tandem.createTandem( 'penEndedEmitter' ),
       phetioType: EmitterIO( [
         { name: 'id', type: NumberIO },
@@ -472,7 +460,6 @@
     // @private {Emitter} - Emits to the PhET-iO data stream.
     this.penMovedEmitter = new Emitter( {
       phetioPlayback: true,
-      valueTypes: [ 'number', Vector2, window.Event ], // Note this is a DOM event, not a scenery.Event
       tandem: options.tandem.createTandem( 'penMovedEmitter' ),
       phetioType: EmitterIO( [
         { name: 'id', type: NumberIO },
@@ -494,7 +481,6 @@
     // @private {Emitter} - Emits to the PhET-iO data stream.
     this.penCanceledEmitter = new Emitter( {
       phetioPlayback: true,
-      valueTypes: [ 'number', Vector2, window.Event ], // Note this is a DOM event, not a scenery.Event
       tandem: options.tandem.createTandem( 'penCanceledEmitter' ),
       phetioType: EmitterIO( [
         { name: 'id', type: NumberIO },
Index: scenery/js/input/EventIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/input/EventIO.js	(revision feb30c14b2d7de6349fb187afc0a60524684637e)
+++ scenery/js/input/EventIO.js	(date 1539914672110)
@@ -31,6 +31,15 @@
   phetioInherit( ObjectIO, 'EventIO', EventIO, {}, {
     get documentation() { return 'An event, with a point'; },
 
+    /**
+     * @override
+     * @public
+     * @param {*} instance
+     * @returns {boolean}
+     */
+    isInstance: function( instance ) { return instance instanceof scenery.Event; },
+
+
     /**
      * Encodes a Color into a state object.
      * @param {Event} event
Index: scenery/js/input/DOMEventIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/input/DOMEventIO.js	(revision feb30c14b2d7de6349fb187afc0a60524684637e)
+++ scenery/js/input/DOMEventIO.js	(date 1539915734425)
@@ -33,6 +33,15 @@
   phetioInherit( ObjectIO, 'DOMEventIO', DOMEventIO, {}, {
     documentation: 'A DOM Event',
 
+    /**
+     * Note this is a DOM event, not a scenery.Event
+     * @override
+     * @public
+     * @param {*} instance
+     * @returns {boolean}
+     */
+    isInstance: function( instance ) { return instance instanceof window.Event; },
+
     /**
      * Encodes a DOMEvent instance to a state.
      * @param {Event} domEvent

</details>

**Comment by samreid** [comment]
Nice patch!  Here are some possibilities for moving forward:

1. Move `phetioInherit.js` to tandem
or
2. Provide a phet-brand compatible definition of phetioInherit that does a subset of the phetioInherit work, such as assigning static properties or a subset of static properties.  OR make it so when ifphetio is false, `phetioInherit` instead calls `inherit`.
or
3. Assign `isInstance` methods outside of phetioInherit like this:
```js
Vector2IO.isInstance = ...
```

(1) is technically the easiest and would provide long term maintainability, but exposes a little more phet-io code.  In my opinion, this is non-critical code that would be OK to move to tandem.
(2) Somewhat of a hack which would probably work but could lead to confusion in debugging some cases.
(3) More extreme hack to work around this particular problem, which would likely work in the short term but feels like a poor long term solution (especially if we face similar problems and apply this solution again).

**Comment by zepumph** [comment]
Blocked by https://github.com/phetsims/phet-io/issues/1401

**Comment by zepumph** [comment]
phetioInherit has now been moved. I'll continue work on this.

**Comment by zepumph** [comment]
>This part seemed suspicious, and may need to be changed when we move to ES6 instead of phetioInherit:

Yes agreed, there are many scary pieces of phetioInherit that will need to be changed when we add support for es6.

>Should isInstance: function( instance ) { return Array.isArray( instance ); }, check element types?

Yes


>Can we eliminate assertValueType and just use TypeDef now?

That is the goal. Again this is still in progress, and I didn't want to change production code too much before discussion #189 this week.

>What is function(*=)?

I'm not sure, WebStorm added that in for me. If I had to guess it looks like it a signature that takes in `*`, with default (signified with `=`) of nothing, and returns boolean. I kinda like it, though I didn't mean to keep it, and don't think it needs the `=`.

**Comment by zepumph** [comment]
Closing this issue. Further work will continue in #189
