### ISSUE TITLE
When should suffix Property be validated?

### ISSUE THREAD

**Issue by chrisklus** [phetsims/axon#191]
When working on https://github.com/phetsims/graphing-quadratics/issues/14, @samreid and I noticed that if a tandem name for a Property does not end with "Property", an assertion error is thrown, even with `phetioValidateTandems=false`.

@zepumph do you think this is appropriate behavior or should this assertion only check with `phetioValidateTandems=false` ?

**Comment by pixelzoom** [comment]
I think it's appropriate to throw the error regardless of `phetioValidateTandems=false`.  The programmer has done something wrong, versus something incomplete.

**Comment by samreid** [comment]
Self-assigning in case I get to this first.

**Comment by chrisklus** [comment]
@samreid does anything need to be done for this given @pixelzoom's comment?

**Comment by samreid** [comment]
Good point @chrisklus, the behavior is already as prescribed, closing.
