### ISSUE TITLE
Avoid storing initial value in Property sometimes?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/axon#193]
It seems that it always will take up additional memory by storing the initial value, particularly when it is never used (especially if it is a large object). Can we have an option, or a way to clear the initial value? (I'd prefer not to initialize it as `null` and have everything that hooks in able to handle `null`).

This came up as part of a memory leak in fractions-common, where whenever a Property changed from `a` to `b`, then `a.someReference = b` was set. If initial value wasn't stored, the old value would be GC'ed when no references were there. WITH the initial value being stored permanently, this resulted in the chain of every single value of the Property ever leaking.

So main options:

1. An option to avoid storing the initial value.
2. A method to clear the initial value.
3. A workaround by initializing as `null` (ideally without having to change to `Property.<X|null>`, or making other changes to client code, but this seems "dirty").

Thoughts?

**Comment by jonathanolson** [comment]
@ariel-phet the commit above could probably use a brief review by another developer.

**Comment by ariel-phet** [comment]
@pixelzoom I believe this is a pretty quick review if you are available.

**Comment by pixelzoom** [comment]
Documentation for DymanicProperty `getInitialValue` was wrong, looked like a copy-paste error, fixed in the above commit.  Otherwise looks good.  Unclear if work is done (no "ready-for-review" label) so back to @jonathanolson.

**Comment by jonathanolson** [comment]
Thanks, sorry about that! Should be done, closing.

**Comment by pixelzoom** [comment]
Reopening.

In Property.ts, we now have:

```js
63 protected _initialValue: T | null;

96 constructor( value: T, providedOptions?: PropertyOptions<T> ) {

140     this._initialValue = value;

224 setInitialValue( initialValue: T ): void {
    this._initialValue = initialValue;
  }
```

And that results in having to use the non-null assertion operator in cases like this:

```
const p = new Vector2Property( Vector.ZERO );
const initialX = p.getInitialValue()!.x;
```

So...  I agree that a read-only Property doesn’t need to have an initial value. But for mutable Properties (derived or otherwise) I don’t agree that the ability to reset has any relevance on whether the initial value is stored. Reset is not the only legitimate reason for doing a reset. Otherwise initialValue would not be public.

I discussed this in Slack with @zepumph and @samreid.  @zepumph came up with what seems like the best solution:

> [Michael Kauzmann](https://app.slack.com/team/U6DFWDG1Z)  [3 minutes ago](https://phetsims.slack.com/archives/C6HPE0J91/p1654101236565139?thread_ts=1654100424.847549&cid=C6HPE0J91)
Perhaps an option to Property called `storeInitialValue` defaults to true. Then ping @jonathanolson to set it to false in the memory problems in fraction-common?

@jonathanolson your opinion?  High priority please.

**Comment by jonathanolson** [comment]
Would `storeInitialValue` default to false for DerivedProperty (but true for Property in general)? If storeInitialValue is false, wouldn't this break the type system if we had `_initialValue: T`? Is the proposal to have `_initialValue: T` (and if so, we could error out if trying to access an un-initialized value?)

**Comment by samreid** [comment]
The proposed patch would be something like this:

<details>

```diff

Index: js/Property.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/Property.ts b/js/Property.ts
--- a/js/Property.ts	(revision cc86b38fdb3c1c01ef1f044d6309ea7d06db18dd)
+++ b/js/Property.ts	(date 1654103788831)
@@ -60,7 +60,7 @@
   units: string | null;
 
   // Initial value
-  protected _initialValue: T | null;
+  protected _initialValue: T;
 
   validValues: readonly T[] | undefined;
 
@@ -333,8 +333,6 @@
    * Resets the value to the initial value.
    */
   reset(): void {
-
-    // @ts-ignore
     this.set( this._initialValue );
   }
 
Index: js/DerivedProperty.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/DerivedProperty.ts b/js/DerivedProperty.ts
--- a/js/DerivedProperty.ts	(revision cc86b38fdb3c1c01ef1f044d6309ea7d06db18dd)
+++ b/js/DerivedProperty.ts	(date 1654103711541)
@@ -93,11 +93,6 @@
     }
 
     this.dependencies = dependencies;
-
-    // We can't reset the DerivedProperty, so we don't store the initial value to help prevent memory issues.
-    // See https://github.com/phetsims/axon/issues/193
-    this._initialValue = null;
-
     this.derivation = derivation;
     this.derivedPropertyListener = this.getDerivedPropertyListener.bind( this );
 
Index: js/DynamicProperty.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/DynamicProperty.ts b/js/DynamicProperty.ts
--- a/js/DynamicProperty.ts	(revision cc86b38fdb3c1c01ef1f044d6309ea7d06db18dd)
+++ b/js/DynamicProperty.ts	(date 1654103711547)
@@ -193,12 +193,6 @@
     this.valuePropertyProperty = valuePropertyProperty;
     this.isExternallyChanging = false;
 
-    // If we can't reset(), then we won't store the initial value.
-    // See https://github.com/phetsims/axon/issues/193.
-    if ( !this.bidirectional ) {
-      this._initialValue = null;
-    }
-
     this.propertyPropertyListener = this.onPropertyPropertyChange.bind( this );
     this.propertyListener = this.onPropertyChange.bind( this );
 

```

</details>

FractionLevel and MatchingLevel already have a sim-specific workaround for the memory issue.  Would more sim-specific workarounds be needed to accommodate this patch?

**Comment by pixelzoom** [comment]
And if `initialValue` was removed from DerivedProperty and DynamicProperty to save memory, why is was it done for those 2 classes?  It seems like a general issue for Property and all of its subclasses.

**Comment by pixelzoom** [comment]
@samreid and I did a live mini review of what he's working on.  His decoupling of Property and DerivedProperty (via AbstractProperty) looks nice.  I'm OK with not having initialValue in DerivedProperty.  We can deal with that if/when someone needs it.

**Comment by samreid** [comment]
Sounds good, I'll put this issue on hold and continue in the related issue https://github.com/phetsims/axon/issues/342

**Comment by samreid** [comment]
Commits for https://github.com/phetsims/axon/issues/342 are pushed.

**Comment by samreid** [comment]
In the commit, I removed the non-null assertion operator in MOTHA.  Heads up to @pixelzoom

**Comment by samreid** [comment]
The last part mentioned is in DynamicProperty:

```ts
    // If we can't reset(), then we won't store the initial value.
    // See https://github.com/phetsims/axon/issues/193.
    if ( !this.bidirectional ) {
      this._initialValue = null;
    }
    else {
      this._initialValue = initialValue;
    }
```

@pixelzoom and I discussed that it seems OK to omit initialValue from DerivedProperty, and I'm wondering if it would be OK to also omit from DynamicProperty.  I removed that code and related parts, and observed that the type checker passed, linting passed and multi snapshot comparison with stride=10 indicated no problems.  So I think I'll commit it, but this part should be checked by @jonathanolson.

We will leave the bulk of the review to https://github.com/phetsims/axon/issues/342 but leaving this issue assigned to @pixelzoom and @jonathanolson in case there are any aspects of `initialValue` to discuss.

**Comment by pixelzoom** [comment]
Thanks for doing this work @samreid. Overall, this is a nice improvement to the Property type hierarchy.   I'm OK with DerivedProperty and DynamicProperty not having initialValue for now - we can address that if it's needed in the future. And having to use IReadOnlyProperty were appropriate is also a nice aspect of this change.

**Comment by samreid** [comment]
We looked at initialValue at today's dev meeting, and agreed it seems reasonable.  @jonathanolson commented that removing initialValue from DynamicProperty seemed OK.  So we will close and continue in https://github.com/phetsims/axon/issues/342
