### ISSUE TITLE
support for valueType:Array

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#195]
Noted during Graphing Quadratics code review https://github.com/phetsims/graphing-quadratics/issues/43, when working on this checklist item:

> - [ ] Assertions should be used appropriately and consistently. Type checking should not just be done in code comments. Use Array.isArray to type check an array.

"Use Array.isArray to type check an array" does not appear to be the case in Property validation. 

Example in GRAPHING_QUADRATICS/GQModel:

```js
// Options for {Property.<Quadratic[]>}
const optionsPropertyQuadraticArray = {
  valueType: Array,
  isValidValue: array => _.every( array, function( value ) { return value instanceof Quadratic; } )
};
```

Property's `valueType` option is handled by assertValueType.js, which contains no special handling for `Array`.   So `valueType: Array` gets checked using `instanceof`, not `Array.isArray`.   

assertValueType.js should either be fixed to handle Array properly, or an assertion should be added to disallow `valueType: Array`.   If the latter, then the above code would need to change to:

```js
// Options for {Property.<Quadratic[]>}
const optionsPropertyQuadraticArray = {
  isValidValue: array => Array.isArray( array ) &&
    _.every( array, function( value ) { return value instanceof Quadratic; } )
};
```

@samreid @jonathanolson opinions? Keep in mind that we're discussing unifying the various validation options in https://github.com/phetsims/axon/issues/189.

High priority because this affects Graphing Quadratics.

**Comment by pixelzoom** [comment]
To fix assertValueType.js, add this after line 34:

```js
      else if ( valueType === Array ) {
        assert( Array.isArray( value ), 'value should be an Array, value=' + value );
      }
```

Does that seem like an acceptable solution?

**Comment by pixelzoom** [comment]
The above passed lint. But WebStorm is complaining about `( valueType === Array )`, with message "Binary operation argument type Function is not compatible with type ArrayConstructor".   Can anyone translate that for me? Something to be concerned about?

**Comment by pixelzoom** [comment]
GRAPHING_QUADRATICS/GQModel appears to be the only place where `valueType: Array` is used.

**Comment by pixelzoom** [comment]
Since I don't have time to be a trailblazer here, I changed GRAPHING_QUADRATICS/GQModel to handle the Array.toArray call, i.e.:

```js
// Options for {Property.<Quadratic[]>}
const optionsPropertyQuadraticArray = {
  isValidValue: array => Array.isArray( array ) &&
    _.every( array, function( value ) { return value instanceof Quadratic; } )
};
``` 

Leaving this issue open to decide how to handle in general.

**Comment by samreid** [comment]
On hold until #189 is decided.

**Comment by zepumph** [comment]
I think #189 is far enough along to bring this back up for discussion. I have two potential proposals:

1. This approach assumes that we only support a homogeneous array: `valueType: ['number']`. Thus we could check if `Array.isArray(options.valueType)` then we assert that it only has one item in it, and we treat that as the valueType for all arrays.
   * This approach is a bit cryptic, but it does potentially allow support in the future for heterogeneous arrays.
   * This approach is nice because it doesn't require giving a `valueType` AND `isValidValue`.
2. We could have `Validator.js` have a static function in which you give it a value type (`'number'` or `Node` etc.), and it returns the options needed to pass to `Validator.validate` in order to validate the array. A method called `Validator.getArrayValidationOptions()` or something.

**Comment by samreid** [comment]
Writing down some options.

```js
// Proposal 1 from preceding comment
new Property(myArray,valueType:['number'])
new Property(myArray,valueType:[Vector2])

// Proposal 2 from preceding comment
new Property(myArray,isValidValue: Validator.getArrayValidator('number'));

// Option 3: checking that it is an array and all values match a spec, using Validator and existing support
new Property(myArray,{isValidValue: v=>Array.isArray(v) && _.every(v, element=>Validator.validate(element,{valueType: 'number'})}

// Option 4: new key type
new Property(myArray,{arrayElementType: 'number'});
new Property(myArray,{arrayElementType: Vector2});
```

1 and 4 seem nice.  In https://github.com/phetsims/axon/issues/189#issuecomment-451994463 we discussed keeping typeof and instanceof bound together in `valueType` and now we're talking about throwing another type in there.  Not sure if it is clever or messy.  What if we had `primitiveType: 'boolean'` vs `valueType: Vector2` vs `arrayElementType: 'number'`?  Or maybe we should consider what was done for array types in Query String Machine--in that case it would be something like: 

```js
// Option 5: nested validator for arrays
new Property(myArray, {arrayElementType:{validValues: [1,2,3]}} // array of values 1,2,3 only
new Property(myArray, {arrayElementType:{isValidValue: x => x>0;}} // array of positive numbers
```

**Comment by pixelzoom** [comment]
My assumption in the solution proposed in https://github.com/phetsims/axon/issues/195#issue-376638347 was that checking that the value is an `Array` is sufficient.  Do you really feel that we need to check that all of the elements in the Array are of some homogenous type? I'm not convinced that's needed or worth the effort.

**Comment by pixelzoom** [comment]
And what if you have an Array of Arrays of Arrays of... ?  Do you propose to do a drill all the way down to test the types of the leaf elements?

**Comment by jonathanolson** [comment]
> Do you really feel that we need to check that all of the elements in the Array are of some homogenous type? I'm not convinced that's needed or worth the effort.

I've found that helpful in the past in a few cases, usually doing `assert && array.forEach( element => assert( element instanceof X ) )`.

No strong feelings, but it seems if Validator can see the Array type and convert the check to `Array.isArray` that seems nice.

**Comment by pixelzoom** [comment]
I really think that something like:

```
new Property( ..., {
  valueType: Array,
  isValidValue: value => // predicate to validate what's in Array
} );
```

... would be sufficient to handle validation of Arrays (and Arrays of Arrays, etc.)  If you really want to incur the cost/complexity of building that into Validator, go for it.   But I think the payoff will be minimal.

**Comment by zepumph** [comment]
I think that ` valueType: Array,` is insufficient on it's own. I too like that approach, but we would need to add this line into Validator.validate:
```
if ( options.valueType ) {
          const valueType = options.valueType;
// start new block **************************************************
          if ( valueType === Array){
                assert( Array.isArray( value ));
          }
// end new block **************************************************
          if ( typeof valueType === 'string' ) { // primitive type
            assert( typeof value === valueType, 'value should have typeof ' + valueType + ', value=' + value );
          }
          else if ( typeof valueType === 'function' ) { // constructor
            assert( value instanceof valueType, 'value should be instanceof ' + valueType.name + ', value=' + value );
          }
        }

**Comment by pixelzoom** [comment]
That's pretty much what I proposed in https://github.com/phetsims/axon/issues/195#issuecomment-435246708.

**Comment by zepumph** [comment]
>arrayElementType

I think that naming it `elementType` would be more general, because perhaps it could work for another composite type? Maybe that's too vague.

I think there are two leading ideas about how we go, please correct me if I am mistaken:

1. Use of `valueType: Array` with `isValidValue`:
 ```js
new Property( ..., {
  valueType: Array,
  isValidValue: value => value.forEach((element)=>typeof element === 'string'); // predicate to validate what's in Array
} );
  ```

2. Use of `valueType:Array` with new key `arrayElementType` (maybe `elementType) where the value of arrayElementType is of type `{ValidatorOptions}` (or maybe it takes the place of `valueType`, not sure that was decided):

```
new Property( ..., {
  valueType: Array,
  arrayElementType: {valueType: 'string'}
} );
```

I think that including `valueType: Array` is very explicit and makes things clear and nice. I think I prefer option 2 because it feels like `Validator` is doing more work for us with little downside. Perhaps there is a downside in the proliferation of more `ValidatorOptions`. 

It's good to note that this has always been a problem for Property validation, the issue has just moved over to being `Validator`'s problem since #189. 

Do people like option 1 or 2 or another thing better?

**Comment by pixelzoom** [comment]
Option 1 seems sufficient to me, as I said in https://github.com/phetsims/axon/issues/195#issuecomment-452459698.

**Comment by samreid** [comment]
@zepumph @chrisklus and I added support for `valueType: Array` in the preceding commit.  This does not preclude us from checking element types in the future.

**Comment by samreid** [comment]
I think `valueType: Array` will be sufficient for now.  If a client needs to check values, they can additionally use `isValidValue`.  In the future, we have the option to add direct support for checking individual element types, but that doesn't seem necessary now.  @zepumph is that satisfactory?  Can this issue be closed?

**Comment by zepumph** [comment]
Yes I think this is most efficient and best way forward right now.

**Comment by zepumph** [comment]
This came up again as part of https://github.com/phetsims/axon/issues/227. Reopening.

As discussion with @pixelzoom and @samreid, it seems like we should make a new validator key like;
```
{
  arrayElementType: Type
}
```

which will basically do:
```
{
         valueType: Array,

        // {TermCreator[]}
        isValidValue: array => {
          return _.every( array, value => value instanceof TermCreator )
        }
      }
```

**Comment by pixelzoom** [comment]
The other common case I’m running into is `{SomeType|null}`.  And I’m having to do this:

`{ isValidValue: value => ( value instanceof Event || value === null ) } // {Event|null}`

**Comment by zepumph** [comment]
>The other common case I’m running into is `{SomeType|null}`. And I’m having to write this type of validator

see https://github.com/phetsims/axon/issues/228

**Comment by zepumph** [comment]
arrayElementType was added in the above commit. @samreid please review this when you review #228.

**Comment by samreid** [comment]
Everything looks great, and the unit tests have good coverage, nice work!  Thanks.  Closing.
