### ISSUE TITLE
convert to type-specific Property subclasses

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#196]
In https://github.com/phetsims/axon/issues/116 we discussed using `BooleanProperty` instead of `Property({phetioType: PropertyIO( BooleanIO )}` and I detected approximately 82 occurrences of the latter.  Should they be converted to `BooleanProperty`?  It seems to me they should.  @chrisklus if you agree, can you please address this?

**Comment by samreid** [comment]
Same thing for `phetioType: PropertyIO( StringIO)`, that seems like it would be better as `StringProperty`

**Comment by pixelzoom** [comment]
The first thing that I've done to prepare a sim for instrumentation is to use BooleanProperty, NumberProperty, and StringProperty wherever possible.  So +1 for conversion.

**Comment by pixelzoom** [comment]
I'm going to make issues for any of my sims that need to be converted to use BooleanProperty, NumberProperty, and StringProperty.  I'll link to this issue.

**Comment by chrisklus** [comment]
Work left for this issue:

- [x] Property( { phetioType: PropertyIO( BooleanIO ) } ) -> BooleanProperty
- [ ] Property( { phetioType: PropertyIO( StringIO ) } ) -> StringProperty
- [ ] Property( { phetioType: PropertyIO( NumberIO ) } ) -> NumberProperty

**Comment by samreid** [comment]
Fixed, closing.
