### ISSUE TITLE
buggy behavior of bidirectional DynamicProperty 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#197]
@samreid @zepumph @chrisklus FYI.

This issue is related to understanding why `reentrant: true` is needed for a bidirectional DynamicProperty in GRAPHING_QUADRATICS/CoefficientSlider, see https://github.com/phetsims/graphing-quadratics/issues/52 and https://github.com/phetsims/sun/issues/417.

Here's an example, a bidirectional mapping where `viewProperty` is the square of `modelProperty`.

```js
      const DynamicProperty = require( 'AXON/DynamicProperty' );
      const NumberProperty = require( 'AXON/NumberProperty' );

      const modelProperty = new NumberProperty( 0, {
        isValidValue: value => ( value >= 0 ),
        reentrant: true
      } );

      const viewProperty = new DynamicProperty( new Property( modelProperty ), {
        bidirectional: true,
        reentrant: true,
        map: value => {
          const newValue = Math.pow( value, 2 );
          console.log( 'map: ' + value + ' -> ' + newValue );
          return newValue;
        },
        inverseMap: value => {
          const newValue = Math.sqrt( value );
          console.log( 'inverseMap: ' + value + ' -> ' + newValue );
          return newValue;
        }
      } );

     debugger;
```

In the console, here's what I observe:

When I set `viewProperty` to a value that does not involve floating point error, both `inverseMap` and `map` are called.  Why is `map` called in this case?

```
> viewProperty.value = 4
inverseMap: 4 -> 2
map: 2 -> 4
< 4
```

When I set `viewProperty` to a value that _does_ involve floating point error, both `inverseMap` and `map` are called, and then `inverseMap` is called again.  Why is `map` called? Why is `inverseMap` called a second time?

```
> viewProperty.value = 4.5
inverseMap: 4.5 -> 2.1213203435596424
map: 2.1213203435596424 -> 4.499999999999999
inverseMap: 4.499999999999999 -> 2.1213203435596424
> 4.5
```

When I set `modelProperty`, I see `map` and `inverseMap` called. Why is `inverseMap` called?  Why do I never see a second call to `map`, as I did for `inverseMap` with `viewProperty`?

 ```
> modelProperty.value = 2
CoefficientSlider.js?bust=1542329934673:158 map: 2 -> 4
CoefficientSlider.js?bust=1542329934673:163 inverseMap: 4 -> 2
< 2

> modelProperty.value = 2.1213203435596424
map: 2.1213203435596424 -> 4.499999999999999
inverseMap: 4.499999999999999 -> 2.1213203435596424
< 2.1213203435596424
```

**Comment by pixelzoom** [comment]
I tried adding a couple of flags to short-circuit "ping ponging" of `map` and `inverseMap`.  I don't know if this is complete or correct, but it seems to solve the problem.

```
    this.callingMap = false; // true when we're in the middle of a call to this.map
    this.callingInverseMap = false; // true when we're in the middle of a call to this.inverseMap

...

    onPropertyPropertyChange: function( value ) {
      if ( !this.callingInverseMap ) {
        // Since we override the setter here, we need to call the version on the prototype
        this.callingMap = true;
        Property.prototype.set.call( this, this.map( value ) );
        this.callingMap = false;
      }
    },

...

   onSelfChange: function( value ) {
      if ( this.valuePropertyProperty.value !== null ) {
        if ( !this.callingMap ) {
          this.callingInverseMap = true;
          this.derive( this.valuePropertyProperty.value ).value = this.inverseMap( value );
          this.callingInverseMap = false;
        }
      }
    },
```

Previous console tests now seem to behave as I'd expect. That is, there no "ping ponging" of `map` and `inverseMap`. And more importantly, `reentrant: true` can be removed from both `modelProperty` and `viewProperty`.

```
> viewProperty.value = 4
inverseMap: 4 -> 2
< 4
> viewProperty.value = 4.5
inverseMap: 4.5 -> 2.1213203435596424
< 4.5
> modelProperty.value = 2
map: 2 -> 4
< 2
> modelProperty.value = 2.1213203435596424
map: 2.1213203435596424 -> 4.499999999999999
< 2.1213203435596424
```

**Comment by pixelzoom** [comment]
I also verified that the guard flags added in https://github.com/phetsims/axon/issues/197#issuecomment-439252158 allow me to remove `reentrant: true` from the `DynamicProperty` in `GRAPHING_QUADRATIC/CoefficientSlider`.  And it resolved the `reentry detected` assertion failure that was occurring with Studio in https://github.com/phetsims/graphing-quadratics/issues/52, allowing us to remove `phetioStudioControl: false` from the associated NumberProperties.

**Comment by pixelzoom** [comment]
Top priority, since this fixes phetsims/graphing-quadratics#52 which is also top priority.

**Comment by samreid** [comment]
DynamicProperty unit tests pass with the changes proposed in https://github.com/phetsims/axon/issues/197#issuecomment-439252158

**Comment by pixelzoom** [comment]
Something like this (untested) might be a better solution.  It puts the guards inside `this.map` and `this.inverseMap`.

```
    this.callingMap = false; // true when we're in the middle of a call to this.map
    this.callingInverseMap = false; // true when we're in the middle of a call to this.inverseMap

    this.map = () => {
      if ( ! this.callingInverseMap ) {
        this.callingMap = true;
        ( typeof options.map === 'string' ? _.property( options.map ) : options.map() )();
        this.callingMap = false;
      }
    };

    this.inverseMap = () => {
      if ( !this.callingMap ) {
        this.callingInverseMap = true;
        ( typeof options.inverseMap === 'string' ? _.property( options.inverseMap ) : options.inverseMap )();
        this.callingInverseMap = false;
      }
    };
```

**Comment by pixelzoom** [comment]
Yeah, that's why I said:
> I don't know if this is complete (there are other calls to `this.map`) or correct (I'm not familiar with all the features of `DynamicProperty`), but it seems to solve the problem.

So however you want to solve this is fine with me.  My "solution" was to illustrate the "bouncing", and to verify that eliminating the bouncing solved the other problems that we were seeing in Graphing Quadratics.

**Comment by pixelzoom** [comment]
Whatever the solution, it also seems like `DynamicPropertyTests` should be augmented to verify behavior related to this issue.

**Comment by jonathanolson** [comment]
I'm running fairly comprehensive testing on a solution right now, I'll expect to commit soon.

It cuts off the Property changes in either direction when `a===map(b)` or `inverseMap(a)===b` (making sure that it is the same Property that the changes result from, etc.)

For testing, it's possible to use a map/inverseMap pair that are obviously not an "exact" inverse:

```js
var sourceProperty = new axon.Property( 0 );
var wrapperProperty = new axon.Property( sourceProperty );
var dynamicProperty = new axon.DynamicProperty( wrapperProperty, {
  bidirectional: true,
  // NOT a true inverse
  map: n => n + 2,
  inverseMap: n => n - 1
} );
// source: 0, dynamic: 2

dynamicProperty.value = 3;
// source: 2, dynamic: 3

sourceProperty.value = 5;
// source: 5, dynamic: 7
```

**Comment by jonathanolson** [comment]
Pushed the main behavior, will be adding full tests.

**Comment by jonathanolson** [comment]
@ariel-phet should this change be reviewed?

**Comment by pixelzoom** [comment]
The example in https://github.com/phetsims/axon/issues/197#issue-381406272 is not behaving as expected.  I'm still seeing ping-ponging and multiple consecutive calls to the same function. Example console output:

```
> viewProperty.value = 4
map: 0 -> 0
inverseMap: 4 -> 2
inverseMap: 4 -> 2
< 4

> viewProperty.value = 2
map: 2 -> 4
inverseMap: 2 -> 1.4142135623730951
inverseMap: 2 -> 1.4142135623730951
< 2

> viewProperty.value = 4.5
map: 1.4142135623730951 -> 2.0000000000000004
inverseMap: 4.5 -> 2.1213203435596424
inverseMap: 4.5 -> 2.1213203435596424
< 4.5

> modelProperty.value = 2
inverseMap: 4.5 -> 2.1213203435596424
map: 2 -> 4
map: 2 -> 4
< 2

> modelProperty.value = 2.1213203435596424
inverseMap: 4 -> 2
map: 2.1213203435596424 -> 4.499999999999999
map: 2.1213203435596424 -> 4.499999999999999
< 2.1213203435596424
```

**Comment by pixelzoom** [comment]
In all of the above examples, it looks like the first call (to map or inverseMap) is somehow related to the previous example.

**Comment by pixelzoom** [comment]
Discussed with @jonathanolson via Zoom.    The first and third calls in each example are actually done in `if` expressions internal to DynamicProperty, to prevent ping-ponging.  The second call is the only one that results in Property value assignment.    So this is working as expected, here and in Graphing Quadratics.   I feel like I've reviewed the code sufficiently, so closing.
