### ISSUE TITLE
Should we add PropertyIO.changeInitialValue or PropertyIO.reset?

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#198]
During https://github.com/phetsims/QA/issues/224 @KatieWoe pointed out it might be useful to change the initial value of Property instances so that reset works seamlessly.

Also, should PhET-iO clients be able to reset Properties?

**Comment by zepumph** [comment]
I could imagine a nice studio UI button for that too, like "reset"

**Comment by samreid** [comment]
`setInitialValue` sounds too much like it may be setting the current value to be the initial value.  Perhaps the method should be `changeInitialValue` or `changeResetValue`.

**Comment by zepumph** [comment]
One strategy would be to have the instance support this, but a general solution could be for phetioEngine to handle this. 

In phetioEngine as part of https://github.com/phetsims/phet-io/issues/1420 we began supporting something called "initialState"

What if each instance that supports this could also have something like "initial state" and we would be able to check against that, and "reset" accordingly. With this approach we don't have to dive into weirdness like in Screen.activeProperty (where all are initialized to false then the first screen is set to true, so its initialValue is still false). 

Instead the "initial value" would be defined by phet-io as when the sim has finished constructing. After all it is only phet-io that cares about this discrepancy. This also takes strain off of developers by removing another "gotcha" to think about.

**Comment by zepumph** [comment]
I don't see a need for this to be high priority. @samreid please change if you disagree.

**Comment by samreid** [comment]
It seems the proposals are for (a) a `changeResetValue(*)` on Property which can be used piecemeal or (b) a more global function that calls something like `changeResetValue()` on each Property with the current value as the reset value.  If we go with (b), we still need a way to hook into that, perhaps it could be automatically written as part of studio customization?  Anyways, I'm wondering if that would ever be the wrong thing to do.  The reset pattern we have documented isn't too clumsy--it's just not automatic, and not clear how it would work easily for multi-screen simulations.  I'll schedule this for discussion at a PhET-iO meeting.

**Comment by zepumph** [comment]
To me this falls into a category of "a feature that we could implement but I don't yet see a large use case." To this point, the way of resetting a Property is with the reset all button. Can we encourage the use of this until this feature is requested.

If we do want to do this:
I think of "this" as supporting a way to call "reset" on a Property from the wrapper.

The way to add this feature to the public api is to add a step to the instrumentation process that makes sure that either (a) Properties are created with an intelligent initial value or (b) are updated manually to be correct on startup. To me this seems like an incorrect cost, and not worth our time. I recommend tagging with labels "enhancement" and "deferred" and assigning until there is need.

**Comment by samreid** [comment]
Sounds good to me, thanks!

**Comment by zepumph** [comment]
I'm actually just going to close this issue. There is no reason to keep this around. If we need to add this functionality in the future, it will be from a trigger (other internal issue/client request/etc). Also I would like to note that our general philosophy is limiting the API to a specific of a feature set as possible. Closing.
