### ISSUE TITLE
Why does Events.off need to return the index?

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#199]
@samreid And I couldn't find any usages of the return value from `off` or `offStatic`. I think it would be good to double check with @jonathanolson before getting rid of it though.

**Comment by zepumph** [comment]
I used ` = (\w*\.){0,3}off(Static){0,1}\(` to search for usages.

**Comment by samreid** [comment]
There is some usage here:

https://github.com/phetsims/scenery/blob/0eaff198894fa9470c47d86dca082aa97f0b70c9/js/nodes/Node.js#L5121-L5130

```js
    offStatic: function offStaticOverride( eventName, listener ) {
      var index = Events.prototype.offStatic.call( this, eventName, listener );

      // Throw an error when removing a non-listener (except when the Node has already been disposed)
      if ( assert && !this.isDisposed ) {
        assert && assert( index >= 0, 'Node.offStatic was called but no listener was removed' );
      }
      this.onEventListenerRemoved( eventName, listener );
      return index;
    },
```

**Comment by samreid** [comment]
But in that case it would be equally good to return true or false, or maybe to have Events do its own assertion.  @jonathanolson what do you think?

**Comment by jonathanolson** [comment]
I'm fine with that feature being removed/changed, I don't remember using it. For Scenery, having strict error checking (fail on trying to remove a non-listener) would be nice.

**Comment by samreid** [comment]
Proposed fix is here.  I had to put a band-aid on one call site to prevent erroring.

**Comment by samreid** [comment]
Events was deleted in https://github.com/phetsims/scenery/issues/490, closing.
