### ISSUE TITLE
Can/should we consolidate options/config default value + documentation + assignment + validation?

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#202]
From conversation in https://github.com/phetsims/wave-interference/issues/275#issuecomment-450068968

I'd like to get feedback from other developers, so I'll mark this for developer meeting.  This is a long issue, so I'll summarize briefly here and again during dev meeting.

Please refer to how `_.extend({},config)` is used in wave-interference/js/common/model/Scene.js and area-model-common/js/common/model/Orientation.js.  In each case, the options object literal has all null values is more meant for developers + readability than for the computer.  For example, in Scene.js, the code would have the same runtime behavior if the 33 lines beginning with `config = _.extend( {` was deleted.  Normally I would say it is a good idea to eliminate 33 lines of code that does nothing, but this code was requested during code review for matching precedent with our options pattern.  I know we have a huge investment in the options pattern, but I'm interested in discussing a pattern that consolidates (default value + validation + assignment) instead of requiring them to be scattered.

**Comment by samreid** [comment]
We discussed this at developer meeting today.  Here are some raw notes.  Leaving self assigned to add more reflection before we move on:

JO: would be nice to quickly scan a file and see the ...
AccordionBox is quickly scannable and readable.

But maybe this belongs in documentation, not in a _.extends call.

It's too difficult to look into Validator.validate lines to see what all eth options are.

Concern about performance and memory.

It's nice to have documentation + validation + default + assignment together.
JO: I agree those are nice qualities too.
JB: It's nice to have those together, and I would get used to the alternative pattern.  We should not just use the prior pattern because we are used to it.
JG: I agree with JB
CK: The proposed pattern seems readable.
JG: I would need some time to get used to the new pattern.
JG: Would this work with our options nesting pattern?
	SR: It seem it would be the same with either.

**Comment by samreid** [comment]
What about when we need to call super(options) with an extended options?  In that case, we need to call `_.extend({},options)` anyways, right?

**Comment by samreid** [comment]
Issues like https://github.com/phetsims/phet-io/issues/1179#issue-243523424 mention garbage that is often created and thrown away when creating default option values.  But if we move to the pattern identified in Scene.js like this:

```js
// @public (read-only) {string} - units for this scene
this.translatedPositionUnits = Validator.validate( config.translatedPositionUnits, VALID_STRING );
```

Then we could also introduce a lazy option default like so:

```js
// @public (read-only) {Node} - title node
this.titleNode = Option.lazy( options.titleNode, ()=>new TitleNode('Hello!'),{valueType: Node} );
```

**Comment by samreid** [comment]
From today's developer meeting:

Conversation B: should we redo how we support options

MK: Middle ground is to leave _.extend(options) as it is, and use validator to combine like this:
    // @private - // {string} horizontal alignment of the content, 'left'|'center'|'right'
    this._contentAlign = Validator.validate(options.contentAlign,{validValues:['center','left','right']});

JO: As long as we have quickly scannable docs, either way is good.
CM: me too, I don't want to dig through code to see what config or options are.

Can move to documentation instead of 

Let's not go through common code and change everything at the moment.
Who else wants to be in the conversation on options patterns?
AP: I recommend MK, CM, SR, DB

**Comment by samreid** [comment]
See also #189

**Comment by pixelzoom** [comment]
> ... we are all accustomed to digging through code to see the `@public` interface.

You can use the Structure window/pane in Webstorm to view the API of a Javascript type or class.  It gives you a quick overview of the API, but it isn't aware of visibility annotations, so you do need to click on fields/methods to view their annotations in the source.  There is no similar support for options/config.

**Comment by samreid** [comment]
If the next versions of Webstorm and Sublime added a feature to show a consolidated view of all of the scattered config/options entries in a file, would we switch over to that pattern?

**Comment by pixelzoom** [comment]
Unlikely (I think) in general, since config/options is PhET specific, not idiomatic JS.

And even more unlikely to be added to something like Structure window.  Structure shows type/class structure, not argument values. options/config are argument values, not available until after instantiation.

**Comment by samreid** [comment]
What if PhET wrote a script that automatically consolidated information about config/options from current type + parent types?

**Comment by pixelzoom** [comment]
Sounds like a challenging script to write.  When would the script be run? Where would the "consolidated information" live?

**Comment by samreid** [comment]
Some possibilities:
(a) when the user presses a keystroke, it displays a popup with the relevant information for that file
(b) when the user presses a keystroke, it gathers the information and updates the corresponding JSDoc for that file

I'm not saying it would be an easy script to write, I'm trying to understand if we prefer the legacy options pattern because of a corresponding tooling deficiency or because it is truly a superior pattern.

**Comment by pixelzoom** [comment]
The description about says "user presses a keystroke, it displays a popup", and I suspect that means inside the IDE's Editor.  There's currently no requirement that a specific IDE must be used to do PhET development.  And I think that should continue to be the case.  So if you do investigate a script, I think we should make sure that it's not IDE-specific.   Or poll developers first to see how people feel about (for example) a solution that only allows WebStorm developers to see options/config API.

**Comment by samreid** [comment]
> I'm trying to understand if we prefer the legacy options pattern because of a corresponding tooling deficiency or because it is truly a superior pattern.

The script that was developed for automatically adding `require` statements is IDE-independent (though I don't know if anyone besides me and @zepumph use it at the moment), and we could choose to do something similar for this case.  Based on your remarks, it does sound like you do not prefer the legacy options pattern because it is an inherently superior pattern, and that improved tooling could help us transition to a pattern that consolidates default value + documentation + assignment + validation.  Please correct me if I'm wrong.

**Comment by pixelzoom** [comment]
I prefer the legacy pattern because it consolidates options/config and their documentation.  And that has benefits;  easier to code review, easier to use, and imo less costly in the long run.  Having to run a script to generate the consolidation is another step to be performed (and sometimes forgotten).   If you want to pursue that approach, go for it.

**Comment by samreid** [comment]
@Denz1994 can you please consider this issue as you prepare for the upcoming patterns meeting?

**Comment by samreid** [comment]
The proposal in the preceding comment looks really nice.  Perhaps we would rename `validate` to `required`?  Everything else seems to be going in a good direction.  However, I wouldn't want to finalize decisions here until we have an opportunity to discuss https://github.com/phetsims/phet-info/issues/122

**Comment by zepumph** [comment]
>The proposal in the preceding comment looks really nice. Perhaps we would rename validate to required? 

Moving this logic into object literal definitions passed to `merge` will not work in the general case. Unfortunately that will only validate the option default. So far, I can't think of a way in which that could apply to validating the passed in option, from the object passed to merge (i.e. BEFORE the merge step has occurred). 

My preference is that it is actually easier and simpler that have that after the merge, as merge is complicated and flexible in and of itself (with ordering and nesting to worry about). It seems like we should have a validation pattern that only cares about the finished product, and not intermediaries. 

An alternative thought is to just apply this to required params, which I think was discussed in the previous meeting. I would say that too should be nixed, as required params still suffer from merge overwritability.

**Comment by pixelzoom** [comment]
The approach shown in https://github.com/phetsims/axon/issues/202#issuecomment-549903553 is generally redundant:

```js
      config = merge( {
        numberOfSources: validate( config.numberOfSources, { validValues: [ 1, 2 ] } );
      }, config );
```

There's no need to do the `merge` because `numberOfSources` will already be set to the value of `config.numberOfSources`.  

This is equivalent:

```js
config = { 
  numberOfSources: validate( config.numberOfSources, { validValues: [ 1, 2 ] } );
};
```

@zepumph said:
> My preference is that it is actually easier and simpler that have that after the merge, as merge is complicated and flexible in and of itself (with ordering and nesting to worry about). It seems like we should have a validation pattern that only cares about the finished product, and not intermediaries.

I agree.  Validation after config is fully formed.

**Comment by Denz1994** [comment]
From our Core Hours meeting on 12/09/19:

Note the comment [here](https://github.com/phetsims/axon/issues/202#issuecomment-450897219), we decided that it is best for readability that the options should be combined in a single object instead of splitting into different statements.

Validation should come after the object merge call.
