### ISSUE TITLE
CT: value failed isValidValue: undefined

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#208]
https://github.com/phetsims/ph-scale-basics/issues/44, https://github.com/phetsims/circuit-construction-kit-dc-virtual-lab/issues/12, and https://github.com/phetsims/circuit-construction-kit-dc/issues/176 are all similar.  Moving them to this one issue.

Example of the failure in CT:

```
ph-scale-basics : fuzz : require.js-canvas : run
Uncaught Error: Assertion failed: value failed isValidValue: undefined
Error: Assertion failed: value failed isValidValue: undefined
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/assert/js/assert.js:22:13)
    at Object.validate (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Validator.js?bust=1546961076643:75:33)
    at Emitter.assertEmittingValidValues (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546961076643:80:21)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546961076643:190:72)
    at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery/js/input/SimpleDragHandler.js?bust=1546961076643:317:29)
    at Array.enabledObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/scenery-phet/js/FaucetNode.js?bust=1546961076643:277:23)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Emitter.js?bust=1546961076643:300:54)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Property.js?bust=1546961076643:228:29)
    at BooleanProperty.setValueAndNotifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Property.js?bust=1546961076643:210:14)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1546923822816/axon/js/Property.js?bust=1546961076643:143:16)
id: Bayes Chrome
Approximately 1/7/2019, 10:03:42 PM
```

Looks like something related to Validator, so assigning to @zepumph since he's been working on that.

**Comment by samreid** [comment]
@zepumph and I identified that the SimpleDragHandler end drag validation wasn't set up to support SimpleDragHandler.interrupt, we added that in the commit.  Fixed in local testing and closing.  Will reopen if Bayes CT says otherwise.

**Comment by samreid** [comment]
There is another problem that sometimes SimpleDragHandler is interrupted but does not have the object literal defined in `SimpleDragHandler.interrupt`.  This is because some clients are calling `SimpleDragHandler.endDrag()` with no args.  Instead, they should be calling `interrupt`.

**Comment by samreid** [comment]
I converted argless `endDrag` to use `interrupt` and tested it is working great for pH scale basics.  Leaving open a bit longer to see what CT says.

**Comment by pixelzoom** [comment]
>  some clients are calling SimpleDragHandler.endDrag() with no args. Instead, they should be calling interrupt.

For the record... Using `endDrag( null )` was the recommended workaround for interrupting SimpleDragHandler.  See for example https://github.com/phetsims/function-builder/issues/57 and https://github.com/phetsims/unit-rates/issues/168.   Is `interrupt` equivalent?

**Comment by pixelzoom** [comment]
> I converted argless endDrag to use interrupt ...

You did not convert `endDrag( null )`, which would presumably have the same problem?

**Comment by pixelzoom** [comment]
> I converted argless endDrag to use interrupt ...

You did not convert `endDrag( null )`, which was the recommended workaround, and would presumably have the same problem.

**Comment by samreid** [comment]
It looks like SimpleDragHandler clients should be using `SimpleDragHandler.interrupt` instead of `SimpleDragHandler.endDrag(null)`.  If you agree, I'm happy to convert function builder and unit rates.  If you disagree, perhaps we should hear from @jonathanolson?

**Comment by pixelzoom** [comment]
I don't know whether I agree or disagree, because I don't know if `end( null )` and `interrupt()` are equivalent.  The only guidance I've had in the past is to use `end( null )` as a workaround for ending a drag cycle.

**Comment by jonathanolson** [comment]
They are probably close enough to equivalent (the `interrupted` flag will be set on the listener during the callback), and it will end up creating a fake hack "synthetic" event instead of the lack of one, but I don't believe that would cause any problems in any current systems.

**Comment by pixelzoom** [comment]
I see 2 occurrences of `endDrag( null )`, identified in issues  phetsims/function-builder#57 and phetsims/unit-rates#168.  If you change those occurrences, please confirm that it behaves properly (which will likely require a multi-touch device), and note in those issues.

**Comment by zepumph** [comment]
I'm trying to keep up in this issue, so hang in there if this is redundant. 

Here is what the dragEndedEmitter validates like currently:
```
    this.dragEndedEmitter = new Emitter( {
      tandem: options.tandem.createTandem( 'dragEndedEmitter' ),

      argumentTypes: [
        { valueType: Vector2 },
        {
          isValidValue: function( value ) {
            return value === null || value instanceof Event ||

                   // When interrupted, an object literal is used to signify the interruption,
                   // see SimpleDragHandler.interrupt
                   ( value.pointer && value.currentTarget );
          }
        }
      ],
. . . 
```

So it will be ok with null, but not with undefined (hence the issues above). I'm not sure why/if we need to support null here, especially if it is preferred to use `interrupt` instead of calling `endDrag(null)` directly.

Should we remove the acceptance of `value=== null` here?

**Comment by pixelzoom** [comment]
I have to bow out of this issue. I simply don't have time, and I have no background on what changed in SimpleDragHandler (and why) to introduce this problem.  Carry on, but please verify that any changes to drag sequence interrupt continues to work properly in my sims.

**Comment by pixelzoom** [comment]
I will add that `endDrag( null )` felt like a smelly workaround from the very beginning.  So if you want to change to `interrupt`, I support that.

**Comment by samreid** [comment]
> If you change those occurrences, please confirm that it behaves properly (which will likely require a multi-touch device), and note in those issues.

Can you please provide instructions of how to trigger this issue using multi-touch?  Preferably one step would be to comment out `endDrag(null)`, then some instructions about how to trigger the error on a multitouch device and some exception is thrown?  After we know how to test use case in FB and UR we can take it from there.

**Comment by pixelzoom** [comment]
> Can you please provide instructions of how to trigger ...

Drag something that has a SimpleDragHandler attached, press the Reset All button, verify that the thing you were dragging is not still dragging.

**Comment by pixelzoom** [comment]
FYI... Over in https://github.com/phetsims/function-builder/issues/57#issuecomment-443337954, I noted that `endDrag` can be replaced with `interruptSubtreeInput` on the target node. I think that's preferable to replacing `endDrag` with `interrupt`.

**Comment by pixelzoom** [comment]
I said:
> I see 2 occurrences of endDrag( null ), identified in issues phetsims/function-builder#57 and phetsims/unit-rates#168. ...

Those occurrences have been converted to `interruptSubtreeInput`. 

I now see zero occurrences of `endDrag( null )` in PhET code.

@samreid anything else to do here?

**Comment by zepumph** [comment]
Using `endDrag\( ` I still see three usages of `this.dragHandler.endDrag( null /* event */ );`. (Weird!)

**Comment by pixelzoom** [comment]
@zepumph I'm not finding those three usages. Can you point me to them?

**Comment by zepumph** [comment]
Is there anything else to do here @samreid?

**Comment by pixelzoom** [comment]
We're just shy of 1 year on requesting whether there's anything else to do here.  It looks to me like the answer is "no", so I'm going to close this issue.
