### ISSUE TITLE
Multilink caches stale values

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#210]
Related to https://github.com/phetsims/axon/issues/141 and https://github.com/phetsims/phet-io-wrappers/issues/229 and #209 

Today @zepumph and @chrisklus and I identified that Multilink is caching stale values, and those values are being used in callbacks.  This used to be a problem with DerivedProperty as well, which was corrected in https://github.com/phetsims/axon/issues/146.  We would like to use the same strategy for Multilink.

**Comment by zepumph** [comment]
@pixelzoom could you please review this issue as it relates to how we get dependency values in DerivedProperty. Anything amiss here?

**Comment by pixelzoom** [comment]
I don't see anything amiss in https://github.com/phetsims/axon/commit/580374983847fb1f603766b254d902701a5305e4.  Looks like a worthwhile change.
