### ISSUE TITLE
Convert emit1, emit2, emit3 to emit

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#211]
From #182 @zepumph @chrisklus and noted we need to iterate through all usages of emit1, emit2 and emit3 and convert them to use emit.  This will require adding `argumentTypes` or equivalent (may be renamed soon in #212).  This should be done after #204 is complete, since it could change the API.

**Comment by zepumph** [comment]
All usages of emit1, emit2, and emit3 have been removed. we used the `validationEnabled` option to bypass validation in almost all instances (some easy ones were converted as I went). See #227 for steps to remove that option. 

There are no longer deprecated emit methods in Emitter. @samreid please review.

**Comment by samreid** [comment]
I reviewed `Emitter` and spot checked a few sim commits, it all looks great.  Thanks @zepumph.  This issue seems good to close and we will continue in https://github.com/phetsims/axon/issues/227
