### ISSUE TITLE
Convert Property to ES6

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#213]
It would be good to convert Property and its subclasses to ES6.  We already converted Emitter to ES6 as part of work in https://github.com/phetsims/axon/issues/182

**Comment by samreid** [comment]
I converted Property and its subclasses to ES6, tested lint is passing, tested local aqua is passing.  Committing.  I apprised slack:

> AXON/Property and its subclasses will be converted to ES6 as part of https://github.com/phetsims/axon/issues/213, many commits expected shortly.

**Comment by samreid** [comment]
@zepumph can you please do a spot check review?  Probably doesn't need to be exhaustive, but would be good to know if I've missed anything critical.

**Comment by zepumph** [comment]
How was https://github.com/phetsims/expression-exchange/commit/e3634ce32656b2ddb36ae04051316561b85dc96d not causing tons of errors before? Good find!

**Comment by zepumph** [comment]
Should this TODO in graphing-lines come with an issue?

>TODO: Shouldn't this be accomplished by adding the first listener to a Property?

**Comment by zepumph** [comment]
It's really annoying that we loose the git history for the constructor in all of these functions:

![image](https://user-images.githubusercontent.com/6856943/51407990-d5f88380-1b09-11e9-9cf3-63497edef17e.png)

Is there any way around it?

**Comment by samreid** [comment]
That is an unfortunate artifact of the GitHub diff viewer.  Other viewers do not suffer from that problem:

![image](https://user-images.githubusercontent.com/679486/51408087-e2d1a300-1b1a-11e9-9592-9f155d2d8081.png)

**Comment by zepumph** [comment]
>Re #213 (comment), If you look at the diff of Property, we basically lost all git history in that commit (8330cdd#diff-a24406f5f2879d5846b0ae23318df8d3). It is enough that I am very close to recommending to revert the commit for axon to see if there is a way that we can get git to recognize these changes a bit nicer. I'm not sure what exactly the history for Property and its subtypes are worth in AXON, but I think it is a bit more investigation before calling this issue one and done.

Nevermind about this whole comment, I did my review on github only, and didn't see https://github.com/phetsims/axon/issues/213#issuecomment-455657171 until after posting. On WebStorm I'm able to see the git history. Please disregard this point.

**Comment by samreid** [comment]
I moved the static functions to the class declarations, anything else to do here before closing?

**Comment by zepumph** [comment]
Looks good to me

**Comment by pixelzoom** [comment]
Reopening.  In https://github.com/phetsims/axon/commit/8330cdd40aba1042af2ccd519b21f6713c1b0f5d, @samreid added this TODO, which was not addressed and has no associated GitHub issue:

```js
82  // TODO: should be handled in the super
```

**Comment by pixelzoom** [comment]
Moved TODO issue to https://github.com/phetsims/axon/issues/247.
