### ISSUE TITLE
Emitter .apply() calls should use null instead of this

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#216]
Discovered in https://github.com/phetsims/scenery/issues/928, For unknown reasons `Emitter` is passing `this` for the `apply` calls.  I discovered this led to a problem in SimpleDragHandler which was incorrectly using `this` instead of `self`.

**Comment by samreid** [comment]
I fixed the main problem with this, but there are still several other occurrences that will need attention.

**Comment by samreid** [comment]
I fixed the validation case.  The other site that is implicitly using `this = Emitter` for callbacks are `emit1, emit2 and emit3` which are deprecated.  So perhaps that's all we need for this issue.  @zepumph are you available to double check that this change is reasonable?

**Comment by zepumph** [comment]
These changes look good.

I also agree that it doesn't make sense to change deprecated methods from something like:

`          this.activeListenersStack[ lastEntry ][ i ]( arg0, arg1, arg2 );`

to

`          this.activeListenersStack[ lastEntry ][ i ].call( null, arg0, arg1, arg2 );`

Hopefully we can update usages soon.
