### ISSUE TITLE
Emitter dispose issues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#220]
`Emitter` is an ES6 class.  Current implementation of `dispose`:

```js
    /**
     * Dispose an Emitter that is no longer used.  Like Property.dispose, this method checks that there are no leaked
     * listeners.
     */
    dispose() {
      this.first = null;
      this.last = null;
      this.listeners.length = 0; // See https://github.com/phetsims/axon/issues/124
      PhetioObject.prototype.dispose.call( this );
    }
```

Problems:

(1) Should be chaining to `super.dispose`.

(2) Missing visibility annotation.

(3) Missing `@override` annotation.

(4) Doc says "Like Property.dispose, this method checks that there are no leaked listeners." I see no evidence of that here. Is that vestigial doc?

**Comment by pixelzoom** [comment]
Doc says "Like Property.dispose, this method checks that there are no leaked listeners."  I see no evidence of that here.  Is that vestigial doc?

**Comment by samreid** [comment]
Committed (1)-(3) above.

> (4) Doc says "Like Property.dispose, this method checks that there are no leaked listeners." I see no evidence of that here. Is that vestigial doc?

Maybe it means it removes its references to the listeners?

**Comment by pixelzoom** [comment]
The doc was added with the first implementation of `dispose` in https://github.com/phetsims/axon/commit/5ccb60d1b7058a3afdbc641f8b8148dcad6089f3, see below.   So it's definitely vestigial - it was checking via an assertion, and now it's not checking.   So I'm going to modify the doc.

```js
    /**
     * Dispose an Emitter that is no longer used.  Like Property.dispose, this method checks that there are no leaked
     * listeners.
     */
    dispose: function() {
      assert && assert( !this.hasListeners(), 'Listeners should have been removed before disposal' );
    },
```

**Comment by pixelzoom** [comment]
@samreid please review, feel free to close or modify.
