### ISSUE TITLE
Add assertions that Property subtypes are used

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#225]
From https://github.com/phetsims/axon/issues/221

> 3. Add an assertion to Property that requires the proper subtype of Property is used (for Color, Vector2, Number, String, Boolean) based on the initially supplied Property value.  Not exactly sure how this will work because the straightforward implementation (instanceof check for Property subtype in Property) would introduce a loop in the module loading.

**Comment by samreid** [comment]
@pixelzoom replied in https://github.com/phetsims/axon/issues/221#issuecomment-466461806

> Unless there's a straightforward implementation of (3), I would be inclined to skip it and address during code review and PhET-iO instrumentation. That seems to be working for the current Properties subclasses.

**Comment by samreid** [comment]
I think there will be a straightforward implementation--something like:

```js
assert && assert (initialValue instanceof dot.Vector2 === this instanceof dot.Vector2Property)
....
```

However, I'm concerned there will be many sites to address (not sure how many or how to easily count them all.)

**Comment by samreid** [comment]
This patch works well in practice: 

```js
Index: js/Property.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/Property.js	(revision d032a83f14fdb36c98adbf471dee6966e319c0fe)
+++ js/Property.js	(date 1577827616143)
@@ -140,6 +140,10 @@
 
         // validate the initial value
         this.validate( value );
+
+        if ( value instanceof phet.dot.Vector2 && !( this instanceof phet.axon.DerivedProperty ) ) {
+          assert && assert( this instanceof phet.dot.Vector2Property, 'Vector2 should use Vector2Property' );
+        }
       }
     }
 
```

I was concerned about the module loading order (like maybe phet.dot.Vector2 or phet.axon.DerivedProperty aren't defined at that time), but if all modules are loaded before we construct our first Property that wouldn't be a problem.  But what if a `new Property` is constructed statically (outside of `main`)?  Then this could fail.

@zepumph what do you think about this issue?

**Comment by zepumph** [comment]
I think that this is worth proceeding with, because it seems complete and straight forward (hopefully not too much grunt work in up converting old usages). 

Thoughts:
* Though assertions like these are helpful, they wouldn't cover all cases, like if a `Property.<Vector2|null>` was passed null to begin with. Does Vector2Property even allow `null`?
* Also do we worry about false positives, what if a `Property.<Vector2|boolean>` is passed a Vector2 to begin with but then will want to set to a boolean later. Is that even allowed?
* To guard against module loading, we could only test if we have access to the other namespace. Presumably we wouldn't need to test that axon exists, only other libraries:

```js
if ( _.hasIn( 'phet.dot', window) && value instanceof phet.dot.Vector2 && !( this instanceof phet.axon.DerivedProperty ) ) {
          assert && assert( this instanceof phet.dot.Vector2Property, 'Vector2 should use Vector2Property' );
        }

```

**Comment by samreid** [comment]
Maybe this will be easier now we have ES6 modules and cycles?

**Comment by samreid** [comment]
I tried this patch again, and ES6 module loading doesn't help because it creates loops and cannot load.  Also, `assert && assert( this instanceof phet.dot.Vector2Property,` fails because in some cases `Vector2Property` hasn't been loaded by the time this code runs.  I'm also concerned about the corner cases @zepumph raised above.  If we even have one case of `Property<Vector|null>` we will need a way to opt out of the checking.  Or maybe this would be a transient strategy (or enabled temporarily with a query parameter during code review)?

@zepumph and/or @pixelzoom how do you recommend to proceed?

**Comment by pixelzoom** [comment]
In addition to using the correct Property subclass, there are other aspects to this issue - like using appropriate validation options - that are even more difficult to catch automatically.  Imo, this should be second-nature for PhET developers, and we shouldn't need to be writing code to make sure they're doing this.   So I recommend that we bail on this issue, and continue to flag it manually via CRC. In the worst case, we'll have to convert when doing PhET-iO instrumentation.

**Comment by zepumph** [comment]
>So I recommend that we bail on this issue, and continue to flag it manually via CRC. In the worst case, we'll have to convert when doing PhET-iO instrumentation.

Sounds good to me!
