### ISSUE TITLE
Remove most or all {validationEnabled: false}

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#227]
As part of #211 @zepumph and I are converting from `emitN` to `emit`.  These sites have not been previously validated and during the port we have added `{validationEnabled: false}`, but the default for `emit` is to validate the emitted values and it will be nice to add the correct validators for these emitters.

There are 52 usages of `{validationEnabled: false}` in many repos. Ideally these sites would be validated by passing in a `validators` argument with the appropriate `validator` object for each arg that the Emitter emits. I will handle common code (with @samreid), as there may be a few spots where we choose to keep validation disabled. Marking for dev meeting to make all aware. Feel free to unassign when completed with your repos. 

- [x] axon @zepumph
- [x] build-a-molecule @jonathanolson
- [x] capacitor-lab-basics @jonathanolson
- [x] circuit-construction-kit-common @samreid
- [x] equality-explorer @pixelzoom
- [x] expression-exchange @jbphet
- [x] forces-and-motion-basics @jessegreenberg
- [x] function-builder @pixelzoom
- [x] gravity-and-orbits @jessegreenberg
- [x] griddle @zepumph
- [x] make-a-ten @jonathanolson
- [x] masses-and-springs @Denz1994
- [x] molecules-and-light @jessegreenberg
- [x] pendulum-lab @jonathanolson
- [x] phet-io @zepumph
- [x] plinko-probability @pixelzoom
- [x] rutherford-scattering @jessegreenberg
- [x] scenery-phet @zepumph
- [x] scenery @zepumph
- [x] sun @zepumph
- [x] tambo @jbphet	
- [x] unit-rates @pixelzoom

EDIT from MK:
## How to convert:

In general you can just follow the below commits as reference, but there are a few key edge cases to note

### Arrays:
To specify a validator for an Array (while https://github.com/phetsims/axon/issues/195 is being worked on), make a validator like:
```
{
     valueType: Array,
     isValidValue: array => _.every( array, value => value instanceof {{TYPE}} )
}
```

### Type|null

And for types that are `{null|Type}` (while https://github.com/phetsims/axon/issues/228 is sorted out), use:
```
{ isValidValue: value => value instanceof {{TYPE}}|| value === null  }
```

### phet-io instrumented Emitters:

NOTE: we don't support the `validators` option if also passing in a phetioType. See https://github.com/phetsims/axon/commit/949905e8f97d0d3b65251e11a7d8412ae95d613b for documentation.

UPDATE:
A final checkbox for cleanup from @samreid's comment lower in this issue

- [x] Reminder to remove the deprecated parts from Emitter once this issue is complete.

**Comment by zepumph** [comment]
There are 52 usages of `{validationEnabled: false}` in many repos. Ideally these sites would be validated by passing in a `validators` argument with the appropriate `validator` object for each arg that the Emitter emits. I will handle common code (with @samreid), as there may be a few spots where we choose to keep validation disabled. Marking for dev meeting to make all aware. Feel free to unassign when completed with your repos. 

- [ ] axon @zepumph
- [ ] build-a-molecule @jonathanolson
- [ ] capacitor-lab-basics @jonathanolson
- [ ] circuit-construction-kit-common @samreid
- [ ] equality-explorer @pixelzoom
- [ ] expression-exchange @jbphet
- [ ] forces-and-motion-basics @jessegreenberg
- [ ] function-builder @pixelzoom
- [ ] gravity-and-orbits @jessegreenberg
- [ ] griddle @zepumph
- [ ] make-a-ten @jonathanolson
- [ ] masses-and-springs @Denz1994
- [ ] molecules-and-light @jessegreenberg
- [ ] pendulum-lab @jonathanolson
- [ ] phet-io @zepumph
- [ ] plinko-probability @pixelzoom
- [ ] rutherford-scattering @jessegreenberg
- [ ] scenery-phet @zepumph
- [ ] scenery @zepumph
- [ ] sun @zepumph
- [ ] tambo @jbphet	
- [ ] unit-rates @pixelzoom

**Comment by pixelzoom** [comment]
No idea how to begin. Can you please provide a concrete example?

**Comment by samreid** [comment]
I addressed this for circuit-construction-kit-common in the aforementioned commit.

**Comment by ariel-phet** [comment]
As of Feb 28 2018 1 of these was done

**Comment by pixelzoom** [comment]
Conversion of my sims from `validationEnabled: false` to `validators: [...]` is done. Sims were tested with `?ea&fuzz`.

**Comment by Denz1994** [comment]
MAS has been taken care of. A similar test was done using `?ea&fuzz` and testing the exact case where emit is called.

**Comment by samreid** [comment]
Reminder to remove the deprecated parts from Emitter once this issue is complete.

**Comment by jbphet** [comment]
Conversion of my sims is done.  I tested by inducing situations that I knew would fire the emitter, and all looked good.  Unassigning myself.

**Comment by samreid** [comment]
38 occurrences to go

**Comment by samreid** [comment]
Around 16 left to go.

**Comment by jessegreenberg** [comment]
`validationEnabled: false` has been removed from sims assigned to me.

**Comment by zepumph** [comment]
I'll take it from here! Thanks all!

**Comment by zepumph** [comment]
The deprecated option and all usages have now been removed. Thank you all! Closing
