### ISSUE TITLE
Document how to pass a validator to a phet-io instrumented Emitter

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#229]
We have put a lot of work into making sure that you don't pass `validators` and `phetioType` to Emitter. @samreid where do you think the best place to add documentation about how to pass `validators` through to Emitter through the EmitterIO? I could see it in the `How to instrument` docs, but to me it seems a little bit far from the implementation. 

We could put it in EmitterIO, and then rely on this assertion to bring people over there:
```
      assert && assert( !( phetioTypeSupplied && validatorsSupplied ),
        'use either phetioType or validators, not both, see EmitterIO to set validators on an instrumented Emitter'
      );
```

**Comment by samreid** [comment]
That seems like it will work well.

**Comment by zepumph** [comment]
I'll implement
