### ISSUE TITLE
Property has no unlinkAttribute

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#23]
This came up in acid-base-solutions.AcidBaseSolutionsAbstractModel, where observers are rewired when the solution changes.  We'd like to use linkAttribute to link to strength and concentration, but there is no unlinkAttribute. So the implementation resorts to using functions.

**Comment by samreid** [comment]
For symmetry, I think we should add unlinkAttribute, which just calls unlink.

**Comment by samreid** [comment]
something like this:

```js
    /**
     * Unlink a listener added with linkAttribute.  Note: the args are asymmetric, and you must pass the listener
     * rather than object and attributeName
     * @param listener
     */
    unlinkAttribute: function( listener ) {
      this.unlink( listener );
    },
```

**Comment by samreid** [comment]
@pixelzoom what do you think about the above API.  Is it acceptable that the args are different?  Not sure of a technical way around it.

**Comment by pixelzoom** [comment]
API proposal looks OK. Does the proposal to remove the property('name') API affect this See https://github.com/phetsims/axon/issues/43

**Comment by pixelzoom** [comment]
This also seems related: https://github.com/phetsims/axon/issues/44

**Comment by pixelzoom** [comment]
@samreid Presumably what you've proposed above is for Property. Note that PropertySet has the same issue - it has linkAttribute, but no unlinkAttribute.

**Comment by samreid** [comment]
OK, in this issue let's add unlinkAttribute in Property.js and PropertySet.js and we can tackle the other work in #44 and #43

**Comment by samreid** [comment]
Fixed above, would you like to take a look @pixelzoom?

**Comment by samreid** [comment]
Note that my implementation uses PropertySet.property() which is marked for deprecation in another issue.  Perhaps useful to keep this method for internal private use in PropertySet (or rename to _property()).  We'll address that issue in #43

**Comment by pixelzoom** [comment]
This was resolved in some other issue.
