### ISSUE TITLE
Disallow passing Emitter a phetioType with no args

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#230]
Since by default the phetioType is `EmitterIO( [] )`, we shouldn't allow clients to also pass in a different instance of that same parametrized type.

**Comment by zepumph** [comment]
Hey I'm also going to add a few emitterIO tests here. . .

**Comment by zepumph** [comment]
@samreid please review.

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
