### ISSUE TITLE
need a better API for specifying "null is a valid value"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#231]
If `null` is a valid value for a Property, then using type-specific Properties is out of the question, and I have to resort to this boilerplate:

```js
const someProperty = new Property( initialValue, {
  isValidValue:  value => ( value instanceof SomeType || value === null ),
  phetioType: NullableIO( SomeTypeIO )
} );
```

I see 165 occurrences of regex `Property.<.*\|null` in PhET code, so this is a common scenario.

Can validator.js and Property APIs support a simple way of specifying that `null` is a valid value? Something that makes the above boilerplate unnecessary?

**Comment by samreid** [comment]
I believe @pixelzoom proposed `valueType: [SomeType, null]` for cases like that.  @zepumph or @pixelzoom does that ring a bell?

**Comment by pixelzoom** [comment]
That rings a bell, but I can't find the issue where I proposed that (if one exists).

**Comment by pixelzoom** [comment]
Ah, here it is: https://github.com/phetsims/axon/issues/228#issuecomment-468490581.  So I'm going to close this as a duplicate issue.
