### ISSUE TITLE
what should an {Object} validator look like?

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#232]
In ObjectIO I used `{ isValidValue: instance => instance !== null && typeof instance === 'object' }`

which feels good to me, but I don't really want to copy that around the project.

What if we made a method like:
```js
    /**
     * Get the validator for testing if something is an object,
     * @returns {ValidatorDef}
     */
    ValidatorDef.getObjectValidator =  () => {
      return { isValidValue: instance => instance !== null && typeof instance === 'object' };
    };
```

Also would be good to note that I currently see multiple usages of `valueType: Object` around the project, which I don't think is complete, but maybe it is. I can't seem to see any false positives/negatives with null/undefined/'' etc.

Should we use `valueType: Object`?

**Comment by pixelzoom** [comment]
Recommended to use `value` instead of `instance` in:

`{ isValidValue: value => value !== null && typeof value === 'object' }`

More generally, what's the motivation for this issue? I'm not clear on what problem we're trying to solve.

**Comment by samreid** [comment]
@zepumph is this covered by https://github.com/phetsims/axon/issues/228?

**Comment by zepumph** [comment]
>valueType: 'object' seem reasonable to me.

Note: 
![image](https://user-images.githubusercontent.com/6856943/54067739-65f4a880-41f0-11e9-8fe5-4f9e5779427b.png)

Let's go with `valueType: Object`. I'll update ObjectIO and document in `ValidatorDef`.

**Comment by zepumph** [comment]
@pixelzoom the goal of this issue was to establish what the preferred validator is when trying to accept any `Object`. Would you mind reviewing?

**Comment by pixelzoom** [comment]
I'd be happy to review.  Will try to get to it on Monday 3/11/19.

**Comment by pixelzoom** [comment]
I reviewed the commits, looks good to me.   Closing.
