### ISSUE TITLE
Factor out Property subtype assertions about validatorKeys

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#236]
Seeing the following chunk in BooleanProperty looks inefficient, and like there will be many duplications. 

```js
      assert && assert( !options || !options.hasOwnProperty( 'isValidValue' ), 'isValidValue is not supported by BooleanProperty' );
      assert && assert( !options || !options.hasOwnProperty( 'validValues' ), 'validValues is not supported by BooleanProperty' );
      assert && assert( !options || !options.hasOwnProperty( 'valueType' ), 'valueType is set by BooleanProperty' );
```

Can we add something like this to ValidatorDef instead, so that if we added another key, we wouldn't need to touch multiple spots?

Maybe something like
`ValidatorDef.assertNoValidatorKeys( options )`

**Comment by pixelzoom** [comment]
How about something that isn't specific to validation options?  For example, to replace:

```js
assert && assert( options.fill, 'MyClass sets fill' );
assert && assert( options.children, 'MyClass sets children' );
```

**Comment by pixelzoom** [comment]
On second thought... 

(1) I think I prefer the individual `assert` statements, since the messages can be very specific, and it's very clear what's going on.    

(2) The current assertions in (e.g.) BooleanProperty don't really bother me -- I think the clarity and specificity of the assertion is worth any duplication.

(3) `ValidatorDef.assertNoValidatorKeys( options )` will not work. Different type-specific Properties disallow the use of different validation-related options.   Compare BooleanProperty and NumberProperty. 

So I don't think this is worth pursuing.

**Comment by zepumph** [comment]
>Different type-specific Properties disallow the use of different validation-related options

Ahh so in NumberProperty, we allow `validValues` to be specified, like in `this.screenIndexProperty`:

```js
 this.screenIndexProperty = new NumberProperty( options.screenIndex, {
      tandem: Tandem.generalTandem.createTandem( 'screenIndexProperty' ),
      phetioFeatured: true,
      phetioDocumentation: 'Indicates which screen is selected (0-indexed)',
      validValues: _.range( 0, screens.length ),
      numberType: 'Integer'
    } );
```

This makes sense. I guess I misunderstood a particular piece of previous discussion, I think involving {Property.<Vector2|null>.  There we said that this sub-Property Type should not use `Vector2Property`, which makes sense because `null` is not of Type `{Vector2}`, but `NumberProperty` isn't allowing overriding of the `valueType` validator key, and instead just providing further constraint on the "number" with `validValues` and `isValidValue`.


>ValidatorDef.assertNoValidatorKeys( options ) will not work

It would work for `BooleanProperty` though right?  I think it is clearer than individual assertions, because it is stating the underlying purpose of these three assertions. We also would not have to refactor if (when?) we add another validator key.

>since the messages can be very specific

We could add key specific messages to a general method in ValidatorDef?


I know there is a philosophy in coding that you shouldn't automate until the second or third, xth time you encounter something (and not the FIRST like here), but I'm still inclined to create something like this under the assumption that it will be used in multiple places in the future.


I guess I'm also trying to facilitate a paradigm shift in Property where we stop thinking of these as individual options, but instead as Property options "mixing in" validator keys as optional keys to pass through with options.

If there is consensus against my thought process from here we should move on and close this issue without action. I'm happy to go with the group here!

**Comment by pixelzoom** [comment]
> We could add key specific messages to a general method in ValidatorDef?

Then you'll end up with something that's just about the same as the assertions. And imo, less readable, less clear.  So my vote would be no change. The assert pattern is obvious and ubiquitous. But if others feel differently, knock yourselves out.

**Comment by zepumph** [comment]
I think this has been thoroughly discussed. It is decided to keep it as is, we can always factor things out later if it becomes more obvious or there are many more usages.
