### ISSUE TITLE
no issue for TODO in NumberProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#237]
Encountered while working on https://github.com/phetsims/axon/issues/234. 

In https://github.com/phetsims/axon/commit/8330cdd40aba1042af2ccd519b21f6713c1b0f5d, @samreid added a TODO in NumberProperty:

```js
    set( value ) {

      // TODO: should be handled in the super
      this.assertNumberPropertyValidateValue && this.assertNumberPropertyValidateValue( value );
      super.set( value );
    }
```

Please create an associated issue and reference it with the TODO.

**Comment by samreid** [comment]
I opened https://github.com/phetsims/axon/issues/253 for this, closing.
