### ISSUE TITLE
ValidatorDef valueType key should handle Enumeration

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/axon#238]
We added an example to ValidatorDef that describes an Enumeration.

```js
/**
 * A validator that accepts Enumeration values:
 * { validValues: MyEnumeration.VALUES }
 * NOTE: {valueType: MyEnumeration } would be ideal, but it is currently not supported.
*/
```

This would be a nice enhancement.

**Comment by pixelzoom** [comment]
This seems straightforward to add.  In ValidatorDef `isValidValue `, add this `else if` clause:

```js
        else if ( valueType instanceof Enumeration && valueType.includes( value ) ) {
          assert && assert( false, 'value is not a member of Enumeration ' + valueType );
          return false;
        }
```

**Comment by pixelzoom** [comment]
Support and unit tests for `valueType: {Enumeration}` were added in the above commits, and used in `EnumerationProperty`.  @zepumph please review.

**Comment by zepumph** [comment]
Looks good. Thank you.
