### ISSUE TITLE
create EnumerationProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#239]
Related to https://github.com/phetsims/axon/issues/221, the need for additional type-specific Properties...

Since I've started using `PHET_CORE/Enumeration`, I've found that an Enumeration is often specific to a Property.  And like `NumberProperty` and its associated `range`, it would be nice to have `EnumerationProperty` with an associated `Enumeration`. 

I'm going to take a stab at creating `EnumerationProperty`, and use it immediately in Gas Properties.

**Comment by pixelzoom** [comment]
Hmmm.. First dilemma is where to put `EnumerationProperty`.  When we created `Vector2Property`, we decided to put it in the same repo (dot) as `Vector2`.   But I don't think I can put `EnumerationProperty` in phet-core with `Enumeraton`, since phet-core cannot depend on axon.

**Comment by pixelzoom** [comment]
`EnumerationProperty` is currently living in (and used by) gas-properties. 

@samreid @jonathanolson opinions on where it should live?

**Comment by pixelzoom** [comment]
Slack dev-public channel, 3/22/19:

Chris Malley [6:33 PM]
I’m creating `EnumerationProperty`.  Based on previous convention, it should live in phet-core with `Enumeration`.  But that would make phet-core depend on axon.  So is it OK to put `EnumerationProperty` in axon?

Sam Reid [6:49 PM]
Yes, I think so. We shouldn’t introduce a phet-core to axon dependency
I believe that’s why we chose to put timer in axon

Chris Malley [6:53 PM]
So leave Enumeration and EnumerationIO in phet-core and put EnumerationProperty in axon?

Sam Reid [7:08 PM]
I’m away from my computer so can’t double check everything but that sounds right

**Comment by pixelzoom** [comment]
@samreid @zepumph since you are assigned to review other type-specific Properties, could you please review this one at the same time?

**Comment by zepumph** [comment]
Besides my note at the end of https://github.com/phetsims/axon/issues/234#issuecomment-477736911, this all looks great.
