### ISSUE TITLE
Create ActionIO

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#241]
From https://github.com/phetsims/axon/issues/222#issuecomment-482625165

> Create ActionIO? Or will that be too complex to have one parametric IO type subtype another parametric IO type?

**Comment by zepumph** [comment]
Added above by @samreid and @zepumph. So far things are working well. Closing, with some review to be had in #222.

**Comment by pixelzoom** [comment]
Reopening.  There is a TODO in EmitterIO that was not addressed:

```js
86       validators: validators,  // TODO: https://github.com/phetsims/axon/issues/241 Can this be supplied by the parent?
```

**Comment by zepumph** [comment]
Today @jessegreenberg showed us that ActionIO still has an `addListener` function. We should clean up ActionIO/EmitterIO.

**Comment by samreid** [comment]
Corrected in ActionIO.js and I ran `grunt update` everywhere.  Local testing appears OK.  @zepumph can you please check this commit and the one in EmitterIO?  Close if all is well.

**Comment by zepumph** [comment]
I reviewed the changes, couldn't find any more TODOs in Action(IO)/Emitter(IO), updated some type docs for TypeIOs. Things look good here. I'm ready to close.
