### ISSUE TITLE
TODO: This should be a NumberProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#246]
In https://github.com/phetsims/axon/commit/24ad552b53624d16c6760a604ebffa9f7366b553, @samreid added this TODO.  Please address it, or create an associated GitHub issue.

PropertyTests:
```js
234 const phetioType = PropertyIO( ObjectIO ); // TODO: This should be a NumberProperty
```

**Comment by samreid** [comment]
Fixed in the commit, closing.
