### ISSUE TITLE
TODO: should be handled in the super

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#247]
In https://github.com/phetsims/axon/commit/8330cdd40aba1042af2ccd519b21f6713c1b0f5d, @samreid added this TODO. Please address or create an associated GitHub issue.

NumberProperty:
```js
82  // TODO: should be handled in the super
```

**Comment by pixelzoom** [comment]
Another TODO that was added in the same commit, DerivedProperty:

```js
124     * TODO: is this still necessary?
```

**Comment by samreid** [comment]
The former TODO is covered in https://github.com/phetsims/axon/issues/237

**Comment by samreid** [comment]
After reading remarks in https://github.com/phetsims/axon/issues/171, I'm inclined to remove the other TODO.
