### ISSUE TITLE
Multilink and DerivedProperty should not allow duplicate dependencies

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#250]
Discovered while working on https://github.com/phetsims/gravity-force-lab-basics/issues/128. 

Right now this "feature" doesn't seem to be used, at least checking via slack. 

I also added an assertion like:
`    assert && assert( _.isEqual( dependencies, _.uniq( dependencies ) ), 'duplicate dependencies' );`

to DerivedProperty and Multilink and ran aqua fuzzing with no errors. With this in mind I'm going to commit these changes, and then clean up any issues that may come from this.

**Comment by zepumph** [comment]
Assigning to myself to look at ct in a few hours, then pass off to review.

**Comment by samreid** [comment]
https://stackoverflow.com/questions/28461014/using-lodash-to-check-whether-an-array-has-duplicate-values recommends checking array length via `_.uniq(a).length !== a.length`, that seems like it could avoid some hassles/headaches with _.isEqual corner cases.

**Comment by jonathanolson** [comment]
Looks like I'm running afoul of this in proportion-playground, but only conditionally:

```js
  PaintChoice.getActiveColorProperty = function( paintChoiceProperty, side ) {
    var dependencies = [ paintChoiceProperty ].concat( PaintChoice.CHOICES.map( function( paintChoice ) {
      return paintChoice.getColorProperty( side );
    } ) );

    return new DerivedProperty( dependencies, function() {
      return paintChoiceProperty.value.getColorProperty( side ).value;
    } );
  };
```

Should I wrap a `_.uniq` around it? Noticed in https://github.com/phetsims/proportion-playground/issues/106.

**Comment by zepumph** [comment]
@samreid implemented above. @jonathanolson that sounds like the right approach.

**Comment by zepumph** [comment]
Implemented above @jonathanolson. Please review. Feel free to close if all looks good.

**Comment by jonathanolson** [comment]
Looks good, thanks! Closing as requested.
