### ISSUE TITLE
Can Property.notifying be changed to @public (read-only)?

### ISSUE THREAD

**Issue by jbphet** [phetsims/axon#251]
I have a case where I need to know whether the change to one axon Property's value was due to a change from another.  I'll describe the particulars below in case it matters, but I was able to solve this problem by referencing the `notifying` flag in `Property.js`.  However, this value is marked as `@private`.  Would it be cool to change it to `@public (read-only)`?

Okay, here are more details on the motivation: In the Molarity sim, I am in the process of adding sonification, and one of the sound generators is used to indicate changes in the amount of precipitate.  However, we **don't** want to play a sound if the reason that the precipitate amount changed was that the user selected a different solute.  I wasn't sure how to handle this, but I ended up adding code in the listener that monitors the precipitate amount that checks the value of `soluteProperty.notifying` and doesn't play sounds if that flag is set to `true`, and this solution seems to work quite well.  Here's the commit, look at line 70 of `PrecipitateSoundGenerator`: https://github.com/phetsims/molarity/commit/31f262eb25af7f95f07adb28d5959c90efce042e.

Assigning to @samreid to comment.

**Comment by samreid** [comment]
I won't be able to get to this for several business days.  @jbphet feel free to ask at dev meeting or ask another developer if you need a quicker response.

**Comment by samreid** [comment]
@chrisklus and I worked on a prototype in a branch for detecting which Properties were changing other Properties.  @chrisklus can you help track that down?

**Comment by jbphet** [comment]
This issue was discussed during the 6/20/2019 status meeting, and @samreid was okay with changing the docs for the `notifying` flag for now, but is concerned that it's not a very reliable or general solution to the issue of knowing whether a Property's value is being changed as a result of another Property's value changing.  Looking at the `notifying` flag works for the particular problem in the Molarity sim, but may not work for other situations.

Once @chrisklus has found the experiments that he and @samreid worked on and has updated this issue to reflect what might be relevant from that, this issue should be assigned to @pixelzoom for his input.  After that, back to me and @samreid to finalize.

**Comment by chrisklus** [comment]
@samreid and I investigated implementing `UserControlledProperty` on branch data-flow of axon and hookes-law, and reported our findings in https://github.com/phetsims/phet-io/issues/1349#issuecomment-422221687.

It looks like the idea was to setup a one-way relationship between Properties, and the leading Property is determined by whichever component is in use.

**Comment by chrisklus** [comment]
I talked a bit more with @jbphet about what he was trying to accomplish, and we were thinking that `UserControlledProperty` could be relevant to this problem if he went about it in a different way. It would allow him to detect if the "amount of precipitate" Property was changed by the Slider in Molarity instead of the solute Property.

However, his current solution seems to be simpler, so I'll pass this off to @pixelzoom to see what he thinks.

**Comment by pixelzoom** [comment]
Looking at `notifying` does not feel like a generally good direction. I'd like to know more about the specific use case here.  Why do we need to know the circumstances that resulted in a Property value change?  Should we even be concerned with that to begin with? And what's the specific case in Molarity? I'm responsible dev and not aware of any reason that this should be needed.

**Comment by pixelzoom** [comment]
Here's what I found in `PrecipitateSoundGenerator`:

```js
        // only play if the change to the precipitate amount is NOT due to a change to the selected solute
        if ( !soluteProperty.notifying ) {
```

I don't think this is a good way to do this. It introduces spaghetti code.

**Comment by jbphet** [comment]
I must admit to being somewhat offended.  From https://www.urbandictionary.com/define.php?term=spaghetti%20code:

> In computer programming, code which flagrantly violates the principles of structured, procedural programming. Usually this means using lots of GOTO statements (or their equivalent in whatever language is being used) - hence the term, which suggests the tangled and arbitrary nature of the program flow. 

> Spaghetti code is almost impossible to debug and maintain, and rarely works well.

So, how does one line of commented code that checks a clearly defined condition qualify as "spaghetti code"?

**Comment by jbphet** [comment]
@pixelzoom said:
> I'd like to know more about the specific use case here.

I think the use case is described reasonably well in the second paragraph of the [opening comment](https://github.com/phetsims/axon/issues/251#issue-457639265).  If more detail is needed, we can set up a meeting.  There are alternatives to looking at the `notifying` flag, such as passing in properties that track whether the user is interacting with the solute amount or solution level sliders, but this seemed simpler, which is why I'm asking about it.

**Comment by jbphet** [comment]
I was about to assign back to @pixelzoom, but decided not to.  I feel like the feedback is a sort of vague "I don't really like this idea" without any concrete reasons as to why or good suggestions for alternatives, but it's "not a hill I'm willing to die on" as they say.  I'll revert the change to the documentation and figure out some alternative way to do it.

**Comment by pixelzoom** [comment]
@jbphet said:
> I must admit to being somewhat offended.  ...

@jbphet sorry to offend you, that wasn't my intention.

> From https://www.urbandictionary.com/define.php?term=spaghetti%20code:

Not a great definition imo, but in the ballpark.  What's missing from the definition is that code can also be negatively impacted by the inclusion (or distribution) of unnecessary or undesirable dependencies that tend to create a web (spider's web, spaghetti,...) that impacts maintainability.  

> So, how does one line of commented code that checks a clearly defined condition qualify as "spaghetti code"?

Checking the condition (the `notifying` flag) isn't the problem.  Using knowledge of a definition and dependencies is the potential problem.  In Molarity specifically, the proposed change uses the knowledge that `precipiateAmountProperty` is defined like this in Solute.js:

```js
 this.precipitateAmountProperty = new DerivedProperty( [ this.soluteProperty, this.soluteAmountProperty, this.volumeProperty ],
```

It's great that you've included a comment in `PrecipitateSoundGenerator`. But you're using knowledge of how `precipitateAmountProperty` is defines that that is internal to Solution.js.  `precipitateAmountProperty` is public, not the details of how it's defined. And if that definition changes, `PrecipitateSoundGenerator` may break.  Probably not a big deal, probably won't be a problem.  But it's in a sim that I'm responsible for maintaining, so I'm voicing my opinion. 

@jbphet said:
>  ... I feel like the feedback is a sort of vague "I don't really like this idea" without any concrete reasons as to why or good suggestions for alternatives, but it's "not a hill I'm willing to die on" as they say. 

I'm on vacation, I don't have a good internet connection, and I'm starting to feel just a tiny bit like I'm getting beat up over this.  If you need to do something before I return, go for it.   If you need or want more feedback, I'll be happy to reply when I get back.

**Comment by ariel-phet** [comment]
@jbphet @pixelzoom please do not edit any comments above for the time being, I think this is a good issue to have a discussion about the back and forth here, and how it could be improved. That is not a knock on either of you, but I think it shows a good example from which we can build off of and inform a "code of conduct"

**Comment by jbphet** [comment]
I've reverted the documentation change to `Property.js` and have implemented an alternative solution.  The alternative, in my opinion, isn't ideal either, so I'll follow up on that in https://github.com/phetsims/molarity/issues/125, since this this case highlights a general issue where we will need to know a bit more about **why** a property value is being changed in some cases.

@pixelzoom said:
> I'm on vacation...

This is definitely not worth any disruption to your vacation, and my apologies if my response caused a distraction to your RnR.  Please feel free to ignore until we're both back in Boulder.

**Comment by jbphet** [comment]
Assigning to @ariel-phet.  I've set up a more general issue to follow up on (links above), and it sounded like he wanted to have a process discussion related to this.

**Comment by ariel-phet** [comment]
Process discussion has occurred. @pixelzoom @jbphet feel free to edit any comments above, and close or such.

**Comment by pixelzoom** [comment]
I believe that @jbphet created a more general issue, #125, and that this issue can be closed.  @jbphet if you agree, and there's nothing else to do here, please close this issue.

**Comment by jbphet** [comment]
This issue was referenced in a meeting today, see the link above.  

Since we've decided, at least for now, not to encourage external usage of the `notifying` flag, I think the essential question has been answered, and I'll go ahead and close.
