### ISSUE TITLE
Assertion failed: value should be instanceof Vector2, value=undefined

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#252]
Looks like `Property.notifyListenersStatic` emits with an `undefined` arg. The emitter is validating that as null, so we should change that to `null` instead.

**Comment by zepumph** [comment]
@samreid  how does this look to you?

**Comment by samreid** [comment]
I was originally skeptical, thinking JS may treat f(x,undefined) differently than f(x,null), but I noted 

```
var x = function(){console.log(arguments.length);}
x(1,undefined)
==> 2
```

But I couldn't figure out which Emitter you are referring to, can you please specify?

**Comment by zepumph** [comment]
Mainly it is to support PropertyIO:

```js
      link: {
        returnType: VoidIO,

        // oldValue will start as "null" the first time called
        parameterTypes: [ FunctionIO( VoidIO, [ phetioValueType, NullableIO( phetioValueType ) ] ) ],
        implementation: function( listener ) {
          this.phetioObject.link( listener );
        },
        documentation: 'Adds a listener which will be called when the value changes. On registration, the listener is ' +
                       'also called with the current value. The listener takes two arguments, the new value and the ' +
                       'previous value.'
      },
```

Since the second arg is serialized as `{null|Type}`, `undefined` seemed buggy. Even more so it seemed buggy that that didn't demonstrate any bugs.

**Comment by samreid** [comment]
My other concern is whether some `Property.<T|null>` may be confusing on the second arg.  But that is a minor concern and since it seems to help `PropertyIO` I think we can keep it.

Still, I'd like to run it past @pixelzoom briefly to see if he sees a problem.
