### ISSUE TITLE
Implement NumberProperty.assertNumberPropertyValidateValue using validate.js

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#253]
We may be able to improve validation in NumberProperty now that we have validate.js.  @zepumph I thought you would be good at this task, but feel free to unassign if you don't have time or priority for this.

**Comment by zepumph** [comment]
I see that `assertNumberPropertyValidateValue` validates two options currently: range and numberType. I converted both to use `validate`. I thought about putting both in one larger isValidValue function, but felt like this was a bit cleaner. Please review.

**Comment by zepumph** [comment]
I messed with simTests because I noticed that while working on a range validator, that the wrapper unit tests just hung there, stuck, due to a logical error in NumberProperty. I then needed to support all the "purposeful errors" that were being triggered from tests.

**Comment by samreid** [comment]
Perhaps now that we are dropping IE support, we can use `Number.isInteger` instead of `%1===0`.  I'm seeing 70 occurrences of that pattern across our codebase (including this occurrence).

**Comment by samreid** [comment]
I reviewed the commits for this issue, and it looks good.  The only thing I noticed is more about ValidatorDef, so I'll open a separate issue for that.  Closing.
