### ISSUE TITLE
EnumerationProperty fails with options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#254]
`EnumerationProperty` fails if you pass it any options (e.g. options.tandem). All of the assertions have incorrect expressions.  They are all `options.hasOwnProperty` and should be `!options.hasOwnProperty`.

**Comment by pixelzoom** [comment]
Fixed in above commit.

**Comment by zepumph** [comment]
After some investigation, I found some tests that should have been failing for this, but were written wrong. @pixelzoom please review my commits.

**Comment by pixelzoom** [comment]
Revised tests look good.  But there's a copy-paste error with the assertions that were added to EnumerationProperty.  Fixed in the above commit.   All tests passing.  Closing.
