### ISSUE TITLE
PhET-iO support for EnumerationProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#255]
From 7/18/19 Gas Properties PhET-iO design meeting, https://github.com/phetsims/gas-properties/issues/30#issuecomment-512980763:
> How to set the value of an `EnumerationProperty` via API?

Gas Properties has several Enumerations (see `HoldContant`, `ParticleType`, `PressureGauge.Units`, and `Thermometer.Units`) and associated EnumerationProperty instances.   The client should be able to set the value of these EnumerationProperties. 

Support for this is apparently limited and/or buggy.   See Slack discussion below.  @kathy-phet @arouinfar @ariel-phet FYI, prioritization needed.

<details>
<summary>Slack discussion</summary>
<br>

Chris Malley 3:31 PM
Via PhET-iO API, how does one set the value of an `EnumerationProperty`?   Do you get the values via the global namespace, e.g. `phet.gasProperties.HoldConstant`? 

Michael Kauzmann:house_with_garden: 3:36 PM
No that wouldn't work because of CORS.
I think there is currently limited support for setting the `EnumerationProperty`. It looks like `EnumerationIO.toStateObject` is written poorly, if you have an issue, I could commit a fix that would accept a mapping from `string -> Enumeration`, so the usage on the client side would work like `client.invoke( 'mySim.myAnimalEnumProperty', 'setValue', ['TURLES']);` and then it would basically work like `phet.sim.mySim.myAnimalEnumProperty.set( phet.sim.mySim.myAnimalEnumProperty.TURTLES);`

</details>

**Comment by ariel-phet** [comment]
From the slack discussion it at least sounded like this ability would not be a huge hurdle to add/fix, so we should go ahead and move forward. @zepumph if turning into a rat hole let us know, but maybe get to this by sometime next week?

**Comment by zepumph** [comment]
Some work was done for this in https://github.com/phetsims/phet-io-wrappers/issues/290, but for the most part it was already set up to work.

The public interface runs on lowercase strings. EnumerationProperty now emits a list of `validValues` in the state object. Those can be used like 

`phetioClient.invoke( 'myEnumProperty', 'setValue', ['units']);`

@pixelzoom please let me know if you need anything else.

**Comment by pixelzoom** [comment]
@zepumph can you please identify the Enumeration associated with your example in https://github.com/phetsims/axon/issues/255#issuecomment-514801958?

**Comment by pixelzoom** [comment]
> The public interface runs on lowercase strings. 

What does this mean?  Do you mean that the EnumerationProperty values are lowercase strings? Why would that be the case when Enumerations are described using _uppercase_ strings?

**Comment by zepumph** [comment]
>@zepumph can you please identify the Enumeration associated with your example in #255 (comment)?

There is a Property called `whichAnimalProperty` in phet-io-test-sim that I was using for these tests. You can experiment in the studio console like `phetio.phetioClient.invoke( 'phetIoTestSim.phetIoTestSimScreen.model.whichAnimalProperty', 'setValue', ['goat']);`

>What does this mean? Do you mean that the EnumerationProperty values provide to setValue are lowercase strings? 

Yes

Why would that be the case when Enumerations are described using uppercase strings?

This occurred because of conversations when we designing the data stream. There is an enum populating the `event.type`, "model" or "wrapper" or "user", and there was a fair bit of code running on those as lowercase values. I guess we designed Enumeration based on the one enumeration published in GQIO. We could change that if we want though. Would you rather have values be upper case?

**Comment by pixelzoom** [comment]
OK, I tracked down your example:

```js
      const whichAnimal = new Enumeration( ['ZEBRA', 'GOAT', 'SPINEY_LUMPSUCKER'] );
      this.whichAnimalProperty = new EnumerationProperty( whichAnimal, whichAnimal.SPINEY_LUMPSUCKER, {
        tandem: tandem.createTandem( 'whichAnimalProperty' )
      } );
```

First, `whichAnimal` should be something like `Animals`.  PhET convention is that Enumeration instances are uppercase.

But back to the issue at hand... How are you mapping from `'spineLumpsucker'` to  `whichAnimal.SPINEY_LUMPSUCKER` ?

**Comment by pixelzoom** [comment]
I'm also not understanding how any mapping could be done between a string and an Enumeration value without relying to the format of the Enumeration value's `toString` method.  And relying on the format of `toString` is an anti-pattern.

**Comment by zepumph** [comment]
>spineyLumpsucker

Not sure how you got to camel case, currently we are mapping with `value.toString().toLowerCase()`.

![image](https://user-images.githubusercontent.com/6856943/62070915-eb044c80-b1e7-11e9-8652-3fba9e1657ed.png)


>And relying on the format of toString is (in general) an anti-pattern.

That makes sense to me not that you say it, but I'm not sure how we can get around it in this case. Would it be better to use `value.name`? When implementing `EnumerationIO` in the first place we thought about using `name`, but then felt like that was too much of an implementation detail.

**Comment by pixelzoom** [comment]
In the absence of examples, I got to camelcase because that's PhET's convention.   I never would have expected (and do not recommend) something as non-standard as "spiney_lumpsucker".

Getting around `toString` shouldn't be a big deal.

If you use `name`.... There's no visibility annotation for Enumeration value `name` field (another problem) so I don't know if it was intended to be `@public`.  If you use that, you'll need to investigate.

You could also add phet-io specific methods that allow you to set and get Enumeration values as strings.

**Comment by samreid** [comment]
In the preceding commits, we exposed an uppercase public API, added the values to the EnumerationIO type name like `EnumerationIO(NORTH|SOUTH)` and added a way to include documentation to `Enumeration` constructor.  We also changed the `Enumeration` constructor signature to take `options` object as 2nd arg (instead of `beforeFreeze` function param).  We also converted the `EventType` usages to uppercase (was previously treated as a special case).

@pixelzoom would you like to review?  Changes are mainly in Enumeration and EnumerationIO.

**Comment by pixelzoom** [comment]
Looks OK to me. Appears to be relying on value.name, which is much better than toString.

Back to @samreid in case there's more to do here.

**Comment by zepumph** [comment]
Thanks for the review @pixelzoom. Closing
