### ISSUE TITLE
PhET-iO API doc for Enumeration and EnumerationProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#256]
From 7/18/19 Gas Properties PhET-iO design meeting notes, https://github.com/phetsims/gas-properties/issues/30#issuecomment-512980763:
> - [ ] Where is the `Enumeration` associated with an `EnumerationProperty` documented?

Gas Properties has several Enumerations (see `HoldContant`, `ParticleType`, `PressureGauge.Units`, and `Thermometer.Units`) and associated EnumerationProperty instances.   We considered describing Eumerations and their values in the `phetioDocumentation` for each EnumerationProperty.  But that could get out of sync with reality, and it's going to be something we want for (every?) EnumerationProperty.   So a general solution is preferred.

We'd like to be able to browse the API docs to determine the Enumeration associated with each EnumerationProperty, and the values for each Enumeration.  And we'll probably want optional documentation for Enumeration values.

@kathy-phet @arouinfar @ariel-phet FYI, prioritization needed.

**Comment by pixelzoom** [comment]
@kathy-phet @arouinfar @ariel-phet FYI.  This will need to be prioritized.

**Comment by arouinfar** [comment]
Assigning @kathy-phet and @ariel-phet for prioritization.

**Comment by ariel-phet** [comment]
Since this is one of those "general improvements" to iO as it will likely be occurring in numerous sims going forward. Since the GQIO milestone is now finished, it seems appropriate to make this a high priority to move forward with,

**Comment by samreid** [comment]
@chrisklus @zepumph and I added a way to add Enumeration documentation in https://github.com/phetsims/axon/issues/255.  Now it is possible to pass `phetioDocumentation` to any `Enumeration` and see it in studio.  Here is an example we baked up:

![image](https://user-images.githubusercontent.com/679486/62238002-58061680-b38f-11e9-9f6d-d70000c8f5e8.png)

@pixelzoom would you like to take a look?

**Comment by pixelzoom** [comment]
I see the Enumeration values in the document (as string), but I don't see the name of the Enumeration itself.  That may be OK, I don't know.    Designers (@arouinfar @kathy-phet) asked for this, best to have them review it to see if it's sufficient.

**Comment by zepumph** [comment]
@arouinfar please review the look of EnumerationProperty in studio, see http://phettest.colorado.edu/phet-io-wrappers/studio/?sim=phet-io-test-sim&phetioValidateTandems&phetioDebug and navigate to `model.whichAnimalProperty` for an example. Let me know what you think!

**Comment by zepumph** [comment]
Please as part of this also review the way to control the EnumerationProperty (i.e. the radio buttons). Is this good for you two?

**Comment by samreid** [comment]
Discussed a bit Aug 8, @kathy-phet said she will take a closer look.  We will refine the Enumeration text (committed above).

**Comment by zepumph** [comment]
We discussed this more in today's PhET-iO meeting. Designers liked how it looked in Studio. @pixelzoom wondered about how to supply documentation regarding the Enumeration. 
* Even though `Enumeration` instances don't get instrumented, we support passing `phetioDocumentation` to them. This then get's filled in in the documentation in the `EnumerationIO` that parametrically wraps individual instances.
* We also support passing "instance level" `phetioDocumentation` to an EnumerationProperty about that particular usage of the Enumeration.

Closing, anyone please reopen if there is anything else to discuss.
