### ISSUE TITLE
ActionIO.typeName should be a unique identifier

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#257]
From https://github.com/phetsims/phet-io/issues/1534, metadata passed into ActionIO like name and documentation for each parameter is backwards. Instead it would be better to just pass a list of parameter types to ActionIO, and have all the other metadata added to the ActionIO instance. This is better because it formalizes the definition of `ActionIO` as a "Type." Currently two idential Actions with a single parameter would be different if the documentation differs by a single character. 

To solve this @samreid and I propose the following:

- [x]  rename Emitter's `options.validators` to `options.parameters`
- [x]  Move items currently bundled in ActionIO args to `Action.options.parameters`.
- [x]  rename type -> phetioType
- [x]  rename documentation -> phetioDocumentation
- [x]  keep name -> name
- [x]  Create an `ActionIO` in the `Action` constructor based on the list of `phetioTypes` provided in options.parameters
- [x]  Create a map of `ActionIO` types and reuse them when possible to save memory. In the map keep a count so that we can also dispose them.
- [ ]  Micro-optimize all logic above because it will be used in every Emitter in the project

**Comment by zepumph** [comment]
Instead of making a map just for Action, what if we could make some sort of phetioEngine global that could be used all over the place?

**Comment by zepumph** [comment]
I did a large amount of the above checklist. Things are still pretty rough, and this issue definitely deserves the blocking publication label for the project. Here are a few more checkboxes to add:

- [ ] How should we hide private emitter args from the public api, right now we use VoidIO, which is a pain for a few reasons. Here is what it looks like in doc, shouldn't they just be totally gone?
   ```
   PressListener PressAction looks like:
   event: EventIO
   targetNode: VoidIO
   callback: VoidIO
   ```
  Why do we even have the second two names? Also There are quite a few TODOs marked in the code that have to do with how this problem effects phetioType/valueType mutual exclusion. Right now specifying a valueType causes an opt out of looking at the phetioType validator. This is not what was decided in https://github.com/phetsims/axon/issues/235#issuecomment-513921073, and I wish we could use a different way to remove parameters from the public phet-io api. Maybe let's make a new issue.

- [ ] valueType currently overrides phetioType, they aren't mutually exclusive, this is to support VoidIO hiding parameters. Ideally we wouldn't need this workaround. Like I said above

- [ ] There is a fair bit of logic around `this.tandem.supplied`, I wonder if this is the best approach. If feels like we shouldn't assume anything about tandem, and instead just look at the validator keys and phetioType. 

- [ ] `phetioOuterType` may be weird, let's talk about it for use in the map and in creating phetioTypes in ActionIO.

- [ ] In places like PressListener, we moved IOType constants directly into the constructor. Though we aren't making a whole ActionIO, we are still adding an object. Is that ok? I think so.

- [ ] There is a todo in the code to make the map work better. We should also test the memory footprint of that solution, and see if we can't use a more general map.

- [ ] There are other todos in the code mainly have to do with optimization. I'm sure I forgot something though. 

For testing I did quite a bit, but would recommend for @samreid and any reviewer to do the same to familiarize with the changes.
* Look at an EmitterIO and ActionIO in studio, especially notice the documentation change.
* Take a look at the top of the constructor and see assertions that define a different way of handling phetioTypes and validation.
* Axon tests are passing
* local phet-io fuzz passing
* local phet fuzz testing.

**Comment by pixelzoom** [comment]
8/1/19 dev meeting:
This affects all brands, so consider master unstable until addressed.

**Comment by zepumph** [comment]
@samreid and I discussed the above points.

- [ ] Let's create `phetioPrivate` `{boolean}` to opt emitter params out of the public api instead of using VoidIO.
- [ ] Make `valueType` and `phetioType` not mutually exclusive. See further discussion in https://github.com/phetsims/axon/issues/235#issuecomment-517448253.
- [ ] add `phetioType` as a key to `ValidatorDef`. See https://github.com/phetsims/axon/issues/258

**Comment by zepumph** [comment]
Above I added `phetioPrivate` and removed the `VoidIO` workarounds.

**Comment by zepumph** [comment]
Summary of changes above:
* Remove usages of `tandem.supplied` that aren't helpful. 
* Make a better ActionIO cache (map).
* Already mentioned, but added `phetioPrivate` to remove VoidIO workaround.

**Comment by zepumph** [comment]
Above is a bug fix for https://github.com/phetsims/equality-explorer/issues/155 where I was initializing the count in the cache map to 0 when there was already 1 in the map.

**Comment by samreid** [comment]
Summarizing notes from above about remaining work:

- [ ] There is a todo in the code to make the map work better. We should also test the memory footprint of that solution, and see if we can't use a more general map.
- [ ] There are other todos in the code mainly have to do with optimization. I'm sure I forgot something though.
- [ ] Micro-optimize all logic above because it will be used in every Emitter in the project

@zepumph anything else to do for this issue?  How much did @chrisklus and I review it in our prior discussions and work with you?  Do any of the related issues need to be marked blocks publication?

**Comment by samreid** [comment]
> TODO: is this taking up too much memory? Does this create too much garbage? https://github.com/phetsims/axon/issues/257

It's called 415 times in Graphing Quadratics with assertions enabled.  0 times with assertions disabled.  It seems these extra allocations with assertions enabled should not block publication.

**Comment by zepumph** [comment]
Everything with the cache looks correct. There is no longer a custom one in Action;s constructor, but there is an idiomatic one for ActionIO. 

@samreid do you see any optimizations that may be needed in Action? I feel like it would be best to get another set of eyes on this code.

**Comment by samreid** [comment]
ActionIO and its cache look good to me, I'm not seeing other worthwhile micro-optimizations.
