### ISSUE TITLE
ValidatorDef should support `phetioType`

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#258]
Over in https://github.com/phetsims/axon/issues/257 we thought this was the best way forward.  Then we don't have to do a special case for the phetioType like we do in this sha here: 

https://github.com/phetsims/axon/blob/9e7e33acd010886c6fec1c99e053e2eb2ff282ce/js/Action.js#L201-L210

**Comment by zepumph** [comment]
Above I added support for `phetioType` as a member of `ValidatorDef`. This was largely straightforward. I also added tests for this and found/fixed a bug in ArrayIO's validator.

The main piece I would like reviewed here is in `Property.js`. Up until this point, validator keys have been passed straight to Property, but have been used to validate the value the Property is set to, not the Property itself. But when adding support for phetioType, we were passing a phetioType like `PropertyIO.<BooleanIO>` into a validator setup to validate `boolean`, not `Property.<boolean>`. To get around this, I am no longer passing Property's options into validator, but instead I am picking out the validator keys into a validator var, and then overwriting the phetioType to be the parameterType of the phetioType (so `BooleanIO` instead of `PropertyIO.<BooleanIO>`). The main concern is that this adds one more object (to hold the validator) per Property instance. I do not know another way around it.

@samreid please review these changes, perhaps together?

**Comment by zepumph** [comment]
How about just 

```
     // Do not allocate the new object when assert is not enabled
      const validator = assert ? _.pick( options, ValidatorDef.VALIDATOR_KEYS ) : options;
```

That way we only make a new object if assert is false. What do you think?

**Comment by samreid** [comment]
That sounds good @zepumph.  I also took that same idea a step further in the commit.  Can you please review?

**Comment by zepumph** [comment]
Oh that is so very nice. How do you like my minor tweak to remove duplicated documentation?

**Comment by samreid** [comment]
Looks great, thanks!  I'm ready to close if you are.
