### ISSUE TITLE
PropertyIO.unlink would never work

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#262]
Functions are serialized into `functionHandle` strings based on the current message, so there is no way to unlink a function. Let's look at the following code:

```js
const myFunction = () => { doSomething();};
phetioClient.invoke( 'myProperty', 'link', [ myFunction ], () => {
  phetioClient.invoke( 'myProperty', 'unlink', [ myFunction ] );
} );

```

The async nature of the callback means that the link will be sent in message X and then the unlink will be sent in message X + Y, such that the same function will never be serialized to the same thing on the sim side. Furthermore, even if it mapped to the same string. phetioCommandProcess.wrapFunction will return a new function for each functionHandle, even if the function handles are the same.

Currently there are no usages of `'unlink'` in the project, so I think this is lowish priority. I think immediately though we should remove `PropertyIO.unlink` as a public and broken method. 

The only reason to unlink anyways is for memory management. Perhaps we can convince ourselves that we don't ever need to support this for wrappers.

Discovered while working on https://github.com/phetsims/gravity-force-lab/issues/172.  @samreid @chrisklus  do you agree with the priority of fixing the main problem as well as the high priority immediate removal?

**Comment by samreid** [comment]
Let's remove this for now.  I think we should work on getting this working for the long term--we can't assume wrappers will never need to unlink.

**Comment by samreid** [comment]
I commented this out.  To solve this in the future, perhaps `link` can return a handle which can be used to `unlink`.

**Comment by samreid** [comment]
I took a look at this today and used the following patch for experimentation:

<details>

```diff
Index: main/phet-io-test-sim/js/phet-io-test-sim/model/PhetIoTestSimModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/phet-io-test-sim/js/phet-io-test-sim/model/PhetIoTestSimModel.js	(revision b760963d5380b13369acec67e54353cc2be219da)
+++ main/phet-io-test-sim/js/phet-io-test-sim/model/PhetIoTestSimModel.js	(date 1594735248966)
@@ -7,6 +7,7 @@
 import BooleanProperty from '../../../../axon/js/BooleanProperty.js';
 import Emitter from '../../../../axon/js/Emitter.js';
 import EnumerationProperty from '../../../../axon/js/EnumerationProperty.js';
+import NumberProperty from '../../../../axon/js/NumberProperty.js';
 import ObservableArray from '../../../../axon/js/ObservableArray.js';
 import ObservableArrayIO from '../../../../axon/js/ObservableArrayIO.js';
 import Enumeration from '../../../../phet-core/js/Enumeration.js';
@@ -119,6 +120,16 @@
     }
 
     NumberPropertyWithRangeTests.init( tandem.createTandem( 'numberPropertyWithRangeTests' ) );
+
+    this.countingProperty = new NumberProperty( 0, {
+      tandem: tandem.createTandem( 'countingProperty' )
+    } );
+    this.countingProperty.debug( 'hello' );
+    console.log(this.countingProperty.tandem.phetioID);
+
+    setInterval( () => {
+      this.countingProperty.value = this.countingProperty.value + 1;
+    }, 1000 );
   }
 
   // @public resets the model
Index: main/axon/js/PropertyIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/axon/js/PropertyIO.js	(revision 3ad31d19d0e0d847b8adf0b6bc711581037dc70a)
+++ main/axon/js/PropertyIO.js	(date 1594736153701)
@@ -161,18 +161,17 @@
       documentation: 'Adds a listener which will be called when the value changes. This method is like "link", but ' +
                      'without the current-value callback on registration. The listener takes two arguments, the new ' +
                      'value and the previous value.'
-    }
+    },
+
     // TODO: get this working again, see https://github.com/phetsims/axon/issues/262
-    // ,
-    //
-    // unlink: {
-    //   returnType: VoidIO,
-    //   parameterTypes: [ FunctionIO( VoidIO, [ parameterType ] ) ],
-    //   implementation: function( listener ) {
-    //     this.phetioObject.unlink( listener );
-    //   },
-    //   documentation: 'Removes a listener.'
-    // }
+    unlink: {
+      returnType: VoidIO,
+      parameterTypes: [ FunctionIO( VoidIO, [ parameterType ] ) ],
+      implementation: function( listener ) {
+        this.phetioObject.unlink( listener );
+      },
+      documentation: 'Removes a listener.'
+    }
   };
 
   PropertyIOImpl.documentation = 'Observable values that send out notifications when the value changes. This differs from the ' +
Index: main/phet-io/js/phetioCommandProcessor.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/phet-io/js/phetioCommandProcessor.js	(revision a1f6b3128aedf12efbc419934e3797aedf046cb6)
+++ main/phet-io/js/phetioCommandProcessor.js	(date 1594736415633)
@@ -324,6 +324,7 @@
   wrapFunction( targetWindow, functionHandle, functionType, request ) {
     const self = this;
 
+    // TODO: cache and reuse, see https://github.com/phetsims/axon/issues/262
     return ( ...args ) => {
 
       // {SimToWrapperCallback} - convert the arguments based on the type specification
Index: main/phet-io-wrappers/active/index.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/phet-io-wrappers/active/index.html	(revision 381100f95b37ebc96ce33cbd71496fcaa854501a)
+++ main/phet-io-wrappers/active/index.html	(date 1594735792385)
@@ -69,13 +69,24 @@
 
       // Send a message using the phetioClient to link up to the active Property
 
-      phetioClient.invoke( activeProperty, 'link', [ function( active ) {
-        lastActiveValue = active;
-        document.getElementById( 'readout' ).innerHTML = 'Active: ' + active;
-      } ] );
+      // phetioClient.invoke( activeProperty, 'link', [ function( active ) {
+      //   lastActiveValue = active;
+      //   document.getElementById( 'readout' ).innerHTML = 'Active: ' + active;
+      // } ] );
 
       // once the sim is loaded and wired up, enable the active checkbox for interaction.
       document.getElementById( 'activeCheckbox' ).disabled = false;
+
+      const listener = counter => {
+        console.log( 'wrapper found count: ' + counter )
+
+        if ( counter === 3 ) {
+          console.log( 'attempting unlink' );
+          phetioClient.invoke( 'phetIoTestSim.phetIoTestSimScreen.model.countingProperty', 'unlink', [ listener ] );
+          debugger;
+        }
+      };
+      phetioClient.invoke( 'phetIoTestSim.phetIoTestSimScreen.model.countingProperty', 'link', [ listener ] );
     },
 
     onError: function( error ) { throw error; }
Index: main/phet-io-wrappers/common/js/Client.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/phet-io-wrappers/common/js/Client.js	(revision 381100f95b37ebc96ce33cbd71496fcaa854501a)
+++ main/phet-io-wrappers/common/js/Client.js	(date 1594736415628)
@@ -678,6 +678,8 @@
       return {
         phetioID: phetioID,
         method: method,
+
+        // TODO: keep track of methods that already have a handle, and reuse them, see https://github.com/phetsims/axon/issues/262
         args: args.map( ( arg, argIndex ) => {
           if ( typeof arg === 'function' ) {
 
```

</details>

I marked 2 places with a TODO referencing `https://github.com/phetsims/axon/issues/262`:
* `Client.itemToCommand` where wrapper-side functions are converted to functionHandles
* `phetioCommandProcessor.wrapFunction` where a functionHandle is converted to a simulation side method.

I think if we cached and reused functions at both of these sites, then unlink would work automatically.  Is it a problem that these caches would keep growing?  Do we need a more manual control, like changing the signature of `unlink` from taking a method to taking a `{number}` or `{string}` ID returned by `link` (like the `clearTimeout` pattern)?  I guess I'm wondering not just for this function but what we'll want to do in future cases where we want to reuse functions.

@zepumph what do you recommend for the way forward and for the priority of this issue?

**Comment by samreid** [comment]
I implemented the `clearTimeout` pattern, by having `link` return a unique `{number}` that can be used for unlink.  It is working properly in the wrapper.  The usage site isn't too palatable:

```js
      let listenerIndex = null;

      const listener = counter => {
        console.log( 'wrapper found count: ' + counter )

        if ( counter === 3 ) {
          console.log( 'attempting unlink on ' + listenerIndex );
          phetioClient.invoke( 'phetIoTestSim.phetIoTestSimScreen.model.countingProperty', 'unlink', [ listenerIndex ] );
        }
      };
      phetioClient.invoke( 'phetIoTestSim.phetIoTestSimScreen.model.countingProperty', 'link', [ listener ], ( result, error ) => {
        console.log( 'result + error', result, error );
        listenerIndex = result;
      } );
```

But maybe this is OK since it will be used rarely?  If we like this pattern and want to move forward with it, some loose ends:
* Apply the pattern to `lazyLink` as well
* Remove methods from the `allListeners` list when they have been unlinked.

Full patch with lots of test code (not committable)

<details>

```diff

Index: main/phet-io-test-sim/js/phet-io-test-sim/model/PhetIoTestSimModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/phet-io-test-sim/js/phet-io-test-sim/model/PhetIoTestSimModel.js	(revision b760963d5380b13369acec67e54353cc2be219da)
+++ main/phet-io-test-sim/js/phet-io-test-sim/model/PhetIoTestSimModel.js	(date 1594735248966)
@@ -7,6 +7,7 @@
 import BooleanProperty from '../../../../axon/js/BooleanProperty.js';
 import Emitter from '../../../../axon/js/Emitter.js';
 import EnumerationProperty from '../../../../axon/js/EnumerationProperty.js';
+import NumberProperty from '../../../../axon/js/NumberProperty.js';
 import ObservableArray from '../../../../axon/js/ObservableArray.js';
 import ObservableArrayIO from '../../../../axon/js/ObservableArrayIO.js';
 import Enumeration from '../../../../phet-core/js/Enumeration.js';
@@ -119,6 +120,16 @@
     }
 
     NumberPropertyWithRangeTests.init( tandem.createTandem( 'numberPropertyWithRangeTests' ) );
+
+    this.countingProperty = new NumberProperty( 0, {
+      tandem: tandem.createTandem( 'countingProperty' )
+    } );
+    this.countingProperty.debug( 'hello' );
+    console.log(this.countingProperty.tandem.phetioID);
+
+    setInterval( () => {
+      this.countingProperty.value = this.countingProperty.value + 1;
+    }, 1000 );
   }
 
   // @public resets the model
Index: main/axon/js/PropertyIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/axon/js/PropertyIO.js	(revision 3ad31d19d0e0d847b8adf0b6bc711581037dc70a)
+++ main/axon/js/PropertyIO.js	(date 1594737369542)
@@ -9,6 +9,7 @@
 
 import FunctionIO from '../../tandem/js/types/FunctionIO.js';
 import NullableIO from '../../tandem/js/types/NullableIO.js';
+import NumberIO from '../../tandem/js/types/NumberIO.js';
 import ObjectIO from '../../tandem/js/types/ObjectIO.js';
 import VoidIO from '../../tandem/js/types/VoidIO.js';
 import axon from './axon.js';
@@ -19,6 +20,8 @@
 // the parameter type, so that it is only created once
 const cache = new Map();
 
+const allListeners = [];
+
 /**
  * An observable Property that triggers notifications when the value changes.
  * This caching implementation should be kept in sync with the other parametric IO type caching implementations.
@@ -138,12 +141,16 @@
     },
 
     link: {
-      returnType: VoidIO,
+      returnType: NumberIO,
 
       // oldValue will start as "null" the first time called
       parameterTypes: [ FunctionIO( VoidIO, [ parameterType, NullableIO( parameterType ) ] ) ],
       implementation: function( listener ) {
         this.phetioObject.link( listener );
+        listener.propertyIOLinkIndex = allListeners.length;
+        allListeners.push( listener );
+
+        return listener.propertyIOLinkIndex;
       },
       documentation: 'Adds a listener which will be called when the value changes. On registration, the listener is ' +
                      'also called with the current value. The listener takes two arguments, the new value and the ' +
@@ -161,18 +168,17 @@
       documentation: 'Adds a listener which will be called when the value changes. This method is like "link", but ' +
                      'without the current-value callback on registration. The listener takes two arguments, the new ' +
                      'value and the previous value.'
-    }
+    },
+
     // TODO: get this working again, see https://github.com/phetsims/axon/issues/262
-    // ,
-    //
-    // unlink: {
-    //   returnType: VoidIO,
-    //   parameterTypes: [ FunctionIO( VoidIO, [ parameterType ] ) ],
-    //   implementation: function( listener ) {
-    //     this.phetioObject.unlink( listener );
-    //   },
-    //   documentation: 'Removes a listener.'
-    // }
+    unlink: {
+      returnType: VoidIO,
+      parameterTypes: [ NumberIO ],
+      implementation: function( number ) {
+        this.phetioObject.unlink( allListeners[ number ] );
+      },
+      documentation: 'Removes a listener.'
+    }
   };
 
   PropertyIOImpl.documentation = 'Observable values that send out notifications when the value changes. This differs from the ' +
Index: main/phet-io/js/phetioCommandProcessor.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/phet-io/js/phetioCommandProcessor.js	(revision a1f6b3128aedf12efbc419934e3797aedf046cb6)
+++ main/phet-io/js/phetioCommandProcessor.js	(date 1594736415633)
@@ -324,6 +324,7 @@
   wrapFunction( targetWindow, functionHandle, functionType, request ) {
     const self = this;
 
+    // TODO: cache and reuse, see https://github.com/phetsims/axon/issues/262
     return ( ...args ) => {
 
       // {SimToWrapperCallback} - convert the arguments based on the type specification
Index: main/phet-io-wrappers/active/index.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/phet-io-wrappers/active/index.html	(revision 381100f95b37ebc96ce33cbd71496fcaa854501a)
+++ main/phet-io-wrappers/active/index.html	(date 1594737448322)
@@ -69,13 +69,27 @@
 
       // Send a message using the phetioClient to link up to the active Property
 
-      phetioClient.invoke( activeProperty, 'link', [ function( active ) {
-        lastActiveValue = active;
-        document.getElementById( 'readout' ).innerHTML = 'Active: ' + active;
-      } ] );
+      // phetioClient.invoke( activeProperty, 'link', [ function( active ) {
+      //   lastActiveValue = active;
+      //   document.getElementById( 'readout' ).innerHTML = 'Active: ' + active;
+      // } ] );
 
       // once the sim is loaded and wired up, enable the active checkbox for interaction.
       document.getElementById( 'activeCheckbox' ).disabled = false;
+      let listenerIndex = null;
+
+      const listener = counter => {
+        console.log( 'wrapper found count: ' + counter )
+
+        if ( counter === 3 ) {
+          console.log( 'attempting unlink on ' + listenerIndex );
+          phetioClient.invoke( 'phetIoTestSim.phetIoTestSimScreen.model.countingProperty', 'unlink', [ listenerIndex ] );
+        }
+      };
+      phetioClient.invoke( 'phetIoTestSim.phetIoTestSimScreen.model.countingProperty', 'link', [ listener ], ( result, error ) => {
+        console.log( 'result + error', result, error );
+        listenerIndex = result;
+      } );
     },
 
     onError: function( error ) { throw error; }
Index: main/phet-io-wrappers/common/js/Client.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- main/phet-io-wrappers/common/js/Client.js	(revision 381100f95b37ebc96ce33cbd71496fcaa854501a)
+++ main/phet-io-wrappers/common/js/Client.js	(date 1594736415628)
@@ -678,6 +678,8 @@
       return {
         phetioID: phetioID,
         method: method,
+
+        // TODO: keep track of methods that already have a handle, and reuse them, see https://github.com/phetsims/axon/issues/262
         args: args.map( ( arg, argIndex ) => {
           if ( typeof arg === 'function' ) {
 
```

</details>

**Comment by samreid** [comment]
Increasing priority since this could pertain to https://github.com/phetsims/studio/issues/137

**Comment by zepumph** [comment]
I think this would be best as having the same signature as the internal link/unlink, unless there is a good reason to deviate. What about the following pattern (which you likely pursued in https://github.com/phetsims/axon/issues/262#issuecomment-658213700 but I didn't fully understand).

* On the client side side I think we could accomplish this by adding a Map from function->functionHandle. This way you can pass a function in and if it is the same function, it will get the same functionHandle.
* On the sim side we will likely want to keep a new Map from functionHandle->function so that we can get that actual function back for unlinking etc. By "actual function" I mean the function returned by `wrapFunction`.
* If we are worried about too much growth, maybe a WeakMap would be helpful, and prevent the necessity for too much memory management on the wrapper side. Likely this won't be too much of a problem because all of these functions were already in memory, this data structure would just congregate them all with another reference to each.
* One potential assertion could be added with the map needed in phetioCommandProcessor. If we can detect that we no longer need that function anymore, perhaps we could replace that function with something that throws and error. I'm not positive this will work, and we'll need to see what the implementation looks like.

@samreid does the above proposal make sense to you?

**Comment by samreid** [comment]
### Implementation notes

I've followed the prescription above. I used 2 maps on the client side, so we can do 2-way lookups between the function and its handle.  I tried `WeakMap` but it cannot be used with non-Object keys, so I left it as `Map` and noted that it is a memory leak on the order of O(N) where N is the number of different functions used as arguments in PhET-iO API calls.

> If we can detect that we no longer need that function anymore, perhaps we could replace that function with something that throws and error.

If we `link` then `unlink` then re-`link` should it create a new function adapter, or use the cached one?  Currently it will use the cached one.

### Instructions for testing:

1. Run natural selection in studio
2. In the console, run 

```js
const b = ()=>console.log('bonjour');
phetio.phetioClient.invoke('naturalSelection.introScreen.view.environmentNode.visibleProperty','link',[b]);
```
3. Navigate to the `naturalSelection.introScreen.view.environmentNode.visibleProperty` in the tree and toggle it a few times, and note that "bonjour" prints to the console.
4. Run this in the console:

```js
phetio.phetioClient.invoke('naturalSelection.introScreen.view.environmentNode.visibleProperty','unlink',[b]);
```
5. Toggle the visibleProperty and notice that the callback is no longer triggered.

### Questions for review

I decided to commit to master since the changes are working and span 3 repos.  This will block publication until review is complete.

1. Previously, the function handles were very specific, like `const key = `functionHandle@messageID=${this.messageID},argIndex=${argIndex},sequenceNumber=${sequenceNumber}`` but that has been changed to 
```js
              const functionHandle = `functionHandle@id=${functionHandleID}`;
              functionHandleID++;
```

Is that selective enough?  I wasn't sure why we needed to track things like sequenceNumber and argIndex.  They have been omitted for now, but please let me know if they are used for something and I can add it back.

**Comment by zepumph** [comment]
>If we link then unlink then re-link should it create a new function adapter, or use the cached one? Currently it will use the cached one.

Can you think of a usage where that would be buggy? Even though it is the same function reference, could it have different behavior somehow? (I'm shrugging)


Looking at other usages of `apply`, it seems like this should have the first arg of `null` instead of `undefined`:
`        this.handleToFunctionMap.get( message.functionHandle ).apply( undefined, message.args );`

>Previously, the function handles were very specific. . . .Is that selective enough?

I noticed that `functionHandleID` is static. This is fine, but an alternative way to do this may be to keep it as an instance var, and then have the client `id` included in the functionHandle be `${this.functionHandleID++}client${this.id}`


* `functionHandleID++;` this can most likely be inlined, and doesn't need to be a separate line.


I really like how simple of a change https://github.com/phetsims/phet-io/commit/68ed180434c6f99bcf36e04cdb4fe3d5f3663975 is. Awesome!

Great work. Thanks for this.

**Comment by zepumph** [comment]
Oh, I'm unsure how to "sign off" on that memory leak. Maybe we should make a side issue to https://github.com/phetsims/studio/issues/137 to see if it is a problem in Studio? Likely that is our best test case in terms of number of Property links from the wrapper.

**Comment by samreid** [comment]
Oops, accidental closure from project board UI.

**Comment by samreid** [comment]
> Can you think of a usage where that would be buggy? Even though it is the same function reference, could it have different behavior somehow? (I'm shrugging)

They should have the same behavior.  I just brought this up in terms of memory leaks.

> Oh, I'm unsure how to "sign off" on that memory leak. Maybe we should make a side issue to phetsims/studio#137 to see if it is a problem in Studio? Likely that is our best test case in terms of number of Property links from the wrapper.

I opened Studio for Natural Selection and measured the heap size as 33.1MB.  Then I searched "Property" and tapped through 100 hits.  Then I recorded memory again, and it measured 34.1MB.  In my opinion, this is acceptable (and indeed may not be 100% attributable to this function leak).

Up to you how to proceed.
