### ISSUE TITLE
Action phetioDocumentation shows up in overrides when not changed

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#263]
Discovered as part of https://github.com/phetsims/gravity-force-lab/issues/174.

Looks like newlines get stripped in inputs, so getting the `input.value` ends up being different from the baseline documentation (which has newlines in it). An easy commit coming in shortly to solve the newline added to Action's phetioDocumentation.

I also think that we should add an assertion in PhetioObject for this (perhaps I shouldn't opened an issue over there). It will be nice to nip this in the bud and fail loudly. I'll investigate how hard that would be.

**Comment by zepumph** [comment]
There is now an assertion, and I removed Action's usage of `\n` in its phetioDocumentation. @samreid please review these changes. Sorry that most are just grunt updates.

**Comment by zepumph** [comment]
Actually @chrisklus would you like to review this one?

**Comment by chrisklus** [comment]
Changes in Action.js look good and the assertion in PhetioObject.js looks good, ready to close.
