### ISSUE TITLE
Grunt update after public phet-io API changes

### ISSUE THREAD

**Issue by chrisklus** [phetsims/axon#267]
From https://github.com/phetsims/axon/commit/3d343ff5c96a561f76385ae4e4638882698280bf.

Whenever there are changes to the public phet-io API (even documentation, because right now validation is a deep equality check), `grunt update` needs to be run on all sims that have their API being validated. CT is currently broken from relevant changes. In the future, we'll just check for backwards compatibility, see https://github.com/phetsims/phet-io/issues/1523.

We use the command `for-each.sh {{PATH}}/perennial/data/phet-io "npm update && grunt update"` to make these changes in a batch.

**Comment by pixelzoom** [comment]
If there’s an urgent need to fix this, someone else please handle. Otherwise I’ll get to it when I can.  And it sure would be nice if there was something that prevented this type of mistake, like a precommit task.  Or something in the “How to instrument” doc about when grunt update needs to be run.

**Comment by pixelzoom** [comment]
PhET-iO API files were updated in the above commits. I'll leave this open until CT shows green.

**Comment by pixelzoom** [comment]
CT is green. Closing.
