### ISSUE TITLE
How to handle calls to a disposed Property

### ISSUE THREAD

**Issue by chrisklus** [phetsims/axon#268]
From https://github.com/phetsims/charges-and-fields/issues/170.

@zepumph, @samreid and I needed to add a small check in `setDeferred` that only notifies listeners if that Property is not already disposed. We noticed that methods like `set` and the beginning of `setDeferred` don't check if the Property is disposed, and we're wondering if they should handle that case gracefully or with an assert. In TinyEmitter.js, we found that assertions are graceful around disposal, so perhaps they should be the same here.

**Comment by chrisklus** [comment]
We committed one guard that handles this case gracefully, and would like to know what @pixelzoom thinks.

**Comment by pixelzoom** [comment]
If "gracefully" means treating the call as a no-op, then this looks like it does the job.  If that's consistent with how other calls are treated when something has already been disposed, then it's probably fine.
