### ISSUE TITLE
problems with Property setDeferred

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#269]
Noted while reviewing https://github.com/phetsims/axon/issues/268.

In https://github.com/phetsims/axon/commit/636fc05d8ab5334d747455c811211fb014326e25, @samreid made this change to the logic in Property`setDeferred`:

```js
 ...
 * @param {boolean} isDeferred - whether the Property should be deferred or not
 ...
setDeferred( isDeferred ) {
  ...
  assert && assert( isDeferred || !isDeferred, 'bad value for isDeferred' );
  if ( isDeferred ) {
    ...
  }
  else if ( !isDeferred ) {
   ...
  }
}
```

Problems:

(1) The assertion should be:

`assert && assert( typeof deferred === 'boolean', 'bad value for isDeferred' );`

(2) The `else if` expression is unnecessary (and confusing).

**Comment by samreid** [comment]
Thanks, I committed updates based on your recommendations.  Ready for review.

**Comment by pixelzoom** [comment]
👍 closing.
