### ISSUE TITLE
Add a listener for when Emitter listeners are added or removed

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#27]
For scenery, it is important to receive callbacks when events listeners are added or removed.  For now, this feature is implemented in scenery using a custom solution, but we wanted to create this issue in case it makes sense to add this feature into axon in the future.

**Comment by samreid** [comment]
> For scenery, it is important to receive callbacks when events listeners are added or removed. 

@jonathanolson is this still true?

**Comment by jonathanolson** [comment]
Yes. The current code:
```js
 ... Events.prototype, {
    on: function onOverride( eventName, listener ) {
      Events.prototype.on.call( this, eventName, listener );
      this.onEventListenerAdded( eventName, listener );
    },

    onStatic: function onStaticOverride( eventName, listener ) {
      Events.prototype.onStatic.call( this, eventName, listener );
      this.onEventListenerAdded( eventName, listener );
    },

    off: function offOverride( eventName, listener ) {
      var index = Events.prototype.off.call( this, eventName, listener );
      assert && assert( index >= 0, 'Node.off was called but no listener was removed' );
      this.onEventListenerRemoved( eventName, listener );
      return index;
    },

    offStatic: function offStaticOverride( eventName, listener ) {
      var index = Events.prototype.offStatic.call( this, eventName, listener );
      assert && assert( index >= 0, 'Node.offStatic was called but no listener was removed' );
      this.onEventListenerRemoved( eventName, listener );
      return index;
    }
  }
```

**Comment by samreid** [comment]
Ok looks good.  Anything else to do for this axon issue?

**Comment by jonathanolson** [comment]
I'd like to not have to override the methods and use super calls, but potentially have this in Events itself.

**Comment by samreid** [comment]
Seems like it is worth more discussion.  I only see one usage of onEventListenerAdded across our simulations (in Node.js).  I'm concerned about complexity in Events as well as performance concerns.  On the other hand, if we can isolate and solve performance problems in Axon, perhaps axon should send the notifications?  Like this.trigger('eventListenerAdded',...) or using an ObservableArray for each named event type in Events?  Or having a separate mechanism is ok too as long as complexity/maintainability/performance are all non-issues.  What is your priority for this?  Are there other places you want to use this pattern outside of Node.js at the moment?

**Comment by pixelzoom** [comment]
Events has been replaced by Emitters.  Can we close this? Do Emitters require a similar feature?

**Comment by samreid** [comment]
All of @jonathanolson's cases above apply to Emitters or Events, so this still requires discussion.

**Comment by jonathanolson** [comment]
> What is your priority for this?

Medium-low. Changes will be very invasive, but it may have performance benefits, but will make code cleaner.

> Are there other places you want to use this pattern outside of Node.js at the moment?

I also have a similar construct for Instances' root transforms, where 1+ listeners will trigger computation. It's generally fairly rare.

Due to that, Node and Instance could just override the methods on Events/Emitter if that's cleaner and higher-performing overall.

Thoughts?

**Comment by pixelzoom** [comment]
@samreid said:
> All of @jonathanolson's cases above apply to Emitters or Events, so this still requires discussion.

Do we intend to do this for both Events and Emitters, or just Emitters? My understanding is that Events are deprecated.

**Comment by samreid** [comment]
We wouldn't implement @jonathanolson's suggestions for Events, if we proceed it would only be with Emitters.

**Comment by pixelzoom** [comment]
Then I'll change the title of this issue to indicate "Emitters".

**Comment by samreid** [comment]
> Due to that, Node and Instance could just override the methods on Events/Emitter if that's cleaner and higher-performing overall.

How about an Emitter subclass in Axon that does this?

**Comment by pixelzoom** [comment]
2/2/16 dev meeting: Deferred to 2/4/16 when @jonathanolson is present.

**Comment by samreid** [comment]
Reassigning to @jonathanolson to look into once he is looking into related scenery code, using an Emitter subclass in Axon for now.

**Comment by samreid** [comment]
I think this has been solved with `TinyEmitter.changeCount`, @jonathanolson please reopen if that's incorrect.
