### ISSUE TITLE
prefer type-specific Properties in API definitions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#272]
This issue originated with https://github.com/phetsims/vector-addition/issues/233 from Vector Addition postmortem.

The [CRC](https://github.com/phetsims/phet-info/blob/master/checklists/code_review_checklist.md) has these 2 items:

> - [ ] Properties should use type-specific subclasses where appropriate (.e.g `BooleanProperty`, `NumberProperty`, `StringProperty`) or provide documentation as to why they are not.

> - [ ] Look for cases where the use of type expressions involving Property subclasses are incorrect.  Because of the structure of the `Property` class hierarchy, specifying type-specific Properties (`{BooleanProperty}`, `{NumberProperty}`,...) may be incorrect, because it precludes values of type `{DerivedProperty}` and `{DynamicProperty}`.   Similarly, use of `{DerivedProperty}` and `{DynamicProperty}` precludes values of (e.g.) `{BooleanProperty}`. Especially in common code, using `{Property,<TYPE>}` is typically correct, unless some specific feature of the `Property` subclass is required.  For example, `{Property.<boolean>}` instead of `{BooleanProperty}`.

These items are somewhat contradictory.  The first item says that we should instantiate type-specific Properties whenever possible. The second items says that we should not use type-specific Properties in type expressions when defining APIs.   

I'd like to revisit the second item.  In general, I agree that APIs should use the most general type for parameters.  But as an exception, there are good arguments for preferring type-specific Properties when defining an API.  I'll discuss those arguments in the context of this example:

```js
// Property.<boolean>
class MyClass {
  /**
   * @param {Property.<boolean>} property
   */
  constructor( property ) {
    assert && assert( property instanceof Property && typeof property.value === 'boolean', ... );
  } 
}

// BooleanProperty
class MyClass {
  /**
   * @param {BooleanProperty} property
   */
  constructor( property ) {
    assert && assert( property instanceof BooleanProperty, ... );
  } 
}

// usage with Property.<boolean>
const myProperty = new Property( true );
const myObject1 = new MyClass( myProperty );

// usage with BooleanProperty
const myBooleanProperty = new BooleanProperty( true );
const myObject2 = new MyClass( myBooleanProperty );
```
<br>

Arguments for `{BooleanProperty}`:

* Type-specific Properties provide value validation.  If the `MyClass` API requires a `{BooleanProperty}`, then `MyClass` can assume that it will be dealing with a boolean value.  If `MyClass` is provided with `{Property.<boolean>}`, then it needs to deal with the case where a the Property is inadvertently set to a non-boolean value.

* Type-specific Properties provide the opportunity to perform arg validation.  If `MyClass` API requires `{BooleanProperty}`, the arg validation it simplified.  If the API is `{Property.<boolean>}`, we can check the value when the constructor is called, but can't guarantee that the value will remain boolean.  Gas Properties and Vector Addition both used arg validation of this sort, and it was very beneficial.

* Type-specific Properties have support for PhET-iO. While `MyClass` doesn't need PhET-iO directly, PhET sims as a whole do.

* Requiring type-specific Properties in APIs encourages their use in client code. The first usage in the example above creates a `{Property.<boolean>}` and will therefore fail code review.  But it could fail much sooner if the API for `MyClass` required `{BooleanProperty}`.

So.. My proposal is to make an exception for type-specific Properties, and prefer their usage in type expressions for API parameters.

**Comment by jonathanolson** [comment]
> we can check the value when the constructor is called, but can't guarantee that the value will remain boolean

If we have a listener added, we can have assertions there on changes (where the value is actually used).

Overall I can't agree with this, because the disadvantages are big. Yes, there is more concise and improved validation when only BooleanProperty is used, but the instant you NEED to use a Derived/Dynamic Property in that case, then you have to gut the "nice" code and put in the slightly more verbose validation. The cost of retrofitting things to be flexible when we need seems much more significant than the cost of being a bit more verbose with assertions (when we want assertions in those cases).

I strongly feel that the default should be to accept `Property.<X>` instead of `XProperty`.

**Comment by pixelzoom** [comment]
@jonathanolson Any thoughts on fixing the type `Property` hierarchy so that `Derived/DynamicProperty` can reap the benefits of type-specific Properties, and so that `BooleanProperty` includes derived/dynamic subtypes?  For example, having to do this for "a dynamic Property whose value is boolean" is a drag:

```js
new DerivedProperty( ..., ..., {
  valueType: 'boolean',
  phetioType: DerivedPropertyIO<BooleanIO>
} );
```

**Comment by jonathanolson** [comment]
> Any thoughts on fixing the type Property hierarchy

I'm still not sure why we have a hierarchy for type-specific versions here. The type things the Property contains seems completely orthogonal to how it is computed, or whether you can change it with setters. Having `new Property( ..., { type: Boolean } )` and `new DynamicProperty( ..., { type: Boolean } )` or having things be concise sounds like a better long-term method. Then it would be possible to type-check properties in assertions with `property.type === Boolean` if we really wanted.

Alternatively, the "Boolean-ness" and "Derived/Dynamic-ness" would both work well as mix-ins that could be combined.

Having a set hierarchy here for both things doesn't sound great. And we still have the problem for things where we can't use BooleanProperty directly (e.g. `{boolean|null}`), but we don't want to create `DerivedBooleanOrNullProperty`, much less `BooleanOrNullProperty`, and we have the same type check issues for those.

**Comment by pixelzoom** [comment]
10/24/19 dev meeting notes.

Consensus for APIs that have parameters of type `Property`...

* Type expressions that use type-specific Properties (e.g.`{BooleanProperty}`) are generally undesirable, because they exclude `DerivedProperty` and `DynamicProperty`.
* Specify APIs using type expressions of the form `{Property.<{{TYPE}}>}`.
* There are 4 levels of argument type checking, see examples below.  Use whichever of these strategies you prefer, depending on context.
* No need to actively change existing code; apply this going forward.

```js
// Example 1: no type checking
/**
 * @param {Property.<boolean>} property
 */
myMethod( property ) {
  ...
}

// Example 2: verify that it's a Property
/**
 * @param {Property.<boolean>} property
 */
myMethod( property ) {
  assert && assert( property instanceof Property, ... );
}

// Example 3: verify that it's a Property and initial value type is correct
/**
 * @param {Property.<boolean>} property
 */
myMethod( property ) {
  assert && assert( property instanceof Property && typeof property.value === 'boolean', ... );
  ...
}

// Example 4: verify that it's a Property, initial value type is correct, guard against bad future values
/**
 * @param {Property.<boolean>} property
 */
myMethod( property ) {
  assert && assert( property instanceof Property && typeof property.value === 'boolean', ... );
  assert && property.link( value => typeof property.value === 'boolean' ;
  ...
}
```

**Comment by samreid** [comment]
@pixelzoom should the code review checklist be revised based on the consensus above?

**Comment by pixelzoom** [comment]
The strategies for validating args listed in https://github.com/phetsims/axon/issues/272#issuecomment-546053856 could be augmented 2 ways:

First, to include the new `isSettable` method that @zepumph added to the Property hierachy.  Probably something like:

```js
// Example 5: If the method will directly set the Property, verify that it's settable.
/**
 * @param {Property.<boolean>} property
 */
myMethod( property ) {
  assert && assert( property.isSettable(), 'property must be settable' );
  ...
}
```

Second, use AssertUtils functions for validating args where appropriate. Something like:

```js
/**
 * @param {EnumerationProperty.<Widget>} property
 */
// Example 6: use AssertUtils functions where it makes validating easier
myMethod( property ) {
  assert && AssertUtils.assertEnumerationPropertyOf( property, Widget );
  ...
}
```

As for whether these strategies should be in the CRC... I don't think so. Observations: (a) This is a lot of stuff to add to the code review, (b) PhET has no standards for when argument validation (or assertions is general) should used, it's at the discretion of the developer, (c) Looking at the codebase, most PhET developers don't appear to include arg validation as part of their regime.  So I'm not enthusiastic about adding a bunch of stuff to the CRC that is optional and gets little use.  But if someone else wants to augment the CRC, go for it.

**Comment by pixelzoom** [comment]
> But if someone else wants to augment the CRC, go for it.

Reconsidering...  I don't want to see these strategies in the CRC.  Unless there are some requirements for when/where to use assertions, it's just more noise.

Here's the relevant CRC item:

> - [ ] Assertions should be used appropriately and consistently. Type checking should not just be done in code comments. Use `Array.isArray` to type check an array.

I think this could be expanded a little bit. But I don't think it's necessary (or desirable) to enumerate all of the strategies for validating Property args.  Using assertions (including for pre-conditions, like arg validation) is something fundamental that should be learned by developers as they evolve, not put in a checklist.

I'll also point out that "appropriately" currently means "if you feel like it".  And "consistently" means "if you felt like it over there, you should probably do it here too, but only if you feel like it."    So this CRC item really has no teeth, and results in no "learning" about how to use assertions.  So if PhET decides that assertions are valuable and should be part of a developer's regime, then there should be some concensus on when/where assertions should be used, and the CRC should reflect that.

**Comment by samreid** [comment]
Let's touch base briefly in dev meeting to decide how to proceed.

**Comment by jessegreenberg** [comment]
Discussion from 3/4/21 - 

We agreed that it is not necessary to add a code review checklist item for this. We also discussed the value of adding assertions and most agreed that it is a good way to make code more robust, but some don't use it as much as they could.

AssertUtils was mentioned as a good way to add assertions, folks can check that out if they wish.
