### ISSUE TITLE
TODO with no issue number in ObservableArray

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#273]
By @samreid:

```js
// TODO: should we really pop if the length was 0?  Or maybe this is OK?
```

**Comment by samreid** [comment]
I added an assertion that there are elements in the ObservableArray when pop is called, and it didn't trigger anything on an aqua test (though some repos had other issues), so I committed this and we can be on the lookout for it on CT.

**Comment by pixelzoom** [comment]
I think that's fine.  The other option would be to make ObservableArray `pop` have the same behavior as Array `pop`.  I.e.:

```
> [].pop
undefined
```

**Comment by samreid** [comment]
I considered matching existing JavaScript behavior of return `undefined` from empty array pop, but thought we could catch logical problems sooner with the assertion.  Based on this reasoning, it seems we should add this for `shift` as well.  I'll add this in an upcoming commit.

**Comment by samreid** [comment]
I added the assertion-style guard on shift as well, closing.

**Comment by pixelzoom** [comment]
Should a similar assertion be added for `get`?

```
> var o = new phet.axon.ObservableArray()
> o.push( 'hello' )
> o.get( 1 )
undefined
```

**Comment by pixelzoom** [comment]
`find` is also questionable. What should be expected if `index` is out of range? There is currently no `@returns` annotation, so it's not clear what is best.

**Comment by samreid** [comment]
It seems best to check both of those bounds, I added docs and assertions in the above commit.  In testing, it revealed a problem in density/buoyancy, I'll open an issue.  @pixelzoom can you please review the changes to ObservableArray?

**Comment by pixelzoom** [comment]
I the above commit, I added the bad index value to assertion messages. For example:

```js
- assert && assert( index >= 0 && index < this.length, 'index out of bounds' );
+ assert && assert( index >= 0 && index < this.length, `index out of bounds: ${index}` );
```

This assertion in `find`, where`findIndex` is optional, is a tad ineffective:

```js
assert && ( typeof fromIndex === 'number' ) && assert( fromIndex >= 0 && fromIndex < this.length,
  `fromIndex out of bounds: ${fromIndex}` );
```

It doesn't handle the case where `findIndex` is not a number, and the implementation doesn't result in an error. For example:

```
> var o = new ObservableArray()
> o.push( 1 )
> o.push( 2 )
> o.find( value => value > 1, null )
2
> o.find( value => value > 1, 'hello world' )
2
```

... but maybe that's OK.  Back to @samreid to decide.

**Comment by samreid** [comment]
I added a test that `fromIndex` is numeric, if provided.

**Comment by pixelzoom** [comment]
👍 closing.
