### ISSUE TITLE
Should NumberProperty.range be mutable for PhET-iO?

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#278]
While working in https://github.com/phetsims/axon/issues/277 @chrisklus and I saw that NumberPropertyIO.setValue is setting the `range` of a NumberProperty, but that isn't doing anything because all the validation logic is set up to read from `options.range`, not `this.range`:

```js
     // validate for range
        if ( options.range ) {
          const currentRange = options.range instanceof Property ? options.range.value : options.range;
          assert && assert( currentRange instanceof Range, `unexpected Range: ${currentRange}` );
          validate( value, { isValidValue: v => currentRange.contains( v ) } );
        }
      } );
```

This seems fine with me on paper, but I think we should remedy this discrepancy and either 
1. convert these `options.range` calls to `this.range` so that it is mutable, and say that `this.range` isn't `read-only` because PhET-iO state can set it.
2. Remove the range setting from `NumberPropertyIO` (I think I prefer this one because there currently isn't a need for mutable static ranges).

Note that this doesn't at all affect how `NumberProperty` treats `range`s that are of type Property.

@samreid what do you think we should do?

**Comment by zepumph** [comment]
I added a TODO in NumberPropertyIO:

```js
static setValue( numberProperty, fromStateObject ) {
      validate( numberProperty, this.validator );

      // If range is a Property
      if ( numberProperty.range instanceof Property ) {
        numberProperty.setValueAndRange( fromStateObject.value, fromStateObject.range );
      }
      else {
        PropertyIOImpl.setValue( numberProperty, fromStateObject );
        numberProperty.range = fromStateObject.range; // TODO: changing this doesn't do anything! https://github.com/phetsims/axon/issues/278
      }
      numberProperty.step = fromStateObject.step;
      numberProperty.numberType = fromStateObject.numberType;
    }

**Comment by samreid** [comment]
There have been changes to NumberProperty since this issue creation, for instance, in https://github.com/phetsims/axon/issues/274 NumberProperty manages its range as `rangeProperty`.  @zepumph can you comment what remains to be done for this issue?

**Comment by zepumph** [comment]
As NumberProperty.rangeProperty now exists, and is often instrumented for PhET-iO, I feel like we are ready to close this issue.
