### ISSUE TITLE
NumberProperty reset can break when it resets range and value together.

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#282]
From https://github.com/phetsims/axon/issues/274, I should write tests to expose this, and fix this by calling `setValueAndRange` when applicable in NumberProperty.reset.

**Comment by zepumph** [comment]
The follow patch makes the test pass. 

It uses deferred, so it wouldn't work in correlation with state. I'm worried about that, since this would break any place where a number Property with a passed in rangeProperty is being reset during state set (likely a smalle edge case). Perhaps we should just apply this patch and see how it goes?

```diff
Index: js/NumberPropertyTests.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/NumberPropertyTests.js	(revision 8c6331740e7d95a1821eddeede4a9b8cf51ecf26)
+++ js/NumberPropertyTests.js	(date 1605745967643)
@@ -102,7 +102,7 @@
   p.rangeProperty.value = new Range( 90, 100 );
 
   // TODO: this should not fail, see https://github.com/phetsims/axon/issues/282
-  // p.reset();
+  p.reset();
 } );
 
 
Index: js/NumberProperty.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/NumberProperty.js	(revision 8c6331740e7d95a1821eddeede4a9b8cf51ecf26)
+++ js/NumberProperty.js	(date 1605745929993)
@@ -150,7 +150,12 @@
 
     // @private
     this.resetNumberProperty = () => {
-      ownsRangeProperty && this.rangeProperty.reset();
+      if ( ownsRangeProperty ) {
+        ownsRangeProperty && this.setValueAndRange( this._initialValue, this.rangeProperty.initialValue );
+      }
+      else {
+        super.reset();
+      }
     };
   }
 
@@ -175,14 +180,11 @@
   }
 
   /**
+   * Don't call up to super, because the value and range have to be set together.
    * @public
    * @overrides
    */
   reset() {
-    super.reset();
-
-    // Do subclass-specific reset after the value has been reset, because this reset may change the range
-    // such that the value isn't valid anymore.
     this.resetNumberProperty();
   }
 

```

**Comment by samreid** [comment]
> It uses deferred, so it wouldn't work in correlation with state. 

Can you elaborate on how it uses deferred?  And how that won't work for state?

In the absence of further information, being able to reset a NumberProperty seems more important than risking the edge cases you described, which could be caught during CT.

**Comment by zepumph** [comment]
I will try, though right now I feel a bit like I'm hanging on for dear life and barely understanding this issue.

This function uses deferred:

https://github.com/phetsims/axon/blob/0cbcf1504e662bc56a97ad22332cba17847b7d18/js/NumberProperty.js#L197-L220

Thus if called during phet-io state, we would have nested deferred, which we don't currently support. I think your idea about letting CT handle the errors may be nice, if we can get to those errors in appropriate time. What do you think?

**Comment by samreid** [comment]
> I'm worried about that, since this would break any place where a number Property with a passed in rangeProperty is being reset during state set (likely a smalle edge case). 

If CT identifies a problem like that, is there a straightforward path to mitigation?  Would we have to (a) avoid calling reset on those Properties or (b) avoid passing in a rangeProperty to those Properties?  Those sound like odd restrictions, but it seems even worse that NumberProperty reset can break when it resets range and value together.  What do you recommend?

**Comment by zepumph** [comment]
(c) implement nested deferral 👎 

I think it will be best to solve this issue when it comes up in real life (on CT). The reason I'm nervous still is that I have a hard time trusting the scope of our state fuzzing to catch this. It feels like it would be challenging to reproduce this, and it wouldn't happen very often.

That said I'm actually ok to close this issue if you are.

**Comment by samreid** [comment]
Perhaps it is best to close this issue until we have a concrete example.  Closing.

**Comment by samreid** [comment]
Reopening based on the TODO added in https://github.com/phetsims/axon/commit/8c6331740e7d95a1821eddeede4a9b8cf51ecf26, @zepumph can you please advise?

**Comment by zepumph** [comment]
Above we decided to not do anything for this issue. I'll keep the test commented out but add documentation about it.
