### ISSUE TITLE
ObservableArray: don't slice() on forEach()

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#283]
Discovered during https://github.com/phetsims/axon/issues/279, it seems a waste of CPU and memory to slice on every forEach, this should be changed to omit the slice().  If a client needs a slice they can do that manually.

This will require a thorough test of all sims to see if anything was relying on the slice(), say for concurrent modifications.

**Comment by pixelzoom** [comment]
Are you saying that if I need to iterate over the collection while modifying it, then I need to do something like `myObservableArray.getArray().slice().forEach( ... )` ?

How about changing the ObservableArray API to `getArray` and `getArrayCopy`, and deleting `forEach` altogether?  That would make it crystal clear on whether you're operating on the array itself or a copy.

**Comment by pixelzoom** [comment]
The bigger issue here is that ObservableArray doesn't have a proper "collection" API.  The most fundamental API requirements for a collection are:

* hide the details of how members of the collection are stored
* provide good iterators (useful, consistent, performant,..,)

ObservableArray does neither of these.

**Comment by pixelzoom** [comment]
Related to the issue, I don't like having to do this:

`myObservableArray.getArray().slice()`

So in the above commit, I've added `getArrayCopy`.  I'm using this in ObservableArray.

**Comment by brandonLi8** [comment]
I'd also like to point out that `forEach` isn't the only method that exposes the underlying array which the user could modify.

For instance, `ObservableArray.some`,`ObservableArray.find`, `ObservableArray.every`, `ObservableArray.filter`, and `ObservableArray.map` all pass the array as the third argument to the call back, which the user could theoretically modify.

**Comment by pixelzoom** [comment]
> I'd also like to point out that `forEach` isn't the only method that exposes the underlying array which the user could modify. ...

That's the main reason why I avoid using those "convenience" methods of ObservableArray.  I think it's much clearer to call `getArray()` or `getArrayCopy()`, then use the Array API directly.

**Comment by samreid** [comment]
Hopefully we will be able to eliminate ObservableArray in the near future, there is a proposal in https://github.com/phetsims/axon/issues/308 that would obviate this problem.  Unassigning until we have a decision on that issue.

**Comment by samreid** [comment]
ObservableArray has been deleted.  `createObservableArray` uses the default behavior for `slice`, closing.
