### ISSUE TITLE
incorrect doc for ObservableArray.reset

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#285]
Over in https://github.com/phetsims/axon/issues/264, the initialArray feature was removed from ObservableArray.  Now the doc for `reset` is incorrect.

```js
    /**
     * Restore the array back to its initial state
     * Note: if an item is in the current array and original array, it is removed and added back
     * This may or may not change in the future, see #4
     * @public
     */
    reset: function() {
      this.clear();
    },
```

**Comment by samreid** [comment]
I revised the documentation, but am not sure whether it is perfect yet.  @pixelzoom can you please review at your convenience?

**Comment by pixelzoom** [comment]
👍 Closing.
