### ISSUE TITLE
Action shouldn't serialize phet-io arguments in phet brand

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#287]
As part of https://github.com/phetsims/gravity-force-lab/issues/256 I saw that Action was emitting a data stream even with `data` instead of `getData`. This mean that args were being serialized in phet brand. I think we should put that inside a closure instead.

**Comment by zepumph** [comment]
@samreid the above commit does three things:

* use `getData` instead of `data` to prevent argument serialization in phet brand
* Adds an assertion that phet-io data is only retrieved in phet-io brand
* remove redundant `isPhetioInstrumented` calls because that is the first line of `phetioStart/EndEvent()`

Please review.

**Comment by samreid** [comment]
I reviewed these changes with @zepumph.  We confirmed that the arguments work in the arrow function OK via:

```js
var x =function(){
    console.log(arguments);
    var z =()=>console.log(arguments);
    z();
    z();
};
undefined
x(1,2,3);
```

Everything else looks great, and this will improve performance in phet brand.  Nice!

**Comment by zepumph** [comment]
Thanks!

**Comment by zepumph** [comment]
Leaving open to make sure this gets into the GFL branch, though there isn't anything needed for QA, so once that is done I can close.

**Comment by zepumph** [comment]
Cherry-picked
