### ISSUE TITLE
EnumerationProperty should accept validValues

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#288]
@jbphet mentioned on slack that it would be nice to let EnumerationProperty accept a subset of Enumeration values as its valid values. Currently it is hard coded to state all possible Enumeration values as its validValues option to Property.

In my current thought, this wouldn't effect the studio control, because it is based solely on looking at `validValues`, but I should test that.

In my other current thought, this wouldn't involve changing the type name/docs for EnumerationIO, but @pixelzoom may disagree and we can discuss that more here in this issue. I personally like that the "type" signifies all the values that an Enumeration allows. Fell free to out vote me though! Tagging also @jbphet and @samreid because I think they were involved in this slack conversation too.

**Comment by pixelzoom** [comment]
Values do not uniquely define an Enumeration, and therefore do not sufficiently describe an EnumerationProperty.   Even more true when you allow an EnumerationProperty to use subsets of values. 

Example:

```js
const Edges = Enumeration.byKeys( 'LEFT', 'RIGHT', 'TOP', 'BOTTOM' );

const Hands = Enumeration.byKeys( 'LEFT', 'RIGHT' );
```

How does `PropertyIO<EnumerationIO(LEFT|RIGHT)>` tell me which of the above Enumerations this refers to?

**Comment by zepumph** [comment]
I removed the assertion above. Most of the work for this one-line change was writing tests and adding an example in phet-io-test-sim. Here is what it looks like in studio. Notice the current difference between the type name and the valid values:

![image](https://user-images.githubusercontent.com/6856943/77125453-a63d5800-69fa-11ea-8ccc-a92b149eaded.png)

Tagging @jbphet because this should unblock his work for states-of-matter

**Comment by zepumph** [comment]
@pixelzoom in response to https://github.com/phetsims/axon/issues/288#issuecomment-601466296 I'm a bit torn. I understand your concern because the typeName is not unique to an Enumeration instance, but I also recognize that from the context of phet-io clients, they would just pass strings to set values, and "LEFT" would correctly set a value for either enumeration. @samreid do you have any thoughts on the matter?

**Comment by pixelzoom** [comment]
It's nice that you can get away with setting an Enumeration value using a string, so that `'LEFT'` will work for any Enumeration that has value `LEFT`.  But that breaks the opaqueness of Enumeration values, and has a smell to it.  Hopefully that won't need to change in the future, e.g. if we want the client to set values the way we do programmatically (e.g. `Edges.LEFT`).

I'm also not suggesting that it's essential to know the name of the Enumeration. I'm just saying that values alone don't fully communicate semantics, and having a name for a collection of values if preferable.  If I give you only values `LEFT, RIGHT`, there is no way you can tell me what the enumeration is.  Hopefully the Property name provides enough clues to the semantics, e.g `edgeProperty` and `handProperty` in the example in https://github.com/phetsims/axon/issues/288#issuecomment-601466296.

**Comment by samreid** [comment]
I don't have much to add beyond what's been said above.  I agree you should be able to restrict a `Property` to a subset of `Enumeration` values, and that in the future it may be interesting to investigate non-string values for `Enumeration` values, but that doesn't seem important now.

**Comment by pixelzoom** [comment]
Nothing to add.

**Comment by jbphet** [comment]
I just used this in States of Matter (SOM), and it worked great.  I you'd like to see how it looks in Studio, launch SOM in Studio and look at `statesOfMatter.statesScreen.model.substanceProperty`, note the lack of `ADJUSTABLE_ATOM` as a selection, then look at `statesOfMatter.statesScreen.model.substanceProperty`, where `ADJUSTABLE_ATOM` *is* a valid option.

If you'd like to see the code where this is used, look at `MultipleParticleModel` and search on `substanceProperty` and work backwards from there.

Thanks for the quick action on this.

**Comment by pixelzoom** [comment]
@jbphet is there a copy-paste error in the previous comment? You have the same `phetioID` for the "is" and "is not" an option examples.

**Comment by jbphet** [comment]
Yep, sorry, I've fixed it now.
