### ISSUE TITLE
add NumberProperty resetValueAndRange

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#290]
Over in https://github.com/phetsims/axon/issues/289#issuecomment-606989893, I noted that NumberProperty lacks `resetValueAndRange`.   If you use `setValueAndRange` to set value and range atomically, then you will likely need to reset them atomically.   Without `resetValueAndRange`, you need to resort to something like:

```js
myNumberProperty.setValueAndRange( myNumberProperty.initialValue, myNumberProperty.rangeProperty.initialValue );
```

Compare with:

```js
myNumberProperty.resetValueAndRange();
```

**Comment by pixelzoom** [comment]
@zepumph since you added `setValueAndRange`, would you mind reviewing this?

**Comment by zepumph** [comment]
Looks good to me. I thought briefly about if this adequately handles the case where range is not specified (making `rangeProperty.value = rangeProperty.initialValue = null`), and I think all looks good here! Thanks for implementing, I'll head over to https://github.com/phetsims/axon/issues/289 now.
