### ISSUE TITLE
instrumented NumberProperty requires its range Property to be instrumented?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#291]
Over in https://github.com/phetsims/axon/issues/289, I was experiencing failures after using the "Lauch" button in Studio, then pressing Reset All button in the launched sim.

From https://github.com/phetsims/axon/issues/289#issuecomment-607003951:

> What I discovered is that if you instrument a NumberProperty (and use setValueAndRange?) then you had better also instrument the associated range Property that you provide. If you don't, then the range won't be saved/restored, and things will fail when you press Reset All in a launched sim. And there is currently nothing in NumberProperty to verify this.

Should something be done about this?

**Comment by zepumph** [comment]
I committed a fix for this. Basically it has NumberProperty setting the range for its rangeProperty even if that rangeProperty is already instrumented. It is a bit redundant, but I think that it is simple and clean code in this implementation. 


I was thinking about adding a "isPhetioInstrumented()" check in the `setValue` conditional, but I didn't like it quite as much (though I'm open to recommendations).

I added code to phet-io-test sim that fails without this patch. @pixelzoom please review and let me know if this handles the case you need it to.

@samreid please review this change also.

**Comment by pixelzoom** [comment]
I did not review code changes, but tested in natural-selection.  I removed instrumentation from `this.generationRangeProperty` in Proportions model, and verified in Studio/Launch/State Wrapper.  Behavior is as desired.

**Comment by samreid** [comment]
The commits above deal with `range` in `setValue` but that is no longer in master.  @zepumph is this by design?

**Comment by zepumph** [comment]
Looks I removed them in https://github.com/phetsims/axon/commit/b222e1a4b25ad63203bfe1fdecdb3c3b94f900c6. @pixelzoom can you please explain why you think that it is the responsibility of the NumberProperty to set the state of its rangeProperty? Perhaps you don't feel this way, and you were just reporting where there was an error in the sim.

I believe that in its current state, the NumberProperty is not responsible for setting its rangeProperty during state, and if you want the rangeProperty to be set, then you need to instrument the rangeProperty. Is this not the intended behavior? Please explain.

**Comment by pixelzoom** [comment]
I didn't say that NumberProperty needed to be responsible for setting state of its rangeProperty.  I said that if you provide a rangeProperty, then it must be instrumented, otherwise its state will not be restored and things will fail in the State Wrapper.  So if you provide a rangeProperty (versus letting NumberProperty create it), then something should verify that the rangeProperty is instrumented.

**Comment by pixelzoom** [comment]
Add something like this at line 113, after `this.rangeProperty` is defined. 

```js
    assert && assert( !this.isPhetioInstrumented() || this.rangeProperty.isPhetioInstrumented, 
      'rangeProperty must be instrument if NumberProperty is instrumented' );
```

**Comment by zepumph** [comment]
Done above, and I added a unit test also. Please review.

**Comment by pixelzoom** [comment]
Commits reviewed. 👍🏻 closing.
