### ISSUE TITLE
Property should run on TinyProperty?

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#292]
Over in  https://github.com/phetsims/scenery/issues/490, TinyProperty was created. Can we use that in Property to simplify the implementation? I'm not sure it will work, but it is at least worth investigation.

**Comment by samreid** [comment]
It's worth a try!  It feels medium priority to me.

**Comment by samreid** [comment]
Property is already using TinyEmitter for its change listeners, and now TinyProperty extends TinyEmitter.  So likely the main benefit from this change would be that `TinyProperty` could contain the `_value`.  I believe most of the rest of the implementation would remain unchanged, so there may not be much benefit.  On the other hand, this code:

```js
  areValuesEqual( a, b ) {
    if ( this.useDeepEquality && a && b && a.constructor === b.constructor ) {

      assert && assert( !!a.equals, 'no equals function for 1st arg' );
      assert && assert( !!b.equals, 'no equals function for 2nd arg' );
      assert && assert( a.equals( b ) === b.equals( a ), 'incompatible equality checks' );
      return a.equals( b );
    }
    else {

      // Reference equality for objects, value equality for primitives
      return a === b;
    }
  }
```
appears in both files, so we could isolate that.

I'm not planning to work on this soon, but I'll put a calendar entry to remind me to re-evaluate in a few months.

**Comment by zepumph** [comment]
This has been duplicated and implemented over in https://github.com/phetsims/axon/issues/344
