### ISSUE TITLE
Too many tiny Property implementations

### ISSUE THREAD

**Issue by chrisklus** [phetsims/axon#293]
From https://github.com/phetsims/scenery/issues/490, and made worse by work with @jonathanolson @zepumph @samreid in https://github.com/phetsims/scenery/issues/1046.

The switch from running Scenery on Events to axon Properties has created a need for several lighter-weight implementations of Properties. This has started to feel like a duplication of axon and is undesirable. Assigning to @jonathanolson for brainstorming.

**Comment by samreid** [comment]
We have been using the TinyProperty* implementations in axon for a while and they are working nicely, closing.
