### ISSUE TITLE
add Vector2Property.validBounds as a {Bounds2}

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#294]
This would help me with some Vector2Property instances in ratio and proportion.  Thus it feels as good a time as any to add it. On slack @samreid said it "sounds like a nice thing we should support."  This will be similar to `NumberProperty.range`.

I think it will be a simple addition. I'll add tests and use RaP as a test case too.

**Comment by zepumph** [comment]
@samreid can you please review. Any thoughts?

**Comment by samreid** [comment]
This looks great, thanks!  Closing.
