### ISSUE TITLE
DerivedProperty.multilink is abusive, should be deprecated

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#30]
See #29.

**Comment by samreid** [comment]
I'd prefer to just replace DerivedProperty.multilink with Property.multilink.  Sound OK @pixelzoom ?

**Comment by pixelzoom** [comment]
Sounds good to me.

**Comment by samreid** [comment]
@AshrafSharf can you please make sure these changes are compatible with your sims?  I think you are working with fixed SHAs for neuron and I want to check if there is a problem or not.

**Comment by AshrafSharf** [comment]
@samreid There is no dependencies.json defined for Neuron,I am creating one and will commit it

**Comment by samreid** [comment]
Thanks @AshrafSharf.  And to clarify (from my email):

> I suspect (but not sure) you can use the SHAs identified here:
http://www.colorado.edu/physics/phet/dev/html/neuron/1.0.0-dev.8/dependencies.json

> If those don't work, you could try dev.7.

> Please try it out and let me know if you run into trouble.

**Comment by samreid** [comment]
> @samreid There is no dependencies.json defined for Neuron,I am creating one and will commit it

Ah sorry, I think I understand--since you are developing with fixed SHAs, it will be difficult to test the latest version of axon.  That's OK.  Once neuron is published, we can (at lower priority) work on making sure it works with the master version of all repositories.

**Comment by AshrafSharf** [comment]
@samreid  @jbphet Have added dependencies.json (axon now pointing to 5ee82d888ca4639a7b4d59e5e83843e8e09c6425).

**Comment by samreid** [comment]
Sounds good, thanks!

**Comment by samreid** [comment]
I'll leave this issue open until we have been able to test it sufficiently.

**Comment by samreid** [comment]
@pixelzoom anything else to do here?

**Comment by pixelzoom** [comment]
Looks like this is done, closing.
