### ISSUE TITLE
Multilink doc about calling its constructor

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#302]
This came up in the context of discussing the Observer pattern that @brandonLi8 wrote up.

Multilink is documented like this:

```js
/**
 * A Multilink is an instance that can be used to link to multiple properties.  It is very similar to a DerivedProperty,
 * but has no value and does not conform to the Property API because it is intended for use with callbacks that do not
 * compute a value.  Multilink should not be created through calling its constructor directly, but through the
 * Property.multilink and Property.lazyMultilink functions.
 *
 * @author Sam Reid (PhET Interactive Simulations)
 */
```

I see no reason that you can't create a Multilink by calling its constructor -- and you probably should if you need a reference to it for calling dispose.  Property.multilink is a convenience function provided as a way of avoiding lint errors in the cases (which are the majority) where you don't need a reference to the Multilink.   Because these would result in lint errors:

```js
// lint error: using new for side effects
new Multilink( ... );

// lint error: unused variable 
const multilink = new Multilink( ... ); 
```

@samreid is the author. Do you mind if I change this doc?

**Comment by samreid** [comment]
Yes, please update this doc.
