### ISSUE TITLE
Should ValidatorDef have a typedef?

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#304]
In https://github.com/phetsims/axon/issues/253 I noticed that WebStorm marks usage of `validate` as problematic:

![image](https://user-images.githubusercontent.com/679486/84850011-dbfed680-b013-11ea-960f-fbdc6729499c.png)

However, if I add this code to `validate.js`

```js
/**
 * @typedef ValidatorDef extends Object
 */
```

The problem goes away:

![image](https://user-images.githubusercontent.com/679486/84850040-f638b480-b013-11ea-962a-c616a8a5158a.png)

Should we use a typedef like this?  What do you recommend @zepumph?

**Comment by zepumph** [comment]
I added a typedef in ValidatorDef, and I noted that about 80% of the under-linings in `ValidatorDefTests` went away. Can you think of any improvements to be made here?

**Comment by samreid** [comment]
That looks really great, thanks!  I had to invalidate caches and restart the IDE to get it to pick it up, but now it is working well, even in NumberProperty.  Closing.
