### ISSUE TITLE
TinyProperty fails as a dependency of Multilink (and DerivedProperty?)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#305]
In natural-selection PopulationPlotNode.js (a subclass of Node), I had this:

```js
    Property.multilink( [ xRangeProperty, yRangeProperty, this.visibleProperty ],
      () => this.plotPoints()
    );
```

That worked fine with brand=phet.  But when Studio starts up, it failed with:

```
Uncaught TypeError: dependency.isPhetioInstrumented is not a function
    at Property.addPhetioStateDependencies (Property.js:358)
    at Property.lazyLink (Property.js:392)
    at Multilink.js:49
    at Array.forEach (<anonymous>)
    at new Multilink (Multilink.js:40)
    at Function.multilink (Property.js:518)
    at new PopulationPlotNode (PopulationPlotNode.js:114)
    at new PopulationPlotsNode (PopulationPlotsNode.js:39)
    at new PopulationGraphNode (PopulationGraphNode.js:103)
    at new PopulationNode (PopulationNode.js:49)
```

`this.visibleProperty` was apparently the problem. It's a TinyProperty, not a Property, and that causes a PhET-iO-specific problem with Multilink.   I suspect (but have not confirmed) that it would also be a problem with DerivedProperty.  

Is there something that can be done to make this work?  If not, then there should be checks to confirm that dependencies are Properties, otherwise there will be code that works in brand=phet but fails in brand=phet-io.

To work around this problem, I had to resort to this, which duplicates code:

```
    Property.multilink( [ xRangeProperty, yRangeProperty ],
      () => this.plotPoints()
    );

    // Update when this Node becomes visible.
    // visibleProperty is a TinyProperty, so cannot be included in the above multilink.
    this.visibleProperty.link( visible => {
      if ( visible ) {
        this.plotPoints();
      }
    } );
```

**Comment by samreid** [comment]
@zepumph should `addPhetioStateDependencies` check and use `TinyForwardingProperty.forwardingProperty`?

**Comment by zepumph** [comment]
>@zepumph should addPhetioStateDependencies check and use TinyForwardingProperty.forwardingProperty?

I do not think so. `forwardingProperty` feels very private to me. Instead I think addPhetioStateDependencies should just support TinyProperty as a argument type, and check to make sure that `isPhetioInstrumented` exists.

```
if ( Tandem.PHET_IO_ENABLED && dependency.isPhetioInstrumented && dependency.isPhetioInstrumented() && this.isPhetioInstrumented()
```

I won't be able to get to this until Wednesday at least.

**Comment by samreid** [comment]
I added this to our PhET-iO Wednesday agenda and am self-unassigning.

**Comment by zepumph** [comment]
The phet-io team added support for TinyProperty dependencies in DerivedProperty, Multilink, and Property. We also took a crack at removing your workaround in `PopulationPlotNode`. Please review.

**Comment by pixelzoom** [comment]
I didn't dig into the axon changes.  But this is working in natural-selection, so closing.
