### ISSUE TITLE
Alternatives to ObservableArray

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#308]
`ObservableArray` has numerous problems, many identified in other axon issues.  Several of the recent conversations revolve around using the array directly, such as https://github.com/phetsims/axon/issues/283#issuecomment-654994805.  I wonder if we should deprecate `ObservableArray` and investigate an alternative "array-centric" strategy.

Brainstorming some possibilities:
1. Create a new type that `extends Array` and adds `itemAddedEmitter` and `itemRemovedEmitter` which are called at the appropriate times.  (Or are called only for new methods, like `removeAndNotify` `pushAndNotify`.
2. Encourage manual creation of `itemAddedEmitter` and `itemRemovedEmitter` which would be passed around with the array when necessary.
3. Strip most functionality out of `ObservableArray` (including the array convenience methods), but leave in methods to add and remove elements, which call the emitters.  And encourage users to use the `Array` directly.
4. Mixin/trait pattern

Some other ideas are mentioned here: https://stackoverflow.com/questions/5100376/how-to-watch-for-array-changes

@pixelzoom how would you like to see this evolve?

**Comment by chrisklus** [comment]
This sounds really nice - I like that an "array-centric" version would not duplicate a bunch of default methods like `ObservableArray` does. For any that modify the array, we could override them so the API is the same but we've just added some listeners.

In discussion with @zepumph and @samreid, we also brought up that this then couldn't extend PhetioObject. Some possible workarounds: instrument its children like `countProperty` and `itemAddedEmitter`, so it still has desirable phet-io functionality. Or, convert PhetioObject so that it can also be used as a mixin.

**Comment by pixelzoom** [comment]
I like the idea of `ObservableArray extends Array mixes PhetioObject`.  I'm not sure what issues would be encountered, but I think it's worth an exploratory sprint.

**Comment by samreid** [comment]
I ran an exploratory sprint and created `AxonArray`.  It supports all array mutators except for `array.length=...` which cannot be overridden.  I added basic unit tests and noted a few TODOs for next steps.

**Comment by samreid** [comment]
In the above commit I added PhET-iO support for `AxonArray` and I took it for a test drive in Natural Selection in my working copy.  I tested in Studio and saw that counts were updating properly.  It was nice that we could use bracket access for values, like

```js
const firstPoint = this.points[ firstIndex ];
```

Here is the patch that converts NaturalSelection from ObservableArray to AxonArray (just for PopulationModel points):

<details>

```diff

Index: js/common/model/PopulationModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/PopulationModel.js	(revision 3a7db5e5add741a522257855e6d0ae92f3781f42)
+++ js/common/model/PopulationModel.js	(date 1594387591314)
@@ -6,12 +6,11 @@
  * @author Chris Malley (PixelZoom, Inc.)
  */
 
+import AxonArray from '../../../../axon/js/AxonArray.js';
 import BooleanProperty from '../../../../axon/js/BooleanProperty.js';
 import DerivedProperty from '../../../../axon/js/DerivedProperty.js';
 import DerivedPropertyIO from '../../../../axon/js/DerivedPropertyIO.js';
 import NumberProperty from '../../../../axon/js/NumberProperty.js';
-import ObservableArray from '../../../../axon/js/ObservableArray.js';
-import ObservableArrayIO from '../../../../axon/js/ObservableArrayIO.js';
 import Property from '../../../../axon/js/Property.js';
 import PropertyIO from '../../../../axon/js/PropertyIO.js';
 import Range from '../../../../dot/js/Range.js';
@@ -89,33 +88,33 @@
 
     // @public data points, for total population and the population of each allele.
     // Vector2.x = generation, Vector2.y = population
-    this.totalPoints = new ObservableArray( {
+    this.totalPoints = new AxonArray( {
       tandem: dataPointsTandem.createTandem( 'totalPoints' ),
-      phetioType: ObservableArrayIO( Vector2IO )
+      validator: { phetioType: Vector2IO }
     } );
-    this.whiteFurPoints = new ObservableArray( {
+    this.whiteFurPoints = new AxonArray( {
       tandem: dataPointsTandem.createTandem( 'whiteFurPoints' ),
-      phetioType: ObservableArrayIO( Vector2IO )
+      validator: { phetioType: Vector2IO }
     } );
-    this.brownFurPoints = new ObservableArray( {
+    this.brownFurPoints = new AxonArray( {
       tandem: dataPointsTandem.createTandem( 'brownFurPoints' ),
-      phetioType: ObservableArrayIO( Vector2IO )
+      validator: { phetioType: Vector2IO }
     } );
-    this.straightEarsPoints = new ObservableArray( {
+    this.straightEarsPoints = new AxonArray( {
       tandem: dataPointsTandem.createTandem( 'straightEarsPoints' ),
-      phetioType: ObservableArrayIO( Vector2IO )
+      validator: { phetioType: Vector2IO }
     } );
-    this.floppyEarsPoints = new ObservableArray( {
+    this.floppyEarsPoints = new AxonArray( {
       tandem: dataPointsTandem.createTandem( 'floppyEarsPoints' ),
-      phetioType: ObservableArrayIO( Vector2IO )
+      validator: { phetioType: Vector2IO }
     } );
-    this.shortTeethPoints = new ObservableArray( {
+    this.shortTeethPoints = new AxonArray( {
       tandem: dataPointsTandem.createTandem( 'shortTeethPoints' ),
-      phetioType: ObservableArrayIO( Vector2IO )
+      validator: { phetioType: Vector2IO }
     } );
-    this.longTeethPoints = new ObservableArray( {
+    this.longTeethPoints = new AxonArray( {
       tandem: dataPointsTandem.createTandem( 'longTeethPoints' ),
-      phetioType: ObservableArrayIO( Vector2IO )
+      validator: { phetioType: Vector2IO }
     } );
 
     // @public visibility of each data set, on the graph and data probe
@@ -291,17 +290,17 @@
 
 /**
  * Records a count if it differs from the previous data point.
- * @param {ObservableArray.<Vector2>} observableArray
+ * @param {AxonArray.<Vector2>} array
  * @param {number} generation - floating point, not integer!
  * @param {number} count
  */
-function recordCount( observableArray, generation, count ) {
-  assert && assert( observableArray instanceof ObservableArray, 'invalid observableArray' );
+function recordCount( array, generation, count ) {
+  assert && assert( array instanceof AxonArray, 'invalid observableArray' );
   assert && assert( NaturalSelectionUtils.isNonNegative( generation ), 'invalid generation' );
   assert && assert( NaturalSelectionUtils.isNonNegativeInteger( count ), 'invalid count' );
 
-  if ( observableArray.length === 0 || observableArray.get( observableArray.length - 1 ).y !== count ) {
-    observableArray.push( new Vector2( generation, count ) );
+  if ( array.length === 0 || array[ array.length - 1 ].y !== count ) {
+    array.push( new Vector2( generation, count ) );
   }
 }
 
Index: js/common/view/population/PopulationPlotNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/population/PopulationPlotNode.js	(revision 3a7db5e5add741a522257855e6d0ae92f3781f42)
+++ js/common/view/population/PopulationPlotNode.js	(date 1594387144864)
@@ -7,7 +7,7 @@
  * @author Chris Malley (PixelZoom, Inc.)
  */
 
-import ObservableArray from '../../../../../axon/js/ObservableArray.js';
+import AxonArray from '../../../../../axon/js/AxonArray.js';
 import Property from '../../../../../axon/js/Property.js';
 import Shape from '../../../../../kite/js/Shape.js';
 import merge from '../../../../../phet-core/js/merge.js';
@@ -28,13 +28,13 @@
 
   /**
    * @param {PopulationModel} populationModel
-   * @param {ObservableArray.<Vector2>} points - data points, in model coordinates (x=Generation, y=Population)
+   * @param {AxonArray.<Vector2>} points - data points, in model coordinates (x=Generation, y=Population)
    * @param {Property.<boolean>} plotVisibleProperty - whether this plot is visible
    * @param {Object} [options]
    */
   constructor( populationModel, points, plotVisibleProperty, options ) {
     assert && assert( populationModel instanceof PopulationModel, 'invalid populationModel' );
-    assert && assert( points instanceof ObservableArray, 'invalid points' );
+    assert && assert( points instanceof AxonArray, 'invalid points' );
     assert && AssertUtils.assertPropertyOf( plotVisibleProperty, 'boolean' );
 
     options = merge( {
@@ -122,7 +122,7 @@
       // to find this index is not critical.
       let firstIndex = 0;
       for ( let i = numberOfPoints - 1; i >= 0; i-- ) {
-        const point = this.points.get( i );
+        const point = this.points[ i ];
         if ( point.x < this.xRangeProperty.value.min ) {
           firstIndex = i;
           break;
@@ -132,7 +132,7 @@
       // For mutant plots (drawn with a lineDash), adjust lineDashOffset so that the dash appears to scroll.
       // See https://github.com/phetsims/natural-selection/issues/111
       if ( this.isDashed && this.points.length > 0 ) {
-        const firstPoint = this.points.get( firstIndex );
+        const firstPoint = this.points[ firstIndex ];
         const xRemainderModel = firstPoint.x % 1;
         const xRemainderView = this.modelToViewX( xRemainderModel );
         this.stepPath.lineDashOffset = -( xRemainderView % MUTANT_LINE_DASH_SUM );
@@ -144,7 +144,7 @@
       // Plot from left to right
       for ( let i = firstIndex; i < numberOfPoints; i++ ) {
 
-        const point = this.points.get( i );
+        const point = this.points[i];
 
         if ( this.xRangeProperty.value.contains( point.x ) ) {
 
Index: js/common/model/DataProbe.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/DataProbe.js	(revision 3a7db5e5add741a522257855e6d0ae92f3781f42)
+++ js/common/model/DataProbe.js	(date 1594387144872)
@@ -125,8 +125,8 @@
     let count = 0;
 
     // Optimize for scrolling graph. Start with most recent points and work backwards in time.
-    for ( let i = points.length - 1; i >=0; i-- ) {
-      const point = points.get( i );
+    for ( let i = points.length - 1; i >= 0; i-- ) {
+      const point = points[ i ];
       if ( generation >= point.x ) {
         count = point.y;
         break;

```

</details>

The only thing I haven't tested yet is how to instrument `phetioType` for the `itemAddedEmitter` and `itemRemovedEmitter`.

But I think this is at a good point to get feedback from @pixelzoom, can you please take a look?

**Comment by samreid** [comment]
> The only thing I haven't tested yet is how to instrument `phetioType` for the `itemAddedEmitter` and `itemRemovedEmitter`.

After the above commit, the `itemAddedEmitter` and `itemRemovedEmitter` can be phet-io instrumented and emit data to the data stream.  Here's a patch that exercises it in Natural Selection.

<details>

```diff
Index: js/common/model/PopulationModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/PopulationModel.js	(revision 3a7db5e5add741a522257855e6d0ae92f3781f42)
+++ js/common/model/PopulationModel.js	(date 1594388797134)
@@ -6,12 +6,11 @@
  * @author Chris Malley (PixelZoom, Inc.)
  */
 
+import AxonArray from '../../../../axon/js/AxonArray.js';
 import BooleanProperty from '../../../../axon/js/BooleanProperty.js';
 import DerivedProperty from '../../../../axon/js/DerivedProperty.js';
 import DerivedPropertyIO from '../../../../axon/js/DerivedPropertyIO.js';
 import NumberProperty from '../../../../axon/js/NumberProperty.js';
-import ObservableArray from '../../../../axon/js/ObservableArray.js';
-import ObservableArrayIO from '../../../../axon/js/ObservableArrayIO.js';
 import Property from '../../../../axon/js/Property.js';
 import PropertyIO from '../../../../axon/js/PropertyIO.js';
 import Range from '../../../../dot/js/Range.js';
@@ -89,33 +88,33 @@
 
     // @public data points, for total population and the population of each allele.
     // Vector2.x = generation, Vector2.y = population
-    this.totalPoints = new ObservableArray( {
+    this.totalPoints = new AxonArray( {
       tandem: dataPointsTandem.createTandem( 'totalPoints' ),
-      phetioType: ObservableArrayIO( Vector2IO )
+      elementOptions: { phetioType: Vector2IO }
     } );
-    this.whiteFurPoints = new ObservableArray( {
+    this.whiteFurPoints = new AxonArray( {
       tandem: dataPointsTandem.createTandem( 'whiteFurPoints' ),
-      phetioType: ObservableArrayIO( Vector2IO )
+      elementOptions: { phetioType: Vector2IO }
     } );
-    this.brownFurPoints = new ObservableArray( {
+    this.brownFurPoints = new AxonArray( {
       tandem: dataPointsTandem.createTandem( 'brownFurPoints' ),
-      phetioType: ObservableArrayIO( Vector2IO )
+      elementOptions: { phetioType: Vector2IO }
     } );
-    this.straightEarsPoints = new ObservableArray( {
+    this.straightEarsPoints = new AxonArray( {
       tandem: dataPointsTandem.createTandem( 'straightEarsPoints' ),
-      phetioType: ObservableArrayIO( Vector2IO )
+      elementOptions: { phetioType: Vector2IO }
     } );
-    this.floppyEarsPoints = new ObservableArray( {
+    this.floppyEarsPoints = new AxonArray( {
       tandem: dataPointsTandem.createTandem( 'floppyEarsPoints' ),
-      phetioType: ObservableArrayIO( Vector2IO )
+      elementOptions: { phetioType: Vector2IO }
     } );
-    this.shortTeethPoints = new ObservableArray( {
+    this.shortTeethPoints = new AxonArray( {
       tandem: dataPointsTandem.createTandem( 'shortTeethPoints' ),
-      phetioType: ObservableArrayIO( Vector2IO )
+      elementOptions: { phetioType: Vector2IO }
     } );
-    this.longTeethPoints = new ObservableArray( {
+    this.longTeethPoints = new AxonArray( {
       tandem: dataPointsTandem.createTandem( 'longTeethPoints' ),
-      phetioType: ObservableArrayIO( Vector2IO )
+      elementOptions: { phetioType: Vector2IO }
     } );
 
     // @public visibility of each data set, on the graph and data probe
@@ -291,17 +290,17 @@
 
 /**
  * Records a count if it differs from the previous data point.
- * @param {ObservableArray.<Vector2>} observableArray
+ * @param {AxonArray.<Vector2>} array
  * @param {number} generation - floating point, not integer!
  * @param {number} count
  */
-function recordCount( observableArray, generation, count ) {
-  assert && assert( observableArray instanceof ObservableArray, 'invalid observableArray' );
+function recordCount( array, generation, count ) {
+  assert && assert( array instanceof AxonArray, 'invalid observableArray' );
   assert && assert( NaturalSelectionUtils.isNonNegative( generation ), 'invalid generation' );
   assert && assert( NaturalSelectionUtils.isNonNegativeInteger( count ), 'invalid count' );
 
-  if ( observableArray.length === 0 || observableArray.get( observableArray.length - 1 ).y !== count ) {
-    observableArray.push( new Vector2( generation, count ) );
+  if ( array.length === 0 || array[ array.length - 1 ].y !== count ) {
+    array.push( new Vector2( generation, count ) );
   }
 }
 
Index: js/common/view/population/PopulationPlotNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/population/PopulationPlotNode.js	(revision 3a7db5e5add741a522257855e6d0ae92f3781f42)
+++ js/common/view/population/PopulationPlotNode.js	(date 1594387144864)
@@ -7,7 +7,7 @@
  * @author Chris Malley (PixelZoom, Inc.)
  */
 
-import ObservableArray from '../../../../../axon/js/ObservableArray.js';
+import AxonArray from '../../../../../axon/js/AxonArray.js';
 import Property from '../../../../../axon/js/Property.js';
 import Shape from '../../../../../kite/js/Shape.js';
 import merge from '../../../../../phet-core/js/merge.js';
@@ -28,13 +28,13 @@
 
   /**
    * @param {PopulationModel} populationModel
-   * @param {ObservableArray.<Vector2>} points - data points, in model coordinates (x=Generation, y=Population)
+   * @param {AxonArray.<Vector2>} points - data points, in model coordinates (x=Generation, y=Population)
    * @param {Property.<boolean>} plotVisibleProperty - whether this plot is visible
    * @param {Object} [options]
    */
   constructor( populationModel, points, plotVisibleProperty, options ) {
     assert && assert( populationModel instanceof PopulationModel, 'invalid populationModel' );
-    assert && assert( points instanceof ObservableArray, 'invalid points' );
+    assert && assert( points instanceof AxonArray, 'invalid points' );
     assert && AssertUtils.assertPropertyOf( plotVisibleProperty, 'boolean' );
 
     options = merge( {
@@ -122,7 +122,7 @@
       // to find this index is not critical.
       let firstIndex = 0;
       for ( let i = numberOfPoints - 1; i >= 0; i-- ) {
-        const point = this.points.get( i );
+        const point = this.points[ i ];
         if ( point.x < this.xRangeProperty.value.min ) {
           firstIndex = i;
           break;
@@ -132,7 +132,7 @@
       // For mutant plots (drawn with a lineDash), adjust lineDashOffset so that the dash appears to scroll.
       // See https://github.com/phetsims/natural-selection/issues/111
       if ( this.isDashed && this.points.length > 0 ) {
-        const firstPoint = this.points.get( firstIndex );
+        const firstPoint = this.points[ firstIndex ];
         const xRemainderModel = firstPoint.x % 1;
         const xRemainderView = this.modelToViewX( xRemainderModel );
         this.stepPath.lineDashOffset = -( xRemainderView % MUTANT_LINE_DASH_SUM );
@@ -144,7 +144,7 @@
       // Plot from left to right
       for ( let i = firstIndex; i < numberOfPoints; i++ ) {
 
-        const point = this.points.get( i );
+        const point = this.points[i];
 
         if ( this.xRangeProperty.value.contains( point.x ) ) {
 
Index: js/common/model/DataProbe.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/DataProbe.js	(revision 3a7db5e5add741a522257855e6d0ae92f3781f42)
+++ js/common/model/DataProbe.js	(date 1594387144872)
@@ -125,8 +125,8 @@
     let count = 0;
 
     // Optimize for scrolling graph. Start with most recent points and work backwards in time.
-    for ( let i = points.length - 1; i >=0; i-- ) {
-      const point = points.get( i );
+    for ( let i = points.length - 1; i >= 0; i-- ) {
+      const point = points[ i ];
       if ( generation >= point.x ) {
         count = point.y;
         break;

```

</details>

**Comment by pixelzoom** [comment]
This looks nice.  But I'm hesitant to use it in Natural Selection because of potential performance problems.

Calling any mutator on AxonArray creates a copy (`slice`) of the entire AxonArray, then iteration over both the copy and the mutated array, for the purposes of discovering differences. When 900+ bunnies are born (Bunny instances are created) at the start of generation 6, they will be added 1 at a time via PhetioGroup.  And that will result in 900+ copies of the AxonArray being made, as each Bunny instance is added to BunnyCollection `this.liveBunnies`. 

I have similar performance concerns about the use in PopulationModel.js (the patch provided in https://github.com/phetsims/axon/issues/308#issuecomment-656688011).  These arrays will potentially contain up to 3000 points each. Is AxonArray scalable? Will the sim slow down as the number of array elements increases? 

It's important to consider and test the performance of any collection implementation.  And the way that PhET tends to do this (by trying it in a sim that doesn't fully exercise it, and/or waiting until there are performance problems) is inefficient and expensive. Collection performance should be a consideration during initial implementation, because it will inform the implementation.  So I'll be interested to see how a large AxonArray performs.

**Comment by samreid** [comment]
There were indeed performance problems with the original version.  I revised it and checked performance using this harness:

```js
// performance test
const a = new AxonArray();
const start = Date.now();
for ( let i = 0; i < 100000; i++ ) {
  a.push( { object: 'literal' } );

}
const t2 = Date.now();
console.log( 'elapsed time = ', ( t2 - start ) );
```

The prior version crashed the browser, the new version runs in 167ms.

Some notes and questions:
* I left `AxonArray.copyWithin` unimplemented (throws an error).
* I left `AxonArray.fill` unimplemented (throws an error).
* All other `AxonArray` mutators have been optimized, and I wrote unit tests to check their behavior.
* I'm considering renaming `itemAddedEmitter` to `elementAddedEmitter` etc.  Sound OK?

@pixelzoom can you please review at your convenience?

**Comment by pixelzoom** [comment]
The doc says some variation of this in 3 places:

```js
>  * The only unsupported Array mutation feature is:
>  *
>  * myArray.length = 0;
```

But I see that `copyWithin` and `fill` are also not supported, and they are most definitely mutators.

**Comment by samreid** [comment]
Thanks, I revised that part of the documentation.

**Comment by pixelzoom** [comment]
> The doc says some variation of this in 3 places: ...

You fixed one.  I fixed the other in the above commit.

**Comment by samreid** [comment]
Excellent, thanks!

**Comment by pixelzoom** [comment]
I haven't gotten to the reviewing the performance changes yet.  But I do have some API comments:

- [ ] Constructor

Should AxonArray constructor support providing an initial set of elements or initial length?  Having to use `push` to populate an AxonArray (as in AxonArrayTests.js) is inconvenient.  Is there any reason why we can't support the same constructor signatures as Array?  Array's constructor signatures are:

```
new Array(element0, element1[, ...[, elementN]])
new Array(arrayLength)
```

- [ ] Methods that return a new Array

Array has a number of methods that return a new Array: `from`, `concat`, `filter`.  How do we want these to behave for AxonArray?  Should they be overridden to return an AxonArray?  Consider examples like:

```js
// Example 1
const axonArray = new AxonArray();
axonArray.push( 1 );
const array = axonArray.concat( [ 2 ] );  // AxonArray returns an Array?

// Example 2
const axonArray = new AxonArray();
axonArray.push( 1 );
const array = [ 2 ];
array = array.concat( axonArray );  // odd?
```

**Comment by samreid** [comment]
> new Array(element0, element1[, ...[, elementN]])

That won't work exactly because we want to support a final `options` argument.  But how about passing an array as an optional first argument?
```js
new AxonArray([1,2,3],{my:options});
new AxonArray({my:options}); // also OK
new AxonArray(); // also OK
```

> Must their arg be of type {AxonArray}, {Array}, either?

To maintain polymorphic subtyping, the argument type should remain `{Array}`.  If it requires an `{AxonArray}` then it is no longer interchangeable with the parent type. (Contravariant parameter types).

> Should they be overridden to return {AxonArray}?

The purpose of `AxonArray` is to make it easy to add listeners and phet-io instrumentation.  That seems rare to want to want to instrument the result of one of the array methods, or add listeners to it.  And if we did want to support that, we would have to augment the methods with a new options argument, like:

```js
array = axonArray.concat(regularArray,{tandem: tandem.createTandem('concattedArray')}) // not recommended
```

Instead, it seems simpler to return `{Array}` and in the cases where an `AxonArray` is desired, to convert at the call site like so:

```js
const axonArray2 = new AxonArray(axonArray.concat(regularArray),{tandem: tandem.createTandem('concattedArray'});
```

**Comment by zepumph** [comment]
>To maintain polymorphic subtyping, the argument type should remain {Array}. If it requires an {AxonArray} then it is no longer interchangeable with the parent type. (Contravariant parameter types).


Feel free to nix this idea, but I think it would be more phet-like to not support polymorphism in constructor signtaure, and instead just support everything desired through a single, options arg:

```js
new AxonArray( {length: 5} );
new AxonArray( { values: [ 1,2,3,4,5] } )
new AxonArray( { tandem: tandem.createTandem( 'helloArray' ) } ) // empty array
```

I know this goes away supporting/mimicking `Array`'s api, and would be fine not doing this. I just thought I would recommend a single signature that supports all features.

**Comment by pixelzoom** [comment]
Proposal in https://github.com/phetsims/axon/issues/308#issuecomment-659720934 sounds good to me. `length` and `values` options should be mutually exclusive.

**Comment by pixelzoom** [comment]
Stopping my review of performance, because this implementation is buggy.  `lengthProperty` is not being updated. 

Example:

```
> var a = new phet.axon.AxonArray()
undefined
> a.length
0
> a.lengthProperty.value
0
> a.push( 1 )
1
> a.length
1
> a.lengthProperty.value
0
```

**Comment by pixelzoom** [comment]
Stopping my review of performance, because this implementation is buggy.  `lengthProperty` is not being updated.  This also point to a deficiency in unit tests. 

Example:

```
> var a = new phet.axon.AxonArray()
undefined
> a.length
0
> a.lengthProperty.value
0
> a.push( 1 )
1
> a.length
1
> a.lengthProperty.value
0
```

**Comment by samreid** [comment]
I updated `lengthProperty` on mutation, and added a basic unit tests for `lengthProperty` under push and pop.

**Comment by samreid** [comment]
I added more unit test coverage and another fix in the commit.  This should no longer block performance testing.

**Comment by samreid** [comment]
In the commit, I renamed "item" to "element".

**Comment by samreid** [comment]
I added constructor `options.values` and `options.length`.  

There is a new problem that I could use help with.  When invoking 

```js
const deletedElements = Array.prototype.splice.apply( this, arguments );
```

from splice, somehow this ends up invoking the subtype constructor with a number argument.  I'm concerned the current handling will create an inconsistent state for the AxonArray, and not allow us to error out when `AxonArray({number})` is called.

**Comment by samreid** [comment]
I added a commit that addresses the 1st concern, but I'm not sure what to do about the 2nd concern other than adding a lint rule.  I'l leave it up for discussion as part of the review.

**Comment by pixelzoom** [comment]
@samreid said:
> In the commit, I renamed "item" to "element".

Should options.values be renamed to options.elements? 

I also don't see any unit test for an attempt to initialize with invalid elements.  Something like:

```js
new AxonArray( {
  values: [ 'a', 'b' ],
  elementOptions: {
    valueType: 'number'
  }
} );
```

**Comment by pixelzoom** [comment]
@samreid said:
> In the commit, I renamed "item" to "element".

Should options.values be renamed to options.elements? 

I also don't see any unit tests that involve `elementOptions`.  For example:

```js
// should succeed
new AxonArray( {
  values: [ 'a', 'b' ],
  elementOptions: {
    valueType: 'string'
  }
} );

// should fail
new AxonArray( {
  values: [ 'a', 'b' ],
  elementOptions: {
    valueType: 'number'
  }
} );
```

**Comment by pixelzoom** [comment]
A couple more comments about AxonArrayTest.js....

(1) There's a set of unit tests that deal with `length`:

```js
QUnit.test( 'Test axon array length', function( assert ) {
 ...
} );
```

Not one of them actually checks `length`, they all check `lengthProperty.value`.  

(2) This is test for the `values` option:

```js
  const a2 = new AxonArray( {
    values: [ 'hi', 'there' ]
  } );
  assert.equal( a2.length, 2, 'array length test' );
```

This is an insufficient test. Checking length does not guarantee that the array was initialized with the correct elements, in the correct order.

**Comment by pixelzoom** [comment]
Re the changes that were made for performance...  Many methods fire an emitter, then update `lengthProperty`.  That order seems very problematic, because `lengthProperty` will be out of sync, especially in cases like `push` and `unshift` where the emitter may fire multiple times before `lengthProperty` is updated.   Are you assuming that listeners to `elementAddedEmitter` and `elementRemovedEmitter` cannot use `lengthProperty`?  That's an unreasonable constraint, and not documented.

I would think that it would be better to update `lengthProperty` before firing emitters, and to update `lengthProperty` incrementally in `push`/`unshift` loops.   E.g.:

```js
  // @public
  push() {
    const result = Array.prototype.push.apply( this, arguments );
    for ( let i = 0; i < arguments.length; i++ ) {
      this.lengthProperty.value = this.length;
      this.elementAddedEmitter.emit( arguments[ i ] );
    }
    return result;
  }
```

This concludes my review. Back to @samreid.

**Comment by samreid** [comment]
I addressed the recommendations.  Back to @pixelzoom for re-review.  Can you also comment on overall game plan?  Should we deprecate `ObservableArray` and recommend using `AxonArray` instead?  Should we rename `AxonArray`?  There are 132 occurrences of ObservableArray, should any of them be ported to `AxonArray`?

**Comment by pixelzoom** [comment]
> I addressed the recommendations. Back to @pixelzoom for re-review.

Changes look good.

I'm not clear what "I'm not sure what to do about the 2nd concern" is referring to in https://github.com/phetsims/axon/issues/308#issuecomment-661939044.   Are you referring to support for methods that return a new Array, as mentioned in https://github.com/phetsims/axon/issues/308#issuecomment-659572320.  Should they return a new AxonArray?  I'm not clear on where we landed on that question. 

The implementations of `pop` and `unshift` look like they could be simplified a bit.  Local variable `hasElement` is not really necessary, and it's not necessary to set `this.lengthProperty` if the array is empty. For example:

```diff
Index: js/AxonArray.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/AxonArray.js	(revision 571ed8f322a9815e3634a041cafe79a66bbcbf95)
+++ js/AxonArray.js	(date 1595889824064)
@@ -139,10 +139,11 @@
   pop() {
 
     // Supports notifying for [...,undefined]
-    const hasElement = this.length > 0;
     const removedElement = Array.prototype.pop.apply( this, arguments );
-    this.lengthProperty.value = this.length;
-    hasElement && this.elementRemovedEmitter.emit( removedElement );
+    if ( removedElement !== undefined ) {
+      this.lengthProperty.value = this.length;
+      this.elementRemovedEmitter.emit( removedElement );
+    }
     return removedElement;
   }
 ```

> Can you also comment on overall game plan?  Should we deprecate `ObservableArray` and recommend using `AxonArray` instead?  Should we rename `AxonArray`?  There are 132 occurrences of ObservableArray, should any of them be ported to `AxonArray`?

I much prefer AxonArray to ObservableArray.  I recommend deprecating ObservableArray. Whether I spend the time to convert my sims to AxonArray is up to PhET management.  I'm currently responsible for only 5 sims that use ObservableArray.  Natural Selection is at a critical point, a bit risky to convert, but that's up to PhET.

**Comment by samreid** [comment]
Thanks for the review.  I recommend opening the remaining points in new issues so they can be threaded separately.  I'll open them then close this parent issue.

**Comment by samreid** [comment]
I moved all remaining discussion topics to new issues.  I'll close for now, but please reopen or add new issues as appropriate.
