### ISSUE TITLE
TinyProperty._value isn't up to date in link

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/axon#309]
It looks like some Properties wait to update their `_value` until `get()` is called with the `onAccessAttempt` function. This is used by Properties of Node, like

```js
  this.boundsProperty = new TinyStaticProperty( Bounds2.NOTHING.copy() );
  this.boundsProperty.onAccessAttempt = boundsInvalidationListener;
  this.boundsProperty.changeCount = boundsListenersAddedOrRemovedListener;
```

In https://github.com/phetsims/sun/issues/444#issuecomment-658933682, I encountered an issue where the value passed to the callback eagerly called by `link` was incorrect (old) because we use `this._value` instead of `this.get()` to call `onAccessAttempt`.

```js
  link( listener ) {
    this.addListener( listener );

    listener( this._value, null, this ); // null should be used when an object is expected but unavailable
  }
```

Should that listener be using `this.get()`? What about other usages of `this._value`?

**Comment by zepumph** [comment]
Pinging @jonathanolson as I am working on https://github.com/phetsims/sun/issues/444 and not seeing a better way to solve this than @jessegreenberg's thoughts above.

**Comment by jessegreenberg** [comment]
I encountered this again trying to link to Node.boundsProperty.  My temporary fix was to get the bounds from the node in the callback instead of using the listener param:
```js
      node.boundsProperty.link( bounds => {

        // bounds param is out of date here, use get instead
        doSomethingWithBounds( node.bounds );
      } );
```

This seems like it could cause other problems, @jonathanolson do you have any thoughts on https://github.com/phetsims/axon/issues/309#issue-657583000?

**Comment by jonathanolson** [comment]
It seems best to call `this.get()` in that case, so we have the up-to-date value.

**Comment by jessegreenberg** [comment]
Oh, this is actually the same as https://github.com/phetsims/scenery/issues/1103 where it was suggested to use get() in link and notifyListeners. Ill close this and move over there.
