### ISSUE TITLE
Property.once can be fired multiple times if the observer triggers other changes to the property

### ISSUE THREAD

**Issue by jbphet** [phetsims/axon#31]
The Property.one function doesn't unlink the observer until after it fires it, which means that if the observer causes some action which triggers another change to the property, the observer can get fired again.  It would be better to first unlink the observer and then invoke it so the observer doesn't end up getting called multiple times.

For reference, this issue was discovered while working on the interaction between orphan release and animation observers in the Area Builder simulation.

**Comment by samreid** [comment]
Both Property.once and Events.once look like they are unlinking before callbacks are made.  @jbphet anything else to be done here?

**Comment by jbphet** [comment]
Nope, closing.
