### ISSUE TITLE
TinyEmitter allows addListener when disposed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#310]
TinyEmitter.addListener (and therefore Emitter.addListener and Property.link) happily allows you to add a listener after it has been disposed.  Not until you call `emit` will you discover your error.

Example:

```js
> var emitter = new phet.axon.Emitter()
undefined
> emitter.addListener( () => {} )
undefined
> emitter.emit()
undefined
> emitter.dispose()
undefined
> emitter.addListener( () => {} )
undefined
> emitter.emit()
assert.js:21 Assertion failed: should not be called if disposed
assert.js:22 Uncaught Error: Assertion failed: should not be called if disposed
    at window.assertions.assertFunction (assert.js:22)
    at TinyEmitter.emit (TinyEmitter.js:54)
    at Emitter.js:33
    at Emitter.execute (Action.js:225)
    at Emitter.emit (Emitter.js:58)
    ...
```

Shouldn't this be more robust, and detect the programming error at the `addListener` site, rather than waiting for `emit`?

Look like this has been the case since Emitter was first created, so assigning to the original author @samreid.

**Comment by samreid** [comment]
I made this change, added a unit test and tested phet-brand aqua and everything came out clear.  I'll commit momentarily.

**Comment by samreid** [comment]
Committed.  @pixelzoom can you please review at your convenience?  Should this block publication until the review is complete?

**Comment by pixelzoom** [comment]
Looks good. Closing.
