### ISSUE TITLE
Should new AxonArray({number}) fail?

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#311]
From https://github.com/phetsims/axon/issues/308

When invoking 

```js
const deletedElements = Array.prototype.splice.apply( this, arguments );
```

from splice, somehow this ends up invoking the *subtype* constructor with a number argument. That is, it calls the `AxonArray` constructor with a `{number}`.

Thus the constructor has to be documented like so:

```js
  /**
   * @param {Object|number} [options] - Support construction via splice(), which invokes the sub-constructor
   */
  constructor( options ) {
```

Do we need a way to guard against simulations calling `new AxonArray(3)`?  Right now that isn't caught.  We cannot make that a shorthand for `new AxonArray({length:3})` because that would have different semantics for the subtype invocation.

Other options:
* Add a code review item or lint rule preventing `new AxonArray({number})`
* Push/pop a counter in methods like splice that call `AxonArray.constructor`.  Throw an assertion error if `AxonArray({number})` is called with counter===0

**Comment by pixelzoom** [comment]
Why are you calling `Array.prototype.splice.apply( this, arguments )` instead of `super.splice( arguments )` ?

**Comment by pixelzoom** [comment]
> Support construction via splice(), which invokes the sub-constructor

I'm unable to verify that AxonArray's constructor is called when `splice` is called. What am I doing wrong?

I added a `console.log` here, in AxonArray constructor:

```js
    if ( typeof options === 'number' ) {
      console.log( `calling constructor with ${options}` );
      super( options );
      return;
    }
```

I don't see that log message when exercising AxonArray `splice`:

```
> var a = new phet.axon.AxonArray( { elements: [ 1, 2, 3 ] } ) 
undefined
> a.splice( 0, 1 )
AxonArray [1]
```

**Comment by samreid** [comment]
I tried the same code in natural-selection-main and I did see the console.log statement.  Want to schedule a zoom call?

**Comment by samreid** [comment]
I also tried a `debugger` and ran the axon unit tests, and it was triggered.

**Comment by pixelzoom** [comment]
I do see the console.log now. My browser must've been caching (which has been happening chronically since updating to Chrome 84).

**Comment by pixelzoom** [comment]
We definitely don't want to be calling `new AxonArray( {number} )` in sim code. But I'm not sure what the best solution is for preventing that.  

What is the answer to my question in https://github.com/phetsims/axon/issues/311#issuecomment-665177597?

> Why are you calling `Array.prototype.splice.apply( this, arguments )` instead of `super.splice( arguments )` ?

**Comment by samreid** [comment]
> Why are you calling `Array.prototype.splice.apply( this, arguments )` instead of `super.splice( arguments )` ?

We cannot use `super.splice(arguments)` because it passes through the arguments object directly as a single argument (like `call`), but we need them to be spread out.  I think `const deletedElements = super.splice(...arguments);` would have the same functional behavior, but that probably requires more CPU/heap compared to `apply`.  Therefore `Array.prototype.splice.apply` seems preferable.

**Comment by pixelzoom** [comment]
Thanks for clarifying. 

I still don't know what's best for preventing calls to `new AxonArray( {number} )`.    Of the 2 options you proposed in https://github.com/phetsims/axon/issues/311#issue-666642149, the lint rule seems easiest.   But you should get other opinions.

**Comment by samreid** [comment]
For now, I have forbidden `new AxonArray({number})` via a lint rule.

**Comment by samreid** [comment]
Public Service Announcement about AxonArray and not calling it with `{number}`.

**Comment by pixelzoom** [comment]
The PSA is actually that no one should be using this yet in production code, right?

**Comment by samreid** [comment]
It looks like there are other issues for developer meeting about the game plan for AxonArray, so this public service announcement will be a brief one about not calling it with `{number}`.

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/natural-selection/issues/178, @samreid converted natural-selection to use AxonArray.  In subclass `BunnyArray extends AxonArray`, he added this same bit of code that we've been discussing here:

```js
    // Support construction via Array.prototype.splice.apply(), etc., which invoke the sub-constructor
    if ( typeof options === 'number' ) {
      super( options );
      return;
    }
```

Hopefully we can find a better solution, because having to duplicate this in all subclasses is very undesirable.

**Comment by samreid** [comment]
At today's meeting, @zepumph recommended overriding methods that return `Array` so that we can assert that the argument is not a number, and that we can return `Array` instances instead of the subtype?

It sounds promising, I'll go for it!

**Comment by pixelzoom** [comment]
... similarly in https://github.com/phetsims/axon/issues/312#issuecomment-679317030, I said:
> ...  If it were me, I'd bail completely on extending Array. When there are this many weird problems, composition is definitely favored over inheritance.

**Comment by jonathanolson** [comment]
After doing a bit more diving into this, I'm trying to understand the use case for AxonArray over ObservableArray/Array. The doc says:

> AxonArray adds the ability to observe when elements are added or removed from an Array. This was created as an alternative to ObservableArray with the distinguishing change that this extends Array and hence uses the native Array API.

but, what is the advantage? I don't feel like I can suggest options without understanding the purpose.

> The PSA is actually that no one should be using AxonArray yet in production code, right?

I'm code-reviewing code that is using AxonArray, so this is coming up as part of https://github.com/phetsims/collision-lab/issues/153.

> The advantages of this proposal are:
> (a) implementations will be provided by the built-in Array type, and hence will be efficient and correct
> (b) we will not need to trigger any deoptimizations

Subtyping Array potentially includes performance issues, right? Has performance been tested? I also see a list of things that isn't supported.

**Comment by pixelzoom** [comment]
@brandonLi8 @jonathanolson I really don't think that AxonArray should be used in collision-lab.  It has too many problems, and any advantages that it might have had over ObservableArray feel like they are evaporating.

**Comment by brandonLi8** [comment]
@samreid one proposal could be to provide the [`Symbol.species`]( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/species) static getter.

With this:
```
  static get [Symbol.species]() { return Array; }
```
`filter`, `map`, etc. would return Array and we shouldn't need to override the default browser implementation. Thoughts?

**Comment by samreid** [comment]
`static get [Symbol.species]() { return Array; }` is exactly what we needed, thanks @brandonLi8!  I committed it above.  This allowed us to remove all of the workarounds related to calling the sub-constructor.

**Comment by pixelzoom** [comment]
JavaScript continues to amaze me (and not in a good way).

**Comment by samreid** [comment]
> I'm trying to understand the use case for AxonArray over ObservableArray/Array

* The main idea is that by subtyping `Array` we automatically get a uniform API that is consistent with the built-in Array API.
* Recent work was spurred by https://github.com/phetsims/axon/issues/283#issuecomment-654994805 which says:

>>  I'd also like to point out that `forEach` isn't the only method that exposes the underlying array which the user could modify. [...]

> That's the main reason why I avoid using those "convenience" methods of ObservableArray.  I think it's much clearer to call `getArray()` or `getArrayCopy()`, then use the Array API directly.

**Comment by samreid** [comment]
Thanks to @brandonLi8, the problem regarding "Should new AxonArray({number}) fail?" has been addressed, and this issue is ready to close.  However, there have been more general questions and comments by @pixelzoom and @jonathanolson which should be resolved or moved elsewhere first.

**Comment by brandonLi8** [comment]
I prefer sticking to AxonArray in collision lab.

To add onto what @samreid said in https://github.com/phetsims/axon/issues/311#issuecomment-679429777...

I believe (but not fully sure without performance tests) that AxonArray is actually more performant than ObservableArray because it is able to utilize native methods from Array which are optimized. 

I also believe it is more natural to have AxonArray to be an actual array instead of wrapping an array via composition (which ObservableArray does). From the CRC:

> - [ ]  Prefer the most basic/restrictive type expression when defining APIs. For example, if a client only needs to know that a parameter is {Node}, don’t describe the parameter as {Rectangle}.

I think this applies to my usages of AxonArray in Collision Lab. In some APIs, it is not necessary to know that the passed-in array is an AxonArray or an ObservableArray. In other API's, I need to register a listener (or something specific to AxonArray), in which I define my API to take in the AxonArray.

**Comment by jonathanolson** [comment]
I’ll look into this more tomorrow, including performance. The documentation also states that this is NOT API compatible with Array, since there are unsupported methods/getters/setters, so it seems *unsafe* in general to pass an AxonArray in place of an Array, no?

If those are the goals, I’m curious if Proxy has been tested (as it probably would have worse performance unfortunately), since it presumably wouldn’t suffer from any API compatibility drawbacks.

**Comment by pixelzoom** [comment]
Looks OK to me, unassigning.

**Comment by jonathanolson** [comment]
1. If we're passing subtyped arrays to things that expect vanilla arrays, it's a potential that code would need to get deoptimized to handle another type of array. My testing shows no major difference in Chrome/Safari, but a potential difference in Firefox (which could slow down our code in general, beyond the scope of what AxonArray is used for). This could drown out performance gains of the actual arrays, but may not also. Firefox showed a 19.5% +/- 2% REDUCTION in speed for code that has handled an AxonArray as an Array once.
2. The core behavior of AxonArray seems 10-20% faster (although AxonArray isn't doing duplicate checks or conditionals that may add some other overhead).
3. AxonArray doesn't seem API compatible for a lot of our needs. The core differences also trigger things like lodash's _.remove, _.pull, etc. to fail to notify, e.g.:

```
var arr = new axon.AxonArray();
arr.addItemAddedListener( item => console.log( `add ${item}` ) );
arr.addItemRemovedListener( item => console.log( `remove ${item}` ) );
arr.push( 1, 2, 3 ); // notifies
_.remove( arr, x => x === 2 ); // does not notify
_.pull( arr, 3 ); // does not notify
arr.length = 0; // does not notify (as expected)
```

4. We're adding in enumerable properties, is this an issue? `Object.keys( arr )` includes `["elementAddedEmitter", "elementRemovedEmitter", "lengthProperty", "axonArrayPhetioObject", "phetioElementType"]`
5. We don't need prototype references here? `AxonArray.prototype.push.apply( this, options.elements )` can be `this.push( ...options.elements )`? `Array.prototype.something` can be `super.something`, no?

So overall: this looks like it can be a cleaner ObservableArray with restrictions! However it seems unsafe to treat it as a general Array, both because of API reasons, AND because of the deoptimizations we can trigger in that case.

@samreid, @brandonLi8, @pixelzoom thoughts?

**Comment by jonathanolson** [comment]
Benchmarking committed above, should be testable with scenery/tests/benchmarking.html (there is other benchmarking code in that general location)

**Comment by samreid** [comment]
Results on my mac/chrome:

```
Creation#Array x 80,851,468 ops/sec ±2.68% (58 runs sampled)
Creation#ObservableArray x 26,569 ops/sec ±6.21% (63 runs sampled)
Creation#AxonArray x 27,056 ops/sec ±1.70% (63 runs sampled)
AssortedActions#Array x 718 ops/sec ±1.60% (61 runs sampled)
AssortedActions#ObservableArray x 71.20 ops/sec ±1.08% (53 runs sampled)
AssortedActions#AxonArray x 85.57 ops/sec ±0.85% (55 runs sampled)
Deopt#pure x 718 ops/sec ±0.36% (49 runs sampled)
Deopt#impure x 700 ops/sec ±2.78% (48 runs sampled)
```

Results on my Mac/Firefox:

```
Creation#Array x 10,962,687 ops/sec ±3.73% (55 runs sampled)
Creation#ObservableArray x 8,700 ops/sec ±6.42% (53 runs sampled)
Creation#AxonArray x 9,436 ops/sec ±2.47% (58 runs sampled)
AssortedActions#Array x 2,711 ops/sec ±2.26% (48 runs sampled)
AssortedActions#ObservableArray x 12.02 ops/sec ±2.02% (33 runs sampled)
AssortedActions#AxonArray x 15.80 ops/sec ±1.19% (29 runs sampled)
Deopt#pure x 2,274 ops/sec ±11.31% (17 runs sampled)
Deopt#impure x 1,978 ops/sec ±0.44% (14 runs sampled)
```

**Comment by samreid** [comment]
> `_.remove( arr, x => x === 2 ); // does not notify`

Lodash unfortunately calls `Array.prototype.splice(array)` instead of `array.slice`.

**Comment by samreid** [comment]
> 5. We don't need prototype references here? `AxonArray.prototype.push.apply( this, options.elements )` can be `this.push( ...options.elements )`? `Array.prototype.something` can be `super.something`, no?

I was concerned that our Babel step would do something suboptimal for `this.push(...options.elements)`.  For instance, babel targeting es2015 converts 

```js
    // A
    AxonArray.prototype.push.apply( this, options.elements );
    
    // B
    this.push(...options.elements);
```

to

```js
    // A
    AxonArray.prototype.push.apply(_assertThisInitialized(_this), options.elements);

    // B
    _this.push.apply(_this, _toConsumableArray(options.elements));
```

That being said, `this.push(...options.elements)` does read nicer, and maybe `prototype.push.apply` is a premature optimization?

**Comment by samreid** [comment]
Should we prototype a `Proxy`-based solution that aims for 100% safety?

**Comment by jonathanolson** [comment]
> Should we prototype a Proxy-based solution that aims for 100% safety?

If that doesn't cause deoptimizations or performance loss, that would be great! I fear it's likely to cause performance loss, but could be worth a try. Probably worth some checks with performance.

**Comment by samreid** [comment]
I'm interested in prototyping that.  I'll self assign, but also leave marked for developer meeting in case we have time to touch base and get a shared sense of what is acceptable on the performance/safety tradeoff spectrum.

**Comment by samreid** [comment]
Can you recommend how to proceed with Array + Proxy and subclassing?  For instance, we have `BunnyArray extends ObservableArray` and adds methods and attributes.  But I don’t see a clear way to do that with `Proxy`, which cannot be subclassed like `class MyClass extends Proxy`.  The "return a different object from the constructor" pattern appears to be used commonly as an alternative, but then I don't see how subclassing would work for that.  Or should we say that subclassing would not be possible if we use Proxy?

**Comment by samreid** [comment]
We would like to experiment with `Proxy` to have full support for `array.length=...` and `array[3]=differentObject`.  However, that will probably have the following disadvantages:
1. lower performance
2. more difficulty in code navigation (e.g. navigating to an AxonArrayProxy method)
3. difficulty extending AxonArrayProxy, like `BunnyArray extends AxonArrayProxy`

For developer meeting: are any of these dealbreakers?  Does anyone know a way around (3)? - more detail on that in previous comment.

**Comment by zepumph** [comment]
We discussed this at developer meeting today, and feel like `Proxy` is worth investigation, as nothing above feels like a total "deal breaker", although it seems like a bummer to not be able to use inheritance.

We are most excited about 100% (or close to) api coverage of native Array. This will help convert arrays to this new type.

**Comment by samreid** [comment]
I'll pursue the Proxy-based approach in new issue #330.

**Comment by samreid** [comment]
On hold pending results in #330

**Comment by samreid** [comment]
#330 is working well and does not suffer from this problem, closing.
