### ISSUE TITLE
Should AxonArray array methods return Array or AxonArray?

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#312]
@pixelzoom asked:

> Are you referring to support for methods that return a new Array, as mentioned in https://github.com/phetsims/axon/issues/308#issuecomment-659572320?  Should they return a new AxonArray?  I'm not clear on where we landed on that question.

**Comment by samreid** [comment]
In https://github.com/phetsims/axon/issues/308#issuecomment-659696840 I recommended leaving `Array` as the return type:

The purpose of `AxonArray` is to make it easy to add listeners and phet-io instrumentation.  That seems rare to want to want to instrument the result of one of the array methods, or add listeners to it.  And if we did want to support that, we would have to augment the methods with a new options argument, like:

```js
array = axonArray.concat(regularArray,{tandem: tandem.createTandem('concattedArray')}) // not recommended
```

Instead, it seems simpler to return `{Array}` and in the cases where an `AxonArray` is desired, to convert at the call site like so:

```js
const axonArray2 = new AxonArray(axonArray.concat(regularArray),{tandem: tandem.createTandem('concattedArray'});
```

**Comment by pixelzoom** [comment]
This sounds reasonable to me. But I think we should get some other opinions at developer meeting.

**Comment by jessegreenberg** [comment]
8/13/20

Reviewed this issue and all thought it was reasonable that functions returning an array return an `Array` rather than an `AxonArray` instance.

Closing.

**Comment by samreid** [comment]
Something funny is happening.  I hit a debugger in Natural Selection while in the mirror inputs wrapper in this branch: https://github.com/phetsims/natural-selection/issues/178

this.lengthProperty is coming up undefined in splice:

```js
  // @public
  splice() {
    const deletedElements = Array.prototype.splice.apply( this, arguments );
    this.lengthProperty.value = this.length;
    for ( let i = 2; i < arguments.length; i++ ) {
      this.elementAddedEmitter.emit( arguments[ i ] );
    }
    deletedElements.forEach( deletedElement => this.elementRemovedEmitter.emit( deletedElement ) );
    return deletedElements;
  }
```

slice is actually returning an `AxonArray`

![image](https://user-images.githubusercontent.com/679486/90413134-4e6b5180-e06b-11ea-9184-bb4f5c7092bf.png)

**Comment by samreid** [comment]
Even this small test has `y` as type `MyArray`

```js
  class MyArray extends Array {}
  const x = new MyArray();
  const y = x.slice(); // it's a MyArray
```

According to our developer meeting consensus, it should return a `Array` but this may be going against the grain of JavaScript.  It seems appropriate to use `super.slice`, but we don't want the expense of the full `AxonArray` constructor.  Maybe the overriden methods should guard themselves and support both?

**Comment by samreid** [comment]
I added guards in the overriden methods and added a unit test to make sure it doesn't fail any more.  @pixelzoom you are the most familiar with this implementation context from the review in #308.  What do you recommend?

**Comment by pixelzoom** [comment]
Wow. I'd love to have a discussion with whoever implemented Array. 

I'm guessing that this behavior is symptomatic of JavaScript's lack of real support for OO programming (`class` and other OO stuff is syntactic sugar, "lipstick on a pig").   Array obvious wasn't implemented as a proper class.  If it were me, I'd bail completely on extending Array.  When there are this many weird problems, composition is definitely favored over inheritance.

**Comment by samreid** [comment]
A note to myself to investigate returning `AxonArray` from its methods.  How many of our problems go away if we take that approach?

**Comment by samreid** [comment]
UPDATE: @brandonLi8 suggested a better way in https://github.com/phetsims/axon/issues/311#issuecomment-679376704

**Comment by samreid** [comment]
@brandonLi8's solution is working great, and we are correctly returning `Array` instead of `AxonArray` from all of the `AxonArray` methods.
