### ISSUE TITLE
The implementations of pop and unshift look like they could be simplified a bit.

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#313]
In https://github.com/phetsims/axon/issues/308#issuecomment-664677904 @pixelzoom said:

The implementations of `pop` and `unshift` look like they could be simplified a bit.  Local variable `hasElement` is not really necessary, and it's not necessary to set `this.lengthProperty` if the array is empty. For example:

```diff
Index: js/AxonArray.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/AxonArray.js	(revision 571ed8f322a9815e3634a041cafe79a66bbcbf95)
+++ js/AxonArray.js	(date 1595889824064)
@@ -139,10 +139,11 @@
   pop() {
 
     // Supports notifying for [...,undefined]
-    const hasElement = this.length > 0;
     const removedElement = Array.prototype.pop.apply( this, arguments );
-    this.lengthProperty.value = this.length;
-    hasElement && this.elementRemovedEmitter.emit( removedElement );
+    if ( removedElement !== undefined ) {
+      this.lengthProperty.value = this.length;
+      this.elementRemovedEmitter.emit( removedElement );
+    }
     return removedElement;
   }
 ```

**Comment by samreid** [comment]
It isn't accurate to use `removedElement !== undefined` because that gives the wrong value for arrays with `undefined` values, such as `[1,2,undefined,4]`.  Therefore, we should use `this.length>0` to determine if an element would be removed.

**Comment by pixelzoom** [comment]
Good point. Closing.
