### ISSUE TITLE
Game Plan for AxonArray

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#314]
In https://github.com/phetsims/axon/issues/308#issuecomment-662709935 I asked:

> Can you also comment on overall game plan?  Should we deprecate `ObservableArray` and recommend using `AxonArray` instead?  Should we rename `AxonArray`?  There are 132 occurrences of ObservableArray, should any of them be ported to `AxonArray`?

@pixelzoom replied:

> I much prefer AxonArray to ObservableArray. I recommend deprecating ObservableArray. Whether I spend the time to convert my sims to AxonArray is up to PhET management. I'm currently responsible for only 5 sims that use ObservableArray. Natural Selection is at a critical point, a bit risky to convert, but that's up to PhET.

Let's discuss this at an upcoming developer meeting.  Maybe before going "all in" we should schedule 1-2 developers to try AxonArray in a simulation (PhET and PhET-iO) to make sure it is a good fit and see if there are further changes to be made before wide adoption.

**Comment by pixelzoom** [comment]
AxonArray does not (and cannot) extend PhetioObject.  How do you propose to support PhET-iO?

**Comment by pixelzoom** [comment]
There are many ObservableArray methods that are not currently supported by AxonArray, including: shuffle, reduce, find, every, count, clear, remove, removeAll, add, addAll, reset, dispose.  How widely used are they? Should they be added to AxonArray?  This will affect ability to convert easily from ObservableArray to AxonArray.

`dispose` in particular must be implemented, to clean up `elementAddedEmitter`, `elementRemovedEmitter`, and `lengthProperty`.

**Comment by samreid** [comment]
`ObservableArray.shuffle` appears unused.  `phet.joist.random.shuffle` would work out of the box for `AxonArray`.  I'm not sure whether we should add a convenience method for this on `AxonArray`.

`AxonArray.reduce` takes its implementation from `Array.prototype.reduce`. Same with `find` and `every`.

I don't think we should add every method from `ObservableArray` to `AxonArray`, let's be more careful to define the desired API for AxonArray, and keep in mind that compatibility between AxonArray <=> Array may be more important in the long run than compatibility between ObservableArray <=> AxonArray.

I agree we will need to implement dispose.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/axon/issues/314#issuecomment-664782246:
> AxonArray does not (and cannot) extend PhetioObject. How do you propose to support PhET-iO at the AxonArray level? Don't we need AxonArrayIO?

Thoughts on this @samreid ?

**Comment by samreid** [comment]
I don't think `AxonArray` instances need to be instrumented.  For the data stream, it passes `tandem` to its children.  If a sim needs dynamic serialization, it should use `PhetioGroup` instead of `AxonArray`.

**Comment by pixelzoom** [comment]
In general:

* `AxonArray` is a replacement for `ObservableArray`.  Please explain why `ObservableArray` needed to be instrumented, but `AxonArray` does not.   Please explain why ``PhetioGroup` is now required for use with `AxonArray`.

In Natural Selection...  

* We have`BunnyArray extends ObservableArray`, and every instance of `BunnyArray` is currently instrumented (by request) with `phetioState: false`.  

* We have ObservableArray used throughout the Population graph to store {Vector2} points. There is no PhetioGroup involves. How will there points be saved/restored if AxonArray is not instrumented?

* We have ObservableArray used throughout the Proportions graph to store snapshots of bunny counts, {BunnyCounts}. How will there BunnyCounts be saved/restored if AxonArray is not instrumented?

**Comment by samreid** [comment]
> Please explain why `ObservableArray` needed to be instrumented, but `AxonArray` does not.

ObservableArray provided methods like `ObservableArray.addItemAddedListener` etc.  `AxonArray` provides these functions through its children like `AxonArray.elementAddedEmitter`, etc.

> How will points be saved/restored if AxonArray is not instrumented?

I was unaware how much `ObservableArrayIO` was responsible for serialization/deserialization.  I thought that feature was rarely used and that its deficiencies had led us to create `PhetioGroup`, but it looks like cases like the ones you mentioned, and probably more, are using `ObservableArrayIO` serialization.

I know we have also considered making `PhetioObject` a mixin.  If that is too complicated for the short term, perhaps we could create a child PhetioObject that manages the stateful parts of AxonArray.

It would be best to hear from @zepumph on all points in this comment.

**Comment by samreid** [comment]
I sketched out some ideas about adding a child `AxonArrayState` to manage the `AxonArray` state.  This is incomplete and not ready for testing, just a checkpoint for when I return to it later.

<details>

```diff
Index: js/AxonArrayState.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/AxonArrayState.js	(date 1597089838421)
+++ js/AxonArrayState.js	(date 1597089838421)
@@ -0,0 +1,37 @@
+// Copyright 2020, University of Colorado Boulder
+
+import PhetioObject from '../../tandem/js/PhetioObject.js';
+import axon from './axon.js';
+import validate from './validate.js';
+
+/**
+ *
+ * @author Sam Reid (PhET Interactive Simulations)
+ */
+
+class AxonArrayState extends PhetioObject {
+  constructor( axonArray, options ) {
+    super( options );
+
+    // @private
+    this.axonArray = axonArray;
+  }
+
+  // @public
+  toStateObject() {
+    return {
+      array: this.map( item => this.phetioType.toStateObject( item ) )
+    };
+  }
+
+  // @public
+  static applyState( observableArray, stateObject ) {
+    validate( observableArray, this.validator );
+    observableArray.clear();
+    const elements = stateObject.array.map( paramStateObject => this.phetioType.fromStateObject( paramStateObject ) );
+    observableArray.addAll( elements );
+  }
+}
+
+axon.register( 'AxonArrayState', AxonArrayState );
+export default AxonArrayState;
\ No newline at end of file
Index: js/AxonArrayStateIO.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/AxonArrayStateIO.js	(date 1597089156549)
+++ js/AxonArrayStateIO.js	(date 1597089156549)
@@ -0,0 +1,39 @@
+// Copyright 2020, University of Colorado Boulder
+
+import ObjectIO from '../../tandem/js/types/ObjectIO.js';
+import AxonArrayState from './AxonArrayState.js';
+import validate from './validate.js';
+import axon from './axon.js';
+
+/**
+ * AxonArrayStateIO is the IO Type for AxonArrayState. It delegates most of its implementation to AxonArrayState.
+ *
+ * @author Sam Reid (PhET Interactive Simulations)
+ */
+
+class AxonArrayStateIO extends ObjectIO {
+
+  // @public
+  static toStateObject( axonArray ) {
+    validate( axonArray, this.validator );
+    return axonArray.toStateObject();
+  }
+
+// @public
+  static stateToArgsForConstructor( state ) {
+    return AxonArrayState.stateToArgsForConstructor( state );
+  }
+
+  // @public
+  static applyState( axonArrayState, state ) {
+    axonArrayState.applyState( state );
+  }
+}
+
+AxonArrayStateIO.documentation = 'IO Type for AxonArrayState';
+AxonArrayStateIO.validator = { isValidValue: value => value instanceof AxonArrayState };
+AxonArrayStateIO.typeName = 'AxonArrayStateIO';
+ObjectIO.validateSubtype( AxonArrayStateIO );
+
+axon.register( 'AxonArrayStateIO', AxonArrayStateIO );
+export default AxonArrayStateIO;
\ No newline at end of file
Index: js/AxonArray.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/AxonArray.js	(revision 1ba0a88f2abaa8a762f3ec6c350d7ea9629e3b43)
+++ js/AxonArray.js	(date 1597089229190)
@@ -25,6 +25,7 @@
 import merge from '../../phet-core/js/merge.js';
 import Tandem from '../../tandem/js/Tandem.js';
 import axon from './axon.js';
+import AxonArrayState from './AxonArrayState.js';
 import Emitter from './Emitter.js';
 import NumberProperty from './NumberProperty.js';
 import ValidatorDef from './ValidatorDef.js';
@@ -54,6 +55,9 @@
       tandem: Tandem.OPTIONAL,
       elementOptions: {
         // Supports validator keys, including phetioType (for instrumented instances)
+      },
+      stateOptions: {
+        // Supports phetioState: true and phetioType (for stateful, instrumented instance)
       }
     }, options );
 
@@ -88,6 +92,8 @@
     if ( options.elements.length > 0 ) {
       AxonArray.prototype.push.apply( this, options.elements );
     }
+
+    this.axonArrayState = new AxonArrayState( this, options.stateOptions );
   }
 
   /**

```

</details>

**Comment by zepumph** [comment]
In dev meeting today @samreid mentioned that eventually he will want to take this into a sim for a test drive. I recommended Charges and Fields as an option because it has an ObservableArray that is populated with PhET-iO dynamic elements. Good luck, and let me know if I can be of assistance.

**Comment by samreid** [comment]
Charges and Fields has this ObservableArray:

```js
    // Observable array of all active electric charges (i.e. isActive is true for the chargeParticle(s) in this array)
    // This is the relevant array to calculate the electric field, and electric potential
    // @public {ObservableArray.<ChargedParticle>}
    this.activeChargedParticles = new ObservableArray( {
      phetioType: PropertyIO( ChargedParticleIO )
    } );
```

However, running the simulation in the state wrapper with particles in the play area did not show any state for this (no entries for `array`.  Likewise, putting debuggers in `ObservableArrayIO` serialization code didn't get hit.

Instead, I worked with Natural Selection to get the PhET-iO state working for AxonArray, and from what I can tell it is working nicely.  Unit tests are passing.  State wrapper is working nicely.  Inspection of the state data looks as expected.  I'll commit the changes for AxonArray, then open a branch issue for those changes in Natural Selection.

**Comment by samreid** [comment]
Responding to the unanswered questions:

> AxonArray does not (and cannot) extend PhetioObject. How do you propose to support PhET-iO at the AxonArray level? Don't we need AxonArrayIO?

AxonArray instrumentation is provided by its children, including AxonArrayState which has AxonArrayStateIO.

> There are many ObservableArray methods that are not currently supported by AxonArray, including: shuffle, reduce, find, every, count, clear, remove, removeAll, add, addAll, reset, dispose. How widely used are they? Should they be added to AxonArray? This will affect ability to convert easily from ObservableArray to AxonArray.

I implemented 4 methods like this to enable interoperability in Natural Selection.  We will have to discuss as a team which of those should be deprecated/removed or if we want to add support for more.  I'm happy with these 4 as an interim solution to assist in moving away from ObservableArray.

> dispose in particular must be implemented, to clean up elementAddedEmitter, elementRemovedEmitter, and lengthProperty.

I implemented dispose in the commit.

> How will points be saved/restored if AxonArray is not instrumented?

This is accomplished via AxonArrayState (an implementation detail for AxonArray).

> How will BunnyCounts be saved/restored if AxonArray is not instrumented?

This is accomplished via AxonArrayState (an implementation detail for AxonArray).

**Comment by pixelzoom** [comment]
Re providing PhET-iO support for AxonArray...

In https://github.com/phetsims/natural-selection/issues/178#issuecomment-675162248, I noted:
> * `AxonArrayStateIO` is a new pattern (delegate) for instrumenting a class that can't use inheritance. The implementation looks clean in this case. But where the client might expect to see "IO Type: AxonArrayIO", they see "IO Type: AxonArrayStateIO", which could be a little confusing. Has this pattern been discussed amongst the iO team? Would a `PhetioObject` mixin be a better longterm solution? I'm hesitant to expose this in the PhET-iO API until this is solid.

In https://github.com/phetsims/natural-selection/issues/178#issuecomment-676632364, @samreid said:
> @zepumph @chrisklus and I discussed this today. @zepumph thought it could just take 1/4 of a day to try porting PhetioObject to be a mixin. I was skeptical that it could be done so quickly, but even if it could be done quickly, I'm hesitant to use mixins instead of standard inheritance because static analysis doesn't work for mixins (even with ES6 pattern). For instance, autocomplete, navigation, highlighting does not work for mixins, so I argued that we may prefer the proposed composite pattern anyways.

**Comment by samreid** [comment]
Labeling for developer meeting to discuss names for ObservableArray and AxonArray.

**Comment by samreid** [comment]
@zepumph: It looks like the composition approach for AxonArray is reasonable and we don't need to go for a PhetioObject as a mixin at the moment.  Maybe in the future we will have more need for it.

@pixelzoom: I feel good about the composition pattern now that we discussed making the nested class a private implementation detail.

**Comment by samreid** [comment]
I applied the recommendations from dev meeting.  Tested and verified in the natural selection axon-array branch, closing.
