### ISSUE TITLE
bug in AxonArray unshift?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#315]
```js
  unshift() {
    const result = Array.prototype.push.apply( this, arguments );
    ...
```

Should this be calling `Array.prototype.unshift`? 

If so, is there a missing/incorrect unit test for AxonArray `unshift`?

**Comment by samreid** [comment]
Fixed and added a test to verify the correct behavior, ready for review.

**Comment by pixelzoom** [comment]
Looks good. Closing.
