### ISSUE TITLE
Add option to link for ignoring during set state

### ISSUE THREAD

**Issue by chrisklus** [phetsims/axon#319]
From discussion in https://github.com/phetsims/natural-selection/issues/117, @samreid and I investigated a couple possibilities for reducing the number of times we add the guard `if ( !phet.joist.sim.isSettingPhetioStateProperty.value ) {` in sim code. Since it often occurs in Property `link`s, we thought there might be a way to automate this more.

Here is an example from ShakerParticle.js:

```js
solution.soluteProperty.link( () => {

  // Remove all particles, unless solute was being restored by PhET-iO. Particles will be restored by particlesGroup.
  if ( !phet.joist.sim.isSettingPhetioStateProperty.value ) {
    this.removeAllParticles();
  }
} );
```

First, we thought we could add another function `liveLink` that would just wrap `link` in the above if statement. We thought it looked pretty nice, but would be undesirable to have both `liveLink` and `liveLazyLink`.

```js
solution.soluteProperty.liveLink( () => {
  this.removeAllParticles();
} );
```

To keep the link function names the same, we thought an option pattern might be nicer:

```js
solution.soluteProperty.link( () => {
  this.removeAllParticles();
}, { phetioCallbackState: false } );
```

We think it's not the best, but perhaps better than having as many guards as we do now. And this wouldn't eliminate all of the cases since there can be some code that needs to run in the link call even when setting state, or sometimes the guard is used elsewhere besides links.

**Comment by pixelzoom** [comment]
Since this wouldn't eliminate use of `phet.joist.sim.isSettingPhetioStateProperty.value`, I guess I have a slight preference for continuing to use it, versus adding an additional (less obvious?) way of doing the same thing.

**Comment by zepumph** [comment]
> Since this wouldn't eliminate use of `phet.joist.sim.isSettingPhetioStateProperty.value`, I guess I have a slight preference for continuing to use it, versus adding an additional (less obvious?) way of doing the same thing.

Agreed!
