### ISSUE TITLE
Assertion failed: phetioID already registered: axon.general.thirdProperty

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#320]
Discovered while working on https://github.com/phetsims/axon/issues/316, and this will show up in CT now because of https://github.com/phetsims/perennial/issues/191. I'll take the lead on the issue. 

In this test:
`PropertyStateHandler: Order dependency between NumberProperty and its Range (1, 1, 2)`

```

Error: Assertion failed: phetioID already registered: axon.general.thirdProperty
    at window.assertions.assertFunction (http://localhost:8080/assert/js/assert.js:22:13)
    at PhetioEngine.phetioObjectAdded (http://localhost:8080/phet-io/js/phetioEngine.js:426:36)
    at Object.addPhetioObject (http://localhost:8080/phet-io/js/phetioEngine.js:625:49)
    at Tandem.addPhetioObject (http://localhost:8080/tandem/js/Tandem.js:166:38)
    at Function.launch (http://localhost:8080/tandem/js/Tandem.js:352:27)
    at Object.<anonymous> (http://localhost:8080/axon/js/PropertyStateHandlerTests.js:103:12)
    at runTest (http://localhost:8080/sherpa/lib/qunit-2.10.0.js:3048:29)
    at Test.run (http://localhost:8080/sherpa/lib/qunit-2.10.0.js:3034:5)
    at http://localhost:8080/sherpa/lib/qunit-2.10.0.js:3265:11
    at processTaskQueue (http://localhost:8080/sherpa/lib/qunit-2.10.0.js:2621:23)

**Comment by zepumph** [comment]
The immediate problem was making sure that tests properly disposed the instrumented elements that they created, cleaning up each individual test. That was a pretty simple exercise, but I ran into api validation errors when trying to "dispose static elements". I'll get to my solution for this in a second.

Next. . . . this is maybe the fifth time now that I have dealt with the weirdness of `Tandem.launch()` in tests while in PhET-iO brand. So I decided to factor that out to a central location. Up until this point, I felt like it has been important to only launch Tandem when desired for a test, but more phet-io tests creating instrumented elements want to use it, so I now think it is best in a central location, especially because (if needed) we have `Tandem.unlaunch()` to reset it. 

To fix api validation and to factor out usages of Tandem.launch(), I added these to qunitStart for PhET-iO brand. It is working well, and now axon tests are working. @samreid can you please review my changes. I'm specifically interested in what you think about turning of phetioAPIValidation always in unit tests. It is a bit scary, but it feels largely out of the scope of unit tests. Perhaps if it is needed, individual tests/modules can turn it back on?

**Comment by samreid** [comment]
I reviewed the changes and agree phetioAPIValidation should be disabled for unit tests by default.    All the questions I have from this review are already covered in other issues, like this part:

https://github.com/phetsims/tandem/blob/24fcefcf056ec2173e5493903f3601db96cc2ef6/js/PhetioObjectTests.js#L128-L132

```js
  // launch to make sure tandem registration fires listeners
  Tandem.launch();

  // TODO Failing! because Tandem.launch() doesn't recalculate phetioIsArchetype, see https://github.com/phetsims/tandem/issues/147
  // assert.ok( phetioObject1Child.phetioIsArchetype, 'should be an archetype now that tandem is launched' );
```

I think this issue can be closed, but back to @zepumph to see if there is anything else first.
