### ISSUE TITLE
Rename AxonArray

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/axon#321]
While discussing https://github.com/phetsims/axon/issues/312 @jbphet mentioned that AxonArray requires that you understand what "axon" is and context.  This issue is to brainstorm alternatives and rename. AxonArray is really an Observable array, so ObservableArray is nice. We could name it that after we remove existing ObservableArray.

To do this eagerly, we could rename ObservableArray to ObservableArrayDeprecated, then we could rename AxonArray to ObservableArray. But this is dependent on whether we eagerly remove ObservableArray. It may stay with us for a while, especially if we chip away at removing it. We should decide if it is worth the effort.

**Comment by jessegreenberg** [comment]
Adding to developer meeting agenda to discuss another time, after some other work related to AxonArray is complete.

**Comment by samreid** [comment]
Other AxonArray work is complete.  I propose:

* Rename ObservableArray => ObservableArrayByComposition
* Rename ObservableArrayIO => ObservableArrayByCompositionIO
* Rename AxonArray => ObservableArray
* Rename AxonArrayState => AxonArrayPhetioObject
* Rename AxonArrayStateIO => ObservableArrayIO

These changes would address 2 of the bullet points in https://github.com/phetsims/natural-selection/issues/178#issuecomment-675162248

**Comment by samreid** [comment]
@pixelzoom asks about `ObservableArrayDeprecated` instead of `ObservableArrayByComposition`.

@zepumph asks about naming it to `ObservableArrayPhetioObjectIO` to better match with its core type.  Or we could deviate type name from the filename.  In our code it could be `ObservableArrayDeprecated` and in the API it could be `ObservableArrayByComposition`.

**Comment by zepumph** [comment]
I logged whenever an instrumented ObservableArray was made in a phet-io standalone sim. Here is the list of sims that have these:

```
energy-skate-park
energy-skate-park-basics
states-of-matter
molecules-and-light
natural-selection
phet-io-test-sim
forces-and-motion-basics
circuit-construction-kit-dc
```

**Comment by samreid** [comment]
I added more methods to `AxonArray` to enhance compatibility with the `ObservableArray` API and most things are working nicely.  I don't think it will be too much effort to port things from ObservableArray to AxonArray, so I think it would be safe to follow the renames as prescribed above.  Still, I would like to hedge my bets and wait until #311 discussion completes.

**Comment by samreid** [comment]
`AxonArray` has been deleted and we would like to use `createObservableArray` instead, closing.
