### ISSUE TITLE
enforce tandem.name.endsWith( 'Property' ) in Property constructor

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#322]
Property currently requires that tandem.name.endsWith( 'Property' ).  @zepumph and I expected to find this enforced in the constructor.  Instead its in PropertyIO.  It should be moved to Property

**Comment by zepumph** [comment]
Tagging parent issue; https://github.com/phetsims/sun/issues/615

**Comment by zepumph** [comment]
Done above, in the same style as work in https://github.com/phetsims/sun/issues/615 for `RadioButtons` and `ComboBoxListItem`.

Aqua fuzzing in phet and phet-io brand is clear. Closing

**Comment by pixelzoom** [comment]
> Aqua fuzzing in phet and phet-io brand is clear. Closing

I'm not sure how aqua missed it, but normal-modes is failing.  See phetsims/normal-modes#55.
