### ISSUE TITLE
Should we guard or short circuit validate calls (that don't return a value)?

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#323]
From https://github.com/phetsims/tandem/issues/200 @pixelzoom said:

> Thanks for doing that.  This is a nice "quick fix" for this specific problem in `initializePhetioObject`. 
> 
> And now `initializePhetioObject` is using `validate` differently than all other uses.  I see 150 other occurrences of `validate`, all making unnecessary function calls when assertions are disabled.   Some of these are in critical code -- in a `for` loop in Action.js, throughout serialization methods in IO types, ...
> 
> Should other uses of `validate(...)` be changed to use the `assert && validate(...)` pattern?    Or should `validate` be re-written to be like assert, i.e. `validate && validate(...)`?
> 
> Maybe something like:
> 
```js
let validate = assert && ( value, validator, options ) => {

  // Throws an error if not valid
  ValidatorDef.isValueValid( value, validator, merge( { assertions: true }, options ) );
  return value;
};
 validate = validate || null;

axon.register( 'validate', validate );
export default validate;
```
> 
> Hmmm... I guess that won't work for cases like this that are relying on `validate` returning a value:
> 
```js
// wave-interference.Scene
   this.waveSpatialType = validate( config.waveSpatialType, { validValues: Scene.WaveSpatialType.VALUES } );
```

**Comment by samreid** [comment]
I'm seeing around 170 occurrences of `validate(` but only 21 occurrences of ` = validate(`, all of the latter in wave interference Scene.js.

What about using `assert && validate()` where possible?

**Comment by pixelzoom** [comment]
Yes, we could use the `assert && validate` pattern elsewhere.  But it seems redundant to also be checking `assert` inside of `validate`.   And while `assert && assert(...)` is a nice pattern, `assert && someOtherFunction(...)` is imo questionable.  But I'll go along with whatever the dev team decides.

**Comment by samreid** [comment]
I'm fine with `assert && validate()`.  I'd prefer not to pursue `validate && validate()`, because it seems like too much overhead for something that should be simple.  But maybe we want to investigate a different name for the constant that indicates a line can be stripped from the build.  But `unbuilt && assert()` doesn't sound that good to me.  I've just talked myself into liking `assert && validate()` even more!  But it sounds like we should discuss at dev meeting to get a consensus.

**Comment by zepumph** [comment]
@jonathanolson mentioned that the best way to handle stripping this out would be on build. Perhaps using an AST operation to remove `validate()` calls.

1. @samreid will refactor the identity function part of validate used in `WAVE_INTERFERENCE/Scene.js`, and remove support for that in the library
2. We want to investigate a build process solution to strip things out that is more advanced than our current uglify global for `assert`. We didn't decide who might take this on though, so I'll keep this marked for dev meeting, and make it high priority so that we get back to it next week.

**Comment by samreid** [comment]
I converted Wave Interference to avoid the return value, and I removed the return value.  Local aqua testing is fully green except for density which looked like a separate problem.  Leaving labeled for dev meeting so we can pursue better patterns for stripping out assert and validate calls.

**Comment by samreid** [comment]
I noticed terser has an option for "pure_funcs" in the "compress" section and I tried adding "validate" to that list, but it didn't strip out because that code looks like this:

```js
    Object(validate["a" /* default */])( config.graphHorizontalAxisLabel, VALID_STRING );
    Object(validate["a" /* default */])( config.scaleIndicatorLength, POSITIVE_NUMBER );
```

**Comment by samreid** [comment]
Is there a way to run terser with pure_funcs before webpack runs (as a plugin or something)?

**Comment by Denz1994** [comment]
From Dev Meeting on 09/24/20:

The current priority is figuring out how to remove cases in build artifacts that contain `Object(validate...`. Because this will involve investigating build tools @jonathanolson will take a look when he has time.

@zepumph suggested forcing assertions to be stripped out of built sims and assertions always enabled in unbuilt sims. This is also in an effort to remove `assert &&` except in cases where slow assert is used.

@pixelzoom: We should still be able to generate a debug version with assertions enabled. Third-party devs will also have to honor assertions during development.

**Comment by jonathanolson** [comment]
Do we want validation in cases where assertions are stripped out (e.g. phet-io?). What happens if a client sets invalid data, if we fail an assertion it prevents an invalid thing from happening?

**Comment by samreid** [comment]
Looking through the usages of `validate`, it seems like nearly all of them can be eliminated and replaced by TypeScript.  Most are just checking types.  PhET-iO uses code like `getValidationError` which should not be stripped out.  So it seems unimportant whether we guard or short-circuit validate calls, we should start using TypeScript instead. This can be done lazily as we visit sims instead of eagerly.  Should we close this issue?  Should we open any side issues?  @zepumph or @jonathanolson what do you think?

**Comment by zepumph** [comment]
There are only 70 usages of validate() that I see on the project, I think we should get rid of them and the function entirely. Instead we should:

1. See if it is redundant with TypeScript type checking
2. Convert it to an assertion
3. Use Validation.getValidationError() if we have to

**Comment by jonathanolson** [comment]
I'm fine closing the issue and removing them when things are converted. Or leave this open to remove typescript-existing ones?

**Comment by zepumph** [comment]
How about we just mark it as deprecated. Is that acceptable so people don't think it is still the way of doing things?

**Comment by zepumph** [comment]
Hows that?

**Comment by samreid** [comment]
That works great for me, thanks! It would be even nicer if WebStorm would strikethrough usages. But for some reason that's not happening now. But I think this is good enough.  @jonathanolson or @zepumph please reopen if there's more to do.  Closing.
