### ISSUE TITLE
improve DerivedProperty.dispose

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#327]
In DerivedProperty.dispose:

```
    // Unlink from dependent Properties
    for ( let i = 0; i < this.dependencies.length; i++ ) {
      const dependency = this.dependencies[ i ];
      if ( !dependency.isDisposed ) {
        dependency.unlink( this.dependencyListeners[ i ] );
      }
    }
```

That code makes the assumption that if `!dependency.isDisposed`, then its listeners have been purged. 

This would be more robust:

```js
    // Unlink from dependent Properties
    for ( let i = 0; i < this.dependencies.length; i++ ) {
      const dependency = this.dependencies[ i ];
      const dependencyListener = this.dependencyListeners[ i ];
      if ( dependency.hasListener( dependencyListener ) {
        dependency.unlink( dependencyListener );
      }
    }
```

DerivedProperty also assumes that `this.dependencies` and `this.dependencyListeners` are indexed identically, which isn't documented anywhere and seems brittle.   I suggest that we at least document it.

Assigning to @samreid and @zepumph for feedback.

**Comment by samreid** [comment]
I agree the proposal looked more robust, and I couldn't think of any problems with it, or find any problems when exercising it in the unit tests.  I committed it, and made similar changes to Multilink, and converted the 2nd array to a `Map` so we don't have to keep indices in step.  Ready for review.

**Comment by pixelzoom** [comment]
Skimmed the commit and ran unit tests. I don't see any problems. Thanks for doing this. Closing.
