### ISSUE TITLE
Webstorm intellisense not working for ArrayProxy

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#331]
See https://github.com/phetsims/axon/issues/330.  Testing with natural selection in the `createArrayProxy` branch, we see this in DataProbe.js:

![image](https://user-images.githubusercontent.com/679486/94559916-28ff6500-021f-11eb-9c7d-771901a2141a.png)

I tried a number of ideas for specifying the typedef, but could not get all of the following features working simultaneously:
* The typedef extends Array
* The typedef is parametric
* The typedef adds lengthProperty, elementAddedEmitter and elementRemovedEmitter

One possibility proposed in #330 was to invest in a new pattern that works well with Intellisense, by creating an actual class instead of a typedef.  This can be file-local (declared in createArrayProxy) and marked private, with documentation to indicate that it is solely for Intellisense:

```js
// @private - this is for Webstorm support only and should not be instantiated.
class ArrayProxyDef extends Array { // eslint-disable-line
  constructor() {
    assert && assert( false, 'This class is for documentation and Webstorm support only and should not be instantiated' );
    super();

    // NOTE: This is for Webstorm support only, you are probably looking for the lengthProperty defined below
    this.lengthProperty = new NumberProperty( 0 );

    // NOTE: This is for Webstorm support only, you are probably looking for the elementAddedEmitter defined below
    this.elementAddedEmitter = new Emitter();

    // NOTE: This is for Webstorm support only, you are probably looking for the elementRemovedEmitter defined below
    this.elementRemovedEmitter = new Emitter();
  }
}
```

Adding this to createArrayProxy.js and deleting ArrayProxyDef.js has good autocomplete, navigation, and intellisense.  @pixelzoom pointed out the disadvantages of this strategy:

> That looks dangerous (even with the assertion). I don't think we want an entire Array subclass masquerading/paralleling createArrayProxy.
> I'd rather live with the WebStorm complaints.

By making the class `ArrayProxyDef` private and well-documented, I think it could be acceptable.  But first, maybe it would be nice if someone with more expertise in typedefs could see if there is a workable typedef solution to this problem.  @zepumph can you please take a look at your convenience?

**Comment by zepumph** [comment]
Now I see 
![image](https://user-images.githubusercontent.com/6856943/99605743-c6238200-29b4-11eb-81ed-b35ddeff2ab2.png)

**Comment by zepumph** [comment]
I found that this is not because of the `Array` extending, but instead because of the adding on of Properties. When I apply this patch, there is no issue. This isn't a solution, but helps us understand the problem better.

```
Index: js/ObservableArrayDef.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/ObservableArrayDef.js	(revision 8c6331740e7d95a1821eddeede4a9b8cf51ecf26)
+++ js/ObservableArrayDef.js	(date 1605748261368)
@@ -11,9 +11,6 @@
 // TODO https://github.com/phetsims/axon/issues/331 WebStorm is having problems with {ObservableArrayDef} vs {Array} params
 /**
  * @typedef {Array} ObservableArrayDef
- * @property {Emitter} elementAddedEmitter
- * @property {Emitter} elementRemovedEmitter
- * @property {Property<Number>} lengthProperty
  * See createObservableArray for details
  */
 const ObservableArrayDef = {

```

**Comment by zepumph** [comment]
This has led me into the land of closure compiler syntax, and I will need to pick things up later.

https://closure-compiler-debugger.appspot.com/
https://intellij-support.jetbrains.com/hc/en-us/community/posts/207234329-JSDoc-error-Argument-type-null-is-not-assignable-to-parameter-type-string-

**Comment by samreid** [comment]
Maybe TypeScript can help us here.

**Comment by zepumph** [comment]
@samreid, this seems fixed to me. What about you?

**Comment by samreid** [comment]
It's working now, (probably thanks to TypeScript?).  Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
