### ISSUE TITLE
Determine an appropriate removal API for createObservableArray

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#332]
In https://github.com/phetsims/natural-selection/issues/252#issuecomment-702285672 we agreed on a pattern, but I'm not sure whether it was implemented yet.

@pixelzoom would you like me to add `remove` and `removeIfIncluded` to ObservableArrayProxy?

**Comment by pixelzoom** [comment]
In retrospect...  I don't need it for NS, and probably wouldn't convert anything in NS to use it.   So I'm OK with deferring this issue until we get around to deciding which parts of the ObservableArray-specific API to remove from ArrayProxy.  

If we do add a "remove" API to ArrayProxy...  Add `removeAll` to the list of methods to consider, and how that should behave for elements that aren't in the array.

**Comment by samreid** [comment]
> If we do add a "remove" API to ArrayProxy...  Add `removeAll` to the list of methods to consider, and how that should behave for elements that aren't in the array.

ArrayProxy already has `remove` and `removeAll` which are both "graceful"--that is to say, they both only remove something if it was present, and do not throw an error if it was not present.

One way to proceed for this issue:

Step 1: Rename `remove` => `removeIfIncludes` and `removeAllIfIncludes`.  Not sure if the term should be "included" or "includes" or if we should use the term "graceful".  Like `removeGraceful`.  Or if we frame it differently, like `removeOccurrences`, to imply that we are only removing the occurrences that appear (maybe sounds graceful?) This could go along with `removeAllOccurrences`.  But it sounds odd to have `removeAll` and `removeAllOccurrences` side-by-side (see Step 2).
Step 2: Add new methods `remove` and `removeAll` which are not graceful.

@pixelzoom can you please advise?  Or let me know if this warrants a dev-meeting label.

**Comment by pixelzoom** [comment]
I see no need for `removeAll` and `removeAllOccurrences`. `removeAll` is sufficient, regardless of the array length.

I have a preference for `remove` failing if element is not in the array.  It's in the same spirit as unlink and removeListener. And I can't remember when I needed to remove something that "might be" in an array -- if I did so it was more likely a programming error.  

I'm also not a fan of multiple "remove" methods, like `removeIfIncludes` or `removeGraceful`.  Keep the API lean.   If you need to conditionally remove, do it explicitly, like:

```js
observableArray.includes( element ) && observableArray.remove( element );
```

And that should be needed rarely. If I were to see that a lot in code, I would conclude that there's some sloppy/lazy programming going on.

I'm not sure what we should do about "remove all occurrences".  I'd be fine with leaving that up to the client, like:

```js
while( observableArray.includes( element ) ) {
  observableArray.remove( element );
}
```

Finally, I'm not a fan of using arrayRemove.js (it doesn't return the value returned by splice), or its use in createObservableArray.js.  What it's doing is so simple that I'd inline it and skip the extra function call.

**Comment by samreid** [comment]
I saw nearly 20 usages of `removeAll` so I'm inclined to keep it factored out.  When I change `removeAll` and `remove` to be non-graceful, here are the sims that fail aqua:

- [ ] area-model-decimals
- [ ] balancing-act
- [ ] build-a-fraction
- [ ] build-a-molecule
- [ ] charges-and-fields
- [ ] circuit-construction-kit-ac
- [ ] curve-fitting
- [ ] energy-forms-and-changes
- [ ] least-squares-regression
- [ ] optics-lab
- [ ] twixt
- [ ] unit-rates
- [ ] vector-addition

Tagging for developer meeting to agree on the way forward, potentially changing this to a chip-away issue.

**Comment by zepumph** [comment]
From dev meeting today. 

* We will keep `removeAll`
* @samreid will make `remove` and `removeAll` non-graceful, and surround all failing cases with a `contains` check and create an issue for the responsible dev to take care (if he thinks that is warranted). 

Thanks @samreid!

**Comment by samreid** [comment]
Alls sims have now passed fuzzing at least once.  I should not this is somewhat stochastic--a fuzz doesn't always trigger this error, so we may see more occurrences once on CT.  But it seems reasonable to commit.  I'll open side issues where more attention/review is warranted.

**Comment by samreid** [comment]
I messaged slack:

> As discussed in https://github.com/phetsims/axon/issues/332, createObservableArray.remove and removeAll are no longer graceful.  Any issues discovered on CT like “could not remove item that doesn’t exist” should get a new issue in the corresponding repo, with a link to #332

**Comment by samreid** [comment]
A couple of the occurrences were already documented about why they were graceful.  I opened issues for the other ones.  Newly discovered problems will be created in the appropriate issue (as mentioned 2 comments ago), closing.
