### ISSUE TITLE
Add unit tests to verify that lengthProperty is triggered before elementAdded/Removed

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#333]
From #330, 

```js
    //REVIEW https://github.com/phetsims/axon/issues/330 is this next comment true in general? Has that been thoroughly tested? Should this comment be moved to the header comment?
    // Set length first so it will be correct in elementListener callbacks
```

I revised the comment but opened this issue about "thoroughly testing".  I tested it once, but have not coded any unit tests for ongoing testing of this feature.  By inspection it looks like all the lengthProperty values are being set first.  I'm not sure it would be worth it to add unit tests for those 6 sites.

@pixelzoom what do you think?

**Comment by pixelzoom** [comment]
Imo, this is one of the more important unit tests, since it's a contract with the client that is very clear stated in this comment:

```js
When an item is added or removed, the lengthProperty changes before elementAddedEmitter or elementRemovedEmitter emit.
```

I've added a unit test in the above commit. @samreid please review.

**Comment by pixelzoom** [comment]
A more robust way to address this would be to not call `elementAddedEmitter.emit` and `elementRemovedEmitter.emit` directly. Instead, call these new (untested) private methods:

```js
notifyElementAdded( element ) {
  assert && assert( this.lengthProperty.value === this.length, 'lengthProperty must be set before calling elementAdded listeners' );
  this.elementAddedEmitter.emit( element );
}

notifyElementRemoved( element ) {
  assert && assert( this.lengthProperty.value === this.length, 'lengthProperty must be set before calling elementRemoved listeners' );
  this.elementRemovedEmitter.emit( element );
}
```

This would make the above unit test unnecessary, and would have a better chance of testing any further methods that have this same requirement.

@samreid what do you think? Should we make this change?

**Comment by pixelzoom** [comment]
I see that my unit test doesn't exercise `deleteProperty` and `reportDifference`.    This seems to strengthen the case for what I proposed in https://github.com/phetsims/axon/issues/333#issuecomment-707249780.

**Comment by samreid** [comment]
Yes, that seems like a good change. Please proceed or reassign to me if I should take that step.

**Comment by pixelzoom** [comment]
Rather than the changed I described in https://github.com/phetsims/axon/issues/333#issuecomment-707249780, I decided to try a simpler approach.  I added these lines immediately after the definition of `targetArray`:

```js
  // Enforce the requirement that lengthProperty is updated before listeners are notified.
  assert && elementAddedEmitter.addListener( () => {
    assert && assert( lengthProperty.value === targetArray.length, 'lengthProperty out of sync while adding element' );
  } );
  assert && elementRemovedEmitter.addListener( () => {
    assert && assert( lengthProperty.value === targetArray.length, 'lengthProperty out of sync while removing element' );
  } );
```

And now I'm seeing quite a few unit tests failing, eg:

<img width="954" alt="screenshot_578" src="https://user-images.githubusercontent.com/3046552/95784528-3beb4e00-0c91-11eb-8dab-8a71e311d330.png">

@samreid would you have some time to collaborate on this?

**Comment by samreid** [comment]
Thanks for the patch, I saw the same error--it looks like it internally sets array[0]=..., which triggers an element added emit before the length changes.  I'm not sure what can be done.  I'll reach out to you on slack regarding collaboration.

**Comment by pixelzoom** [comment]
Add done here, thanks for collaborating.
