### ISSUE TITLE
PhET-iO State Wrapper: Assertion failed: lengthProperty out of sync while removing element

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#338]
In #333 we added a check that the lengthProperty is correct when element added/removed listeners are called back.

This is showing for:
* CCK
* EFAC
* FAMB
* MAL
* PM

I'll take a look.

UPDATE: This is only happening in the phet-io state wrapper

**Comment by samreid** [comment]
During PhET-iO state set, the lengthProperty is deferred.  This means it cannot take the correct value when listeners are called.  I'm not sure how to get around this other than to avoid the assertion when the lengthProperty could be deferred:

```js
  // Verify that lengthProperty is updated before listeners are notified.
  assert && elementAddedEmitter.addListener( () => {
    if ( !lengthProperty.isDeferred ) {
      assert && assert( lengthProperty.value === targetArray.length, 'lengthProperty out of sync while adding element' );
    }
  } );
  assert && elementRemovedEmitter.addListener( () => {
    if ( !lengthProperty.isDeferred ) {
      assert && assert( lengthProperty.value === targetArray.length, 'lengthProperty out of sync while removing element' );
    }
  } );
```

@pixelzoom does this sound appropriate to you?

**Comment by samreid** [comment]
I'm fine with that too, but if the lengthProperty becomes deferred for other reasons we would also want to skip the checks.  I'm speaking hypothetically, I can't think of a case right now other than state where the lengthProperty should be deferred.

**Comment by pixelzoom** [comment]
> I can't think of a case right now other than state where the lengthProperty should be deferred.

Then it sounds like we should be checking isSettingPhetioStateProperty.

**Comment by samreid** [comment]
I committed a proposed fix that works on my side.  @pixelzoom can you please check the boolean expression?  I found it was being called before `phet.joist.sim` was assigned, so I had to guard against that.  

@zepumph is there a way to get the sequencing right in PhET-iO state, or is this workaround appropriate?

**Comment by zepumph** [comment]
The above helps unit tests pass in scenery where there is no `phet.joist`. I think I got the logic right, but it would be nice to get a double check on it.

**Comment by pixelzoom** [comment]
Looks good to me, and CT shows no problems.

If there's nothing else to do here, feel free to close.

**Comment by samreid** [comment]
I agree the logic seems good, but I'd like to leave this issue open for @zepumph about this comment:

> @zepumph is there a way to get the sequencing right in PhET-iO state, or is this workaround appropriate?

**Comment by zepumph** [comment]
Yes, this workaround seems to be in response to a lack of support for ordering non-Property PhetioObjects with Properties. I feel like we will eventually need to work on this, see issue for ObservableArray (https://github.com/phetsims/phet-io/issues/1661) and also for PhetioGroup (https://github.com/phetsims/phet-io/issues/1688). I am worried about this. Perhaps add a TODO to your workaround pointing to the observable array issue?

**Comment by samreid** [comment]
I added a TODO to the workaround, closing.
