### ISSUE TITLE
DerivedProperty should not extend Property

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#342]
As described in https://github.com/phetsims/sun/issues/641, DerivedProperty used a "hack" shortcut to share code with Property, but unfortunately needed these methods:

```js
  /**
   * Override the mutators to provide an error message.  These should not be called directly,
   * the value should only be modified when the dependencies change.
   * @param value
   * @override
   * @public
   */
  set( value ) { throw new Error( 'Cannot set values directly to a DerivedProperty, tried to set: ' + value ); }

  /**
   * Override the mutators to provide an error message.  These should not be called directly, the value should only be modified
   * when the dependencies change. Keep the newValue output in the string so the argument won't be stripped by minifier
   * (which would cause crashes like https://github.com/phetsims/axon/issues/15)
   * @param newValue
   * @override
   * @public
   */
  set value( newValue ) { throw new Error( 'Cannot es5-set values directly to a DerivedProperty, tried to set: ' + newValue ); }

  /**
   * Override the mutators to provide an error message.  These should not be called directly,
   * the value should only be modified when the dependencies change.
   * @override
   * @public
   */
  reset() { throw new Error( 'Cannot reset a DerivedProperty directly' ); }
```

Ideally, we would have a new type like `AbstractProperty` that is the parent for `DerivedProperty`.  

Some relevant notes:

> - A full refactoring of the `Property` type hierarchy might resolve this, but it would be prohibitively expensive, and might not work for things like `DynamicProperty`.  In this approach, the base type would essentially be immutable, and mutability would be added in a sub-type.
> - It was noted that we could just do nothing and probably be okay.  These cases, i.e. passing in `DerivedProperty` instances in places where `set` is need, are generally caught pretty quickly.

If/when we proceed on this, keep in mind TinyProperty and DynamicProperty.

**Comment by samreid** [comment]
In today's discussion, we agreed this is stable for now and not needed in the near future.  Setting priority accordingly.

**Comment by samreid** [comment]
Relates to #391

**Comment by samreid** [comment]
This issue came up today in the context of https://github.com/phetsims/axon/issues/193 and I have factored out AbstractProperty.  @jessegreenberg and @pixelzoom took a quick look at the proposal and agreed it is a good direction.  I have changes in 88 files so far, but there are still regressions indicated in multi-snapshot-comparison.html, so I'm not ready to commit yet.

**Comment by samreid** [comment]
Also, `RangedMappedProperty` doesn't appear to have any usages so will be removed in this commit.

**Comment by samreid** [comment]
After the commits, we have 12 TODOs labeled for this issue

**Comment by samreid** [comment]
For the TODO labeled in DynamicProperty, I experimented with this patch:

<details>

```diff

Index: js/DynamicProperty.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/DynamicProperty.ts b/js/DynamicProperty.ts
--- a/js/DynamicProperty.ts	(revision 74ec3ca911eaca0d35a2b2cfd05ba0addc057fde)
+++ b/js/DynamicProperty.ts	(date 1654173616203)
@@ -139,8 +139,7 @@
 // } );
 // Here, ThisValueType=number (we're a Property<number>). You've passed in a Property<Foo>, so OuterValueType is a Foo.
 // InnerValueType is what we get from our derive (Color), and what the parameter of our map is.
-// TODO: https://github.com/phetsims/axon/issues/342 Can OuterValueType default to IProperty?
-export default class DynamicProperty<ThisValueType, InnerValueType = ThisValueType, OuterValueType = Property<InnerValueType>> extends AbstractProperty<ThisValueType> {
+export default class DynamicProperty<ThisValueType, InnerValueType, OuterValueType> extends AbstractProperty<ThisValueType> {
 
   // Set to true when this Property's value is changing from an external source.
   isExternallyChanging: boolean;

```

</details>

But wasn't too confident about it.  @jonathanolson can you please advise?

**Comment by samreid** [comment]
Assigning to @jonathanolson for review.  @zepumph do you have time in the next week or two to review the phet-io aspect and see if work is required before the batch release?

**Comment by jonathanolson** [comment]
```js
// TODO https://github.com/phetsims/axon/issues/342 Move this to AbstractProperty
export { AbstractProperty };
```

Is that for circular dependency issues?

**Comment by jonathanolson** [comment]
Looks good, TODOs mark the things that look like they should be improved upon.

**Comment by zepumph** [comment]
Let me know if you want additional review, but it looks like JO got to it.

**Comment by samreid** [comment]
I addressed several TODOs for this issue.  The remaining two are for DynamicProperty and MappedProperty.  Assigning to @jonathanolson to collaborate on those parts, perhaps during the upcoming TypeScript sprint.

**Comment by samreid** [comment]
Since DerivedProperty no longer extends Property, I think this issue can be closed.  I'll move remaining work to side issues, then close.

**Comment by samreid** [comment]
Issues created and TODOs moved.  Closing.
