### ISSUE TITLE
Add optional assertion message to validate.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#346]
In phetsims/phet-io#1589 (comment), I identified impediments to PhET-iO instrumentation, including:
> (2) Cryptic assertion messages. These require knowledge of phet-io internals, and don't provide the value(s) that caused the problem. I'll try to note these as I encounter them, instead of powering through and moving on.

A good place to start would be to add an optional assertion message to validate.js.  Validators currently have no ability to tell me anything useful, because they lack an assertion message.  For example, see https://github.com/phetsims/tandem/issues/229.

The next step would be to go through PhET-iO (and other common code) and add informative assertion messages to existing validators.

**Comment by zepumph** [comment]
I like this idea. I think it would most easily be solvable by adding a `message` key to the validator itself, which I want to experiement with over in https://github.com/phetsims/axon/issues/347. I'll report back.

**Comment by zepumph** [comment]
@pixelzoom please review this just by looking at the change in PhetioObject, and testing it by adding a newline to your favorite line of phetioDocumentation. Does this feel like an adequate solution to you? If so please assign to @samreid to review the validator implementation.

**Comment by pixelzoom** [comment]
```js
* @param {Object|string} [optionsOrMessage] - see ValidatorDef.isValueValid() for options, or provide a string as a message instead.
...
const validate = ( value, validator, optionsOrMessage ) => {
```

Sorry to be blunt, but `optionsOrMessage ` is gross.  The lesser evil would be having the optional message be part of `options`, like `validate( value, validator, { message: 'blah blah' } )`.

I'm also not sure if having both a generic message and (optional) specific message is useful/neessary in ValidatorDef, but don't see any harm in having both. What if I want to write my own ValidatorDef? Am I required to have a generic message? How do I use `formulateAssertionMessage`, it's `@private`?

**Comment by samreid** [comment]
> Am I required to have a generic message? 

It sounds like the generic messages would be supplied by the library.  Like `'invalid value: 4.  The valid values are 1-3 only'`.  Then the specific message would be something like `acceleration value is out of range`

**Comment by zepumph** [comment]
>@pixelzoom please review this just by looking at the change in PhetioObject

Ugggg looks like that was only committed last night in https://github.com/phetsims/tandem/commit/b8fa64d34f560181a3ab15faf17fa765512c6053. I'm sorry.

Much of the confusion here is my fault.

Yes @samreid, the "generic" message is only provided via the library. 

>`validate( value, validator, { message: 'blah blah' } )`

I didn't really like that, because it would create garbage, and if you don't preface with `assert && validate`, then the garbage objects would be created even when assertions were disabled. IMO I would prefer polymorphism to that. 


>I'm also not sure if having both a generic message and (optional) specific message is useful/neessary in ValidatorDef. What if I want to write my own ValidatorDef? Am I required to have a generic message? How do I use formulateAssertionMessage, it's @private?

All of this is internal to the `ValidatorDef.js` library, and does not need to be exposed. The "generic" message is provided by the library to tell you what part of the `{ValidatorDef}` failed (i.e. `valueType` or `validValues`). The specific message would be what you think of as an assertion message, which you can provide wherever you call `validate`.


>What if I want to write my own ValidatorDef? Am I required to have a generic message?

The message is tied to the usage of a validator, and not the validator itself. I explored having a message built into the validator object over in https://github.com/phetsims/axon/issues/347, but it was too rigid, for example look at all the usages of `BOOLEAN_VALIDATOR` in 

https://github.com/phetsims/tandem/blob/b8fa64d34f560181a3ab15faf17fa765512c6053/js/PhetioObject.js#L164-L174

Each of those will want their own, "specific" assertion message.

Thus, all I wanted for a "client review" (by @pixelzoom or anyone), is discussion about what `validate()` and its call sites should look like. Basically I would love weigh-in on cleaning up the grossness of `validate` polymorphism without generating undo garbage (even with `?ea`, I would prefer to not house the message in an object). What do you two think?

**Comment by pixelzoom** [comment]
> Thus, all I wanted for a "client review" (by @pixelzoom or anyone), is discussion about what validate() and its call sites should look like.

Ideally:

```js
/**
 * @param {*} value
 * @param {ValidatorDef} validator
 * @param {string} [message]
 */
validate( value, validator, message )
```

Call sites:

```js
validate( phaseState, 
 { validValues: [ PhaseStateEnum.SOLID, PhaseStateEnum.LIQUID ] },  
 `This screen does not support phaseState ${phaseState}` );
```

But it looks like that's not possible because of this in validate.js:

```js
  ValidatorDef.isValueValid( value, validator, options );
```

Imo, those options should live with the validator, not be passed through via `validate`.

**Comment by zepumph** [comment]
> Ideally:
>`validate( value, validator, message )`

Yes, that would be really nice. Perhaps we should do this.

Cases where we use `options` in `validate()`:

* Action.js
* Property.js
* IOType.js

Three files out of 79 usages. I think we should treat this as the special case, to make the general case (third arg as a string) nicer.

My new thought is to make message the third arg, and options the 4th. Then in these three cases, just supply a message to each of them (it couldn't hurt).

**Comment by samreid** [comment]
The preceding comment sounds great!

**Comment by zepumph** [comment]
Sounds great. I'll implement

**Comment by zepumph** [comment]
After the above commit, I tested in three ways, each getting the assertion (with a nice, more specific message) that it deserved.

* Add `\n` to a phetioDocumentation, like in https://github.com/phetsims/tandem/issues/229
* To Bunny.js, add:
```js

    const x = new Emitter( {parameters: [{valueType: 'string'}]});
    x.emit( 1);
```

* To Bunny.js, add:
```js
    console.log( Bunny.BunnyIO.toStateObject( 3 ) );
```


All now have messages added to their `validate` calls. @pixelzoom please review before we pick this back up in https://github.com/phetsims/tandem/issues/229

**Comment by pixelzoom** [comment]
I don't understand this implementation of validate.js.  I don't see how `message` and `options` both being optional is (or can be) supported. 

These 3 permutations all work as expected:

> phet.axon.validate( false, { isValidValue: value => value } )
assert.js:21 Assertion failed: value failed isValidValue: false
> phet.axon.validate( false, { isValidValue: value => value }, 'my message' )
assert.js:21 Assertion failed: my message: value failed isValidValue: false
> phet.axon.validate( false, { isValidValue: value => value }, 'my message', {} )
assert.js:21 Assertion failed: my message: value failed isValidValue: false

This permutation is buggy:

> phet.axon.validate( false, { isValidValue: value => value }, {} )
assert.js:21 Assertion failed: [object Object]: value failed isValidValue: false

**Comment by zepumph** [comment]
It is my understanding that in javascript, you cannot (and should not) allow your buggy case. As that is not an example of optional parameters, but instead polymorphism. Multiple optional arguments are not ideal, but for reasons that we discussed in the above issue, we would let slide for this usage.

If you want to provide options, then you must provide a message. Although a bit clunky. I think this is well worth allowing for the flexibility of the optional message in the majority of cases, even though if (in the rare case) you want to supply options, then message is no longer optional.

**Comment by pixelzoom** [comment]
I see.  So this:

```js
 * @param {string} [message]
 * @param {Object} [options]
```

Means that `options` can be provided only if `message` is provided?

**Comment by pixelzoom** [comment]
If there's nothing else to here, feel free to close.
