### ISSUE TITLE
Should Property.equalsValue use an optimized version of value access?

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#349]
From https://github.com/phetsims/axon/issues/344

@zepumph said:
> > * @Protected
> >   */
> >   equalsValue( value ) {
> >   return this.areValuesEqual( value, this.get() );
> >   }
> 
> Using `get()` (a function) is a performance hit as opposed to what it was (this._value), is this low-level enough that it matters in the project?

So this introduces two get() function calls (not ES5 getters) where previously we just had a property access.  @jonathanolson do you think this should be optimized?

The main reason not to optimize is if we somewhere one day override `get()` similar to the situation in TinyStaticProperty.

**Comment by jonathanolson** [comment]
> do you think this should be optimized?

My first instinct is "measure it, make the change and see if it makes snapshot-comparison for all sims at all longer". I see potential advantages for `this.get()`, but also the possibility where that might be too expensive if we don't need it now.

**Comment by samreid** [comment]
I used this test harness:

```js
   */
  equalsValue( value ) {
    const a = performance.now();
    const value1 = this.get();
    const b = performance.now();
    const value2 = this.tinyProperty._value;
    const c = performance.now();

    assert && assert( value1 === value2, 'should be same' );

    x += ( b - a );
    y += ( c - b );

    console.log( x / 1000, y / 1000 );
    return this.areValuesEqual( value, value1 );
  }
```

Here are some results on my Mac/Chrome:

Fuzzing natural selection for 30 seconds: 0.063 sec vs 0.049 sec.  This is a difference of 0.014 seconds.
Startup time for gravity and orbits: 0.0015 sec vs 0.0007 sec.  This is a difference of 0.0008 seconds on startup.

Is this too slow?

**Comment by zepumph** [comment]
I do not think so. Thanks for creating the test harness!

**Comment by jonathanolson** [comment]
That looks like it doesn't have a significant impact for this.

**Comment by samreid** [comment]
Thanks, this issue is ready to close.
