### ISSUE TITLE
Problems with TinyForwardingProperty  setTargetProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#350]
TinyForwardingProperty:

```js
  /**
   * Sets (or unsets if `null` is provided) the Property that we use for forwarding changes.
   * @public
   *
   * @param {Node} node - The container of TinyForwardingProperty which supports updateLinkedElementForProperty()
   * @param {string|null} tandemName - null if the Property doesn't not support PhET-iO instrumentation
   * @param {TinyProperty.<*>|Property.<*>|null} newTarget - null to "unset" forwarding.
   * @returns {Node} - the passed in Node, for chaining.
   */
  setTargetProperty( node, tandemName, newTarget ) {
```

Problems with this method:

- [ ] `newTarget` does not follow PhET naming conventions, it should be `newTargetProperty`.
- [ ] `this.targetProperty` must be settable, and there is no assertion to verify that `newTargetProperty.isSettable()`.

Assigning to the authors.

**Comment by zepumph** [comment]
> this.targetProperty must be settable, and there is no assertion to verify that newTargetProperty.isSettable().


This is not true, like all other Property apis, it depends on how the TinyForwardingProperty is used. If you do not set it, but only get the value, then this works. I wrote tests to demonstrate. From this I added an assertion in a spot that likely doesn't feel very helpful or satisfying, as it is in `set` literally a line before anything unsettable would fail. 

Please review the above commits.

**Comment by pixelzoom** [comment]
> This is not true, like all other Property apis, it depends on how the TinyForwardingProperty is used. If you do not set it, but only get the value, then this works.


Ummm.... OK.  So you're saying that if I'm careful and don't use the parts of the API that expect `targetProperty` to be settable, then it's OK to use a non-settable Property.  That's a pretty lousy API desoign imo.   But I'm not going to push the issue. 

Closing.
