### ISSUE TITLE
BooleanProperty doesn't support validValues.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#359]
Sometimes.an API takes a Property, and you want to pass in a constant.  So you create a Property that can only take 1 value, like:

```js
    const dragBoundsProperty = new Property( options.dragBounds, {
      validValues: [ options.dragBounds ]
    } );
```

In Fourier, I have a chart that always auto-scales the y axis, and the chart's API takes a BooleanProperty.  So I tried this:

```js
    options.yAutoScaleProperty = new BooleanProperty( true, {
      validValues: [ true ]
    } );
```

... which fails with:

> Assertion failed: BooleanProperty does not support validValues

I can't tell for sure, but it looks like this prohibition of `validValues` was in the first version of BooleanProperty, created by @samreid.   Any reason why we can't change this?

The alternative is:

```js
    options.yAutoScaleProperty = new Property( true, {
      validValues: [ true ]
    } );
```

... which would be OK, as long as I don't have to eventually instrument it for PhET-iO.

**Comment by samreid** [comment]
Fixed in the commit.  I tested with `new BooleanProperty(true,{validValues:['hello']});` and saw that it correctly failed.  I tested with `new BooleanProperty(true,{validValues:[true]});` and saw that it correctly succeeded.  @pixelzoom can you please review and test in your context?

**Comment by pixelzoom** [comment]
Looks good, thanks. Tested with my use-case in Fourier, see the above commit. Closing.
