### ISSUE TITLE
Add support for summarizing Properties and how many observers they have

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#36]
In https://github.com/phetsims/reactants-products-and-leftovers/issues/18, @pixelzoom said:

> It sure would be nice if AXON had some support for summarizing Properties and how many observers they have.

Suggestions for an API?

**Comment by pixelzoom** [comment]
This would be a good topic for a developer-meeting discussion.

And idea (but no concrete suggestion for how to implement it):
- add a global AXON flag that enables debugging
- for every 'link' that occurs, record a stack trace
- for every 'unlink' that occurs, delete the associated stack trace
- provide a way to print out how many links exist (coarse means of seeing if this continues to go up)
- provide a (usable?) way to inspect all of the links (finer-grained means of investigating leaks)

**Comment by pixelzoom** [comment]
At 1/6/2015 design meeting, we discussed this, no one had any concrete solutions. Some type of coarse tool for determining if leaking is occurring would probably be the first thing to implement.  If anyone has ideas, please record them here.  In the meantime, low priority, unassigning.

**Comment by pixelzoom** [comment]
This issue has received little discussion in the 4+ years since it was created, so apparently there is no need for such a feature.  So I'm going to close this issue.
