### ISSUE TITLE
NumberProperty should optionally defer validation until next frame

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#364]
From https://github.com/phetsims/phet-io/issues/1824#issuecomment-963466220 and a slack conversation and an issue/workaround in Density involving `class WorkaroundRange`.

Range and the number are constantly having trouble with validation 
Some names:
`options.deferValidation`
`options.validateOnNextFrame` <-- lets do this one

Then we can assume that in the same frame the range and number will be set correctly. We only need one timeout, so don't create a new one each time range or number is set in an frame (just the one is good).

<details>

```diff
Index: js/NumberProperty.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/NumberProperty.js b/js/NumberProperty.js
--- a/js/NumberProperty.js	(revision 5b042219abc8dc9584d457ff3bd9a97ed6c844ba)
+++ b/js/NumberProperty.js	(date 1636397182146)
@@ -94,16 +94,22 @@
     // @private {function|null} validation for NumberProperty and its rangeProperty, null if assertions are disabled
     this.validateNumberProperty = assert && ( value => {
 
-      // validate for integer
-      ( options.numberType === 'Integer' ) && validate( value, VALID_INTEGER );
+      setTimeout( () => {
+
+        if ( !numberPropertychanged || rangePropertyChanged ) {
+
+          // validate for integer
+          ( options.numberType === 'Integer' ) && validate( value, VALID_INTEGER );
 
-      // validate range value type
-      validate( this.rangeProperty.value, { isValidValue: value => ( value instanceof Range || value === null ) } );
+          // validate range value type
+          validate( this.rangeProperty.value, { isValidValue: value => ( value instanceof Range || value === null ) } );
 
-      // validate that value and range are compatible
-      if ( this.rangeProperty.value ) {
-        validate( value, { isValidValue: value => this.rangeProperty.value.contains( value ) } );
-      }
+          // validate that value and range are compatible
+          if ( this.rangeProperty.value ) {
+            validate( value, { isValidValue: value => this.rangeProperty.value.contains( value ) } );
+          }
+        }
+      } );
     } );
 
     // @public (read-only) {Property.<Range|null>}


```

**Comment by zepumph** [comment]
NumberProperty.validateOnNextFrame was added above. @samreid, I think that in general it is pretty safe. It was a fair bit of code, but I feel pretty confident from the tests I made. Can you please review?

**Comment by zepumph** [comment]
Once this is reviewed, we should let @jonathanolson know so that he can remove his workaround in Density

**Comment by samreid** [comment]
TypeScript helped identify a few places where the value was incorrectly being passed to `validateNumberProperty`.  @zepumph can you spot check the subsequent commits about that?  Everything else looks good.

**Comment by zepumph** [comment]
@samreid showed me that the commit to look at is https://cuboulder.zoom.us/j/971965732

**Comment by zepumph** [comment]
@samreid showed me that the commit to review is https://github.com/phetsims/axon/commit/89a3c74863ea5d0f717ff3cb7d4d4f3e5d273cc5

**Comment by zepumph** [comment]
* Can we rename `Listener2`?
* In PropertyIO, can we make `this` be of type `Property` instead of `any`?


It would be nice to convert ValidatorDef at some point soon, but presumably we may be able to deprecate it since it is basically duplicating typescript functionality. 

Thanks for this conversion!

**Comment by zepumph** [comment]
@samreid and I decided to remove validateOnNextFrame today. WorkaroundRange is a bummer, but in the future it may be best to have the ability to have a Property that holds the min/max/value altogether.

**Comment by samreid** [comment]
Can this issue be closed?

**Comment by zepumph** [comment]
Sure!
