### ISSUE TITLE
Fix Property.link signature and call sites

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#365]
@chrisklus discovered that TypeScript should be inferring the Property.link callback parameters, but it isn't, due to numerous syntax errors in the Property JSDoc.  I'll fix it and update call sites.

**Comment by samreid** [comment]
The changes above make it so it is now redundant to specify the type information in Property.link callbacks.

Old code:

```ts
representationProperty.link( ( representation: Representation ) => {
```

New Code:

```ts
representationProperty.link( representation => {
```

However, this doesn't yet work with Property subtypes like BooleanProperty, NumberProperty, etc.  I'll remove the redundant type information from a few sims in the upcoming commits.

**Comment by samreid** [comment]
@chrisklus this was more involved than I anticipated.  Can you spot check?

**Comment by chrisklus** [comment]
@samreid and I looked over some cases together where I had questions and I just spot checked the rest of the commits. Looking good, closing.
