### ISSUE TITLE
Fix DerivedProperty parameter types

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#367]
Similar to #365 we can get better support if DerivedProperty's constructor JSDoc is more accurate.

**Comment by samreid** [comment]
Fixed in the commit.  This allowed refinement in geometric-optics and greenhouse.  @pixelzoom can you please review, at least the part in geometric-optics?

**Comment by pixelzoom** [comment]
DerivedProperty and geometric-optics look good.

**Comment by samreid** [comment]
Thanks, closing.
