### ISSUE TITLE
Problems with EnumerationProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#374]
A few of problems that I encountered when trying to use EnumerationProperty in geometric-optics:

(1) You can't set `validValues`, so you can't use EnumerationProperty with a subset of enumeration values:

```js
type EnumerationPropertyOptions<T> = Omit<PropertyOptions<T>, 'validValues' | 'phetioType'>;
```

This is problematic for many sims where I've used enumerations, and blocks my use of EnumerationProperty in geometric-optics.  Since PropertyOptions provides type-checking for `validValues`, I intended to make it an allowed option.

(2) These assertions are redundant, because these options are excluded by EnumerationPropertyOptions. They can be deleted. 

```js
assert && assert( !providedOptions || !providedOptions.hasOwnProperty( 'validValues' ), 'validValues is supplied by EnumerationProperty' );
assert && assert( !providedOptions || !providedOptions.hasOwnProperty( 'phetioType' ), 'phetioType is supplied by EnumerationProperty' );
```

(3) There's no need for `{}` as the first arg to `merge`, since `validValues` and `phetioType` can't possibly be in `providedOptions`. It would be better to put `providedOptions` as the last arg.

```js
    const options = merge( {}, providedOptions, {
      validValues: value.enumeration!.values,
      phetioType: Property.PropertyIO( EnumerationIO<T>( {
        enumeration: value.enumeration!
      } ) )
    } );
```

**Comment by pixelzoom** [comment]
Problems addresses in the above commit.

@samreid would you mind reviewing, since you and I discussed this issue on Slack?

**Comment by samreid** [comment]
I reviewed the commit, and it seems good.  Thanks also for removing the other assertion which is now unnecessary.  Closing.
