### ISSUE TITLE
Missing modifiers for DerivedProperty fields?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#376]
Are these fields in DerivedProperty really supposed to be public and directly mutable?  Or is `private` and `readonly` missing from some of these?

```ts
  dependencies: MappedProperties<Parameters> | null;
  derivation: Derivation<T, Parameters>;
  derivedPropertyListener: () => void;
```

**Comment by samreid** [comment]
I added some modifiers.  Type check is passing on my side.  @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
👍🏻 closing
