### ISSUE TITLE
Add ReadOnlyProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#377]
This work was started without an issue, but seemed like we should have one, so here it is.

**Comment by pixelzoom** [comment]
@jonathanolson commited ReadOnlyProperty in the above commit, but there were some problems.  See Slack discussion below.

<details>
<summary>Slack</summary>

[onathan Olson](https://app.slack.com/team/U6E4HHSTF)  [6:09 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646356162283089)
Added ReadOnlyProperty, see https://github.com/phetsims/axon/commit/2dc362b17edb24f6f465ef1ee46596eee1c071ce (did some brief type testing, seems like we don't have the ability to have TypeScript type-based unit tests no?)






[Chris Malley](https://app.slack.com/team/U6EMFARV2)  [6:38 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646357930247789)
Thanks for the heads up.  I don’t know about TypeScript type-based unit tests, hasn’t been on my radar.  Maybe ask SR/MK if there’s an issue to eventually get that happening?

[Jonathan Olson](https://app.slack.com/team/U6E4HHSTF)  [6:39 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646357972866939)
Ok will do

[Chris Malley](https://app.slack.com/team/U6EMFARV2)  [6:44 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646358291070669)
Boo hoo. I still can’t pass a ReadOnlyProperty to addLinkedElement(     element: PhetioObject,     options?: any): void.
[6:46](https://phetsims.slack.com/archives/D6FNMP2LX/p1646358405857589)
For example FocalPointNode.ts constructor param pointProperty.

[Jonathan Olson](https://app.slack.com/team/U6E4HHSTF)  [6:47 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646358441777559)
Hmm, checking

[Chris Malley](https://app.slack.com/team/U6EMFARV2)  [6:47 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646358453358009)
addLinkedElement has been my pain point.

[Jonathan Olson](https://app.slack.com/team/U6E4HHSTF)  [6:48 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646358485351349)
Reproduced

[Chris Malley](https://app.slack.com/team/U6EMFARV2)  [6:49 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646358586223089)
This affects lots of common-code UI components, which typically link to the Property that they’re provided.   For example, when I ported AquaRadioButtonGroup.ts, I had to use constructor param property: Property<T> in order to addLinkedElement.

[Jonathan Olson](https://app.slack.com/team/U6E4HHSTF)  [6:50 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646358625407959)
It's expecting... private/protected things?

[Chris Malley](https://app.slack.com/team/U6EMFARV2)  [6:50 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646358648685379)
That’s maybe not a good example… AquaRadioButtonGroup (or the buttons it creates) needs to modify the Property.
[6:51](https://phetsims.slack.com/archives/D6FNMP2LX/p1646358684354209)
The fields that TS identifies as missing are protected/private?

[Jonathan Olson](https://app.slack.com/team/U6E4HHSTF)  [6:51 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646358687340369)
Yeah my ReadOnlyProperty is somehow very broken
[6:51](https://phetsims.slack.com/archives/D6FNMP2LX/p1646358704784059)[](https://files.slack.com/files-pri/T5QBX4DGB-F035E0YC2BY/image.png)[](https://files.slack.com/files-pri/T5QBX4DGB-F035E0YC2BY/download/image.png)
It's worse than PhetioObject
image.png 
image.png



[Chris Malley](https://app.slack.com/team/U6EMFARV2)  [6:52 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646358742397649)
Hmm…. well… Thanks for working on it.  I have to run, probably not in the office until Monday.

[Jonathan Olson](https://app.slack.com/team/U6E4HHSTF)  [6:52 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646358764560979)
ok sorry!

[Chris Malley](https://app.slack.com/team/U6EMFARV2)  [6:53 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646358811769059)
I created https://github.com/phetsims/geometric-optics/issues/359 to remind myself to fix things up in GO when this is working. No rush.

[Jonathan Olson](https://app.slack.com/team/U6E4HHSTF)  [7:12 PM](https://phetsims.slack.com/archives/D6FNMP2LX/p1646359950887119)
TypeScript is... killing me again. Not sure if this is possible. Omit (and the extends/infer it's based on) seems to convert it away from an interface into a type that loses the protected/private info

</details>

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/issues/726#issuecomment-1062117397, @jonathanolson said:
> ReadOnlyProperty is buggy, and not ready for use. I'm not sure it's possible to make it work. Perhaps I should remove it?

Yes, probably so.

**Comment by pixelzoom** [comment]
It's been 30 days since we discussed deleting ReadOnlyProperty .  If ReadOnlyProperty is not going to be fixed, can we please remove it? More than once, I've accidentally ended up with `ReadOnlyProperty` when I wanted `IReadOnlyProperty`.

**Comment by samreid** [comment]
I'll work on removing it momentarily.

**Comment by samreid** [comment]
Removed.  Type checking and linting is passing locally.  There were no usages.  @pixelzoom can you please review?

**Comment by pixelzoom** [comment]
👍🏻
