### ISSUE TITLE
Remove NumberProperty.step?

### ISSUE THREAD

**Issue by zepumph** [phetsims/axon#386]
Over in https://github.com/phetsims/studio/issues/245 we got rid of sliders as a UI control for Properties in PhET-iO studio. This means that the `step` option is no longer used in studio. Should we remove this? Does it serve any other purpose? It isn't part of the validation when the NumberProperty is set, it is just part of the metadata when the instance is created. If it sticks around, it should likely be part of validation.

@samreid can we remove this option though?

**Comment by samreid** [comment]
Removed, can you please review?

**Comment by zepumph** [comment]
This is great. Thanks!
