### ISSUE TITLE
convenience methods on Property

### ISSUE THREAD

**Issue by AshrafSharf** [phetsims/axon#39]
The PropertySet object treats all its members as plain Property items, because of this we couldnt use NumberProperty methods such as __lessThanNumber__ and __greaterThanNumber__. This limitation is forcing us to explicitly define many such NumberProperty members on a Object that already extends PropertySet. It would simplify the make the code consistent If __lessThanNumber__ and __greaterThanNumber__ are moved to Property.

In addition to this, it would also be ideal to have __"plus"__ method similar to __"times"__ in Property Object

**Comment by samreid** [comment]
We discussed this at today's developer meeting.  It looks like the majority of usages of DoubleProperty.java and IntegerProperty.java are in Sugar and Salt Solutions and Fractions Intro.  For the reasons @pixelzoom described above, we concluded that Property.js should *not* contain the convenience methods like `lessThanNumber` etc.  Instead required derived properties should be created like so:

```js
//original Java
anySolutes = salt.moles.greaterThan( 0 ).or( sugar.moles.greaterThan( 0 ) );

//proposed JS implementation
anySolutes = new DerivedProperty([salt.moles,sugar.moles],function(saltMoles,sugarMoles){ 
   return saltMoles > 0 || sugarMoles > 0; 
});
```

We can also work with PropertySet to make it easier to add derived properties that automatically get the ES5 get/set methods created.

There are numerous "higher-order" property functions in Property.js--we should see which can be removed easily:

```js
    /**
     * Returns a new DerivedProperty which is true/false based on whether the value matches (based on ===) the passed in argument.
     * @param value
     * @returns {axon.DerivedProperty}
     */
    valueEquals: function( value ) {
      return new axon.DerivedProperty( [this], function( propertyValue ) { return propertyValue === value; } );
    },

    /**
     * Returns a new boolean DerivedProperty which is true/false based on && operator.
     * @param otherProperty
     * @returns {DerivedProperty.<boolean>}
     */
    and: function( otherProperty ) {
      return new axon.DerivedProperty( [this, otherProperty], function( thisValue, otherValue ) { return thisValue && otherValue; } );
    },

    /**
     * Returns a new boolean DerivedProperty which is true/false based on || operator.
     * @param otherProperty
     * @returns {DerivedProperty.<boolean>}
     */
    or: function( otherProperty ) {
      return new axon.DerivedProperty( [this, otherProperty], function( thisValue, otherValue ) { return thisValue || otherValue; } );
    },

    /**
     * Multiply this property's value by a constant scalar number, and return the derived property.
     *
     * @param scalar
     * @returns {axon.DerivedProperty}
     */
    times: function( scalar ) {
      return new axon.DerivedProperty( [this], function( thisValue ) { return thisValue * scalar; } );
    },

    /**
     * Multiply this property's value by a constant scalar number, and return the derived property.
     *
     * @param number
     * @returns {axon.DerivedProperty}
     */
    plus: function( number ) {
      return new axon.DerivedProperty( [this], function( thisValue ) { return thisValue + number; } );
    },

    /**
     * Return a derived property that is true if and only if this value is less than the specified number.
     *
     * @param number
     * @returns {axon.DerivedProperty}
     */
    lessThanNumber: function( number ) {
      return new axon.DerivedProperty( [this], function( thisValue ) { return thisValue < number; } );
    },

    /**
     * Return a derived property that is true if and only if this value is greater than the specified number.
     *
     * @param number
     * @returns {axon.DerivedProperty}
     */
    greaterThanNumber: function( number ) {
      return new axon.DerivedProperty( [this], function( thisValue ) { return thisValue > number; } );
    },

    /**
     * Not property, which does not propagate changes to dependents.
     * @returns {DerivedProperty}
     */
    derivedNot: function() {
      return new axon.DerivedProperty( [this], function( thisValue ) { return !thisValue; } );
    },

    /**
     * Two way communication for not, so you can set the value and have it come back to the parent
     * Note that noting about the following code is specific to booleans, although this should probably be used mostly for booleans.
     * To unlink both listeners attached unlink a property created with not(), use detach()
     */
    not: function() {
      var parentProperty = this;
      var childProperty = new axon.Property( !this.value );

      var setParentToChild = function( value ) {childProperty.set( !value );};
      parentProperty.link( setParentToChild );

      var setChildToParent = function( value ) {parentProperty.set( !value );};
      childProperty.link( setChildToParent );

      childProperty.detach = function() {
        parentProperty.unlink( setParentToChild );
        childProperty.unlink( setChildToParent );
      };
      return childProperty;
    }
//...
    //Returns a new Property that maps its values using the specified lookup table.
    //If the parent property value does not appear as a key in the lookup table, the returned property value is undefined
    mapValues: function( values ) {
      return new axon.DerivedProperty( [this], function( thisValue ) { return values[thisValue];} );
    },

    //Returns a new Property that maps its values using the specified function
    //See https://github.com/phetsims/axon/issues/25
    map: function( f ) {
      return new axon.DerivedProperty( [this], function( thisValue ) {return f( thisValue );} );
    },
```

**Comment by AshrafSharf** [comment]
Ok. Will refactor the SugarAndSaltSolutions model to reflect the suggestions. Thanks

**Comment by pixelzoom** [comment]
What's the plan for removing these convenience methods from Property, and (as @samreid mentioned above) "work with PropertySet to make it easier to add derived properties that automatically get the ES5 get/set methods created" ?

**Comment by samreid** [comment]
I started looking at the convenience functions in Property.js and saw:

valueEquals: 18 usages.  All but one of these are for the lifetime of the application and do not require cleanup.  So from @pixelzoom's issues above, the only issues that apply to the majority here are:
+(1) function names are misleading (IMO this could be fixed by renaming the method once we have consensus about how to do so)
-(2) chaining not a problem since the property persists for the lifetime of the app
-(3) dependencies are obfuscated.  Not sure if this is a problem since there is only one dependency??
-(4) chaining creates order dependency.  Not sure if this is a problem since there is only one dependency and order is straightforward?

Haven't looked at the other convenience methods yet.  Let's discuss at the developer meeting.

**Comment by pixelzoom** [comment]
Discussed again at 1/27/15 dev meeting. The consensus is still to expunge this API.  @samreid will continue on this. Let me know if you'd like to divide up the work.

**Comment by samreid** [comment]
Rewriting all of the valueEquals and testing it will take some time.  There are a few different kinds of use cases, and several uses which will all need to be thoroughly tested.

**Comment by samreid** [comment]
@aaronsamuel137 can you look into this?  Perhaps start with the least-frequently used higher-order Property methods above?  Also, before working on this, please make sure you have all of the `active-repos` checked out so you can be sure to find all usages across sims.

**Comment by aaronsamuel137** [comment]
I've started this process with the "or" method, which was only in a few sims. I'll keep chipping away at this as times goes on.

**Comment by jonathanolson** [comment]
Just ran test-sims for a Scenery check, and noticed Seasons' IntensityModel is using .or().

**Comment by aaronsamuel137** [comment]
Good catch. Turned out that there was a newline between the "." and the "or", so searching for ".or(" didn't find it.

Looks like I'll have to go regex when searching for these methods - something like "\.\s*or\("

**Comment by aaronsamuel137** [comment]
I forgot to update the commit message for the last 3 commits... it should be: remove "greaterThanNumber" instead of "and".

**Comment by aaronsamuel137** [comment]
OK I've finished removing all of the methods from Property that we wanted to eliminate from the API. I did my best to search through the code for all uses of the methods, but it's possible some were overlooked.

In particular, it is very difficult to search for plus, times, map, mapValues, and not, since these are used all of the place on classes other than Property. I caught all of the errors that I could by running http://localhost:8000/joist/tests/test-sims.html?loadOnly.

If you discover any issues with these methods not being defined in sims, feel free to assign to me, or just fix it yourself.

Assigning to @samreid for review.

**Comment by samreid** [comment]
@aaronsamuel137 thanks for all your work on this.  I'll put it on my todo list to review everything.

**Comment by samreid** [comment]
I have done numerous spot checks and haven't seen any issues.  I was really hoping to use fuzz tester to look for problems that might have been introduced here, but we still aren't to a good point where sims are passing that test regularly.  So I think it is safe to close this issue--any sim-specific issues that come up will be caught before publication during QA testing.  Thanks for your work on this @aaronsamuel137!
