### ISSUE TITLE
Add a non-array DerivedProperty constructor

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#40]
At today's meeting, @jonathanolson suggested a varargs derived property constructor like:

```js
//proposed JS implementation
anySolutes = new DerivedProperty( salt.moles, sugar.moles ,function(saltMoles,sugarMoles){ 
   return saltMoles > 0 || sugarMoles > 0; 
});
```

instead of what we have now:
```js
//proposed JS implementation
anySolutes = new DerivedProperty([salt.moles,sugar.moles],function(saltMoles,sugarMoles){ 
   return saltMoles > 0 || sugarMoles > 0; 
});
```

This would affect several of the DerivedProperty creation methods as well.  We would have to decide whether we want to support both array and varargs construction, or to update all old references to use varargs.

No specific deadline on this, just something on our wish list :stars:

**Comment by pixelzoom** [comment]
There are 145 occurrences of `new DerivedProperty` and 10 occurrences of `DerivedProperty.call`.  I suspect that we would need to support both array and varargs construction.  But I don't really see a significant advantage in the convenience of a varargs constructor, it saves your from typing 2 chars, while complication the implementation.  So imo this is an "enhancement" that isn't desirable.

**Comment by pixelzoom** [comment]
Proposal to close this issue as "will not implement".

**Comment by samreid** [comment]
I also recommend closing this issue as "will not implement".  It seems that using variable types in constructors disables js runtime optimizations and makes the implementation more complex.

**Comment by jonathanolson** [comment]
+1 for "will not implement"

**Comment by pixelzoom** [comment]
Since everyone who has commented on this issue has also weighed in with "will not implement", I'm going to close this issue.
