### ISSUE TITLE
Can we delete ReadOnlyProperty.valueOf?

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#400]
In https://github.com/phetsims/axon/issues/363 @zepumph said `Documentation is needed for the valueOf function`.  To me, it seems it should be deleted, but I wanted to check with @jonathanolson first.  @jonathanolson does it seem safe to delete `ReadOnlyProperty.valueOf`?

**Comment by jonathanolson** [comment]
I don't mind if it's deleted!

**Comment by samreid** [comment]
Removed, closing. Tagging https://github.com/phetsims/tasks/issues/1111
