### ISSUE TITLE
Review/adjust defaults for DynamicProperty type parameters

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#415]
In https://github.com/phetsims/axon/issues/342, we had a TODO:

```ts
// TODO: https://github.com/phetsims/axon/issues/342 Can OuterValueType default to TProperty?
export default class DynamicProperty<ThisValueType, InnerValueType = ThisValueType, OuterValueType = Property<InnerValueType>> extends ReadOnlyProperty<ThisValueType> implements LinkableProperty<ThisValueType> {
```

**Comment by samreid** [comment]
The defaults don't actually seem like they are being used much at the moment.  I tried removing the defaults and the type checker still passed.  I'm not sure what's best here.  

Raising for dev meeting to ask: is this still important, and who should be in the subgroup?

**Comment by jonathanolson** [comment]
SR will remove the defaults

**Comment by samreid** [comment]
I removed the defaults.  We may want to adjust this when we start porting more JS sims that use DynamicProperty to TypeScript.  But for now perhaps it is OK to close.
