### ISSUE TITLE
Document Multilink.multilinkAny

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#418]
There is currently no documentation for `Multilink.multilinkAny`, and the documentation for UnknownMultilink could be improved.  Some vergabe about when one might need to use them would be helpful.

**Comment by samreid** [comment]
After the commits, there is now documentation for `multilinkAny` `deriveAny` and `UnknownDerivedProperty` and `UnknownMultilink`. Some of the docs are terse, but I wasn't sure how to elaborate.  Ready for review.

**Comment by pixelzoom** [comment]
👍🏻 closing
