### ISSUE TITLE
Add ability to add ES5 getter/setter and property reference to non-PropertySet objects

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/axon#42]
Proposed API:

```js
// add this.visible (ES5 getter/setter) and this.visibleProperty, with a new Property( true )
Property.addProperty( this, 'visible', true );
```

**Comment by samreid** [comment]
Seems like a great proposal. I wasn't sure why you assigned it to yourself--feel free to work on it if you wish.  I would also be happy to work on this but wouldn't get to it for quite some time.
