### ISSUE TITLE
Remove PropertySet.property

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#43]
Our group's recent convention has been to use:

```
this.locationProperty
```

instead of

```
this.property('location');
```

Let's reopen discussion briefly on this.  Can/should we remote the latter?  Having two ways of doing the same thing may create maintenance issues here.

**Comment by samreid** [comment]
@jbphet @pixelzoom @jonathanolson can you weigh in briefly?

**Comment by jonathanolson** [comment]
I prefer locationProperty over property( 'location' )

**Comment by pixelzoom** [comment]
I also prefer locationProperty over property( 'location' ). I don't believe I've ever using property( 'name' ).

**Comment by pixelzoom** [comment]
Presumably the fate of `link( propertyName, observer )` and `linkAttribute: function( propertyName, object, attributeName )` are tied to `property( propertyName )`. I've never them either. And the API lacks a corresponding `unlink` and `unlinkAttribute`.

**Comment by samreid** [comment]
I'm seeing 169 occurrences of the string `.property(` in our codebase across about 7 sims.  It will take some time to complete and I am not planning to work on this now.  Unassigning for now.

**Comment by samreid** [comment]
This will get removed as we port away from PropertySet.

**Comment by samreid** [comment]
And, in fact, will never be removed until PropertySet is removed, so this issue doesn't require work.  Closing.
