### ISSUE TITLE
Should getPhetioSpecificValidationError be moved into common code?

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#435]
In https://github.com/phetsims/density/issues/154#issuecomment-1499715567 @jonathanolson and I added a way to do phet-io-only validation (for studio), but there was a lot of overhead to set it up. Unfortunately, it is not possible in this case to use the primary validator because the core objects go through transient intermediate states that do not validate according to the rule we want studio to validate.  I was wondering if we should move `getPhetioSpecificValidationError` into common code.  @zepumph can you please review and advise?

**Comment by zepumph** [comment]
I think we would both agree that this would be sad if we needed this validation generally, due to its complexity. Can we wait until the 3rd or 4th or 5th case to implement something so central for it?

**Comment by samreid** [comment]
I agree completely, thanks! Want to close this issue?
