### ISSUE TITLE
inconsistencies/holes in multilink API

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#44]
Some inconsistencies/holes in the AXON API related to 'multilinks'...

(1) Different objects created for similar functions.
Property.mulitlink creates a Multilink.
PropertySet.multilink creates a DerivedProperty.
Should we changePropertySet.multilink to create a Multilink? (looks pretty trivial, but should be tested)

(2) Missing functionality.
PropertySet has unmultilink. 
Property has no such function.
Should we add Property. unmultilink? (looks pretty trivial)

**Comment by samreid** [comment]
I agreed with @pixelzoom recommendations and pushed changes to a branch above so it could be reviewed before merging to master.  I tested several sims (including forces and motion-basics which appears to use this pattern in several places) and didn't see any problems.  Reassigning to @pixelzoom for review, and at his discretion, merging back to master and deleting the branch.

**Comment by pixelzoom** [comment]
Changes in branch look good. I merged with master and deleted the branch.

I noticed one additional omission; PropertySet has link( propertyName, observer ), but no corresponding unlink. I've added that. Assigned to @samreid for review.

**Comment by samreid** [comment]
Looks good, thanks! Closing.
