### ISSUE TITLE
Improve phetioDocumentation for NumberProperty.rangeProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#440]
@catherinecarter recommends changing it to "Provides the range of possible values for the parent NumberPropertyIO". @marlitas and I agree.

**Comment by pixelzoom** [comment]
This is an API change, and sim API files were not updated. I ran into this in another context, where I’m making complicated API changes (https://github.com/phetsims/natural-selection/issues/339). So not helpful.  How did this get past git-hooks?  Why is it not failing in CT?

**Comment by samreid** [comment]
Fixed and pushed, closing.
