### ISSUE TITLE
Instead of erroring on DerivedProperty methods, just remove the methods?

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#47]
DerivedProperty has these methods:

``` js
      //Override the mutators to provide an error message.  These should not be called directly, the value should only be modified when the dependencies change
      set: function( value ) { throw new Error( 'Cannot set values directly to a derived property, tried to set: ' + value ); },

      //Override the mutators to provide an error message.  These should not be called directly, the value should only be modified when the dependencies change
      //Keep the newValue output in the string so the argument won't be stripped by minifier (which would cause crashes like https://github.com/phetsims/axon/issues/15)
      set value( newValue ) { throw new Error( 'Cannot es5-set values directly to a derived property, tried to set: ' + newValue ); },

      //Override get value as well to satisfy the linter which wants get/set pairs (even though it just uses the same code as the superclass).
      get value() {return Property.prototype.get.call( this );},

      //Override the mutators to provide an error message.  These should not be called directly, the value should only be modified when the dependencies change
      reset: function() { throw new Error( 'Cannot reset a derived property directly' ); }
```

Maybe it is better to remove these methods from the instance's interface instead?  This could be done in the constructor, I suppose.  @jonathanolson @pixelzoom @jbphet any thoughts?

**Comment by pixelzoom** [comment]
Is there any potential performance penalty to removing properties from instances? I suspect so, since I seem to recall discussion of such a penalty when adding properties to instances.

**Comment by samreid** [comment]
Well, it would be better if this could all be done on the prototype--but I'm not sure whether that is technically possible for this case.

**Comment by pixelzoom** [comment]
I prefer having the Errors, since they provide a description of the programming error.  If we remove the "methods", then the error becomes less obvious.

**Comment by pixelzoom** [comment]
Btw... Each of these methods in DerivedProperty should be annotated with `@override`.

**Comment by pixelzoom** [comment]
@samreid Can we leave this as is, or do you have a strong preference for removing the functions?

**Comment by samreid** [comment]
I think it will be OK to leave these functions.
