### ISSUE TITLE
cleanup in PropertySet

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#49]
A bunch of misc cleanup needed in PropertySet:

- @param name and propertyName used interchangeably
- @param propertyNames and dependencies used interchangeably
- @param dependencies used in cases where there's no DerivedProperty involved
- no documentation for many function
- no documentation for propertyID (apparently related to data communication)
- creation of array index duplicated repeatedly: propertyName + 'Property'

**Comment by pixelzoom** [comment]
I did everything except the last item above (propertyName + 'Property'). Is there any concern that encapsulating that in a function might have a negative performance impact?

**Comment by jonathanolson** [comment]
I'm not particularly concerned about encapsulating it.

**Comment by pixelzoom** [comment]
I didn't encapsulate propertyName + 'Property', but I did factor out 'Property' as a constant.

Closing. Feel free to review if anyone is so inclined.
