### ISSUE TITLE
rework ObservableArray

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#5]
After more experience with ObservableArray, I'm really not digging the listener interface. A listener has the form function({Array}added, {Array}removed, array ).  But one of added or removed is always null, and there is never more than 1 item in the arrays.  But I can rely on this in client code, so I'm having to write boilerplate in every callback that iterates over 2 arrays.

Proposed new interface:

``` javascript
addItemAddedListener( callback )
addItemRemovedListener( callback )
addListener( itemAddedCallback, itemRemovedCallback ) // as a convenience

/** 
 * Callbacks have this form.
 * @param {*} item the item that was added to or removed from the array
 * @param {ObservableArray} observableArray the observable array, post modification
 */
function( item, observableArray )
```

**Comment by pixelzoom** [comment]
Oh ObservableArray, how I loathe thee.  Against my better judgement (again), I attempted to use ObservableArray in function-builder, substituting it for a plain old Array that I had.  A couple of omissions that made this substitution a pita:

• ES5 getter for `length`, instead of having to do `array.lengthProperty.get()` or similar
• `splice` function, so it's possible to do more than push.

Postscript: I ultimately bailed on using ObservableArray, and used an Emitter to notify when the array had changed.

**Comment by samreid** [comment]
> • ES5 getter for length

This was added by @pixelzoom in 2a76c11e6879fd81ae06086643337b3da9c90f18

**Comment by samreid** [comment]
The thing that bothers me most about ObservableArray is switching between array.get(i) vs array[i].

Crazy idea hat on: what if we autogenerate array[i] as es5 getters for the first N elements?  We should probably never do this.

**Comment by pixelzoom** [comment]
Well I'll be... Guess I must've been assuming that the standard PhET pattern was used, and searched for `getLength`.

**Comment by samreid** [comment]
Some interesting ideas about wrapping or extending Array at http://perfectionkills.com/how-ecmascript-5-still-does-not-allow-to-subclass-an-array/

**Comment by samreid** [comment]
> splice function, so it's possible to do more than push (I needed to insert at index)

Splice was added in https://github.com/phetsims/axon/commit/b71cc337f6748ee080e97b50497f05972b498de0

**Comment by jonathanolson** [comment]
Also noted from CCK review that there's a common pattern needed to avoid the defensive copy, e.g.:
```js
observableArray.getArray().forEach( ... );
```
where:

1. We have to add getArray() to prevent copying the array
2. We have no safety, as concurrent modification fails silently.

I'd like to see support for this type of operation, and it should (when assertions are enabled) fail out if concurrent modification happens. Maybe we'd need to move to Emitter's handling (lazily copy when necessary).

Additionally, the following is also common:
```js
observableArray.getArray().map( ... );
observableArray.getArray().filter( ... );
```
And since I've never wanted an ObservableArray as the result, maybe the behavior for this could change too.

**Comment by samreid** [comment]
@pixelzoom and @jonathanolson can you please review your remarks above and identify whether any of them apply to `createObservableArray`?  If not, this issue can be closed.

**Comment by pixelzoom** [comment]
No movement on this since 1012/2020.  Back to @samreid to decide whether @jonathanolson's input is really needed.

**Comment by samreid** [comment]
The majority of concerns in https://github.com/phetsims/axon/issues/5#issuecomment-23830189 seem they have been addressed.  If the remaining concerns or others cause problems, let's open a new issue for them.
