### ISSUE TITLE
store Property observers "correctly"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#50]
Property.js has this comment:

> // TODO: JO: avoid slice() by storing observers array correctly

@jonathanolson can you please elaborate on how to store observers "correctly"?

**Comment by pixelzoom** [comment]
Asking again... @jonathanolson can you please elaborate on how to store observers "correctly"?

**Comment by jonathanolson** [comment]
I had thought of a way of not having to slice() when notifying most observers, but I don't think it's still applicable. OK to remove TODO from source?

**Comment by pixelzoom** [comment]
OK with me.
