### ISSUE TITLE
ObservableArray.addAll was broken

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#52]
ObservableArray.addAll was broken--not sending notifications on addAll()

Fixed in this version: https://github.com/phetsims/axon/commit/20e3d6d694e3a968cfc56f063f547dc297a9a4a5

Raising this issue since fixing this bug may have created issues if code was depending on this buggy behavior--want to bring it to the attention of @pixelzoom @jonathanolson @aaronsamuel137 @jbphet.

**Comment by pixelzoom** [comment]
Searching for ".addAll(" ... The only uses of ObservableArray.addAll are in energy-skate-park-basics (1) and neuron (3).

**Comment by pixelzoom** [comment]
Searching for ".addAll(" ... The only uses of ObservableArray.addAll are in energy-skate-park-basics (1) and neuron (3).  So this can be closed after @samreid and @jbphet have verified that these sims weren't depending on the buggy behavior.

**Comment by samreid** [comment]
I tested ESPB and did not see any problems.  Reassigned to @jbphet to look into neuron.

**Comment by pixelzoom** [comment]
@jbphet please verify in neuron.

**Comment by jbphet** [comment]
Verified in Neuron, no reliance on the previously buggy behavior.  Closing.
