### ISSUE TITLE
Events.trigger sends arguments even when there were no arguments

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#53]
Events.trigger0 sends 0 arguments.  Events.trigger1 sends 1 argument.  Events.trigger('started'), which has no arguments, sends 1 argument, which is the word "started".  This is causing some complication for together, which is enforcing the number of arguments.  Here is the problem in Events:

```js
        //Simple case of no arguments, call it separately for improved performance in case it is faster (untested)
        if ( hasNoArguments ) {
          listener( arguments );
        }
```

@jbphet & I would like to change this to

```js
        //Simple case of no arguments, call it separately for improved performance in case it is faster (untested)
        if ( hasNoArguments ) {
          listener( );
        }
```

However, we are unsure if any PhET code is relying on the event name as the single argument for trigger() calls, say for demultiplexing multiple events through a single function.  @pixelzoom @jonathanolson @aaronsamuel137 @phetsims/bereaphysics what do you think?

**Comment by pixelzoom** [comment]
I have not explicitly used Events.trigger* in any code that I've written.  I'm guessing that @jonathanolson might be the biggest client of this feature, so reassigning to him. 

As for the current implementation and API design...  I don't see anything in the current implementation that tracks how many parameters are required for an eventName, and I don't see anything in the various trigger functions that verifies that the correct number of parameters is used.  So what is having trigger, trigger0, trigger1, trigger2,... buying us?  Why not just have trigger, when parameters are passed through to the listener?

**Comment by samreid** [comment]
Here is the documentation for trigger1:

```js
    /**
     * Trigger an event with the specified name, with a single argument. Should get optimized in browsers better than trigger, so we have code duplication for now.
     * @param {string} eventName the name for the event channel
     * @param {object} param1 - the argument to pass through to the listeners
     */
    trigger1: function( eventName, param1 ) {
```

The important line is:
> Should get optimized in browsers better than trigger

That is the entire reason for using triggerN instead of trigger, so that we don't have to deal with extra overhead from using dynamic `arguments`.

**Comment by jonathanolson** [comment]
I haven't to my knowledge used trigger()'s arguments ability, and I'm fine with the replacement described.

Scenery doesn't use the arbitrary arguments version. @pixelzoom, basically ```Array.prototype.slice.call( arguments, 1 );``` is the most expensive part, since the mere presence of ```arguments``` prevents almost all JIT optimizations, so the code will always run in interpreted mode, and it's doing Array allocations/copying on every call.

**Comment by pixelzoom** [comment]
Might be good to put some of the specifics about the reasons for having multiple trigger calls in the code documentation.  It solves a performance problem, and "Should get optimized in browsers better than trigger" tells me very little what that problem is, or how having multiple trigger calls resolves it.

**Comment by samreid** [comment]
I improved the docs above, and will remove the name argument from trigger shortly.

**Comment by samreid** [comment]
I removed the bogus trigger argument as described above.  I tested RPAL and did not see any issues.  We should remain vigilant and report any issues that this may have caused.  @pixelzoom want to review the documentation or anything here?

**Comment by pixelzoom** [comment]
Looks good, closing.
