### ISSUE TITLE
Property needs a dispose function

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#54]
@pixelzoom pointed out that if Property is calling tandem.addInstance() then it should have a dispose function that calls tandem.removeInstance.

Additionally, we will need to iterate over all sims and see if there are Properties that need to be dispose()d of, i.e. Properties that don't persist for the lifetime of the sim.

@pixelzoom suggested that we can probably identify Properties that require a dispose call by looking for unlink calls.  Any Property that is unlinked will probably need to be disposed.

**Comment by pixelzoom** [comment]
I added the dispose function, using our new pattern for dispose (i.e., @private this.diposeProperty). @samreid please review.

How should we go about identifying sims where Property.dispose needs to be called?

**Comment by samreid** [comment]
> @samreid please review.

Change set looks good, thanks.

> How should we go about identifying sims where Property.dispose needs to be called?

This is a tricky problem in general probably warrants carefully examining whether Properties are being dynamically created--which may indicate that they should be disposed as well.

For the specific case of together.js, if two properties are registered with the same name before one is disposed, together.js will error out.  This will help us detect some cases where properties are re-created.  But this is a difficult problem in general.

**Comment by pixelzoom** [comment]
So... This issue is done, but we don't have a way to identify sims where Property.dispose needs to be called.  I guess the best we can do is to be on the lookout for this problem as we instrument sims.

Closing.
