### ISSUE TITLE
PropertySet needs to check tandemSet for presence of bogus keys

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#55]
Related to https://github.com/phetsims/together/issues/85

**Comment by pixelzoom** [comment]
@samreid commit: 99c3766e14d70fc8bad618fdb611d53f3d01142a

**Comment by pixelzoom** [comment]
The first iteration of the assertion required a separate function, which contained unreachable code. I rewrote it to use lodash, and moved verification to the earliest possible point in the constructor.  Tested by in faradays-law.CoilModel, like this:

```js
PropertySet.call( this, {
      B: 0, //current value of magnetic field
      BLast: 0, //previous value of magnetic field
      emf: 0 //signal strength in coil = 'electromotive force'
    }, {
      tandemSet: { foo: null, bar: null }
    } );
```

**Comment by pixelzoom** [comment]
Assigning to @samreid for review.

**Comment by samreid** [comment]
This seems good, thanks!  Closing.
