### ISSUE TITLE
PropertySet support for tandem is incomplete

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#59]
Stuff that needs to be added, not necessarily a complete list:

- [x] addProperty needs options.tandem
- [x] removeProperty should call Property.dispose
- [x] toDerivedProperty needs options.tandem
- [x] addDerivedProperty needs options.tandem

**Comment by pixelzoom** [comment]
This is still half-baked. I'm not comfortable doing a redeploy of sims when something this fundamental is in this state.

**Comment by pixelzoom** [comment]
Looks like addProperty has been handled.

**Comment by pixelzoom** [comment]
I added tandem support to toDerivedProperty and addDerivedProperty.  There was one bogus call to addDerivedProperty in color-vision.RGBModel, and I fixed that too.

**Comment by pixelzoom** [comment]
PropertySet.removeProperty now calls dispose on the Property that is being removed. Note that removeProperty currently has no clients.

All work completed. Assigning to @jonathanolson for review.

**Comment by pixelzoom** [comment]
Btw... I looked through PropertySet and didn't see any additional places where tandem support is required. But it would be good for @jonathanolson to take a quick look while verifying.

**Comment by jonathanolson** [comment]
Not sure if it's related to this issue, but I don't see any documentation on what tandemSet should be in the constructor of PropertySet.

**Comment by jonathanolson** [comment]
Otherwise looks good to me.

**Comment by pixelzoom** [comment]
@jonathanolson wrote:
> Not sure if it's related to this issue, but I don't see any documentation on what tandemSet should be in the constructor of PropertySet.

Reopening to fix that.

**Comment by pixelzoom** [comment]
Documentation added. Closing.
