### ISSUE TITLE
Delete NumberProperty, BooleanProperty, ToggleProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#60]
See #57

**Comment by samreid** [comment]
NumberProperty.js is gone and tested in the 3 sims where it appeared.

**Comment by samreid** [comment]
BooleanProperty.js is gone too.

**Comment by samreid** [comment]
I had difficult testing Energy Forms and Changes.  @phetsims/jessegreenberg can you take a look and make sure everything seems good?

**Comment by samreid** [comment]
Everything is deleted.  Would be good to hear from @phetsims/jessegreenberg about whether EFAC is ok after this.

**Comment by jessegreenberg** [comment]
All is well in EFAC after removing BooleanProperty.  Sorry the sim was not in an easily testable state!

**Comment by pixelzoom** [comment]
Looks like this is done, closing.
