### ISSUE TITLE
verify arg count to Events.trigger0, trigger1 and trigger2 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#62]
In light of https://github.com/phetsims/together/issues/131, I suggest that we add code to Events.trigger0, trigger1 and trigger2 that verifies that the number of arguments matches the expected number of parameters.

**Comment by pixelzoom** [comment]
Done. Beware that you may experience failures when running with ?ea, especially if you have data collection features enabled. 

Assigning to @jbphet for review.

**Comment by pixelzoom** [comment]
Before "Summer 2015 redeploy", we should probably track down and fix all of the bogus calls to trigger0/1/2.

**Comment by pixelzoom** [comment]
This wasn't sufficient to catch the programming errors in https://github.com/phetsims/together/issues/131.  In many cases, the trigger call was used correctly, but the callback in TogetherCommon.js had the wrong number of parameters. For example:

```js
// ComboBox.js line 198
self.trigger1( 'endedCallbacksForItemFired', event.currentTarget.item.value );

// TogetherCommon.js line 443
comboBox.onStatic( 'endedCallbacksForItemFired', function() {
  togetherEvents && togetherEvents.end( messageIndex );
} );
```

So I added an assertion to each callback, to confirm the number of arguments. For the above example:

```js
// TogetherCommon.js line 443
comboBox.onStatic( 'endedCallbacksForItemFired', function() {
  assert && assert( arguments.length === 0 );
  togetherEvents && togetherEvents.end( messageIndex );
} );
```

Testing with beaker, this assertion fails when you interact with the "Solute Type" combo box.

**Comment by pixelzoom** [comment]
Based on https://github.com/phetsims/together/issues/131#issuecomment-107768678, omitting the args in the "endCallbacks" events was a "feature".  So I'm going to remove the assertions.

**Comment by pixelzoom** [comment]
Closing this since these seems to be general agreement that verifying the number of args to Events.trigger0/1/2 is useful.

**Comment by samreid** [comment]
I thought the assertions were a great idea, see https://github.com/phetsims/together/issues/131#issuecomment-108114169.  Are you still thinking about removing them?  If so, why?

**Comment by pixelzoom** [comment]
I'm removing the assertions from TogetherCommon.js because you said (in https://github.com/phetsims/together/issues/131#issuecomment-107768678) that ignoring args was being done by design.  I am leaving the assertion in Events.trigger0/1/2.

**Comment by samreid** [comment]
Ah sorry, I was unaware of the assert statements introduced in https://github.com/phetsims/together/commit/4e904d893488353d0ff647e22cb5f0477abc3e9d . Yes I agree those should go and the Events.trigger0/1/1 assertions should stay.

**Comment by samreid** [comment]
Upon reflection--I'm not sure why you added the assert statements https://github.com/phetsims/together/commit/4e904d893488353d0ff647e22cb5f0477abc3e9d in the first place--instead of being deleted, they could be updated to reflect the correct number of args.  But since I am not sure why you introduced them in the first place, I am not sure whether this would be useful.

**Comment by pixelzoom** [comment]
The reason for introducing them is described in https://github.com/phetsims/axon/issues/62#issuecomment-107668233.

**Comment by pixelzoom** [comment]
The reason for introducing them is described in https://github.com/phetsims/axon/issues/62#issuecomment-107668233. But you indicated that this was incorrect because the client was ignoring the API arg (in this case `value`) by design.

**Comment by samreid** [comment]
Understood--I'll leave it up to you whether it will be better to remove these asserts or keep them and update them to have the right numerical values.

**Comment by pixelzoom** [comment]
They are removed. The decision now (in https://github.com/phetsims/together/issues/131#issuecomment-107768678) is whether to add the ignored `value` parameter to the function signatures in TogetherCommon.js, or to delete the `value` argument from trigger calls in sim/common code.
