### ISSUE TITLE
Avoid typos in event names

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#68]
While we discussed https://github.com/phetsims/scenery/issues/460, we discussed the problem of listening for an unsupported event in Events.js

For instance:

```js
var eventChannel = new Events();
eventChannel.on('dwn',function(){}); // This typo will never be caught

eventChannel.trigger('down');
```

One possible solution for this problem would be for each Events instance to know what events it can trigger when it is created.  Perhaps something like this:

```js
var eventChannel = new Events(['up','down']);
eventChannel.on('dwn',function(){}); // Throws an assertion error since 'dwn' is not in the events list.
```

This could take away some of the freedom from dynamically creating event names, but I don't think we are using that much anyways (or if so, it may be dubious).  I'll assign for developer-meeting to see what others think of this issue.

**Comment by samreid** [comment]
Something else that would be possible if passing the event names on Events construction:

```js
var eventChannel = new Events(['bounds','up','visible']);
eventChannel.addBoundsListener(function(){...});
eventChannel.addUpListener(function(){...});
eventChannel.addVolatileVisibleListener(function(){});
```
etc.  The methods could be dynamically created.

**Comment by pixelzoom** [comment]
9/10/15 dev meeting notes:

`var eventChannel = new Events(['up','down']);`

... seems promising. We should schedule some time to investigate this.

**Comment by pixelzoom** [comment]
@samreid In light of the Emitter.js work, is this issue still relevant?

**Comment by samreid** [comment]
Emitter.js sounds like the best solution to this problem.  Let's leave existing usages of axon.Events as they are (or can be converted on a case-by-case-basis), but let's prefer Emitter for future events of this sort.

@jessegreenberg @jonathanolson @pixelzoom @aaronsamuel137 @jbphet please make a note to use Emitter instead of Events for future events.
