### ISSUE TITLE
change behavior and names of "on" and "onStatic"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#69]
Factored out of https://github.com/phetsims/scenery/issues/460:

Proposal to change behavior of 'on' and 'onStatic'. Have 'on' operate on actual listener list (not a copy), and 'onVolatile' operate on a copy.  Set a flag in during notification that indicates that functions that modify the list (e.g. addListener, removeListener) will become unsafe, and throw and Error if one of those functions is called.

**Comment by samreid** [comment]
As I mentioned in https://github.com/phetsims/axon/issues/70#issuecomment-147152633

> There is also the matter of deciding what the addListener method will be named. Naming it on seems too ambiguous for a single Emitter. I recommend something like addListener. Method names in Events will remain the same.

Perhaps we should go with addListener (operates on actual listener list, not a copy) and addVolatileListener (operates on a copy).

**Comment by samreid** [comment]
As described in #70 I believe we can get away from the static/volatile distinction while still maintaining optimal performance for the case where nothing is removed from the list.  Hopefully if that issue gets solves then this issue becomes irrelevant.

**Comment by pixelzoom** [comment]
This is never going to happen, so I'm withdrawing the proposal and closing this issue.
