### ISSUE TITLE
Unify event and listener APIs and implementations

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#70]
Currently axon has three event types:
1. Property.link
2. Events.on
3. ObservableArray.addItemAddedListener

While these are indeed three different kinds of events, there is no reason that they must be implemented in such different ways.  Why not listen to a Property with 

``` js
myProperty.on('change',function(){});
```

or listen to events with:

``` js
myEvents.visibleChannel.link(function(){});
```

or listen to observable array methods like:

``` js
myObservableArray.on('itemAdded',function(newItem){});
```

Unifying these APIs may lead to a more consistent development experience.  Unifying the implementations would also be possible, and lead to a more uniform way to deal with issues like trigger('callbacksStarted') and volatile vs safe array copying.

**Comment by samreid** [comment]
Related to #68:

One possibility would be to have Events parallel PropertySet it its usage:

```js
// PropertySet
var person = new PropertySet({name:'moe',id:7})
person.nameProperty.link(function(){});
person.name = 'larry';

// Events
var events = new Events(['lunch','audited']);
events.lunchEvent.on(function(){});
events.lunchEvent.trigger();
```

We abandoned the `propertySet.property('name')` approach--isn't events.trigger('eventName') sort of exactly the same thing? (I'm coining the phrase "sort of exactly" here :)  Also, I'm not tied to any of the names above, if there are better suggestions, we should use them.

:arrow_up: Everything above here should be discussed based on its own merit.  The next comment is a bit more brainstormy.

**Comment by samreid** [comment]
If we proceed with the above suggestion, then one way to unify the axon properties and events would be to say that each property has an event channel associated with it which triggers a change event.  Something like:

```js
var person = new PropertySet({name:'moe',id:7});
person.nameProperty.changeEvent.on(function(){
 console.log('the name changed');
});
```

Axon events support parameters, so we could even think of a way to pass the new name through that callback.  Then instead of properties being the common denominator, event channels could be.  Though `link` has been a powerful abstraction for us--it is very nice to get an initial synchronizing callback when the listener is added without having to remember to always do it manually.  Not sure how to capture this idea or perhaps we would keep link but implement it on top of the event channels.

While we're here, let's evaluate the two strategies (strings vs object properties) side by side for this hypothetical paradigm:

```js
// strings
person.property('name').on('change',function(name){...});

// object properties
person.nameProperty.changeEvent.on(function(name){...});

**Comment by samreid** [comment]
While we are brainstorming, another (extremely quirky!) way to unify events with properties would be to turn events into states (the above ideas discussed getting events from properties).  For instance, if there is a 'itemDropped' event, we could envision a dragState property, and when it transitions from dragging to dropped, that callback would be like the event.on('itemDropped').  However, this feels like a step in the wrong direction.  Events seem like the more fundamental paradigm here.

**Comment by samreid** [comment]
To draw a symmetry between link and on: on is like lazyLink for events, in that it is not called back right away.  If there were ever any events that we wanted to call the callback right away when registering a listener, we could have something like `eagerOn`.  Or we could rename everything to accentuate the symmetry:

```
Property.link // immediate callback
Event.link // immediate callback
Property.on // lazy callback
Event.on // lazy callback
```
Though we probably shouldn't mix names between Events and Properties.

**Comment by samreid** [comment]
We also have another divergence in our event types.  Some event types are done like this:

```js
new MovableDragHandler( {
        dragBounds: Bounds2.EVERYTHING, // {Bounds2} dragging will be constrained to these bounds, in model coordinate frame
        //modelViewTransform: ModelViewTransform2.createIdentity(), // {ModelViewTransform2} defaults to identity
        startDrag: function( event ) {},  // use this to do something at the start of dragging, like moving a node to the foreground
        endDrag: function( event ) {},  // use this to do something at the end of dragging, like 'snapping'
        onDrag: function( event ) {} // use this to do something every time drag is called, such as notify that a user has modified the position
      } )
```

And some are done like this:

```js
var handler = new MovableDragHandler( {
        dragBounds: Bounds2.EVERYTHING, // {Bounds2} dragging will be constrained to these bounds, in model coordinate frame      } )
handler.on('startDrag',function(){});
```

Why are these so different?  Can we simplify our lives by unifying or only using one type?

**Comment by samreid** [comment]
@pixelzoom says it is valuable to use the same API for properties whether they were created as singles or single properties or propertyset, and just use the propertyset for creating the group and resetting as a group.  He pointed out it is also awkward when changing the type from PropertySet to Property and having things still "work" (fail silently).

@samreid would like to investigate this and investigate the same approach for events.  We would need a new axon type for a single event.  Then Events could parallel PropertySet (maybe rename to EventSet)?  After @samreid looks into this we can discuss it at a future developer meeting.

**Comment by samreid** [comment]
Not sure what to name the single event emitter.  IntelliJ IDEA treats `new Event()` as an interface and provides wacky highlighting for it.  `EventEmitter` already means something pretty different in Node.js.  We could go with Emitter or EventEmitter?

**Comment by samreid** [comment]
The composite one could be EmitterSet? or EventEmitterSet?

**Comment by samreid** [comment]
Also, Event seems more like *what happens* when trigger is called, not the name of the object that calls back the listeners.

**Comment by samreid** [comment]
Not sure emitter is the best name.  Perhaps event source?  If we went with emitter, then the method should probably be `emit` instead of `trigger`.

**Comment by samreid** [comment]
I'm (a) concerned about the amount of time it will take to redo pre-existing simulations that are relying on PropertySet extending Events, but on the other hand (b) if EmitterSet works out nicely it would be good to switch together.js to it as soon as possible.  I'll mark this for discussion in https://github.com/phetsims/together/issues/175

**Comment by samreid** [comment]
EventSource is already something else: https://developer.mozilla.org/en-US/docs/Web/API/EventSource

**Comment by samreid** [comment]
I'm already seeing a nice place where Emitter would come in handy in https://github.com/phetsims/axon/issues/67

**Comment by pixelzoom** [comment]
I think this is a great topic, and that we should continue to discuss and brainstorm. But are you thinking about making changes to axon while we're trying to meet the S2015R milestone?  Imo, we should be minimizing changes to common code, except where we need to make progress on data collection.

**Comment by samreid** [comment]
> I think this is a great topic, and that we should continue to discuss and brainstorm. But are you thinking about making changes to axon while we're trying to meet the S2015R milestone? Imo, we should be minimizing changes to common code, except where we need to make progress on data collection.

As noted above: 

> (b) if EmitterSet works out nicely it would be good to switch together.js to it as soon as possible.

We could also discuss a middle-of-the-road solution in which we leave all pre-existing axon things alone (until S2016R complete or later) and just add the proposed items to axon.  This would leave pre-existing code 100% safe until it is a good time to switch over.

**Comment by samreid** [comment]
Unassigning until after we discuss at an upcoming phet-io-meeting or developer meeting.

**Comment by samreid** [comment]
Please see https://github.com/phetsims/axon/issues/71 for a description of why we do *not* need EmitterSet, and would be best just to have Emitter.

**Comment by samreid** [comment]
We could reimplement Events in terms of Emitter.

**Comment by samreid** [comment]
@jonathanolson suggests using Emitter, with trigger1, trigger2, etc.  Would be good to start using this soon.

@jbphet I've also seen places I would use this.

**Comment by samreid** [comment]
@samreid will proceed with Emitter.

**Comment by samreid** [comment]
There is also the matter of deciding what the addListener method will be named.  Naming it `on` seems too ambiguous for a single Emitter.  I recommend something like addListener.  Method names in Events will remain the same.

**Comment by samreid** [comment]
Another proposed simplification for Emitter: We could make the number of args explicit.  emit() has no args, emit1() has 1 arg, etc.  This may be best for cases where Emitter is appropriate.

**Comment by samreid** [comment]
Also, if you want more than N args, then you should be passing an object literal.  I'm thinking 2 is a fine limit, though would change my mind later if we have excessive compeling N>2 examples.

**Comment by samreid** [comment]
Since create Emitter.js is tracked in #72, I'll enumerate the remaining items for this issue:

1. Should we create EmitterSet or change the Events constructor to have the names of accepted event types?
2. Emitter's add listener method is going to be called addListener--perhaps it is still valuable to call Property's add listener method `link` and `lazyLink` since link has the automatic callback.
3. There is issue #71 regarding bailing on PropertySet as it is known now--this could be another step toward unifying Emitter and Property.

**Comment by samreid** [comment]
The questions above are lower priority so  I'll unassign for now.

**Comment by samreid** [comment]
> Should we create EmitterSet or change the Events constructor to have the names of accepted event types?

No.  And Events is deprecated.

> Emitter's add listener method is going to be called addListener--perhaps it is still valuable to call Property's add listener method link and lazyLink since link has the automatic callback.

For me the only question is whether lazyLink should be renamed to addListener.  I'll create a separate issue for that.

> There is issue #71 regarding bailing on PropertySet as it is known now--this could be another step toward unifying Emitter and Property.

Already tracked in #71
