### ISSUE TITLE
Create Emitter.js

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#72]
It should be a single event type variant of Events.js.  Events.js can use it in its implementation.  See #70

**Comment by samreid** [comment]
I'd like to investigate unifying the standard and volatile listeners.  I think we can optimize for the standard case (no array copy) and if we detect a listener was removed during processing callbacks, then automatically copy the array.  This will simplify the API significantly without harming performance.

**Comment by samreid** [comment]
I'm confused about the desired behavior and our current behavior.

Let's say I have listener A and listener B.  Listener A removes listener B.
Then when I emit(), should listener B get a callback?

I believe with our copy() semantics, B does get a callback.  However, this seems odd since it should have been removed.  Also at the end of the A callback, if you check emitter.containsListener(B) then it would return false, yet B would get the callback.

What is described above may be much simpler to implement, so we may stick with it, but I wanted to bring it up for discussion and keep my eyes peeled for a more straightforward behavior.

**Comment by samreid** [comment]
With the caveats noted above, and the following implementation of Emitter.removeListener:

```js
    removeListener: function( listener ) {

      var index = this.listeners.indexOf( listener );
      assert && assert( index >= 0, 'tried to removeListener on something that wasnt a listener' );

      // If processing callbacks during an emit() call and removeListener() is called,
      // make a defensive copy of the array of listener before removing anything, and use it for 
      // the rest of the callbacks.
      if ( this.listenersToEmitTo !== null && !this.alreadyCopiedDuringEmit ) {
        this.listenersToEmitTo = this.listeners.slice();
        this.alreadyCopiedDuringEmit = true;
      }

      this.listeners.splice( index, 1 );
    }
```

Processing callbacks in a defensive and performant way has become extremely simple:

```js
    /**
     * @public emit a single event.
     * This method is called many times in a simulation and must be well-optimized.
     */
    emit: function() {
      assert && assert( this.listenersToEmitTo === null, 're-entrant emit not allowed because it would interfere with removal of ' +
                                                         'listeners while processing emit' );
      this.listenersToEmitTo = this.listeners;
      for ( var i = 0; i < this.listenersToEmitTo.length; i++ ) {
        this.listenersToEmitTo[ i ]();
      }

      this.listenersToEmitTo = null;
      this.alreadyCopiedDuringEmit = false;
    },
```

Compare this to the more complex implementation that was used in Events.js to support static/nonstatic listeners and various number of args.

```js
    /**
     * Trigger an event with the specified name and arguments.
     * @param {string} eventName the name for the event channel
     * @param args... optional arguments to pass to the listeners
     * @public
     */
    trigger: function( eventName ) {
      assert && assert( typeof eventName === 'string', 'eventName should be a string' );

      var listeners = this._eventListeners[ eventName ];
      var staticListeners = this._staticEventListeners[ eventName ];

      // listener quantities for normal and static
      var count = listeners ? listeners.length : 0;
      var staticCount = staticListeners ? staticListeners.length : 0;

      // only compute our arguments suffix once, instead of in our inner loop
      var suffix;
      var hasNoArguments = arguments.length === 1;
      if ( !hasNoArguments && ( count > 0 || staticCount > 0 ) ) {
        phetAllocation && phetAllocation( 'Array' );
        suffix = Array.prototype.slice.call( arguments, 1 );
      }

      // make a copy of non-static listeners, in case callback removes listener
      if ( count > 0 ) {
        listeners = listeners.slice();
      }

      var i;

      for ( i = 0; i < count; i++ ) {
        var listener = listeners[ i ];

        //Simple case of no arguments, call it separately for improved performance in case it is faster (untested)
        if ( hasNoArguments ) {
          listener();
        }
        else {
          listener.apply( this, suffix );
        }

        assert && assert( !staticListeners || staticListeners.length === staticCount, 'Concurrent modifications of static listeners from within non-static listeners are forbidden' );
      }

      for ( i = 0; i < staticCount; i++ ) {
        var staticListener = staticListeners[ i ];

        //Simple case of no arguments, call it separately for improved performance in case it is faster (untested)
        if ( hasNoArguments ) {
          staticListener( arguments );
        }
        else {
          staticListener.apply( this, suffix );
        }

        assert && assert( staticListeners.length === staticCount, 'Concurrent modifications from static listeners are forbidden' );
      }
    }
```

**Comment by samreid** [comment]
I've also checked in a unit test that demonstrates the behavior of dispatching to all listener that were registered at the time of the emit call, and making sure they were removed:

```js
  test( 'Emitter Basics', function() {
    var stack = [];
    var emitter = new axon.Emitter();
    var a = function() {
      stack.push( 'a' );
      emitter.removeListener( b );
    };
    var b = function() {
      stack.push( 'b' );
    };
    emitter.addListener( a );
    emitter.addListener( b );
    emitter.emit();

    equal( stack.length, 2, 'Should have received 2 callbacks' );
    equal( stack[ 0 ], 'a', 'true' );
    equal( stack[ 1 ], 'b', 'true' );

    equal( emitter.containsListener( b ), false, 'b should have been removed' );
  } );
```

I believe we could achieve the behavior of: removing a listener during callbacks prevents it from getting a callback, it would just be a bit more complex and may slow down things slightly.  But it would still be automatic (no dual addListener API) and much faster than always creating a defensive copy of the array.  However, perhaps the current behavior (which I believe matches the behavior we've had for many years) is sufficient.

**Comment by samreid** [comment]
Likewise we need to discuss the current/desired behavior of addListener during an emit() call.  Currently in Emitter.js if you add a listener during an emit() call, there are 2 possibilities:

1. if you haven't removed a listener previously during the emit callbacks, then the newly added listener will be called back during callbacks
2. if you have removed a listener previously during the emit callbacks, then the newly added listener won't be called back during callbacks (since a defensive copy was being used).

This seems tricky and asymmetrical.  Perhaps we should make a defensive copy during addListener() as well?

**Comment by samreid** [comment]
Another note: I'm disallowing re-entrant emit calls, if emit calls a listener that calls emit on the same emitter, that will be an assertion error.  Seems likely to be buggy and interferes with the optimizations described above.

**Comment by samreid** [comment]
I've made addListener have a behavior parallel to removeListener when it comes to add/remove during callbacks, see code comments in the code.

**Comment by samreid** [comment]
I should also note: if we decide we want the behavior of "if you add a listener while callbacks are being processed, then the newly added listener will get called back during that same event", it would be straightforward--mainly some index & counting calisthenics. We could keep track of the index of iteration and when listeners are added or removed, we could update the index of iteration accordingly.  The only case this wouldn't handle is if a listener was inserted in the middle of the list rather than added to the end of the list.

**Comment by samreid** [comment]
I'm ready for feedback on this approach and the desired behavior.  @jonathanolson and/or @pixelzoom may be good ones to chime in--let me know if you have time & interest.

**Comment by samreid** [comment]
Labeling for developer meeting to discuss states and discuss review.  Also note: this appears in https://github.com/phetsims/joist/issues/301 and should be reviewed before publication.

**Comment by jonathanolson** [comment]
> This seems tricky and asymmetrical. Perhaps we should make a defensive copy during addListener() as well?

Yes, defensive copy there sounds good, looks like this was done already.

> Another note: I'm disallowing re-entrant emit calls

Instead of a single defensive copy location, we could use a stack pattern to allow re-entrant emit calls. This is an issue, since bounds in Scenery is potentially re-entrant.

**Comment by samreid** [comment]
@jonathanolson says he can review this.

**Comment by samreid** [comment]
Consensus from meeting: the behavior from copying the listener list is preferable.

**Comment by samreid** [comment]
> Instead of a single defensive copy location, we could use a stack pattern to allow re-entrant emit calls. This is an issue, since bounds in Scenery is potentially re-entrant.

Would it be sufficient to permit only up to 1 level of re-entry?  Then instead of the complication of stacks and multiple different copies of listener lists, we would have the following:

* at the beginning of emit(), it checks if emit is already being processed.  If so, it will set `this.emitAgain=true` and return immediately.
* at the end of emit, it checks if `this.emitAgain` is true.  If so, it will set `this.emitAgain=false` and call `this.emit()`

**Comment by pixelzoom** [comment]
1 level of reentry seems like a difficult constraint to keep track of in the client.

**Comment by samreid** [comment]
It would be handled completely by Emitter.js.  Multiple calls to emit() during an emit() would essentially be batched.

**Comment by jonathanolson** [comment]
Mind if I take a shot at re-entrance in a branch?

**Comment by samreid** [comment]
I don't mind, but it would be great if you can also explain why single re-entry batching is insufficient.

**Comment by jonathanolson** [comment]
> I don't mind, but it would be great if you can also explain why single re-entry batching is insufficient.

It's fairly easy to cook up an example like below, and these types of things did seem to arise previously.
```js
var rect = new scenery.Rectangle( 0, 0, 100, 50 );

// vertical listener
rect.events.transform.addListener( function() {
  if ( rect.top < 0 ) {
    rect.top = 0;
  }
} );

// horizontal listener
rect.events.transform.addListener( function() {
  if ( rect.left < 0 ) {
    rect.left = 0;
  }
} );

rect.translation = new dot.Vector2( -5, -5 );
// triggers transform event (#1)
  // calling vertical listener, changes transform to (-5, 0)
    // triggers transform event (#2)
      // calling vertical listener, no change
      // calling horizontal listener, changes transform to (0, 0)
        // triggers transform event (#3)
          // ...
        // ...
      // ...
    // ...
  // ...
// ...
```

Or alternatively, you could have one listener that may take a few attempts before it stops changing the transform, etc. Listeners like this are supported by Scenery (as we've basically been using them), so that would mean we may not be able to use Emitter if it doesn't support this type of pattern.

**Comment by samreid** [comment]
@jonathanolson & I discussed the problem and the issue is that Events.js `on` always creates a copy so it supports nested listeners lists.  We also tinkered with this qunit test example:

```js
var emitter = new axon.Emitter();
    var rect = {
      x: 0, y: 0, width: 100, height: 50, setTranslation: function( x, y ) {
        this.x = x;
        this.y = y;
        //console.log( 'setTranslation: (' + x + ',' + y + ')' );
        emitter.emit();
      }
    };

    var a = function() {
      console.log( 'a' );
      if ( rect.x < 0 ) {
        if ( emitter.containsListener( a ) ) {
          emitter.removeListener( a );
        }
        rect.setTranslation( 0, rect.y );
      }
    };
    var b = function() {
      console.log( 'b' );
      if ( rect.y < 0 ) {
        if ( emitter.containsListener( b ) ) {
          emitter.removeListener( b );
        }
        rect.setTranslation( rect.x, 0 );
      }
    };
    emitter.addListener( a );
    emitter.addListener( b );
    rect.setTranslation( -5, -5 );

    // emit 1: a
    // emit 2: b
    // emit 1: b
```

The desired behavior is listed below and the single re-entry doesn't work in this case because it doesn't have the right copy of listeners to use at each level.

One solution we discussed: put
```js
    this.depth = 0;
    this.listenersToEmitToStack = [];
```
in Emitter.js so it can keep track of the listeners at each level.

We should create a unit test for this desired behavior.

**Comment by samreid** [comment]
I did the straightforward implementation of a listener list stack, emit now looks like this:

```js
    emit: function() {
      this.listenersToEmitTo.push( this.listeners );
      var lastEntry = this.listenersToEmitTo.length - 1;

      for ( var i = 0; i < this.listenersToEmitTo[ lastEntry ].length; i++ ) {
        this.listenersToEmitTo[ lastEntry ][ i ]();
      }

      this.listenersToEmitTo.pop();
    },
```

This passes the "abb" test.

@jonathanolson is one push/pop per emit too much overhead?  What do you recommend here?

**Comment by samreid** [comment]
I decided to push my changes, but we still need to discuss whether push/pop every emit is OK, or if there are other ways to proceed.

**Comment by jonathanolson** [comment]
Performance testing sounds useful. Try with no re-entrance support, push/pop, direct array assignment (e.g. arr = []; arr[0] = x) with no pop, conditional push with no pop (e.g. if( index >= arr.length ) { arr.push( x ); } else { arr[ index ] = x }, or maybe other options.

Maybe not having to push/pop on the first call (before re-entering) is an option?

**Comment by samreid** [comment]
Using the push/pop emitter, creating one and calling emit with a listener that just does x++ on an otherwise unused global, incrementing by powers of 10, I got to 100,000 emit calls before the performance dropped to 30fps in GAO on iPad3 (when nothing is animating).

Removing the push/pop for 100,000 emits gets the performance back to 60fps.  Then when I went to 1,000,000 emits/frame the performance (with no push/pop) dropped to 15fps.

So, trying to estimate an order of magnitude of the cost: 100,000 emit calls per frame cost roughly 15ms/frame, so that is 15/100000=0.00015ms per push/pop.

GC's did not seem more prevalent.

I believe the current implementation also has a bug that could occur if addListener or removeListener was called twice during one emit frame, if the defend() is called twice, the second time could end up with the wrong thing.

**Comment by samreid** [comment]
The performance cost of push/pop seems negligible on iPad3 in the test cases above.  Still, we know this pattern will be widely used and perhaps it is worth investing in the complexity of a push/pop-less top level emit.  @jonathanolson can you review my notes and discuss?

**Comment by samreid** [comment]
We could create an abstraction MyStack.js which hard codes the first few elements and uses an array after n>N.  This could keep the implementation in Emitter really simple.

**Comment by jonathanolson** [comment]
> 0.00015ms per push/pop

Let's call that good for now, and only work at further optimization if we find it's a bottleneck.

**Comment by samreid** [comment]
Sounds good.  Remaining work here:

* emit1 and emit2 should be updated to match emit's push and pop.
* I believe the current implementation also has a bug that could occur if addListener or removeListener was called twice during one emit frame, if the defend() is called twice, the second time could end up with the wrong thing.

**Comment by samreid** [comment]
Proposed fix is above, it should be reviewed and discussed.  @jonathanolson do you have time to look at this with me?

**Comment by samreid** [comment]
@jonathanolson pointed out the unit tests are failing--I'll look into this before review.

**Comment by samreid** [comment]
Fixed the logic issue above.  @jonathanolson if you can find me more problems to solve I will be grateful.

**Comment by jonathanolson** [comment]
Looks good except for the case where defendCallbacks needs to defend multiple undefended arrays. 

Added failing test case with documentation of what is the expected order.

**Comment by samreid** [comment]
@jonathanolson & I fixed the multiple defended arrays issues yesterday, and @jonathanolson said he thought everything else was good to go here, so I'll close.
