### ISSUE TITLE
onValue uses the wrong equals definition

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#73]
See https://github.com/phetsims/axon/issues/10

onValue currently uses ===, but it should use something like equalsValue.  I couldn't update it to use equalsValue right away because equalsValue compares input to this.value, not input1 to input2.  We may need to change this in the future.

This is a purely latent bug at the moment because all of the 19 usage sites are currently testing values of booleans and strings.

**Comment by samreid** [comment]
Fixed above, tested in Under Pressure, which uses onValue.  @jbphet can you review or re-delegate to someone else for review?

**Comment by jbphet** [comment]
Looks okay to me.  For anyone looking at this in the future, the key to understanding why this is done is that the equality test is being put into a method so that it can be overridden in subclasses if a different equality test is needed.  Closing.
