### ISSUE TITLE
incomplete/incorrect jsdoc in Emitter.js

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#74]
Various problems with the jsdoc in Emitter.js:

(1) No type expression for various parameters (listener, arg1, arg2, ...)

(2) Visibility modifier missing for some functions (hasListener, emit, ...)

(3) Visibility modifier should be on it's own line, not followed by the function description. Eg:

```js
/**
  * @public add a listener
  * @param listener
  */
```

Should be:

```js
/**
  * Add a listener
  * @param {function} listener
  * @public
  */
```

**Comment by pixelzoom** [comment]
@samreid please verify.

**Comment by samreid** [comment]
The change set was in https://github.com/phetsims/axon/commit/fd6908bf9c95c518bd91fdff46029ae694ee3eab

**Comment by samreid** [comment]
Looks good, thanks.

**Comment by pixelzoom** [comment]
Btw... I think it's OK to put the visibility modifier on the same line as a the description of single-line (non-jsdoc) comments.  Eg in FireOnHoldInputListener:

```js
// @public Adds a {function} lister
addListener: function( listener ) { ... }
```
