### ISSUE TITLE
Axon unit tests failing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/axon#76]

**Comment by pixelzoom** [comment]
Unit tests are failing and I published RC versions based on this ?!?!  Why isn't this high priority?

**Comment by samreid** [comment]
> Why isn't this high priority?

This code isn't used by the RC versions.

**Comment by pixelzoom** [comment]
Please clarify: Is production code failing unit tests, or are the unit tests failing to run? And if the latter, how do we know the former isn't true?

**Comment by samreid** [comment]
To run the unit tests for axon, please visit:

http://localhost/axon/tests/qunit/unit-tests.html

I am seeing:
> 131 assertions of 133 passed, 2 failed.

The failed 2 assertions are in "Emitter Tricks" from a test added Oct 22 which only test features in Emitter.js.  Emitter is only instantiated in scenery.Input and currently the only listeners are added to it via together.js, which is unused in our production sims.  The failing tests are of the sort "one listener removes another listener which removes another while callbacks are being processed"

**Comment by samreid** [comment]
I addressed the issue in the above commit using a strategy @jonathanolson described to me more than a week ago.  @jonathanolson can you take a look at your convenience?

**Comment by samreid** [comment]
By the way, all unit tests are passing and I confirmed that no slice occurs if no listeners are added/removed during an emit.

**Comment by samreid** [comment]
I also dropped the high-priority label because the unit tests are passing and the review requested from @jonathanolson is regular priority rather than high.

**Comment by jonathanolson** [comment]
Looks good to me.
