### ISSUE TITLE
Automatically pair links and unlinks

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#84]
During the meeting on Dec 29, we discussed an API that automatically pairs link/unlink and addListener/removeListener, etc.  This is not exclusive to axon, but would also appear in scenery, etc.

We discussed an API like this:

``` js
    var Disposable = function() {
      this.disposeActions = [];
    };
    Disposable.prototype.dispose = function() {
      for ( var i = 0; i < this.disposeActions.length; i++ ) {
        var disposeAction = this.disposeActions[ i ];
        disposeAction();
      }
    };
    Disposable.prototype.autolink = function() {
      property.link( listener );
      disposeActions.push( function() {
        property.unlink( listener );
      } );
    };

    this.autolink( myProperty, myListener );
```

Discussed in the context of https://github.com/phetsims/chipper/issues/418

**Comment by jonathanolson** [comment]
Most Scenery objects are reused, so they have initialize() and dispose(). Thus dispose would be called multiple times.

So if Scenery internal code were to use this:
1. dispose() would need to be callable multiple times (actually clear the array)
2. autolink shouldn't create a new function closure every time it's called (avoiding creation of objects, particularly when our disposable thing is pulled out of a pool).
3. Would be ideal if it can be mixed in.

**Comment by samreid** [comment]
We agreed the current convention (dispose functions) is very clear and we do not want to investigate auto-unlink.
