### ISSUE TITLE
Property: add set/get for initialValue

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#86]
Following up on the function-builder discussion that I had with @samreid, @jbphet and @jonathanolson today...  We concluded that it was OK to initialize some portion of the model after the view has been created.  And to do that properly, there are some instances of `axon.Property` (for {Vector2} locations, in function-builder) whose initial value needs to be adjusted, so that "Reset All" works property.  E.g., functions in the carousel are created and added to the carousel before we know the (view) position of the carousel, and the position of the carousel determines the proper initial location of the functions.

Looking at Property, there is currently an ES5 getter for `initiallocation`, but no setter.  And the getter doesn't use the pattern used elsewhere for ES5, i.e., it doesn't call `getInitialLocation`.   So...

Proposal to add this to Property's prototype:

``` js
/**
 * Adjusts the initial value of the Property.  
 * Use this only in situations where the Property cannot be properly initialized when it's constructed.
 * @param {*} initialValue
 * @public
 */
setInitialValue: function( initialValue ) {
  this._initialValue = initialValue;
},
set initialValue( value ) { this.setInitialValue( value ); },

/**
 * Gets the Property's initial value.
 * @returns {*}
 * @public
 */
getInitialValue: function() {
  return this._initialValue;
},
get initialValue() { return this.getInitialValue(); }
```

This will require no change to existing sims.

**Comment by pixelzoom** [comment]
Btw... I advocated for the removal of (among other things) `storeInitialValue` in https://github.com/phetsims/axon/issues/67, where `storeInitialValue` was an interface to setting the initial value.  I'm still not wild about having this exposed. But I think that doing it via a uniform setter/getter interface is preferable to having `get initialValue()` and `storeInitialValue`.

**Comment by pixelzoom** [comment]
Btw... I advocated for the removal of (among other things) `storeInitialValue` in https://github.com/phetsims/axon/issues/67, where `storeInitialValue` was an interface to setting the initial value.  I'm still not wild about having this exposed, and I think we should be judicious about using it. But I think that exposing the initial value it via a uniform setter/getter interface is preferable to having `get initialValue()` and `storeInitialValue`.

**Comment by pixelzoom** [comment]
@samreid, @jbphet, @jonathanolson  I could use this feature in function-builder before the next developer meeting. Please weigh in on the proposal in https://github.com/phetsims/axon/issues/86#issue-128936523.

**Comment by samreid** [comment]
Generally it would be nice if Properties could be created after their initial values are known.  @pixelzoom, @jonathanolson @jbphet and I discussed ways to implement this, which may include a separate model startup phase (after view parameters are known).  However, in some cases `setInitialValue` may be the simplest solution to a difficult problem.  Feel free to implement at your convenience.

**Comment by pixelzoom** [comment]
2/2//16 dev meeting: OK to add this, but I'm going to continue to look for a better way to handle this in function-builder before I add it.

**Comment by samreid** [comment]
My 2 cents that I also mentioned in today's meeting, it worked well when I modeled the positions of the cards in the view rather than the model for build-a-fraction.

One additional complication you may not have considered is that if the carousel on the left may be aligned to the left side of the screen, in which case resetting the initial coordinates of the value cards may not be sufficient, depending on how you implement things.

**Comment by pixelzoom** [comment]
Thanks @samreid, I hadn't thought of that additional complication. I'd check with my design team on the probability of that feature being desired.

**Comment by pixelzoom** [comment]
Checked with my design team regarding the "one additional complication" in https://github.com/phetsims/axon/issues/86#issuecomment-178874447.  This feature is not desired in function-builder, where we want to (1) maintain proximity of the inputs and outputs so they can be easily compared, and (2) have a fairly short "drag distance" between carousels and the builder.

**Comment by pixelzoom** [comment]
Tracking the issue of anchoring carousels in https://github.com/phetsims/function-builder/issues/9.

**Comment by pixelzoom** [comment]
By populating the carousels after they are realized in the view, I no longer need to resort to adjusting the initial locations of the cards and functions in the model.  So I'm not going to do this.  I'll leave this open for now. But this experience suggests that this feature is not needed, and situations where it might seem to be needed can be better addressed by reconsidering how (and when) a sim's model and view are constructed.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/axon/issues/86#issuecomment-184295522, I said:
> this experience suggests that this feature is not needed, and situations where it might seem to be needed can be better addressed by reconsidering how (and when) a sim's model and view are constructed.

Since no one else has needed this feature in 8+ months, I'm going to close this issue.
