### ISSUE TITLE
PropertySet.unlinkAll?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#87]
Shall we add `unlinkAll` to PropertySet? 

```js
/**
 * Unlinks all Property instances from all observers.
 * @public
 */
unlinkAll: function() {
  this.getProperties().forEach( function( property ) {
    property.unlinkAll();
  } );
}
```

This would be useful when implementing `dispose` for instances of PropertySet.  Attempting to dispose of a Property that has observers results in an assertion failure (Property line 56).

**Comment by pixelzoom** [comment]
Whoops, the above implementation won't work. `getProperties` requires an array of Property {string} names.

**Comment by pixelzoom** [comment]
Revised:

```js
    /**
     * Unlinks all Property instances from all observers.
     * @public
     */
    unlinkAll: function() {
      var propertySet = this;
      this.keys.forEach( function( key ) {
        propertySet[ key + SUFFIX ].unlinkAll();
      } );
    },
```

**Comment by pixelzoom** [comment]
I went ahead and added this, tested in `function-builder.Movable`.  @samreid can you take a peek?

**Comment by samreid** [comment]
Looks great, I just fixed the docs a bit, closing.
