### ISSUE TITLE
Add DerivedProperty convenience constructors

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/axon#88]
Mirroring https://github.com/phetsims/axon/issues/39 but like:

``` js
var property = DerivedProperty.and( [ propA, propB, propC ], {
  tandem: tandem
} );
```

with signature `function( {Array.<Property.<boolean>>} properties, {Object} [options] ) : Property.<boolean>`, and similarly for the numeric/binary ones.

**Comment by jonathanolson** [comment]
@samreid, do you mind reviewing? I'd also like to discuss implementation of not().

**Comment by samreid** [comment]
I'm seeing ` // TODO: fix`, can you comment?

**Comment by samreid** [comment]
Can the accumulator be eliminated for the case of `and` and `or`?

**Comment by samreid** [comment]
Perhaps renaming `conjunctionWithProperty` to `orCombination` or something else with the word `or` would be simpler for many programmers.  Likewise for the other functions declared near the top of DerivedProperty.

**Comment by samreid** [comment]
What do you think about moving the derivations closer to the functions that create them?  For instance, valueEquals is

```js
    and: function( properties, options ) {
      return new DerivedProperty( properties, _.reduce.bind( null, properties, conjunctionWithProperty, true ), options ); // TODO: fix
```

What about inlining conjunctionWithProperty here?  It seems that `conjunctionWithProperty` is not reused and a new function is already being declared with `bind`.  The for-loop version can also bail early:

```js
    and: function( properties, options ) {
      return new DerivedProperty( properties, function() {
        for ( var i = 0; i < properties.length; i++ ) {
          var p = properties[ i ];
          if ( !p ) {
            return false;
          }
        }
        return true;
      }, options ); // TODO: fix
    }
```

**Comment by samreid** [comment]
I like how you've named `derivedNot` like the Java, it will make porting easier.

**Comment by samreid** [comment]
Can you add a unit test or two covering at least some of the DerivedProperty cases?  At least enough to demonstrate that the idea works.

**Comment by samreid** [comment]
I've finished my review, nice work @jonathanolson, everything seems like it is in good shape.

**Comment by jonathanolson** [comment]
> Perhaps renaming conjunctionWithProperty to orCombination or something else with the word or would be simpler for many programmers. Likewise for the other functions declared near the top of DerivedProperty.

I'd find `conjunctionWithProperty` or the "combination" terms much less intuitive. We could instead borrow Lodash styles, like `_.every` / `_.some`, or JS style with `Promise.all`. Thoughts?

> Can you add a unit test or two covering at least some of the DerivedProperty cases? At least enough to demonstrate that the idea works.

I see unit tests covering some of the cases.

> Can the accumulator be eliminated for the case of and and or?

I'm not sure what would be done here, it looks good to me the way it is.

> What do you think about moving the derivations closer to the functions that create them?

The suggestions are more verbose and will create more garbage. I don't find it worth the effort in order to "break early", which would only be relevant if we're listening to MANY Properties (which could happen, we could discuss then?)

**Comment by samreid** [comment]
Currently we have `DerivedProperty.and`, `DerivedProperty.or`, etc.  Everything else seems good, thanks! Closing.
