### ISSUE TITLE
Test for 2nd arg instanceof Tandem

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#89]
More than once a Tandem has been supplied as a 2nd arg of Property, but it should appear in an options object instead.  See https://github.com/phetsims/beers-law-lab/issues/158

Can we detect Tandem instances and throw an assertion error in cases like this?

**Comment by samreid** [comment]
This will put a dependency from axon->tandem, but this seems OK since tandem is already in common libs.

**Comment by samreid** [comment]
Fixed above, tested with a synthetic case, builds/lints pass, closing.

**Comment by samreid** [comment]
@jbphet said:

> Hey Sam, I'm finding that the sims I'm working on are failing to launch if they don't have TANDEM defined their config file.  I've fixed it for Expression Exchange, and about to do so for Neuron.  Was this due to something you checked in recently?

**Comment by samreid** [comment]
OK I'm using duck typing above so that axon, dot, kite, scenery do not have a direct dependence on Tandem.

**Comment by samreid** [comment]
Thanks for alerting me to this problem, I’ve removed the explicit Tandem check in Axon and moved to a duck-type check for now.  In the future if/when all repos depend on tandem, we can add back an Axon->Tandem dependency and do a direct type check.

**Comment by pixelzoom** [comment]
The current implementation is not arg type verification. Verification of arguments should confirm an *expected type*, not check to see if the type is some specific unexpected type. In this case specifically, if you pass in a {Tandem} by mistake, you get an assertion failure.  But if you in some other type by mistake, then you're out of luck.  Proper type verification would check for the expected type of `options`, i.e. an Object literal.

**Comment by samreid** [comment]
Tandem instances also pass the test `typeof options === 'object'`, so we need a way to distinguish them.

**Comment by pixelzoom** [comment]
How about this?

`assert && assert( !options.constructor );`

An object literal has no constructor.

**Comment by samreid** [comment]
It does seem unlikely (though not impossible) that someone would pass in an options object with a `constructor` property, like:

```js
{
 x:10,
 y:10,
 name:'Alice',
 constructor: Person
}
```

It seems like whatever check we put here will have to be a heuristic that cannot be guaranteed to be accurate 100% of the time.  Alternatively, we could make all repos depend on Tandem and just do an instanceof check instead.

**Comment by jonathanolson** [comment]
It's also possible to have ```isTandem: true``` on Tandem's prototype. It is very unlikely we would unintentionally pass a non-Tandem object with that set.

**Comment by samreid** [comment]
That seems great to me @jonathanolson, I'll go for it.  I'll remove the developer-meeting flag but if others want to discuss further, please do so.
