### ISSUE TITLE
mark Events as @deprecated?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#90]
My understanding is that we should be using Emitter, not Events. Should Events be marked as @deprecated?

**Comment by samreid** [comment]
Yes, but the road to deletion will be long since PropertySet *and* Node extend Events.  I've marked Events as deprecated in the above commit.  Anything else to discuss here @pixelzoom?

**Comment by pixelzoom** [comment]
I should have noted in the first comment...This came up when pairing with @andrewadare, and he was wondering how he was supposed know that Emitter had replaced Events.  Marking as deprecated with a note to "use Emitter instead"  (as you've done) addresses that concern.  Closing.
