### ISSUE TITLE
Investigate pattern for automatically wiring up dispose

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#93]
Currently link/unlink, addListener/removeListener, addTandem/removeTandem are spread out, with all the add's together and all the removes together.  Today we discussed an idea to couple each link/unlink add/remove etc instead of scattering them.  It could be mediated through a disposeEmitter.

From 4/14/16 dev meeting notes:

* @pixelzoom will commit DisposeExampleNode to phet-info
* @samreid will tinker with a pattern for specifying link + unlink in 1 call, probably based on disposeEmitter
* @andrewadare will hold off on further dispose implementation
* The current pattern will persist for a while, since we have a lot of it.

**Comment by pixelzoom** [comment]
DisposeExampleNode committed in https://github.com/phetsims/phet-info/commit/3b9cc3532f22a54e99085e6f0b540a28c590aac6.

**Comment by samreid** [comment]
Previous discussion is in https://github.com/phetsims/axon/issues/84

**Comment by samreid** [comment]
I committed sample usage of the proposed API, and @pixelzoom and I reviewed it.  We were on the fence about whether `linkWithDispose` should be used vs `link(observer,options)`; the former seemed more readable while the latter is more consistent with `new Property(initialValue,{disposeEmitter:disposeEmitter});`

@pixelzoom and I agreed this pattern was worth further investigation.

**Comment by samreid** [comment]
It would be great if @andrewadare @jessegreenberg @jbphet and @jonathanolson could review example usage of the proposed API in https://github.com/phetsims/phet-info/blob/be0d86f262bed4cbb5734db48626a6ee41021725/js/DisposeExampleNode.js Review will be important here because this would be a widely used API.

**Comment by samreid** [comment]
The latest version is available at https://github.com/phetsims/phet-info/blob/master/js/DisposeExampleNode.js

**Comment by andrewadare** [comment]
I am inclined to prefer the `link(observer,options)` approach to `linkWithDispose` because the `*withDispose` syntax, while short to type, is less clear than it could be (so I guess I disagree with SR about it being more readable). 

For example, the [.withDisposal](https://github.com/phetsims/phet-info/blob/38ba1fe81f4ac789c18894f2974dcf1b632596bc/js/DisposeExampleNode.js#L52-L55) functions don't make it very apparent (to me) what they actually do. In my simple-minded thinking, a function is usually something verb-like, unless it's a constructor.

 I also don't like the potential confusion that `linkWithSomething` sounds like the function is linking with (i.e. to) something.

Maybe this is just a solvable naming issue that causes my hangup, I'm not sure yet. In an ideal world, there would be some way that Axon could track the property/emitter/event without the necessity for doing it in user code. But I have no idea how that could be implemented.

**Comment by samreid** [comment]
@andrewadare thanks for your thoughts

> I am inclined to prefer the `link(observer,options)` approach to `linkWithDispose` because the `*withDispose` syntax, while short to type, is less clear than it could be (so I guess I disagree with SR about it being more readable). 

The main problem with `link(observer,options)` is that the observer function may be many lines of code, and hence the options would appear many lines from the link site.  This is why many APIs put the callback function last in the list of arguments.  For instance, here is how a Hooke's Law link would read with the options style:

```js
    displacementProperty.link( function( displacement ) {

      // update the vector
      arrowNode.visible = ( displacement !== 0 ); // since we can't draw a zero-length arrow
      if ( displacement !== 0 ) {
        arrowNode.setTailAndTip( 0, 0, options.unitDisplacementLength * displacement, 0 );
      }

      // update the value
      var displacementText = Util.toFixed( Math.abs( displacement ), HookesLawConstants.DISPLACEMENT_DECIMAL_PLACES );
      valueNode.text = StringUtils.format( pattern0Value1UnitsString, displacementText, metersString );

      // center value on arrow
      valueNode.centerX = ( displacement === 0 ) ? 0 : arrowNode.centerX;

      // resize the background behind the value
      backgroundNode.setRect( 0, 0, 1.1 * valueNode.width, 1.1 * valueNode.height, 5, 5 );
      backgroundNode.center = valueNode.center;
    }, {
      disposeEmitter: disposeEmitter
    } );
```

Perhaps a better name would help, such as `linkDisposable`?

> In an ideal world, there would be some way that Axon could track the property/emitter/event without the necessity for doing it in user code.

Today @jonathanolson and I were discussing ways of factoring out more of the dispose emitter boilerplate, we'll have to try it out.

**Comment by samreid** [comment]
Other review notes from @jonathanolson:

* match the names, use dispose or disposal consistently
* Emitter should iterate in reverse order to dispose items
* DisposeEmitter could be a reverse-order Emitter subclass

And he will send a copy of his notes/thoughts about factoring out more dispose boilerplate.

**Comment by andrewadare** [comment]
I see your point that if the observer callback is large, the syntax looks unwieldy. @pixelzoom and I were discussing yesterday that using named callbacks more often is something we might benefit from. That's a general remark, but may help some with readability here, with the side-benefit of improved call stack readability.

And going back more in your direction, giving a clear name for the link functions might be enough. The various "smart pointers" in modern C++ have names indicative of their policy on how to reclaim memory,  and what they are appropriate  for: `scoped_ptr`,  `shared_ptr`, `unique_ptr`, etc.  Although C++ is one of the last languages I'd want to emulate in terms of syntax, it is fairly transparent in these short type names what they are and roughly how they work. Maybe something like `scopedLink` is not so bad.

**Comment by jbphet** [comment]
There is a pattern that occurs frequently in our simulations where things come and go from a model and the corresponding view watches an ObservableArray for added items, attaches listeners to these items, then hooks up removal listeners that clean up view representations when the model representation is removed from the model.  Such code could be made more compact if a single dispose emitter could be fired to cause the item-removed-listener as well as all property listeners to be removed.  We should consider this pattern when working through the API, since we may end up adding it to types like ObservableArray.  This makes me think that we may want a more general term, like 'detachEmitter' or 'releaseEmitter'.

I realize that this comment may not read easily in English and would be glad to do a code example if anyone wants it.

**Comment by samreid** [comment]
Assigning to @jonathanolson to elaborate on a new pattern that factors out even more boilerplate.  Leaving tagged for developer meeting for next week.

**Comment by samreid** [comment]
Not sure if this is what @jonathanolson was thinking, but one possibility would be to create a Disposable mixin that supports the common things that need to be registered for unlinking, including Property, DerivedProperty, Emitter, Events, Tandem.  Could lead to API usage like:

```js
// Copyright 2016, University of Colorado Boulder

/**
 * Example of the various situations related to dispose.
 * This example does not run, it's intended for discussion of patterns.
 * See https://github.com/phetsims/axon/issues/93
 *
 * @author Chris Malley (PixelZoom, Inc.)
 */
define( function( require ) {
  'use strict';

  // modules
  var inherit = require( 'PHET_CORE/inherit' );
  var Node = require( 'SCENERY/nodes/Node' );
  var Property = require( 'AXON/Property' );

  /**
   * @param {Property} valueProperty
   * @param {Emitter} changedEmitter
   * @param {Events} stateEvents
   * @param {Object} options
   * @constructor
   */
  function ExampleNode( valueProperty, changedEmitter, stateEvents, options ) {

    options = _.extend( {
      enabledProperty: new Property( true ), // optionally provided by client
      tandem: null
    }, options );

    Disposable.call( this );

    // Add observers to observables provided by the client.
    this.link( valueProperty, function( value ) {} );

    this.link( options.enabledProperty, function( value ) {} );

    this.addListener( changedEmitter, function() { /* ... */ } );

    this.on( stateEvents, 'someState', function() {} );

    // @public Properties owned by this instance
    // TODO: what if clients linked to options.enabledProperty?
    this.myPublicProperty = this.createProperty( 0 );
    this.myEmitter = this.createEmitter();
    this.myEvents = this.createEvents();

    // @private
    var myDerivedProperty = this.createDerivedProperty( [ valueProperty ], function( value ) { /*...*/ } );
    console.log( myDerivedProperty );

    Node.call( this );

    // register with tandem
    this.addTandemInstance( options );
  }

  return inherit( Node, ExampleNode );
} );
```

**Comment by samreid** [comment]
Thoughts on the above pattern:
* it eliminates the need to pass `disposeEmitter` everywhere
* it eliminates the need for a `dispose` implementation
* it can handle the ordering of disposal

Questions:
* does it put too much logic in one class?
* does it deal with subclasses properly?

**Comment by pixelzoom** [comment]
Correct me if I'm wrong, but it sounds like Disposable implements `dispose`, which does 2 things:

(1) Calls `unlink/removeListener/off` for things that were registered using `Disposable.link/addListener/on`.

(2) Iterate over instance properties (that's lowercase properties), looks for property types that need to be cleaned up (Property, DerivedProperty, Emitter, Events,...), and calls their appropriate cleanup function (dispose, detach, removeListener,...) That sounds like a lot of `instanceof` checks.

I'm not wild about this bit in the above example:

``` var myDerivedProperty = this.createDerivedProperty(...);```

Following that pattern, Disposable would also need to implement `createProperty`, `createEmitter`, `createEvents`,... a creation function for every type of thing that needs to be cleaned up. To simplify Disposable, it might be preferable to require anything that needs to be cleaned up to be a `this` property.  E.g., change the above to:

```this.myDerivedProperty = new DerivedProperty(...); // @private```

**Comment by samreid** [comment]
> That sounds like a lot of `instanceof` checks.

I was picturing that internally Disposable would use a queue like we discussed with Emitter.  For instance, calling `createProperty` would create the property and add a list item that handles the cleanup.

> To simplify Disposable, it might be preferable to require anything that needs to be cleaned up to be a `this` property.

This would necessitate a large number of instanceof checks, and may run the risk of false positives.  Any problem with Disposable having a creation function for everything it knows how to clean up?

**Comment by samreid** [comment]
We could separate responsibilities by having a DisposablePropertyFactory mixin, DisposableTandemFactory mixin, etc.  And a convenience "combo" mixin for something that needs most/all of them.

**Comment by samreid** [comment]
We could use Proxy `handler.set` to intercept set calls, and (based on `instanceof` check) wire up dispose/removal listeners.  It looks like Proxy isn't too widely supported now but perhaps there is some kind of polyfill?

**Comment by samreid** [comment]
I'm also wondering if we should investigate garbage-free patterns?  Or if they break modularity too much?

**Comment by pixelzoom** [comment]
> Any problem with Disposable having a creation function for everything it knows how to clean up?

I really dislike having to call a function to create a Property, DerivedProperty, Emitter, etc., its awkward and has a smell about it.  And now the programming error that cause a memory leak has been shifted from forgetting to call something's cleanup function to forgetting to use a creation function.  I'm starting to feel like maybe our original pattern wasn't so bad. Yes, it's a bit boilerplate. But it's very obvious what's going on.

**Comment by samreid** [comment]
+1 for keeping it obvious and +1 for not having to use a different way for creating emitters, properties, etc.

How about a compromise where create emitters and properties using the usual syntax, then wire them to a disposal like so:

```js
    this.myPublicProperty = new Property( 0 );
    disposer.addProperty( this.myPublicProperty );
```
and
```js
    var link = options.enabledProperty.link( function( enabled ) {/*...*/} );
    disposer.addLink( link );
```

This would allow us to deal with disposal close to the site of creation instead of getting the disposes separated.  The link syntax is a bit different (returns a handle now), but I don't see a way around that in this paradigm.

**Comment by samreid** [comment]
> I don't see a way around that in this paradigm.

Well, you could do:

```js
    var updateEnabled = function( enabled ) {/*...*/};
    options.enabledProperty.link( updateEnabled );
    disposer.addLink( options.enabledProperty,updateEnabled );
```

**Comment by samreid** [comment]
We could redesign our `addListener` and `link` style functions so that they return a 0-arg function which can be used to `removeListener` or `unlink` the same thing.  Or could return a handle with an `unlink` function, to make it more clear?  But this may risk creating new memory leaks or damaging performance in every case (there may be many cases where we do not want to spend time + memory creating handles).

**Comment by samreid** [comment]
Summarizing the problems with the traditional approach and reasons I'm interested in finding a superior approach:

1. Having the link function and the unlink function separated by potentially hundreds of lines of code seems like a code smell to me.  It would be better if the two were co-located.
2. It would be nice for there to be a semi or fully automated way to tell if things like `link` or `new Property` are being cleaned up properly.  Currently this is completely manual and not too easy because of (1).
3. It would be nice for there to be framework support for automatic cleanup of things like `link`, `new Property` and implementation of `dispose()` as a way of factoring out duplicated code and isolating this pattern in a single implementation as much as possible.
4. It would be nice if we no longer had to choose between "Does this feature persist for the lifetime of the sim" vs "cleanup needs to be implemented for this feature", if the latter was simple enough to implement (3) and easy to verify (2) then many/all of our features could be moved to the cleanup-style.

**Comment by samreid** [comment]
According to https://unspace.ca/dev/2013/avoiding-memory-leaks-in-backbone-js

> But wait you say, the new version of Backbone comes with .listenTo which will automagically unbind from event listeners and now we can go back to faceroll development mode. Sweet! Let’s check it out.

Sweet, we should check it out.

**Comment by jonathanolson** [comment]
Here's a draft of my proposal where it uses a Disposable super-type, but without the functions to create things. Instead, we pass through a disposable object in options, so that our links/addListeners/etc. would be able to notify the Disposable that they have been added. E.g. link() would have ```options.disposable && options.disposable.registerLink( ... )``` or equivalent.

```js
// Copyright 2016, University of Colorado Boulder

/**
 * Example of the various situations related to dispose.
 * This example does not run, it's intended for discussion of patterns.
 * See https://github.com/phetsims/axon/issues/93
 *
 * @author Chris Malley (PixelZoom, Inc.)
 */
define( function( require ) {
  'use strict';

  // modules
  var inherit = require( 'PHET_CORE/inherit' );
  var Node = require( 'SCENERY/nodes/Node' );
  var Property = require( 'AXON/Property' );

  /**
   * @param {Property} valueProperty
   * @param {Emitter} changedEmitter
   * @param {Events} stateEvents
   * @param {Object} options
   * @constructor
   */
  function ExampleNode( valueProperty, changedEmitter, stateEvents, options ) {

    options = _.extend( {
      enabledProperty: new Property( true ), // optionally provided by client
      tandem: null
    }, options );

    Node.call( this ); // Node would be a Disposable, so this sets things up.

    // Add observers to observables provided by the client.
    valueProperty.link( function( value ) {}, { disposable: this } ); // Disposable as second argument

    changedEmitter.addListener( function() { /* ... */ }, { disposable: this } );

    stateEvents.on( 'someState', function() {}, { disposable: this } );

    // @public Properties owned by this instance
    this.myPublicProperty = new Property( 0, { disposable: this } );
    this.myEmitter = new Emitter( { disposable: this } );
    this.myEvents = new Events( { disposable: this } );

    // @private
    var myDerivedProperty = new DerivedProperty( [ valueProperty ], function( value ) { /* ... */ }, {
      disposable: this
    } );
    
    this.mutate( options );

    // register with tandem
    tandem.addInstance( this, { disposable: this } );
  }

  return inherit( Node, ExampleNode );
} );
```

**Comment by samreid** [comment]
We are generally in favor of the approach proposed above, next step is to implement Disposable, make common code changes to accept disposable as an option and try it out in a sim.

**Comment by samreid** [comment]
@jonathanolson will investigate this in the context of Charges and Fields.

**Comment by samreid** [comment]
Automatically wiring up dispose and reset is more complex than we thought and decided to proceed with the existing strategy where the simulation implements a `disposeClass` function or `resetClass` function as necessary, closing.

**Comment by samreid** [comment]
Reassigning myself to clean up the Dispose example and make sure the recommended process is well documented.

**Comment by samreid** [comment]
ComboBox.js has a good example of dispose.  I removed DisposeExampleNode.
