### ISSUE TITLE
Simplify multilink

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#95]
While debugging https://github.com/phetsims/circuit-construction-kit-common/issues/172 I realized multilink could be simpler by using forEach instead of IIFE.

**Comment by samreid** [comment]
I've implemented the fix above, and axon unit tests are still passing.  Could I trouble @jbphet, @jessegreenberg or @pixelzoom for a quick review to make sure everything is good to go?

**Comment by pixelzoom** [comment]
This new implementation looks buggy:

```js
    dependencies.forEach( function( dependency, i ) {
      var listener = function( value ) {
        multilink.dependencyValues[ i ] = value;
        callback.apply( null, multilink.dependencyValues );
      };
      multilink.dependencyListeners.push( listener );
      dependency.lazyLink( listener );
    } );
```

The function provided to `forEach` only takes 1 parameter, you're using 2 parameters. Where is the value of `i` coming from? It will be undefined, and promoted to zero when evaluating `multilink.dependencyValues[ i ]`.

**Comment by pixelzoom** [comment]
Ah, I stand corrected.  General form of `forEach` is:

`someArray.forEach( function( item, index, array ) {... } );`

where `item` is an item in the someArray, `index` is the index of `item` in someArray, and `array` is the array being traversed.

**Comment by samreid** [comment]
@pixelzoom took a look and said it's looking good enough to close.
