### ISSUE TITLE
tandem-related bug in DerivedProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#98]
Noted while reviewing https://github.com/phetsims/phet-io/issues/534...

There's a bug in the tandem-related code in DerivedProperty:

```js
    // If running as phet-io and a tandem is supplied, register with tandem.
    options && options.tandem && options.tandem.addInstance( this, TDerivedProperty( options.type ) );

    this.disposeDerivedProperty = function() {
      options.tandem && options.tandem.removeInstance( this );
    };
```

The bug occurs when `dispose` is called for a DerivedProperty that has no options. This line will fail:

```js
options.tandem && options.tandem.removeInstance( this );
```

In general, rather than prefixing things with `options &&` (which is error prone in general), I like to add this as the first line of the constructor:

```js
options = options || {};
```

**Comment by samreid** [comment]
I like the suggestion to have `options = options || {};` or `options = _.extend(...)` instead of `options &&`.  I'm seeing 43 occurrences of `options &&` across our repos.

**Comment by pixelzoom** [comment]
I fixed this specific bug, assigning to @samreid for review.  Up to you whether to create another issue to rid PhET code of `options &&`.

**Comment by samreid** [comment]
Change set looks good, I'll close this issue and create a separate issue for getting rid of `options &&`
