### ISSUE TITLE
is there a `typeof` bug in PropertySet?

### ISSUE THREAD

**Issue by andrewadare** [phetsims/axon#99]
This line appears in `setValues`:
```js
if ( typeof( propertySet[ propertyName + SUFFIX ] === 'Property' ) ) {
```
The most recent change to this line is attributed to me, which had me concerned, but it was just a formatting change. My linter flags it with the message "Unexpected constant condition", yet there are no complaints when running `grunt lint`.

Sorry if this is a misguided question, but the line looks strange to me at best, and maybe I'll learn something by asking.

**Comment by samreid** [comment]
Yes, this line is very buggy.  I'll fix it.  Or we could work on deprecating/removing this method altogether, not too widely used and could have unpredictable behavior for non-commutative properties.

**Comment by samreid** [comment]
I fixed the logic above.  The previous version was always returning true because:

```js
propertySet[ propertyName + SUFFIX ] === 'Property'
```

evaluated to false

and 

```js
typeof false
```

evaluated to "boolean", which is truthy.

Let's save it for future work for deprecation.  @andrewadare can you review the changes and let me know your thoughts?

**Comment by andrewadare** [comment]
@samreid this looks much better. Thanks for fixing so quickly. I'll close this, and if you want to open a new issue for deprecating setValues, go for it.
